<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7.4 Commercial Advertising – Creative Commons Recognition and Copyright Infringement Perceptions Survey Experiment</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../_scenarios/ls.html" rel="next">
<link href="../_scenarios/eu.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-df8e7534cb4cb7c4e956089768985eef.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked slimcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../_scenarios/ca.html">7.4 Commercial Advertising</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Creative Commons Recognition and Copyright Infringement Perceptions Survey Experiment</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ludist/cc-survey" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Experimental Design &amp; Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02-codebook.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Codebook &amp; Variable Dictionary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../03-validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Validation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../04-randomization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Randomization Check</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../05-population.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sample v. Population Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../06-brand.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Brand Recognition</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../07-scenarios.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Scenario Analysis Overview</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_scenarios/pd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.1 Public Domain</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_scenarios/pu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.2 Personal Use</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_scenarios/eu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.3 Educational Use</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_scenarios/ca.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">7.4 Commercial Advertising</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_scenarios/ls.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.5 Large Scale Copying</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_scenarios/wn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.6 Wikipedia Image Search</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_scenarios/fs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.7 Filesharing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../08-summaries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Question Summaries</span></span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#scenario-presentation" id="toc-scenario-presentation" class="nav-link active" data-scroll-target="#scenario-presentation">7.4.0 Scenario Presentation</a></li>
  <li><a href="#sec-ca-q1" id="toc-sec-ca-q1" class="nav-link" data-scroll-target="#sec-ca-q1">7.4.1 Q1: Commercial Advertising Legal Risk</a></li>
  <li><a href="#sec-ca-q2" id="toc-sec-ca-q2" class="nav-link" data-scroll-target="#sec-ca-q2">7.4.2 Q2: Perceived Consequences for Commercial Infringement</a></li>
  <li><a href="#sec-ca-q3" id="toc-sec-ca-q3" class="nav-link" data-scroll-target="#sec-ca-q3">7.4.3 Q3: Normative Preferences</a></li>
  <li><a href="#sec-ca-delta" id="toc-sec-ca-delta" class="nav-link" data-scroll-target="#sec-ca-delta">7.4.4 Delta (Q2 - Q3): Commercial Regulation Attitudes</a></li>
  <li><a href="#sec-ca-price" id="toc-sec-ca-price" class="nav-link" data-scroll-target="#sec-ca-price">7.4.5 Q4: Commercial License Value</a></li>
  <li><a href="#sec-ca-summary" id="toc-sec-ca-summary" class="nav-link" data-scroll-target="#sec-ca-summary">7.4.6 Summary</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/ludist/cc-survey/edit/main/_scenarios/ca.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/ludist/cc-survey/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-ca" class="quarto-section-identifier">7.4 Commercial Advertising</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="scenario-presentation" class="level2">
<h2 class="anchored" data-anchor-id="scenario-presentation">7.4.0 Scenario Presentation</h2>
<p>Respondents saw a two-part scenario. First, a search engine result showing a photograph with a caption that varied by condition. Then, all respondents saw the same Facebook advertisement using that photograph.</p>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>A bike shop owner who wants to create a social media ad finds the following image on a search engine. The search result is displayed as follows:</p>
</div>
</div>
</div>
<div id="ca-instrument">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Control (C)</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Short (A)</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false" href="">Full + Primer (B)</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../data/survey-images/Vignette Images/Bike.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%"></p>
</figure>
</div>
<div class="scenario-caption">
<p>© 2018 D. Green. All Rights Reserved.</p>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../data/survey-images/Vignette Images/Bike.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%"></p>
</figure>
</div>
<div class="scenario-caption">
<p><img src="../data/survey-images/Vignette Images/CC-BY-NC.png" height="20"> © 2018 D. Green is licensed under CC BY-NC 4.0</p>
</div>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<p>Full + Primer (B) respondents first reviewed a <strong>CC Education</strong> page explaining all six Creative Commons license types and the CC0 Public Domain Dedication before seeing this scenario.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../data/survey-images/Vignette Images/Bike.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%"></p>
</figure>
</div>
<div class="scenario-caption">
<p><img src="../data/survey-images/Vignette Images/CC-BY-NC.png" height="20"> © 2018 by D. Green is licensed under Creative Commons Attribution-NonCommercial 4.0 International</p>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>The bike shop owner uses the image in the following Facebook ad.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../data/survey-images/Vignette Images/bikeAd.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
<div class="scenario-caption">
<p>The ad is shown to more than 100,000 people.</p>
</div>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">Q1: Likelihood</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">Q2: Current Law</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-3" role="tab" aria-controls="tabset-2-3" aria-selected="false" href="">Q3: Normative</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-4" role="tab" aria-controls="tabset-2-4" aria-selected="false" href="">Q4: License Price</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<p><em>In your opinion, how likely is the bike shop owner to face legal consequences for this use?</em> <br>7-point scale: 1 “Extremely unlikely” <em>to</em> 7 “Extremely likely”</p>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<p><em>In your opinion, if the bike shop owner were sued for these actions, what legal consequences do you think they <strong>would</strong> face?</em> <br>7-point scale: 1 “No consequences” <em>—</em> 4 “Some negative consequences, such as a court order to stop and/or a moderate fine” <em>—</em> 7 “Very negative consequences, such as incarceration and/or a large fine”</p>
</div>
<div id="tabset-2-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-3-tab">
<p><em>In your opinion, what legal consequences <strong>should</strong> the bike shop owner face for these actions?</em> <br>7-point scale: 1 “No consequences” <em>—</em> 4 “Some negative consequences, such as a court order to stop and/or a moderate fine” <em>—</em> 7 “Very negative consequences, such as incarceration and/or a large fine”</p>
</div>
<div id="tabset-2-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-4-tab">
<p><em>Now imagine that <strong>before</strong> the use described above, the bike shop owner and the owner of this work agreed on a price for a non-exclusive license. In your opinion, what do you think would be a reasonable price for that license?</em> <br>Open response in US dollars</p>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Scenario Context
</div>
</div>
<div class="callout-body-container callout-body">
<p>A local bike shop owner uses a copyrighted photograph by D. Green in a <strong>Facebook advertisement</strong> that receives over 100,000 impressions. The photographer discovers the unauthorized use and considers legal action. The image caption varies by treatment condition:</p>
<table class="table">
<colgroup>
<col style="width: 55%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Condition</th>
<th>Caption</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Control (C)</strong></td>
<td>© 2018 D. Green. All Rights Reserved.</td>
</tr>
<tr class="even">
<td><strong>Short (A)</strong></td>
<td>© 2018 D. Green is licensed under CC BY-NC 4.0</td>
</tr>
<tr class="odd">
<td><strong>Full + Primer (B)</strong></td>
<td>© 2018 by D. Green is licensed under Creative Commons Attribution-NonCommercial 4.0 International</td>
</tr>
</tbody>
</table>
<p><strong>Legal Context:</strong> This use is <strong>infringing across all conditions</strong>. Under the Control’s standard copyright notice, any unauthorized commercial reproduction infringes. Under the treatment conditions’ CC BY-NC 4.0 license, commercial advertising plainly violates the NonCommercial clause. Unlike PD or FS, where the treatment changes the infringement analysis, here the CC license does not excuse the commercial use. Any treatment effect reflects how CC licensing <em>information</em> shapes perceptions of an act that remains infringing regardless.</p>
<p><strong>Expected Pattern:</strong> High perceived risk across all groups, with treatment effects driven by CC signaling rather than changes in legal status. The full-text license (Full + Primer (B)) may paradoxically <em>increase</em> perceived risk if respondents interpret the explicit NonCommercial restriction as signaling enforcement willingness.</p>
</div>
</div>
</section>
<section id="sec-ca-q1" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="sec-ca-q1">7.4.1 Q1: Commercial Advertising Legal Risk</h2>
<p>Do respondents recognize commercial use as high-risk?</p>
<div class="cell" data-layout-align="center">
<div id="tbl-ca-q1-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-ca-q1-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Std. Dev.</th>
<th style="text-align: right;">Median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control (C)</td>
<td style="text-align: right;">3.25</td>
<td style="text-align: right;">1.95</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Short (A)</td>
<td style="text-align: right;">3.27 (+0.6%)</td>
<td style="text-align: right;">1.87</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Full + Primer (B)</td>
<td style="text-align: right;">4.09 (+25.8%)</td>
<td style="text-align: right;">1.92</td>
<td style="text-align: right;">5</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-ca-q1-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Commercial Advertising Q1: Descriptive Statistics by Group
</figcaption>
</figure>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>* <em>p</em> &lt; .05, ** <em>p</em> &lt; .01, *** <em>p</em> &lt; .001</p>
</div></div><div class="cell" data-layout-align="center">
<div id="tbl-ca-q1-vda" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-ca-q1-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: left;">P(1st &gt; 2nd)</th>
<th style="text-align: left;">Effect Size</th>
<th style="text-align: left;">Sig.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">C &gt; A</td>
<td style="text-align: left;"> 61.7%</td>
<td style="text-align: left;">small</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">C &gt; B</td>
<td style="text-align: left;"> 61.9%</td>
<td style="text-align: left;">small</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A &gt; B</td>
<td style="text-align: left;"> 49.2%</td>
<td style="text-align: left;">negligible</td>
<td style="text-align: left;">n.s.</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-ca-q1-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Commercial Advertising Q1: Pairwise Effect Sizes
</figcaption>
</figure>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>* <em>p</em> &lt; .05, ** <em>p</em> &lt; .01, *** <em>p</em> &lt; .001<br> n.s. = not significant</p>
</div></div><div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-ca-q1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ca-q1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ca_files/figure-html/fig-ca-q1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ca-q1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Commercial Advertising Q1: Likelihood of Legal Consequences by Group
</figcaption>
</figure>
</div>
</div>
</div>
<p>Q1 asks respondents how likely the bike shop owner is to face legal consequences for using the photograph in a Facebook advertisement without permission. Because the use is commercial — and commercial advertising plainly violates the NonCommercial clause of CC BY-NC — the use is infringing across all conditions. The question, then, is whether respondents perceive commercial use of a photograph as high-risk, and whether exposure to CC licensing information shifts that perception.</p>
<p>The results indicate that respondents across all groups recognize commercial advertising as relatively high-risk. The Control (C) group rated the likelihood of legal consequences at 3.25 (SD = 1.95), Short (A) at 3.27 (SD = 1.87), and Full + Primer (B) at 4.09 (SD = 1.92). The Kruskal-Wallis test was significant (<span class="math inline">\(\chi^2\)</span>(2) = 45.67, <em>p</em> = &lt; .001). Pairwise VDA effect sizes are reported in <a href="#tbl-ca-q1-vda" class="quarto-xref">Table&nbsp;<span>2</span></a>. Unlike the Public Domain and Educational Use scenarios, where CC licensing information reduced perceived risk, the Commercial Advertising scenario presents a case where CC information may have an ambiguous or even paradoxical effect: the NonCommercial restriction could signal that the licensor cares about commercial misuse, potentially <em>increasing</em> perceived risk among respondents who read the full license text.</p>
</section>
<section id="sec-ca-q2" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="sec-ca-q2">7.4.2 Q2: Perceived Consequences for Commercial Infringement</h2>
<p>What penalties do respondents expect for commercial use of copyrighted material?</p>
<div class="cell" data-layout-align="center">
<div id="tbl-ca-q2-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-ca-q2-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Std. Dev.</th>
<th style="text-align: right;">Median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control (C)</td>
<td style="text-align: right;">3.15</td>
<td style="text-align: right;">1.39</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Short (A)</td>
<td style="text-align: right;">3.08 (−2.2%)</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Full + Primer (B)</td>
<td style="text-align: right;">3.46 (+9.8%)</td>
<td style="text-align: right;">1.44</td>
<td style="text-align: right;">4</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-ca-q2-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Commercial Advertising Q2: Descriptive Statistics by Group
</figcaption>
</figure>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>* <em>p</em> &lt; .05, ** <em>p</em> &lt; .01, *** <em>p</em> &lt; .001</p>
</div></div><div class="cell" data-layout-align="center">
<div id="tbl-ca-q2-vda" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-ca-q2-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: left;">P(1st &gt; 2nd)</th>
<th style="text-align: left;">Effect Size</th>
<th style="text-align: left;">Sig.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">C &gt; A</td>
<td style="text-align: left;"> 56.3%</td>
<td style="text-align: left;">small</td>
<td style="text-align: left;">**</td>
</tr>
<tr class="even">
<td style="text-align: left;">C &gt; B</td>
<td style="text-align: left;"> 57.6%</td>
<td style="text-align: left;">small</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A &gt; B</td>
<td style="text-align: left;"> 51.5%</td>
<td style="text-align: left;">negligible</td>
<td style="text-align: left;">n.s.</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-ca-q2-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Commercial Advertising Q2: Pairwise Effect Sizes
</figcaption>
</figure>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>* <em>p</em> &lt; .05, ** <em>p</em> &lt; .01, *** <em>p</em> &lt; .001<br> n.s. = not significant</p>
</div></div><div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-ca-q2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ca-q2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ca_files/figure-html/fig-ca-q2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ca-q2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Commercial Advertising Q2: Estimated Legal Consequences (Current) by Group
</figcaption>
</figure>
</div>
</div>
</div>
<p>Q2 shifts from likelihood to severity: given that the bike shop used the photograph without permission, what legal consequences do respondents believe would result under the current law? The response scale runs from 1 (“No consequences”) to 7 (“Very negative consequences, such as incarceration and/or a large fine”), with 4 anchored at “Some negative consequences, such as a court order to stop and/or a moderate fine.”</p>
<p>The Control (C) group estimated consequences at 3.15 (SD = 1.39), Short (A) at 3.08 (SD = 1.45), and Full + Primer (B) at 3.46 (SD = 1.44). The Kruskal-Wallis test was significant (<span class="math inline">\(\chi^2\)</span>(2) = 16.89, <em>p</em> = &lt; .001). The means across all groups sit in the moderate-to-high range of the 7-point scale, reflecting a shared intuition that unauthorized commercial use of a photograph carries meaningful consequences. Pairwise VDA effect sizes are reported in <a href="#tbl-ca-q2-vda" class="quarto-xref">Table&nbsp;<span>4</span></a>. The Commercial Advertising scenario’s high baseline severity — even in the Control — is consistent with the scenario’s design: a high-visibility advertisement with over 100,000 impressions is the kind of use that respondents intuitively associate with legal exposure, regardless of whether a CC license is present.</p>
</section>
<section id="sec-ca-q3" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="sec-ca-q3">7.4.3 Q3: Normative Preferences</h2>
<p>What consequences do respondents believe <em>should</em> apply to commercial infringement?</p>
<div class="cell" data-layout-align="center">
<div id="tbl-ca-q3-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-ca-q3-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Std. Dev.</th>
<th style="text-align: right;">Median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control (C)</td>
<td style="text-align: right;">3.03</td>
<td style="text-align: right;">1.49</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Short (A)</td>
<td style="text-align: right;">3.05 (+0.7%)</td>
<td style="text-align: right;">1.46</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Full + Primer (B)</td>
<td style="text-align: right;">3.33 (+9.9%)</td>
<td style="text-align: right;">1.47</td>
<td style="text-align: right;">4</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-ca-q3-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Commercial Advertising Q3: Descriptive Statistics by Group
</figcaption>
</figure>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>* <em>p</em> &lt; .05, ** <em>p</em> &lt; .01, *** <em>p</em> &lt; .001</p>
</div></div><div class="cell" data-layout-align="center">
<div id="tbl-ca-q3-vda" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-ca-q3-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: left;">P(1st &gt; 2nd)</th>
<th style="text-align: left;">Effect Size</th>
<th style="text-align: left;">Sig.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">C &gt; A</td>
<td style="text-align: left;"> 55.5%</td>
<td style="text-align: left;">negligible</td>
<td style="text-align: left;">*</td>
</tr>
<tr class="even">
<td style="text-align: left;">C &gt; B</td>
<td style="text-align: left;"> 55.6%</td>
<td style="text-align: left;">negligible</td>
<td style="text-align: left;">*</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A &gt; B</td>
<td style="text-align: left;"> 49.9%</td>
<td style="text-align: left;">negligible</td>
<td style="text-align: left;">n.s.</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-ca-q3-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Commercial Advertising Q3: Pairwise Effect Sizes
</figcaption>
</figure>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>* <em>p</em> &lt; .05, ** <em>p</em> &lt; .01, *** <em>p</em> &lt; .001<br> n.s. = not significant</p>
</div></div><div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-ca-q3" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ca-q3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ca_files/figure-html/fig-ca-q3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ca-q3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Commercial Advertising Q3: Estimated Legal Consequences (Preferred) by Group
</figcaption>
</figure>
</div>
</div>
</div>
<p>Q3 uses the same severity scale as Q2 but asks what consequences respondents think <em>should</em> follow from the bike shop’s unauthorized use of the photograph. This measures normative preferences rather than perceptions of current law. For the Commercial Advertising scenario — where the use is clearly commercial and therefore infringing under all conditions — Q3 captures whether respondents believe commercial infringement warrants the consequences the law currently provides.</p>
<p>The Control (C) group’s preferred consequence level was 3.03 (SD = 1.49), Short (A) was 3.05 (SD = 1.46), and Full + Primer (B) was 3.33 (SD = 1.47). The Kruskal-Wallis test was significant (<span class="math inline">\(\chi^2\)</span>(2) = 10.23, <em>p</em> = 0.006). The relatively tight grouping of Q3 means across conditions suggests that respondents’ normative judgments about commercial infringement are more stable than their perceptions of what the law currently does. This pattern — Q3 less variable than Q2 across treatments — is consistent with the idea that CC licensing information primarily shapes perceptions of the legal <em>status quo</em> rather than underlying moral intuitions about the appropriate severity of consequences. Pairwise VDA effect sizes are reported in <a href="#tbl-ca-q3-vda" class="quarto-xref">Table&nbsp;<span>6</span></a>.</p>
</section>
<section id="sec-ca-delta" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="sec-ca-delta">7.4.4 Delta (Q2 - Q3): Commercial Regulation Attitudes</h2>
<p>Do respondents want stricter or more lenient commercial use rules?</p>
<p>Delta = Q2 − Q3. Positive values indicate the law is perceived as stricter than preferred; negative values indicate the law is perceived as more lenient than preferred; zero indicates alignment.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-ca-delta-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-ca-delta-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Std. Dev.</th>
<th style="text-align: right;">Median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control (C)</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">0.89</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Short (A)</td>
<td style="text-align: right;">0.04 (−63.6%)</td>
<td style="text-align: right;">0.78</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Full + Primer (B)</td>
<td style="text-align: right;">0.13 (+18.2%)</td>
<td style="text-align: right;">0.74</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-ca-delta-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Commercial Advertising Delta: Descriptive Statistics by Group
</figcaption>
</figure>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>* <em>p</em> &lt; .05, ** <em>p</em> &lt; .01, *** <em>p</em> &lt; .001</p>
</div></div><div class="cell" data-layout-align="center">
<div id="tbl-ca-delta-vda" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-ca-delta-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: left;">P(1st &gt; 2nd)</th>
<th style="text-align: left;">Effect Size</th>
<th style="text-align: left;">Sig.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">C &gt; A</td>
<td style="text-align: left;"> 50.4%</td>
<td style="text-align: left;">negligible</td>
<td style="text-align: left;">n.s.</td>
</tr>
<tr class="even">
<td style="text-align: left;">C &gt; B</td>
<td style="text-align: left;"> 53.2%</td>
<td style="text-align: left;">negligible</td>
<td style="text-align: left;">n.s.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A &gt; B</td>
<td style="text-align: left;"> 52.7%</td>
<td style="text-align: left;">negligible</td>
<td style="text-align: left;">n.s.</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-ca-delta-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Commercial Advertising Delta: Pairwise Effect Sizes
</figcaption>
</figure>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>* <em>p</em> &lt; .05, ** <em>p</em> &lt; .01, *** <em>p</em> &lt; .001<br> n.s. = not significant</p>
</div></div><div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-ca-delta" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ca-delta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ca_files/figure-html/fig-ca-delta-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ca-delta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Commercial Advertising Delta: Current–Preferred Legal Consequences by Group
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-ca-delta-wilcox" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-ca-delta-wilcox-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: right;">V</th>
<th style="text-align: left;">Non-Zero</th>
<th style="text-align: left;">Dir.</th>
<th style="text-align: left;">Sig.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control (C)</td>
<td style="text-align: right;">5972.0</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">+</td>
<td style="text-align: left;">**</td>
</tr>
<tr class="even">
<td style="text-align: left;">Short (A)</td>
<td style="text-align: right;">4682.5</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">+</td>
<td style="text-align: left;">n.s.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Full + Primer (B)</td>
<td style="text-align: right;">4669.5</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">+</td>
<td style="text-align: left;">***</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-ca-delta-wilcox-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: Commercial Advertising Delta: Wilcoxon Signed-Rank Tests by Group
</figcaption>
</figure>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>* <em>p</em> &lt; .05, ** <em>p</em> &lt; .01, *** <em>p</em> &lt; .001<br> n.s. = not significant</p>
</div></div><p>The Delta analysis for Commercial Advertising addresses two distinct questions. First, the <em>between-group</em> Kruskal-Wallis test asks whether CC licensing information shifts the law–preference gap: Control Delta = 0.11 (SD = 0.89), Short (A) = 0.04 (SD = 0.78), Full + Primer (B) = 0.13 (SD = 0.74). The omnibus test was not significant (<span class="math inline">\(\chi^2\)</span>(2) = 4.16, <em>p</em> = 0.125). All three deltas were positive, indicating that respondents across all conditions perceived current law as imposing stricter consequences for commercial advertising infringement than they personally preferred. Pairwise VDA effect sizes are reported in <a href="#tbl-ca-delta-vda" class="quarto-xref">Table&nbsp;<span>8</span></a>.</p>
<p>Second, the <em>within-group</em> Wilcoxon signed-rank tests ask whether each group’s Delta differs significantly from zero — that is, whether there is a genuine gap between perceived law and preferences within each condition. As reported in the Wilcoxon table above, at least one group showed a significant departure from zero.</p>
</section>
<section id="sec-ca-price" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="sec-ca-price">7.4.5 Q4: Commercial License Value</h2>
<p>Commercial licenses are typically expensive. Do respondents’ estimates reflect this?</p>
<div class="cell" data-layout-align="center">
<div id="tbl-ca-price-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-ca-price-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Std. Dev.</th>
<th style="text-align: right;">Median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control (C)</td>
<td style="text-align: right;">2263.39</td>
<td style="text-align: right;">11214.42</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Short (A)</td>
<td style="text-align: right;">746.89 (−67.0%)</td>
<td style="text-align: right;">2469.81</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Full + Primer (B)</td>
<td style="text-align: right;">791.10 (−65.0%)</td>
<td style="text-align: right;">2960.75</td>
<td style="text-align: right;">100</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-ca-price-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10: Commercial Advertising Q4: Descriptive Statistics by Group
</figcaption>
</figure>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>* <em>p</em> &lt; .05, ** <em>p</em> &lt; .01, *** <em>p</em> &lt; .001</p>
</div></div><div class="cell" data-layout-align="center">
<div id="tbl-ca-price-vda" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-ca-price-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: left;">P(1st &gt; 2nd)</th>
<th style="text-align: left;">Effect Size</th>
<th style="text-align: left;">Sig.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">C &gt; A</td>
<td style="text-align: left;"> 47.8%</td>
<td style="text-align: left;">negligible</td>
<td style="text-align: left;">n.s.</td>
</tr>
<tr class="even">
<td style="text-align: left;">C &gt; B</td>
<td style="text-align: left;"> 51.6%</td>
<td style="text-align: left;">negligible</td>
<td style="text-align: left;">n.s.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A &gt; B</td>
<td style="text-align: left;"> 53.8%</td>
<td style="text-align: left;">negligible</td>
<td style="text-align: left;">n.s.</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-ca-price-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11: Commercial Advertising Q4: Pairwise Effect Sizes
</figcaption>
</figure>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>* <em>p</em> &lt; .05, ** <em>p</em> &lt; .01, *** <em>p</em> &lt; .001<br> n.s. = not significant</p>
</div></div><div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-ca-price" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ca-price-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ca_files/figure-html/fig-ca-price-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ca-price-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Commercial Advertising Q4: License Price Estimate by Group
</figcaption>
</figure>
</div>
</div>
</div>
<p>Q4 asks respondents to estimate the price of a non-exclusive license for the photograph used in the Facebook advertisement. After trimming the top 1% of responses to remove outlier estimates, median license price estimates were $100 for the Control, $100 for Short (A), and $100 for Full + Primer (B). Mean estimates — which are pulled upward by the right-skewed distribution typical of open-ended price questions — were $2,263, $747, and <span class="math inline">\(791, respectively. The Kruskal-Wallis test was not significant (\)</span>^2$(2) = 3.49, <em>p</em> = 0.175). Pairwise VDA effect sizes are reported in <a href="#tbl-ca-price-vda" class="quarto-xref">Table&nbsp;<span>11</span></a>.</p>
<p>The divergence between means and medians is informative: it reflects a long right tail of respondents who estimated very high commercial licensing fees, consistent with the scenario’s high-visibility, high-impression advertising context. Commercial stock photography licenses for advertisements with national reach can range from hundreds to thousands of dollars, and the median estimates suggest that respondents’ intuitions about commercial licensing value are broadly calibrated to market reality.</p>
</section>
<section id="sec-ca-summary" class="level2">
<h2 class="anchored" data-anchor-id="sec-ca-summary">7.4.6 Summary</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Key Findings — Commercial Advertising
</div>
</div>
<div class="callout-body-container callout-body">
<p>The Commercial Advertising scenario is the study’s clearest case of <strong>uniform infringement</strong>: the CC BY-NC 4.0 license explicitly prohibits commercial use, so the bike shop’s Facebook advertisement infringes under all three conditions. Any between-group differences reflect how CC licensing <em>information</em> shapes perceptions of an act whose legal status does not change. The key findings are:</p>
<ol type="1">
<li><p><strong>Uniformly infringing scenario confirmed.</strong> All group means for Q1–Q3 sit in the moderate-to-high range of the 7-point scale, confirming that respondents across all conditions recognize commercial advertising use of a copyrighted photograph as carrying meaningful legal risk. The high baseline in the Control (C) group (Q1 M = 3.25, Q2 M = 3.15) indicates that respondents associate high-visibility commercial use with legal exposure regardless of licensing information.</p></li>
<li><p><strong>CC signaling, not legal change.</strong> Unlike the Public Domain scenario (where treatment information clarifies the absence of copyright) or Filesharing (where the license may alter the infringement analysis), the Commercial Advertising scenario isolates the <em>signaling</em> function of CC licensing. Treatment effects here cannot be attributed to changes in legal status — the NonCommercial clause does not excuse commercial use. Any observed differences reflect how the presence and detail of licensing information shapes respondent perceptions.</p></li>
<li><p><strong>NonCommercial clause paradox.</strong> The CC BY-NC license’s explicit NonCommercial restriction creates a potential paradox: rather than reducing perceived risk (as CC information does in non-infringing scenarios), the restriction may <em>increase</em> perceived risk by signaling that the licensor specifically anticipated and prohibited commercial use. The significant between-group difference on Q1 (Kruskal-Wallis <em>p</em> = &lt; .001) is consistent with this signaling mechanism.</p></li>
<li><p><strong>Pricing patterns reflect commercial context.</strong> License price estimates (median: Control = $100, Short (A) = $100, Full + Primer (B) = $100) are calibrated to the commercial advertising context, with the right-skewed distribution reflecting respondents who anchored on the high-visibility, high-impression nature of the use.</p></li>
<li><p><strong>Law–preference gap direction.</strong> All three groups’ Delta values were positive, indicating that respondents across all conditions perceived current law as imposing stricter consequences for commercial advertising infringement than they personally preferred. This suggests that even for a clearly infringing commercial use, respondents’ normative preferences are somewhat more lenient than their perceptions of what the law currently requires. Within-group Wilcoxon tests confirm this gap is significant for at least one treatment condition.</p></li>
<li><p><strong>Normative stability.</strong> Q3 means were relatively stable across conditions compared to Q2, suggesting that CC licensing information primarily shapes perceptions of the legal status quo rather than underlying moral intuitions about the appropriate severity of consequences for commercial infringement.</p></li>
</ol>
</div>
</div>


<!-- -->

</section>

</main> <!-- /main -->
<script>
/*
 * sidebar-toc.js — CC Survey Online Appendix
 *
 * Quarto Book sidebar accordion for within-page sections.
 *
 * Actual Quarto behavior (confirmed from rendered HTML):
 *   - toc-location: left places the TOC as <nav id="TOC"> inside #quarto-sidebar,
 *     AFTER the chapter list. The <ul> has class="collapse" (Bootstrap-hidden).
 *   - There is NO #quarto-sidebar-toc-left element in Quarto 1.8.
 *   - CSS hides the nav#TOC block; this script moves the links to nest under
 *     the active chapter <li>, achieving accordion display.
 *
 * Edge case handled: chapters with a body H1 (e.g. {.unnumbered} intro) produce
 * a TOC where the H1 is the sole top-level link and H2s are nested under it.
 * In that case we skip the H1 (which duplicates the sidebar chapter entry) and
 * promote the nested H2 links instead.
 */
(function () {
  'use strict';

  function injectAuthorLine() {
    // Add author name below the book title/subtitle, above the search bar
    if (document.querySelector('.sidebar-author')) return;

    var sidebar = document.getElementById('quarto-sidebar');
    if (!sidebar) return;

    // Insert after subtitle if present, else after title
    var anchor = sidebar.querySelector('.sidebar-subtitle')
              || sidebar.querySelector('.sidebar-title');
    if (!anchor) return;

    var authorDiv = document.createElement('div');
    authorDiv.className = 'sidebar-author';
    authorDiv.innerHTML = '<span class="sidebar-author-label">inquiry by</span><br>Thomas H. Rousse<br>J.D., Ph.D.';

    // Insert between subtitle/title and search bar (equidistant)
    var search = sidebar.querySelector('#quarto-search');
    if (search) {
      search.parentNode.insertBefore(authorDiv, search);
    } else {
      anchor.parentNode.insertBefore(authorDiv, anchor.nextSibling);
    }
  }

  function injectSections() {
    // 1. Find the active chapter <li> in the sidebar
    var activeLink = document.querySelector('#quarto-sidebar .sidebar-link.active');
    if (!activeLink) return;
    var activeItem = activeLink.closest('li.sidebar-item');
    if (!activeItem) return;

    // 2. Find the TOC nav that Quarto placed inside the sidebar
    var tocNav = document.querySelector('#quarto-sidebar nav#TOC');
    if (!tocNav) return;

    // 3. Get all section links (already depth-filtered by Quarto's toc-depth: 2)
    var allLinks = Array.from(tocNav.querySelectorAll('a[data-scroll-target]'));

    // Keep only top-level links (no grandparent <li>)
    var topLevelLinks = allLinks.filter(function (link) {
      var parentLi = link.closest('li');
      if (!parentLi) return false;
      var grandparentLi = parentLi.parentElement && parentLi.parentElement.closest('li');
      return !grandparentLi;
    });

    // Edge case: body-H1 chapters (e.g. {.unnumbered} intro).
    // The sole top-level link IS the chapter title — injecting it would duplicate
    // the sidebar chapter entry. Detect this and promote the nested H2 links instead.
    var chapterText = activeLink.textContent.replace(/^\d+[\.\s]+/, '').trim();
    if (
      topLevelLinks.length === 1 &&
      topLevelLinks[0].textContent.trim() === chapterText
    ) {
      // Promote one level deeper (the H2s nested under the H1)
      topLevelLinks = allLinks.filter(function (link) {
        var parentLi = link.closest('li');
        if (!parentLi) return false;
        var grandparentLi = parentLi.parentElement && parentLi.parentElement.closest('li');
        if (!grandparentLi) return false;
        var greatGrandparentLi = grandparentLi.parentElement && grandparentLi.parentElement.closest('li');
        return !greatGrandparentLi;
      });
    }

    if (topLevelLinks.length === 0) return;

    // 4. Build the nested section list
    var sectionList = document.createElement('ul');
    sectionList.className = 'sidebar-sections list-unstyled';

    topLevelLinks.forEach(function (link) {
      var li = document.createElement('li');
      li.className = 'sidebar-section-item';
      // Replace nav-link class with our sidebar class; keep data-scroll-target
      link.className = 'sidebar-section-link';
      li.appendChild(link); // move (not clone) to preserve Quarto scroll-tracking refs
      sectionList.appendChild(li);
    });

    // 5. Insert immediately after the active chapter <li>
    activeItem.parentNode.insertBefore(sectionList, activeItem.nextSibling);

    // 6. tocNav is already hidden via CSS; no further action needed
  }

  function init() {
    injectAuthorLine();
    injectSections();
  }

  if (document.readyState === 'complete') {
    init();
  } else {
    window.addEventListener('load', init);
  }
}());
</script>
<script>
/*
 * section-numbering.js — CC Survey Online Appendix
 *
 * Renumbers ALL tables and figures to use section-level numbering:
 *   Table 7.1.1.1 = Chapter 7, Scenario 1, Subsection 1, Table 1
 *   Figure 3.2.1  = Chapter 3, Section 2, Figure 1
 *
 * Works on ALL pages:
 *   - Numbered chapters: reads Quarto's .header-section-number spans
 *   - Unnumbered scenario chapters: parses manual section numbers from
 *     heading text (e.g., "## 7.1.1 Q1: ...")
 *
 * Fixes both same-page AND cross-page cross-reference links.
 * Cross-page xrefs are resolved by fetching the target page, computing
 * its section-level numbering, and patching the link text. Each target
 * page is fetched at most once (results are cached per session).
 *
 * Replaces the original scenario-numbering.html (which only handled
 * 3-level numbering for figures on scenario pages).
 *
 * Runs after DOM load.
 */
document.addEventListener('DOMContentLoaded', function() {

  // ── Shared: compute section-level numbering for a root element ──
  // Returns { elementId: { type: 'Table'|'Figure', number: '6.3.1' } }
  // If mutate=true, also rewrites captions and wraps manual heading
  // numbers in .header-section-number spans (only for the live page).
  function computeNumbering(root, mutate) {
    var nodes = root.querySelectorAll(
      'h1, h2, h3, h4, [id^="tbl-"], [id^="fig-"]'
    );

    var currentSection = '';
    var tblCount = {};
    var figCount = {};
    var map = {};

    nodes.forEach(function(el) {
      var tag = el.tagName;

      // ── Heading: update current section number ───────────────
      if (/^H[1-4]$/i.test(tag)) {
        var numSpan = el.querySelector('.header-section-number');
        if (numSpan) {
          currentSection = numSpan.textContent.trim();
          return;
        }
        var m = el.textContent.trim().match(/^(\d+(?:\.\d+)*)/);
        if (m) {
          currentSection = m[1];
          if (mutate) {
            var secId = el.querySelector('.quarto-section-identifier');
            var target = secId || el;
            var html = target.innerHTML;
            if (html.indexOf('header-section-number') === -1) {
              target.innerHTML = html.replace(
                /^(\d+(?:\.\d+)*)\s*/,
                '<span class="header-section-number">$1</span> '
              );
            }
          }
        }
        return;
      }

      // ── Float container: compute new number ─────────────────
      if (!currentSection) return;

      var cap = el.querySelector('figcaption') || el.querySelector('caption');
      if (!cap) return;

      var id = (el.id || '').toLowerCase();
      var type, counter;
      if (id.startsWith('tbl-')) {
        type = 'Table';
        counter = tblCount;
      } else if (id.startsWith('fig-')) {
        type = 'Figure';
        counter = figCount;
      } else {
        return;
      }

      if (!counter[currentSection]) counter[currentSection] = 0;
      counter[currentSection]++;
      var newNum = currentSection + '.' + counter[currentSection];

      map[el.id] = { type: type, number: newNum };

      if (mutate) {
        var re = new RegExp(
          '(' + type + ')(&#160;|&nbsp;|\\u00A0|\\s)(\\d+(?:\\.\\d+)*)'
        );
        cap.innerHTML = cap.innerHTML.replace(
          re, '<span class="float-label">$1$2' + newNum + '</span>'
        );
        el.setAttribute('data-section-num', newNum);
        el.setAttribute('data-section-type', type);
      }
    });

    return map;
  }

  // ── Helper: update a cross-reference link with new numbering ──
  function patchXrefLink(link, info) {
    var spans = link.querySelectorAll('span');
    if (spans.length > 0) {
      spans[spans.length - 1].textContent = info.number;
    } else {
      link.innerHTML = info.type + '&nbsp;' + info.number;
    }
  }

  // ══════════════════════════════════════════════════════════════
  // 1. Renumber the current page (mutate captions + headings)
  // ══════════════════════════════════════════════════════════════
  var main = document.getElementById('quarto-document-content');
  if (!main) return;

  var localMap = computeNumbering(main, true);

  // ══════════════════════════════════════════════════════════════
  // 2. Fix same-page cross-reference links
  // ══════════════════════════════════════════════════════════════
  document.querySelectorAll('a.quarto-xref').forEach(function(link) {
    var href = link.getAttribute('href');
    if (!href || !href.startsWith('#')) return;

    var targetId = href.substring(1);
    var info = localMap[targetId];
    if (!info) return;

    patchXrefLink(link, info);
  });

  // ══════════════════════════════════════════════════════════════
  // 3. Fix cross-page cross-reference links
  //    Group by target page URL, fetch each once, compute
  //    numbering on the fetched DOM, patch all links to that page.
  // ══════════════════════════════════════════════════════════════
  var crossPageGroups = {};   // pageUrl → [{link, targetId}]

  document.querySelectorAll('a.quarto-xref').forEach(function(link) {
    var href = link.getAttribute('href');
    if (!href || href.startsWith('#')) return;

    var hashIdx = href.indexOf('#');
    if (hashIdx === -1) return;

    var pageUrl  = href.substring(0, hashIdx);
    var targetId = href.substring(hashIdx + 1);

    // Skip if target ID doesn't look like a table/figure
    if (!targetId.startsWith('tbl-') && !targetId.startsWith('fig-')) return;

    if (!crossPageGroups[pageUrl]) crossPageGroups[pageUrl] = [];
    crossPageGroups[pageUrl].push({ link: link, targetId: targetId });
  });

  // Fetch each unique target page and resolve its numbering
  Object.keys(crossPageGroups).forEach(function(pageUrl) {
    fetch(pageUrl)
      .then(function(response) {
        if (!response.ok) throw new Error(response.status);
        return response.text();
      })
      .then(function(html) {
        var parser = new DOMParser();
        var doc = parser.parseFromString(html, 'text/html');
        var remoteMain = doc.getElementById('quarto-document-content');
        if (!remoteMain) return;

        // Compute numbering on the fetched page (read-only, no mutation)
        var remoteMap = computeNumbering(remoteMain, false);

        // Patch all links pointing to this page
        crossPageGroups[pageUrl].forEach(function(entry) {
          var info = remoteMap[entry.targetId];
          if (!info) return;
          patchXrefLink(entry.link, info);
        });
      })
      .catch(function(err) {
        // Graceful degradation: cross-page links keep Quarto-native numbers
        console.warn('[section-numbering] Could not resolve xrefs for '
          + pageUrl + ':', err.message || err);
      });
  });
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../_scenarios/eu.html" class="pagination-link" aria-label="7.3 Educational Use">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">7.3 Educational Use</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../_scenarios/ls.html" class="pagination-link" aria-label="7.5 Large Scale Copying">
        <span class="nav-page-text">7.5 Large Scale Copying</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r setup, include=FALSE}</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"_common.R"</span>))</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu"># 7.4 Commercial Advertising {.unnumbered #sec-ca}</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.4.0 Scenario Presentation</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>Respondents saw a two-part scenario. First, a search engine result showing a photograph with a caption that varied by condition. Then, all respondents saw the same Facebook advertisement using that photograph.</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>::: {.callout-important appearance="simple" icon=false}</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>A bike shop owner who wants to create a social media ad finds the following image on a search engine. The search result is displayed as follows:</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>::: {#ca-instrument}</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>::: {.panel-tabset}</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="fu">### Control (C)</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="al">![](../data/survey-images/Vignette%20Images/Bike.jpg)</span>{fig-align="center" width="95%"}</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>::: {.scenario-caption}</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="dv">&amp;copy;</span> 2018 D. Green. All Rights Reserved.</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="fu">### Short (A)</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="al">![](../data/survey-images/Vignette%20Images/Bike.jpg)</span>{fig-align="center" width="95%"}</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>::: {.scenario-caption}</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="al">![](../data/survey-images/Vignette%20Images/CC-BY-NC.png)</span>{height="20px"} <span class="dv">&amp;copy;</span> 2018 D. Green is licensed under CC BY-NC 4.0</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="fu">### Full + Primer (B)</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>Full + Primer (B) respondents first reviewed a **CC Education** page explaining all six Creative Commons license types and the CC0 Public Domain Dedication before seeing this scenario.</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a><span class="al">![](../data/survey-images/Vignette%20Images/Bike.jpg)</span>{fig-align="center" width="95%"}</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>::: {.scenario-caption}</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a><span class="al">![](../data/survey-images/Vignette%20Images/CC-BY-NC.png)</span>{height="20px"} <span class="dv">&amp;copy;</span> 2018 by D. Green is licensed under Creative Commons Attribution-NonCommercial 4.0 International</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>::: {.callout-important appearance="simple" icon=false}</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>The bike shop owner uses the image in the following Facebook ad.</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a><span class="al">![](../data/survey-images/Vignette%20Images/bikeAd.png)</span>{fig-align="center" width="70%"}</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>::: {.scenario-caption}</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>The ad is shown to more than 100,000 people.</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>::: {.panel-tabset}</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a><span class="fu">### Q1: Likelihood</span></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>*In your opinion, how likely is the bike shop owner to face legal consequences for this use?*</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span>7-point scale: 1 "Extremely unlikely" *to* 7 "Extremely likely"</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a><span class="fu">### Q2: Current Law</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>*In your opinion, if the bike shop owner were sued for these actions, what legal consequences do you think they **would** face?*</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span>7-point scale: 1 "No consequences" *---* 4 "Some negative consequences, such as a court order to stop and/or a moderate fine" *---* 7 "Very negative consequences, such as incarceration and/or a large fine"</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="fu">### Q3: Normative</span></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>*In your opinion, what legal consequences **should** the bike shop owner face for these actions?*</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span>7-point scale: 1 "No consequences" *---* 4 "Some negative consequences, such as a court order to stop and/or a moderate fine" *---* 7 "Very negative consequences, such as incarceration and/or a large fine"</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a><span class="fu">### Q4: License Price</span></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>*Now imagine that **before** the use described above, the bike shop owner and the owner of this work agreed on a price for a non-exclusive license. In your opinion, what do you think would be a reasonable price for that license?*</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span>Open response in US dollars</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a><span class="fu">## Scenario Context</span></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>A local bike shop owner uses a copyrighted photograph by D. Green in a **Facebook advertisement** that receives over 100,000 impressions. The photographer discovers the unauthorized use and considers legal action. The image caption varies by treatment condition:</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Condition <span class="pp">|</span> Caption <span class="pp">|</span></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a><span class="pp">|-----------|---------|</span></span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Control (C)** <span class="pp">|</span> <span class="dv">&amp;copy;</span> 2018 D. Green. All Rights Reserved. <span class="pp">|</span></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Short (A)** <span class="pp">|</span> <span class="dv">&amp;copy;</span> 2018 D. Green is licensed under CC BY-NC 4.0 <span class="pp">|</span></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Full + Primer (B)** <span class="pp">|</span> <span class="dv">&amp;copy;</span> 2018 by D. Green is licensed under Creative Commons Attribution-NonCommercial 4.0 International <span class="pp">|</span></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>**Legal Context:** This use is **infringing across all conditions**. Under the Control's standard copyright notice, any unauthorized commercial reproduction infringes. Under the treatment conditions' CC BY-NC 4.0 license, commercial advertising plainly violates the NonCommercial clause. Unlike PD or FS, where the treatment changes the infringement analysis, here the CC license does not excuse the commercial use. Any treatment effect reflects how CC licensing *information* shapes perceptions of an act that remains infringing regardless.</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>**Expected Pattern:** High perceived risk across all groups, with treatment effects driven by CC signaling rather than changes in legal status. The full-text license (Full + Primer (B)) may paradoxically *increase* perceived risk if respondents interpret the explicit NonCommercial restriction as signaling enforcement willingness.</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a><span class="in">```{r ca-analysis}</span></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>ca_results <span class="ot">&lt;-</span> <span class="fu">analyze_full_scenario</span>(</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>  <span class="at">data         =</span> survey_data,</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>  <span class="at">scenario_code =</span> <span class="st">"CA"</span>,</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>  <span class="at">scenario_name =</span> <span class="st">"Commercial Advertising"</span>,</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>  <span class="at">questions    =</span> <span class="fu">c</span>(<span class="st">"q1"</span>, <span class="st">"q2"</span>, <span class="st">"q3"</span>, <span class="st">"delta"</span>, <span class="st">"price"</span>),</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>  <span class="at">export_tiffs =</span> <span class="cn">TRUE</span></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a><span class="in">```{r ca-extract, include=FALSE}</span></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a><span class="fu">list2env</span>(<span class="fu">extract_scenario_inline</span>(ca_results, <span class="st">"CA"</span>, survey_data), <span class="at">envir =</span> <span class="fu">environment</span>())</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.4.1 Q1: Commercial Advertising Legal Risk {#sec-ca-q1}</span></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>Do respondents recognize commercial use as high-risk?</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-ca-q1-stats</span></span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Commercial Advertising Q1: Descriptive Statistics by Group"</span></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">fmt_stats_table</span>(ca_results<span class="sc">$</span>statistics<span class="sc">$</span>q1, <span class="at">dunn =</span> ca_results<span class="sc">$</span>dunn<span class="sc">$</span>q1), <span class="at">align =</span> <span class="st">"lrrr"</span>)</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>{{&lt; include ../_includes/sig-legend.qmd &gt;}}</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-ca-q1-vda</span></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Commercial Advertising Q1: Pairwise Effect Sizes"</span></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(ca_vda_q1)</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>{{&lt; include ../_includes/sig-legend-long.qmd &gt;}}</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-ca-q1</span></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Commercial Advertising Q1: Likelihood of Legal Consequences by Group"</span></span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ca_results<span class="sc">$</span>plots<span class="sc">$</span>q1)</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>Q1 asks respondents how likely the bike shop owner is to face legal consequences for using the photograph in a Facebook advertisement without permission. Because the use is commercial --- and commercial advertising plainly violates the NonCommercial clause of CC BY-NC --- the use is infringing across all conditions. The question, then, is whether respondents perceive commercial use of a photograph as high-risk, and whether exposure to CC licensing information shifts that perception.</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>The results indicate that respondents across all groups recognize commercial advertising as relatively high-risk. The Control (C) group rated the likelihood of legal consequences at <span class="in">`r ca_q1_c`</span> (SD = <span class="in">`r ca_q1_sd_c`</span>), Short (A) at <span class="in">`r ca_q1_a`</span> (SD = <span class="in">`r ca_q1_sd_a`</span>), and Full + Primer (B) at <span class="in">`r ca_q1_b`</span> (SD = <span class="in">`r ca_q1_sd_b`</span>). The Kruskal-Wallis test was <span class="in">`r ifelse(ca_kw_q1$p.value &lt; 0.05, "significant", "not significant")`</span> ($\chi^2$(<span class="in">`r ca_kw_q1$parameter`</span>) = <span class="in">`r fmt(ca_kw_q1$statistic)`</span>, *p* = `r fmtp(ca_kw_q1$p.value)`). Pairwise VDA effect sizes are reported in @tbl-ca-q1-vda. Unlike the Public Domain and Educational Use scenarios, where CC licensing information reduced perceived risk, the Commercial Advertising scenario presents a case where CC information may have an ambiguous or even paradoxical effect: the NonCommercial restriction could signal that the licensor cares about commercial misuse, potentially *increasing* perceived risk among respondents who read the full license text.</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.4.2 Q2: Perceived Consequences for Commercial Infringement {#sec-ca-q2}</span></span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>What penalties do respondents expect for commercial use of copyrighted material?</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-ca-q2-stats</span></span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Commercial Advertising Q2: Descriptive Statistics by Group"</span></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">fmt_stats_table</span>(ca_results<span class="sc">$</span>statistics<span class="sc">$</span>q2, <span class="at">dunn =</span> ca_results<span class="sc">$</span>dunn<span class="sc">$</span>q2), <span class="at">align =</span> <span class="st">"lrrr"</span>)</span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a>{{&lt; include ../_includes/sig-legend.qmd &gt;}}</span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-ca-q2-vda</span></span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Commercial Advertising Q2: Pairwise Effect Sizes"</span></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(ca_vda_q2)</span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a>{{&lt; include ../_includes/sig-legend-long.qmd &gt;}}</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-ca-q2</span></span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Commercial Advertising Q2: Estimated Legal Consequences (Current) by Group"</span></span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ca_results<span class="sc">$</span>plots<span class="sc">$</span>q2)</span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a>Q2 shifts from likelihood to severity: given that the bike shop used the photograph without permission, what legal consequences do respondents believe would result under the current law? The response scale runs from 1 ("No consequences") to 7 ("Very negative consequences, such as incarceration and/or a large fine"), with 4 anchored at "Some negative consequences, such as a court order to stop and/or a moderate fine."</span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a>The Control (C) group estimated consequences at <span class="in">`r ca_q2_c`</span> (SD = <span class="in">`r ca_q2_sd_c`</span>), Short (A) at <span class="in">`r ca_q2_a`</span> (SD = <span class="in">`r ca_q2_sd_a`</span>), and Full + Primer (B) at <span class="in">`r ca_q2_b`</span> (SD = <span class="in">`r ca_q2_sd_b`</span>). The Kruskal-Wallis test was <span class="in">`r ifelse(ca_kw_q2$p.value &lt; 0.05, "significant", "not significant")`</span> ($\chi^2$(<span class="in">`r ca_kw_q2$parameter`</span>) = <span class="in">`r fmt(ca_kw_q2$statistic)`</span>, *p* = <span class="in">`r fmtp(ca_kw_q2$p.value)`</span>). The means across all groups sit in the moderate-to-high range of the 7-point scale, reflecting a shared intuition that unauthorized commercial use of a photograph carries meaningful consequences. Pairwise VDA effect sizes are reported in @tbl-ca-q2-vda. The Commercial Advertising scenario's high baseline severity --- even in the Control --- is consistent with the scenario's design: a high-visibility advertisement with over 100,000 impressions is the kind of use that respondents intuitively associate with legal exposure, regardless of whether a CC license is present.</span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.4.3 Q3: Normative Preferences {#sec-ca-q3}</span></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a>What consequences do respondents believe *should* apply to commercial infringement?</span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-ca-q3-stats</span></span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Commercial Advertising Q3: Descriptive Statistics by Group"</span></span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">fmt_stats_table</span>(ca_results<span class="sc">$</span>statistics<span class="sc">$</span>q3, <span class="at">dunn =</span> ca_results<span class="sc">$</span>dunn<span class="sc">$</span>q3), <span class="at">align =</span> <span class="st">"lrrr"</span>)</span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a>{{&lt; include ../_includes/sig-legend.qmd &gt;}}</span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-ca-q3-vda</span></span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Commercial Advertising Q3: Pairwise Effect Sizes"</span></span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(ca_vda_q3)</span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a>{{&lt; include ../_includes/sig-legend-long.qmd &gt;}}</span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-ca-q3</span></span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Commercial Advertising Q3: Estimated Legal Consequences (Preferred) by Group"</span></span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ca_results<span class="sc">$</span>plots<span class="sc">$</span>q3)</span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a>Q3 uses the same severity scale as Q2 but asks what consequences respondents think *should* follow from the bike shop's unauthorized use of the photograph. This measures normative preferences rather than perceptions of current law. For the Commercial Advertising scenario --- where the use is clearly commercial and therefore infringing under all conditions --- Q3 captures whether respondents believe commercial infringement warrants the consequences the law currently provides.</span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a>The Control (C) group's preferred consequence level was <span class="in">`r ca_q3_c`</span> (SD = <span class="in">`r ca_q3_sd_c`</span>), Short (A) was <span class="in">`r ca_q3_a`</span> (SD = <span class="in">`r ca_q3_sd_a`</span>), and Full + Primer (B) was <span class="in">`r ca_q3_b`</span> (SD = <span class="in">`r ca_q3_sd_b`</span>). The Kruskal-Wallis test was <span class="in">`r ifelse(ca_kw_q3$p.value &lt; 0.05, "significant", "not significant")`</span> ($\chi^2$(<span class="in">`r ca_kw_q3$parameter`</span>) = <span class="in">`r fmt(ca_kw_q3$statistic)`</span>, *p* = `r fmtp(ca_kw_q3$p.value)`). The relatively tight grouping of Q3 means across conditions suggests that respondents' normative judgments about commercial infringement are more stable than their perceptions of what the law currently does. This pattern --- Q3 less variable than Q2 across treatments --- is consistent with the idea that CC licensing information primarily shapes perceptions of the legal *status quo* rather than underlying moral intuitions about the appropriate severity of consequences. Pairwise VDA effect sizes are reported in @tbl-ca-q3-vda.</span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.4.4 Delta (Q2 - Q3): Commercial Regulation Attitudes {#sec-ca-delta}</span></span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a>Do respondents want stricter or more lenient commercial use rules?</span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a>{{&lt; include ../_includes/delta-definition.qmd &gt;}}</span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-ca-delta-stats</span></span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Commercial Advertising Delta: Descriptive Statistics by Group"</span></span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">fmt_stats_table</span>(ca_results<span class="sc">$</span>statistics<span class="sc">$</span>delta, <span class="at">dunn =</span> ca_results<span class="sc">$</span>dunn<span class="sc">$</span>delta), <span class="at">align =</span> <span class="st">"lrrr"</span>)</span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a>{{&lt; include ../_includes/sig-legend.qmd &gt;}}</span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-ca-delta-vda</span></span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Commercial Advertising Delta: Pairwise Effect Sizes"</span></span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(ca_vda_delta)</span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a>{{&lt; include ../_includes/sig-legend-long.qmd &gt;}}</span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-ca-delta</span></span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Commercial Advertising Delta: Current\u2013Preferred Legal Consequences by Group"</span></span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ca_results<span class="sc">$</span>plots<span class="sc">$</span>delta)</span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-ca-delta-wilcox</span></span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Commercial Advertising Delta: Wilcoxon Signed-Rank Tests by Group"</span></span>
<span id="cb1-284"><a href="#cb1-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-285"><a href="#cb1-285" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">format_wilcoxon_table</span>(ca_results), <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a>{{&lt; include ../_includes/sig-legend-long.qmd &gt;}}</span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a>The Delta analysis for Commercial Advertising addresses two distinct questions. First, the *between-group* Kruskal-Wallis test asks whether CC licensing information shifts the law--preference gap: Control Delta = `r ca_delta_c` (SD = `r ca_delta_sd_c`), Short (A) = `r ca_delta_a` (SD = `r ca_delta_sd_a`), Full + Primer (B) = `r ca_delta_b` (SD = `r ca_delta_sd_b`). The omnibus test was `r ifelse(ca_kw_delta$p.value &lt; 0.05, "significant", "not significant")` ($\chi^2$(`r ca_kw_delta$parameter`) = `r fmt(ca_kw_delta$statistic)`, *p* = <span class="in">`r fmtp(ca_kw_delta$p.value)`</span>). <span class="in">`r if (ca_delta_all_pos) "All three deltas were positive, indicating that respondents across all conditions perceived current law as imposing stricter consequences for commercial advertising infringement than they personally preferred." else "Deltas were mixed in sign across groups, suggesting no uniform direction in the law--preference gap."`</span> Pairwise VDA effect sizes are reported in @tbl-ca-delta-vda.</span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a>Second, the *within-group* Wilcoxon signed-rank tests ask whether each group's Delta differs significantly from zero --- that is, whether there is a genuine gap between perceived law and preferences within each condition. As reported in the Wilcoxon table above, <span class="in">`r ifelse(ca_wilcox_all_sig, "all three groups showed significant departures from zero, confirming that the law--preference gap is not an artifact of between-group averaging but exists within each treatment condition individually", ifelse(ca_wilcox_any_sig, "at least one group showed a significant departure from zero", "no group's delta significantly differed from zero"))`</span>.</span>
<span id="cb1-293"><a href="#cb1-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-294"><a href="#cb1-294" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.4.5 Q4: Commercial License Value {#sec-ca-price}</span></span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-296"><a href="#cb1-296" aria-hidden="true" tabindex="-1"></a>Commercial licenses are typically expensive. Do respondents' estimates reflect this?</span>
<span id="cb1-297"><a href="#cb1-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-300"><a href="#cb1-300" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-301"><a href="#cb1-301" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-ca-price-stats</span></span>
<span id="cb1-302"><a href="#cb1-302" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Commercial Advertising Q4: Descriptive Statistics by Group"</span></span>
<span id="cb1-303"><a href="#cb1-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-304"><a href="#cb1-304" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">fmt_stats_table</span>(ca_results<span class="sc">$</span>statistics<span class="sc">$</span>price, <span class="at">dunn =</span> ca_results<span class="sc">$</span>dunn<span class="sc">$</span>price), <span class="at">align =</span> <span class="st">"lrrr"</span>)</span>
<span id="cb1-305"><a href="#cb1-305" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-306"><a href="#cb1-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-307"><a href="#cb1-307" aria-hidden="true" tabindex="-1"></a>{{&lt; include ../_includes/sig-legend.qmd &gt;}}</span>
<span id="cb1-308"><a href="#cb1-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-311"><a href="#cb1-311" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-312"><a href="#cb1-312" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-ca-price-vda</span></span>
<span id="cb1-313"><a href="#cb1-313" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Commercial Advertising Q4: Pairwise Effect Sizes"</span></span>
<span id="cb1-314"><a href="#cb1-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-315"><a href="#cb1-315" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(ca_vda_price)</span>
<span id="cb1-316"><a href="#cb1-316" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-317"><a href="#cb1-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-318"><a href="#cb1-318" aria-hidden="true" tabindex="-1"></a>{{&lt; include ../_includes/sig-legend-long.qmd &gt;}}</span>
<span id="cb1-319"><a href="#cb1-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-322"><a href="#cb1-322" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-323"><a href="#cb1-323" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-ca-price</span></span>
<span id="cb1-324"><a href="#cb1-324" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb1-325"><a href="#cb1-325" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Commercial Advertising Q4: License Price Estimate by Group"</span></span>
<span id="cb1-326"><a href="#cb1-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-327"><a href="#cb1-327" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ca_results<span class="sc">$</span>plots<span class="sc">$</span>price)</span>
<span id="cb1-328"><a href="#cb1-328" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-329"><a href="#cb1-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-330"><a href="#cb1-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-331"><a href="#cb1-331" aria-hidden="true" tabindex="-1"></a>Q4 asks respondents to estimate the price of a non-exclusive license for the photograph used in the Facebook advertisement. After trimming the top 1% of responses to remove outlier estimates, median license price estimates were <span class="in">`r ca_price_md_c`</span> for the Control, <span class="in">`r ca_price_md_a`</span> for Short (A), and <span class="in">`r ca_price_md_b`</span> for Full + Primer (B). Mean estimates --- which are pulled upward by the right-skewed distribution typical of open-ended price questions --- were <span class="in">`r ca_price_m_c`</span>, <span class="in">`r ca_price_m_a`</span>, and <span class="in">`r ca_price_m_b`</span>, respectively. The Kruskal-Wallis test was <span class="in">`r ifelse(ca_kw_price$p.value &lt; 0.05, "significant", "not significant")`</span> ($\chi^2$(<span class="in">`r ca_kw_price$parameter`</span>) = <span class="in">`r fmt(ca_kw_price$statistic)`</span>, *p* = <span class="in">`r fmtp(ca_kw_price$p.value)`</span>). Pairwise VDA effect sizes are reported in @tbl-ca-price-vda.</span>
<span id="cb1-332"><a href="#cb1-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-333"><a href="#cb1-333" aria-hidden="true" tabindex="-1"></a>The divergence between means and medians is informative: it reflects a long right tail of respondents who estimated very high commercial licensing fees, consistent with the scenario's high-visibility, high-impression advertising context. Commercial stock photography licenses for advertisements with national reach can range from hundreds to thousands of dollars, and the median estimates suggest that respondents' intuitions about commercial licensing value are broadly calibrated to market reality.</span>
<span id="cb1-334"><a href="#cb1-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-335"><a href="#cb1-335" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.4.6 Summary {#sec-ca-summary}</span></span>
<span id="cb1-336"><a href="#cb1-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-337"><a href="#cb1-337" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip}</span>
<span id="cb1-338"><a href="#cb1-338" aria-hidden="true" tabindex="-1"></a><span class="fu">## Key Findings --- Commercial Advertising</span></span>
<span id="cb1-339"><a href="#cb1-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-340"><a href="#cb1-340" aria-hidden="true" tabindex="-1"></a>The Commercial Advertising scenario is the study's clearest case of **uniform infringement**: the CC BY-NC 4.0 license explicitly prohibits commercial use, so the bike shop's Facebook advertisement infringes under all three conditions. Any between-group differences reflect how CC licensing *information* shapes perceptions of an act whose legal status does not change. The key findings are:</span>
<span id="cb1-341"><a href="#cb1-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-342"><a href="#cb1-342" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Uniformly infringing scenario confirmed.** All group means for Q1--Q3 sit in the moderate-to-high range of the 7-point scale, confirming that respondents across all conditions recognize commercial advertising use of a copyrighted photograph as carrying meaningful legal risk. The high baseline in the Control (C) group (Q1 M = <span class="in">`r ca_q1_c`</span>, Q2 M = <span class="in">`r ca_q2_c`</span>) indicates that respondents associate high-visibility commercial use with legal exposure regardless of licensing information.</span>
<span id="cb1-343"><a href="#cb1-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-344"><a href="#cb1-344" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**CC signaling, not legal change.** Unlike the Public Domain scenario (where treatment information clarifies the absence of copyright) or Filesharing (where the license may alter the infringement analysis), the Commercial Advertising scenario isolates the *signaling* function of CC licensing. Treatment effects here cannot be attributed to changes in legal status --- the NonCommercial clause does not excuse commercial use. Any observed differences reflect how the presence and detail of licensing information shapes respondent perceptions.</span>
<span id="cb1-345"><a href="#cb1-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-346"><a href="#cb1-346" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**NonCommercial clause paradox.** The CC BY-NC license's explicit NonCommercial restriction creates a potential paradox: rather than reducing perceived risk (as CC information does in non-infringing scenarios), the restriction may *increase* perceived risk by signaling that the licensor specifically anticipated and prohibited commercial use. `r ifelse(ca_kw_q1$p.value &lt; 0.05, paste0("The significant between-group difference on Q1 (Kruskal-Wallis *p* = ", fmtp(ca_kw_q1$p.value), ") is consistent with this signaling mechanism."), "The between-group differences on Q1, however, did not reach significance, suggesting that the paradox may not manifest strongly in perceived likelihood.")`</span>
<span id="cb1-347"><a href="#cb1-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-348"><a href="#cb1-348" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Pricing patterns reflect commercial context.** License price estimates (median: Control = <span class="in">`r ca_price_md_c`</span>, Short (A) = <span class="in">`r ca_price_md_a`</span>, Full + Primer (B) = <span class="in">`r ca_price_md_b`</span>) are calibrated to the commercial advertising context, with the right-skewed distribution reflecting respondents who anchored on the high-visibility, high-impression nature of the use.</span>
<span id="cb1-349"><a href="#cb1-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-350"><a href="#cb1-350" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**Law--preference gap direction.** <span class="in">`r if (ca_delta_all_pos) "All three groups' Delta values were positive, indicating that respondents across all conditions perceived current law as imposing stricter consequences for commercial advertising infringement than they personally preferred. This suggests that even for a clearly infringing commercial use, respondents' normative preferences are somewhat more lenient than their perceptions of what the law currently requires." else "Delta values were mixed across groups, indicating no uniform direction in the law--preference gap for commercial advertising infringement."`</span> <span class="in">`r ifelse(ca_wilcox_all_sig, "Within-group Wilcoxon tests confirm this gap is significant for all three treatment conditions individually.", ifelse(ca_wilcox_any_sig, "Within-group Wilcoxon tests confirm this gap is significant for at least one treatment condition.", "Within-group Wilcoxon tests did not confirm a significant gap for any individual treatment condition."))`</span></span>
<span id="cb1-351"><a href="#cb1-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-352"><a href="#cb1-352" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**Normative stability.** Q3 means were relatively stable across conditions compared to Q2, suggesting that CC licensing information primarily shapes perceptions of the legal status quo rather than underlying moral intuitions about the appropriate severity of consequences for commercial infringement.</span>
<span id="cb1-353"><a href="#cb1-353" aria-hidden="true" tabindex="-1"></a>:::</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ludist/cc-survey/edit/main/_scenarios/ca.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/ludist/cc-survey/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>