<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Brand Recognition – Creative Commons Recognition and Copyright Infringement Perceptions Survey Experiment</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07-scenarios.html" rel="next">
<link href="./05-population.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-725ff378461d03fdd1d6ea4db46cc69a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked slimcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./06-brand.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Brand Recognition</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Creative Commons Recognition and Copyright Infringement Perceptions Survey Experiment</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ludist/cc-survey" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Experimental Design &amp; Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-codebook.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Codebook &amp; Variable Dictionary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Validation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-randomization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Randomization Check</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-population.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sample v. Population Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-brand.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Brand Recognition</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-scenarios.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Factorial Vignette Analysis Overview</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_scenarios/pd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.1 Public Domain</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_scenarios/pu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.2 Personal Use</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_scenarios/eu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.3 Educational Use</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_scenarios/ca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.4 Commercial Advertising</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_scenarios/ls.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.5 Large Scale Copying</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_scenarios/wn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.6 Wikipedia Image Search</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_scenarios/fs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.7 Filesharing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-summaries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Question Summaries</span></span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#sec-brand-overview" id="toc-sec-brand-overview" class="nav-link active" data-scroll-target="#sec-brand-overview"><span class="header-section-number">6.1</span> Overview</a></li>
  <li><a href="#sec-brand-design" id="toc-sec-brand-design" class="nav-link" data-scroll-target="#sec-brand-design"><span class="header-section-number">6.2</span> Survey Instrument Design</a></li>
  <li><a href="#sec-logo-recognition" id="toc-sec-logo-recognition" class="nav-link" data-scroll-target="#sec-logo-recognition"><span class="header-section-number">6.3</span> Logo Recognition</a></li>
  <li><a href="#sec-brand-brands" id="toc-sec-brand-brands" class="nav-link" data-scroll-target="#sec-brand-brands"><span class="header-section-number">6.4</span> Brands Tested</a></li>
  <li><a href="#sec-brand-analysis" id="toc-sec-brand-analysis" class="nav-link" data-scroll-target="#sec-brand-analysis"><span class="header-section-number">6.5</span> Brand Familiarity Analysis</a></li>
  <li><a href="#sec-brand-attention" id="toc-sec-brand-attention" class="nav-link" data-scroll-target="#sec-brand-attention"><span class="header-section-number">6.6</span> Attention Check</a></li>
  <li><a href="#sec-brand-by-group" id="toc-sec-brand-by-group" class="nav-link" data-scroll-target="#sec-brand-by-group"><span class="header-section-number">6.7</span> CC Familiarity by Group</a></li>
  <li><a href="#sec-brand-summary-findings" id="toc-sec-brand-summary-findings" class="nav-link" data-scroll-target="#sec-brand-summary-findings"><span class="header-section-number">6.8</span> Summary</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/ludist/cc-survey/edit/main/06-brand.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/ludist/cc-survey/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Brand Recognition</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-brand-overview" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="sec-brand-overview"><span class="header-section-number">6.1</span> Overview</h2>
<p>Both the adoption of Creative Commons licensing and compliance with its terms depend on public recognition of the CC brand. This Chapter reports two complementary measures of CC brand awareness collected <em>before</em> respondents were exposed to any experimental treatment:</p>
<ol type="1">
<li>a logo identification task, in which respondents viewed the CC logo alongside control logos and indicated whether they recognized each brand; and</li>
<li>a brand familiarity battery, in which respondents rated their understanding of Creative Commons and three reference brands on a 1–5 Likert-type scale.</li>
</ol>
<p>Together, these measures establish the baseline level of CC recognition in the sample. Because the brand questions preceded treatment exposure, they capture pre-existing awareness rather than any effect of the experimental manipulation. The results have direct implications for interpreting the scenario analyses in <a href="./07-scenarios.html">Chapter 7</a>: if most respondents are unfamiliar with Creative Commons at baseline, then observed differences in infringement perceptions between treatment groups reflect the information provided in the experimental vignettes rather than prior knowledge.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Scope and Sample.</strong> This Chapter reports data from Groups A, B, and C (<em>n</em> = 1222). The B1 Educational Use supplement is excluded because B1 participants did not complete the brand recognition battery. <em>See</em> <a href="./02-codebook.html#sec-b1">Codebook §2.1.3</a> for B1 details.</p>
<p>The Chapter covers both <strong>logo recognition</strong> (RQ 1.1: Can respondents identify the CC logo?) and <strong>brand familiarity</strong> (RQ 1.2: How familiar are respondents with Creative Commons as a brand?). <em>See</em> <a href="./02-codebook.html#sec-brand">Codebook, Brand Recognition</a> for variable definitions (<code>IDCC</code>, <code>IDCC-CAT</code>, <code>CCREC</code>, <code>BRANDSKILLS_1–4</code>).</p>
</div>
</div>
</section>
<section id="sec-brand-design" class="level2 page-columns page-full" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="sec-brand-design"><span class="header-section-number">6.2</span> Survey Instrument Design</h2>
<p>The brand familiarity battery was adapted from Hargittai and Hsieh’s (2012) internet skills measure, which embeds target items among reference items to reduce strategic response inflation.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Rather than asking about Creative Commons in isolation, which could prime respondents to overstate their familiarity, the instrument presents four brands in random order within a single matrix question:</p>
<div class="no-row-height column-margin column-container"><div id="fn1"><p><sup>1</sup>&nbsp;Eszter Hargittai &amp; Yuli Patrick Hsieh, <em>Succinct Survey Measures of Web-Use Skills</em>, 30 <strong>Soc. Sci. Computer Rev.</strong> 95 (2012).</p></div></div><table class="table">
<thead>
<tr class="header">
<th>Brand</th>
<th>Role in Design</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Creative Commons</td>
<td>Brand of interest</td>
</tr>
<tr class="even">
<td>Byteyield</td>
<td>Fabricated brand (attention check)</td>
</tr>
<tr class="odd">
<td>Microsoft</td>
<td>High-recognition ceiling reference</td>
</tr>
<tr class="even">
<td>Mozilla</td>
<td>Moderate-recognition comparison</td>
</tr>
</tbody>
</table>
<p><strong>Byteyield</strong> is a fabricated brand created for this study. Its name was generated to sound plausible as a technology company and verified through Google search and USPTO TESS trademark search to confirm that no real brand existed under that name. A respondent who reports familiarity with Byteyield is likely responding inattentively or strategically inflating their claimed knowledge.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn2"><p><sup>2</sup>&nbsp;<em>See</em> Jesse Chandler &amp; Gabriele Paolacci. “Lie for a Dime: When Most Prescreening Responses Are Honest but Most Study Participants Are Impostors.” 8 <strong>Soc. Psychological &amp; Personality Sci.</strong> 500 (2017); Katelyn Sharpe Wessling, Joel Huber, &amp; Oded Netzer. “MTurk Character Misrepresentation: Assessment and Solutions.” 44 <strong>J. Cons. Res.</strong> 211 (2017).</p></div></div><p><strong>Microsoft</strong> and <strong>Mozilla</strong> serve as anchoring references: Microsoft provides a near-universal recognition ceiling, while Mozilla (the organization behind Firefox) occupies a middle ground because it is well-known among technology users but less universally recognized than Microsoft. Together, these anchors establish a credibility spectrum against which CC familiarity can be meaningfully interpreted. <em>See</em> <a href="./02-codebook.html#sec-brandskills">Codebook, BRANDSKILLS</a> for scale definitions and <a href="./02-codebook.html#sec-skills-scale">§2.6</a> for the 1–5 response scale (None / Little / Some / Good / Full).</p>
</section>
<section id="sec-logo-recognition" class="level2 page-columns page-full" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="sec-logo-recognition"><span class="header-section-number">6.3</span> Logo Recognition</h2>
<p>Before the brand familiarity battery, respondents completed a logo identification task. Four logos were displayed in random order and respondents answered: <em>“Do you know the brand associated with this logo?”</em> (Yes / No). Including multiple logos, such as the McDonald’s golden arches as a near-universal reference and a novel fabricated logo as a floor control, reduced the likelihood that respondents would strategically inflate their claimed recognition of any single logo.</p>
<p>Respondents who answered “Yes” for the Creative Commons logo were then prompted with a free-text entry: <em>“Please identify the brand you associate with this logo.”</em> These responses were hand-coded into six categories. <em>See</em> <a href="./02-codebook.html#sec-idcc-cat">Codebook, IDCC-CAT</a> for the categorization scheme.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-logo-recognition" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-logo-recognition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<colgroup>
<col style="width: 27%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Logo</th>
<th style="text-align: right;">Recognized (n)</th>
<th style="text-align: right;">Recognized (%)</th>
<th style="text-align: right;">Not Recognized (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">McDonald’s</td>
<td style="text-align: right;">1217</td>
<td style="text-align: right;">99.6</td>
<td style="text-align: right;">0.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Creative Commons</td>
<td style="text-align: right;">262</td>
<td style="text-align: right;">21.4</td>
<td style="text-align: right;">78.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Firefox</td>
<td style="text-align: right;">1050</td>
<td style="text-align: right;">85.9</td>
<td style="text-align: right;">14.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Novel (fabricated)</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.7</td>
<td style="text-align: right;">99.3</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-logo-recognition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.1: Logo recognition rates across all four brands. McDonald’s provides a near-ceiling reference; the novel (fabricated) logo provides a floor control.
</figcaption>
</figure>
</div>
</div>
<p>Among the 262 respondents who claimed to recognize the Creative Commons logo, free-text identification responses were coded into six categories:</p>
<div class="cell" data-layout-align="center">
<div id="tbl-cc-misid" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-cc-misid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Identification</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Creative Commons (correct)</td>
<td style="text-align: right;">85</td>
<td style="text-align: right;">32.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Closed Captioning</td>
<td style="text-align: right;">84</td>
<td style="text-align: right;">32.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Comedy Central</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">16.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chanel</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">9.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Copyright</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">6.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">3.4</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-cc-misid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.2: CC logo misidentification breakdown. Categorization of free-text responses among respondents who claimed to recognize the Creative Commons logo.
</figcaption>
</figure>
</div>
</div>
<div class="cell page-columns page-full" data-layout-align="center">
<div class="cell-output-display page-columns page-full">
<div id="fig-logo-recognition" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-logo-recognition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<img src="06-brand_files/figure-html/fig-logo-recognition-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img column-page-right" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-logo-recognition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: Logo recognition rates. The gap between claimed CC recognition and correct identification highlights the visual ambiguity of the ‘CC’ mark.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Logo Recognition Interpretation.</strong> McDonald’s, as expected, achieved near-ceiling recognition (99.6%), confirming that respondents understood the task and were attending to the logos. The fabricated novel logo serves as a floor control; its recognition rate (0.7%) captures the base rate of false positive claims.</p>
<p>For Creative Commons, 21.4% of respondents claimed to recognize the logo, but only 7% correctly identified it as Creative Commons — meaning roughly 68% of claimants were mistaken. The most common misidentification was <em>Closed Captioning</em>, reflecting the visual similarity of the “CC” letterform. Other misidentifications included Comedy Central, Chanel, and generic copyright associations. <em>See</em> <a href="./02-codebook.html#sec-idcc-cat">Codebook, IDCC-CAT</a> for the full categorization scheme.</p>
<p><strong>Key Takeaway:</strong> True CC logo recognition is very low (7%), even lower than brand name familiarity (26% rated “Some” understanding or better on the BRANDSKILLS scale).</p>
</div>
</div>
</div>
</section>
<section id="sec-brand-brands" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="sec-brand-brands"><span class="header-section-number">6.4</span> Brands Tested</h2>
<p>Respondents rated their familiarity with four brands on a 1–5 Likert-type scale (1 = None, 5 = Full understanding). The four brands serve distinct roles in the experimental design:</p>
<table class="table">
<thead>
<tr class="header">
<th>Brand</th>
<th>Variable</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Creative Commons</td>
<td><code>BRANDSKILLS_1</code></td>
<td>Brand of interest</td>
</tr>
<tr class="even">
<td>Byteyield</td>
<td><code>BRANDSKILLS_2</code></td>
<td>Fabricated brand (attention check)</td>
</tr>
<tr class="odd">
<td>Microsoft</td>
<td><code>BRANDSKILLS_3</code></td>
<td>High-recognition ceiling</td>
</tr>
<tr class="even">
<td>Mozilla</td>
<td><code>BRANDSKILLS_4</code></td>
<td>Moderate-recognition comparison</td>
</tr>
</tbody>
</table>
<section id="sec-brand-howto" class="level3" data-number="6.4.1">
<h3 data-number="6.4.1" class="anchored" data-anchor-id="sec-brand-howto"><span class="header-section-number">6.4.1</span> How to Read the Likert Plot</h3>
<p>The Likert plot below is a <strong>diverging stacked bar chart</strong> centered at the scale midpoint. Each bar represents one brand, and the colored segments show the proportion of respondents at each familiarity level:</p>
<ul>
<li><strong>Left of center</strong> = lower familiarity (None, Little) — bars extending leftward indicate less recognition</li>
<li><strong>Right of center</strong> = higher familiarity (Good, Full) — bars extending rightward indicate greater recognition</li>
<li><strong>Bar width</strong> reflects the proportion of respondents at each level</li>
</ul>
<p><strong>Quick Interpretation:</strong> A brand with bars mostly extending to the right is well-known; a brand with bars mostly extending to the left is unfamiliar to most respondents. The relative positions reveal the expected ordering: Microsoft dominates the right side, Byteyield (fabricated) dominates the left, and Creative Commons and Mozilla fall between these anchors.</p>
</section>
</section>
<section id="sec-brand-analysis" class="level2 page-columns page-full" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="sec-brand-analysis"><span class="header-section-number">6.5</span> Brand Familiarity Analysis</h2>
<section id="sec-brand-likert" class="level3 page-columns page-full" data-number="6.5.1">
<h3 data-number="6.5.1" class="anchored" data-anchor-id="sec-brand-likert"><span class="header-section-number">6.5.1</span> Familiarity Plot</h3>
<div class="cell page-columns page-full" data-layout-align="center">
<div class="cell-output-display page-columns page-full">
<div id="fig-brand-likert" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-brand-likert-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<img src="06-brand_files/figure-html/fig-brand-likert-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img column-page-right" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brand-likert-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2: Brand familiarity Likert plot. Stacked bars show the distribution of familiarity ratings (1–5 scale) for each brand. Creative Commons (brand of interest), Microsoft (high-recognition baseline), Mozilla (moderate-recognition comparison), Byteyield (fabricated attention check).
</figcaption>
</figure>
</div>
</div>
</div>
<p>The plot confirms the expected brand recognition ordering. Microsoft anchors the high end, with the vast majority of respondents rating their familiarity at “Good” or “Full” (mean = 4.40, High). Mozilla occupies the middle — recognizable to most respondents but with more spread across the familiarity scale (mean = 3.65, Moderate). Creative Commons clusters heavily on the left side of the chart: 59.6% of respondents reported <em>no</em> familiarity whatsoever, and only 26% rated their understanding at “Some” or better (mean = 1.84, Very Low). Byteyield, the fabricated brand, anchors the lowest end (mean = 1.14, Very Low), confirming that respondents were not indiscriminately inflating their claimed knowledge.</p>
</section>
<section id="sec-brand-summary" class="level3" data-number="6.5.2">
<h3 data-number="6.5.2" class="anchored" data-anchor-id="sec-brand-summary"><span class="header-section-number">6.5.2</span> Summary Statistics</h3>
<div class="cell" data-layout-align="center">
<div id="tbl-brand-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-brand-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 22%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Brand</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Max</th>
<th style="text-align: left;">Recognition_Level</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">BRANDSKILLS_1</td>
<td style="text-align: left;">Creative Commons</td>
<td style="text-align: right;">1.84</td>
<td style="text-align: right;">1.21</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Very Low</td>
</tr>
<tr class="even">
<td style="text-align: left;">BRANDSKILLS_2</td>
<td style="text-align: left;">Byteyield</td>
<td style="text-align: right;">1.14</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Very Low</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BRANDSKILLS_3</td>
<td style="text-align: left;">Microsoft</td>
<td style="text-align: right;">4.40</td>
<td style="text-align: right;">0.70</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">High</td>
</tr>
<tr class="even">
<td style="text-align: left;">BRANDSKILLS_4</td>
<td style="text-align: left;">Mozilla</td>
<td style="text-align: right;">3.65</td>
<td style="text-align: right;">1.21</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Moderate</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-brand-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.3: Brand familiarity summary statistics. Mean, SD, median, and qualitative recognition level for each brand on the 1–5 scale (None / Little / Some / Good / Full).
</figcaption>
</figure>
</div>
</div>
<p>The CC familiarity distribution is heavily left-skewed, with a median of 1 and a mean of 1.84. Most members of the general public have little to no familiarity with Creative Commons licensing. For the experimental design, this low baseline means that most respondents encounter the CC license markings <em>for the first time</em> during the treatment vignettes, strengthening the interpretation that between-group differences in the scenario analyses reflect the treatment information rather than prior knowledge.</p>
</section>
</section>
<section id="sec-brand-attention" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="sec-brand-attention"><span class="header-section-number">6.6</span> Attention Check</h2>
<p>The fabricated brand Byteyield provides an embedded attention check. Because no real brand exists under this name, any reported familiarity beyond the floor suggests either inattentive responding or strategic overclaiming. A meaningful gap between CC familiarity and Byteyield familiarity provides evidence that respondents’ CC familiarity ratings reflect genuine self-assessment rather than random or inflated responses.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>✓ Attention check passed: fabricated brand (Byteyield) has appropriately low recognition.</code></pre>
</div>
</div>
<p>The CC–Byteyield gap in mean familiarity is 0.71 points (CC mean = 1.84 vs.&nbsp;Byteyield mean = 1.14). This gap confirms that the modest CC familiarity observed above reflects genuine variation in brand awareness, not response noise. Respondents can and do distinguish between brands they have some awareness of and brands they have never encountered.</p>
</section>
<section id="sec-brand-by-group" class="level2 page-columns page-full" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="sec-brand-by-group"><span class="header-section-number">6.7</span> CC Familiarity by Group</h2>
<p>If randomization succeeded, CC familiarity should not differ systematically across the three treatment groups. The brand familiarity question precedes treatment exposure in the survey flow, so any between-group difference would indicate a pre-treatment confound — a threat to internal validity independent of the demographic balance confirmed in <a href="./04-randomization.html">Chapter 4</a>. This test parallels the covariate balance logic applied to demographics: just as age, income, and education should be balanced across groups, so too should pre-existing brand awareness.</p>
<div class="cell page-columns page-full" data-layout-align="center">
<div class="cell-output-display page-columns page-full">
<div id="fig-brand-cc-by-group" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-brand-cc-by-group-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<img src="06-brand_files/figure-html/fig-brand-cc-by-group-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img column-page-right" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brand-cc-by-group-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.3: Creative Commons brand familiarity by treatment group. The brand question precedes treatment exposure; a non-significant result confirms that pre-existing CC awareness does not confound the experimental design.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>CC familiarity by group interpretation.</strong> Kruskal-Wallis <em>p</em> = 0.166. The three treatment groups do not differ significantly in pre-existing CC familiarity, confirming that brand awareness is balanced across conditions. This result, combined with the demographic balance confirmed in <a href="./04-randomization.html">Chapter 4</a>, supports a causal interpretation of between-group differences in the scenario analyses.</p>
</div>
</div>
</div>
</section>
<section id="sec-brand-summary-findings" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="sec-brand-summary-findings"><span class="header-section-number">6.8</span> Summary</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Key Findings — Brand Recognition
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p><strong>CC familiarity is low.</strong> 59.6% of respondents reported no familiarity with Creative Commons (BRANDSKILLS_1 = 1, “None”), and only 26% rated their understanding at “Some” or better (mean = 1.84, recognition level: Very Low).</p></li>
<li><p><strong>Logo recognition confirms low awareness.</strong> Only 7% of respondents correctly identified the Creative Commons logo — roughly 68% of those who <em>claimed</em> to recognize it were mistaken. Common misidentifications (Closed Captioning, Comedy Central, Chanel) reveal the visual ambiguity of the “CC” mark. True logo recognition is even lower than self-reported brand name familiarity.</p></li>
<li><p><strong>The fabricated brand test passes.</strong> Byteyield, the fabricated attention check brand, shows appropriately low familiarity (mean = 1.14, Very Low). The CC–Byteyield gap of 0.71 points confirms that respondents’ CC familiarity ratings reflect genuine self-assessment rather than random or inflated responses.</p></li>
<li><p><strong>Microsoft anchors the ceiling; Mozilla occupies the middle.</strong> Microsoft achieves near-universal recognition (mean = 4.40, High), while Mozilla occupies a credible middle position (mean = 3.65, Moderate). These reference points confirm that the 1–5 scale discriminates meaningfully across the recognition spectrum.</p></li>
<li><p><strong>CC familiarity is balanced across treatment groups.</strong> Kruskal-Wallis <em>p</em> = 0.166, confirming that pre-existing CC awareness does not differ significantly across Groups A, B, and C. Combined with <a href="./04-randomization.html">Chapter 4</a>’s demographic balance results, this supports a causal interpretation of between-group differences in the <a href="./07-scenarios.html">scenario analyses</a>.</p></li>
<li><p><strong>Implications for the scenario analyses.</strong> The low baseline means that most respondents encounter the CC license notice for the first time during the experimental vignettes. Treatment effects therefore operate on a largely uninformed population — a condition that strengthens the ecological validity of the study (most real-world encounters with CC-licensed content likely involve users with little prior CC knowledge) but also means the results reflect <em>first impressions</em> rather than informed judgments.</p></li>
</ol>
</div>
</div>


<!-- -->

</section>


</main> <!-- /main -->
<script>
/*
 * sidebar-toc.js — CC Survey Online Appendix
 *
 * Quarto Book sidebar accordion for within-page sections.
 *
 * Actual Quarto behavior (confirmed from rendered HTML):
 *   - toc-location: left places the TOC as <nav id="TOC"> inside #quarto-sidebar,
 *     AFTER the chapter list. The <ul> has class="collapse" (Bootstrap-hidden).
 *   - There is NO #quarto-sidebar-toc-left element in Quarto 1.8.
 *   - CSS hides the nav#TOC block; this script moves the links to nest under
 *     the active chapter <li>, achieving accordion display.
 *
 * Edge case handled: chapters with a body H1 (e.g. {.unnumbered} intro) produce
 * a TOC where the H1 is the sole top-level link and H2s are nested under it.
 * In that case we skip the H1 (which duplicates the sidebar chapter entry) and
 * promote the nested H2 links instead.
 */
(function () {
  'use strict';

  function injectAuthorLine() {
    // Add author name below the book title/subtitle, above the search bar
    if (document.querySelector('.sidebar-author')) return;

    var sidebar = document.getElementById('quarto-sidebar');
    if (!sidebar) return;

    // Insert after subtitle if present, else after title
    var anchor = sidebar.querySelector('.sidebar-subtitle')
              || sidebar.querySelector('.sidebar-title');
    if (!anchor) return;

    var authorDiv = document.createElement('div');
    authorDiv.className = 'sidebar-author';
    authorDiv.innerHTML = 'Thomas H. Rousse<br>J.D., Ph.D.';

    // Insert between subtitle/title and search bar (equidistant)
    var search = sidebar.querySelector('#quarto-search');
    if (search) {
      search.parentNode.insertBefore(authorDiv, search);
    } else {
      anchor.parentNode.insertBefore(authorDiv, anchor.nextSibling);
    }
  }

  function injectSections() {
    // 1. Find the active chapter <li> in the sidebar
    var activeLink = document.querySelector('#quarto-sidebar .sidebar-link.active');
    if (!activeLink) return;
    var activeItem = activeLink.closest('li.sidebar-item');
    if (!activeItem) return;

    // 2. Find the TOC nav that Quarto placed inside the sidebar
    var tocNav = document.querySelector('#quarto-sidebar nav#TOC');
    if (!tocNav) return;

    // 3. Get all section links (already depth-filtered by Quarto's toc-depth: 2)
    var allLinks = Array.from(tocNav.querySelectorAll('a[data-scroll-target]'));

    // Keep only top-level links (no grandparent <li>)
    var topLevelLinks = allLinks.filter(function (link) {
      var parentLi = link.closest('li');
      if (!parentLi) return false;
      var grandparentLi = parentLi.parentElement && parentLi.parentElement.closest('li');
      return !grandparentLi;
    });

    // Edge case: body-H1 chapters (e.g. {.unnumbered} intro).
    // The sole top-level link IS the chapter title — injecting it would duplicate
    // the sidebar chapter entry. Detect this and promote the nested H2 links instead.
    var chapterText = activeLink.textContent.replace(/^\d+[\.\s]+/, '').trim();
    if (
      topLevelLinks.length === 1 &&
      topLevelLinks[0].textContent.trim() === chapterText
    ) {
      // Promote one level deeper (the H2s nested under the H1)
      topLevelLinks = allLinks.filter(function (link) {
        var parentLi = link.closest('li');
        if (!parentLi) return false;
        var grandparentLi = parentLi.parentElement && parentLi.parentElement.closest('li');
        if (!grandparentLi) return false;
        var greatGrandparentLi = grandparentLi.parentElement && grandparentLi.parentElement.closest('li');
        return !greatGrandparentLi;
      });
    }

    if (topLevelLinks.length === 0) return;

    // 4. Build the nested section list
    var sectionList = document.createElement('ul');
    sectionList.className = 'sidebar-sections list-unstyled';

    topLevelLinks.forEach(function (link) {
      var li = document.createElement('li');
      li.className = 'sidebar-section-item';
      // Replace nav-link class with our sidebar class; keep data-scroll-target
      link.className = 'sidebar-section-link';
      li.appendChild(link); // move (not clone) to preserve Quarto scroll-tracking refs
      sectionList.appendChild(li);
    });

    // 5. Insert immediately after the active chapter <li>
    activeItem.parentNode.insertBefore(sectionList, activeItem.nextSibling);

    // 6. tocNav is already hidden via CSS; no further action needed
  }

  function init() {
    injectAuthorLine();
    injectSections();
  }

  if (document.readyState === 'complete') {
    init();
  } else {
    window.addEventListener('load', init);
  }
}());
</script>
<script>
/*
 * scenario-numbering.js — CC Survey Online Appendix
 *
 * Renumbers tables, figures, and cross-reference links in unnumbered
 * scenario sub-chapters from bare sequential numbers (Table 1, Figure 1)
 * to 3-level format (Table 7.1.1, Figure 7.1.1).
 *
 * Parent chapter: 07-scenarios.qmd = Chapter 7
 * Sub-chapters: pd=1, pu=2, eu=3, ca=4, ls=5, wn=6, fs=7
 *
 * Runs after DOM load. Only modifies scenario pages.
 */
document.addEventListener('DOMContentLoaded', function() {
  var scenarios = {pd:1, pu:2, eu:3, ca:4, ls:5, wn:6, fs:7};
  var path = window.location.pathname;
  var scenarioIdx = null;

  for (var code in scenarios) {
    if (path.match(new RegExp('[/\\\\]' + code + '\\.html$'))) {
      scenarioIdx = scenarios[code];
      break;
    }
  }

  if (!scenarioIdx) return;

  var prefix = '7.' + scenarioIdx + '.';

  // ── Figure captions ──────────────────────────────────────────
  // Quarto renders: Figure&nbsp;N: caption text
  document.querySelectorAll('figcaption').forEach(function(cap) {
    cap.innerHTML = cap.innerHTML.replace(
      /Figure(&nbsp;|\u00A0|\s)(\d+)(?![\d.])/g,
      function(m, sp, n) { return 'Figure' + sp + prefix + n; }
    );
  });

  // ── Cross-reference links ────────────────────────────────────
  // Quarto renders: <a class="quarto-xref">Table&nbsp;<span>N</span></a>
  // or:             <a class="quarto-xref">Figure&nbsp;<span>N</span></a>
  document.querySelectorAll('a.quarto-xref').forEach(function(link) {
    var spans = link.querySelectorAll('span');
    if (spans.length === 0) return;

    // The last span contains the bare number
    var numSpan = spans[spans.length - 1];
    var num = numSpan.textContent.trim();
    if (/^\d+$/.test(num) && !num.includes('.')) {
      // Check the text before the span is "Table" or "Figure"
      var text = link.textContent;
      if (/^(Table|Figure)/.test(text)) {
        numSpan.textContent = prefix + num;
      }
    }
  });
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05-population.html" class="pagination-link" aria-label="Sample v. Population Analysis">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sample v. Population Analysis</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07-scenarios.html" class="pagination-link" aria-label="Factorial Vignette Analysis Overview">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Factorial Vignette Analysis Overview</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Brand Recognition"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="in">```{r setup, include=FALSE}</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"_common.R"</span>))</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="in">```{r brand-analysis}</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>brand_results <span class="ot">&lt;-</span> <span class="fu">check_brand_recognition</span>(</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">data       =</span> survey_data,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">brand_cols =</span> <span class="fu">c</span>(<span class="st">"BRANDSKILLS_1"</span>, <span class="st">"BRANDSKILLS_2"</span>, <span class="st">"BRANDSKILLS_3"</span>, <span class="st">"BRANDSKILLS_4"</span>),</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">create_plot =</span> <span class="cn">TRUE</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="in">```{r brand-helpers, include=FALSE}</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Brand familiarity summary statistics (from check_brand_recognition output)</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>cc_mean   <span class="ot">&lt;-</span> brand_results<span class="sc">$</span>summary<span class="sc">$</span>Mean[brand_results<span class="sc">$</span>summary<span class="sc">$</span>Brand <span class="sc">==</span> <span class="st">"Creative Commons"</span>]</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>cc_sd     <span class="ot">&lt;-</span> brand_results<span class="sc">$</span>summary<span class="sc">$</span>SD[brand_results<span class="sc">$</span>summary<span class="sc">$</span>Brand <span class="sc">==</span> <span class="st">"Creative Commons"</span>]</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>cc_median <span class="ot">&lt;-</span> brand_results<span class="sc">$</span>summary<span class="sc">$</span>Median[brand_results<span class="sc">$</span>summary<span class="sc">$</span>Brand <span class="sc">==</span> <span class="st">"Creative Commons"</span>]</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>cc_level  <span class="ot">&lt;-</span> brand_results<span class="sc">$</span>summary<span class="sc">$</span>Recognition_Level[brand_results<span class="sc">$</span>summary<span class="sc">$</span>Brand <span class="sc">==</span> <span class="st">"Creative Commons"</span>]</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>by_mean   <span class="ot">&lt;-</span> brand_results<span class="sc">$</span>summary<span class="sc">$</span>Mean[brand_results<span class="sc">$</span>summary<span class="sc">$</span>Brand <span class="sc">==</span> <span class="st">"Byteyield"</span>]</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>by_sd     <span class="ot">&lt;-</span> brand_results<span class="sc">$</span>summary<span class="sc">$</span>SD[brand_results<span class="sc">$</span>summary<span class="sc">$</span>Brand <span class="sc">==</span> <span class="st">"Byteyield"</span>]</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>by_median <span class="ot">&lt;-</span> brand_results<span class="sc">$</span>summary<span class="sc">$</span>Median[brand_results<span class="sc">$</span>summary<span class="sc">$</span>Brand <span class="sc">==</span> <span class="st">"Byteyield"</span>]</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>by_level  <span class="ot">&lt;-</span> brand_results<span class="sc">$</span>summary<span class="sc">$</span>Recognition_Level[brand_results<span class="sc">$</span>summary<span class="sc">$</span>Brand <span class="sc">==</span> <span class="st">"Byteyield"</span>]</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>ms_mean   <span class="ot">&lt;-</span> brand_results<span class="sc">$</span>summary<span class="sc">$</span>Mean[brand_results<span class="sc">$</span>summary<span class="sc">$</span>Brand <span class="sc">==</span> <span class="st">"Microsoft"</span>]</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>ms_sd     <span class="ot">&lt;-</span> brand_results<span class="sc">$</span>summary<span class="sc">$</span>SD[brand_results<span class="sc">$</span>summary<span class="sc">$</span>Brand <span class="sc">==</span> <span class="st">"Microsoft"</span>]</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>ms_median <span class="ot">&lt;-</span> brand_results<span class="sc">$</span>summary<span class="sc">$</span>Median[brand_results<span class="sc">$</span>summary<span class="sc">$</span>Brand <span class="sc">==</span> <span class="st">"Microsoft"</span>]</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>ms_level  <span class="ot">&lt;-</span> brand_results<span class="sc">$</span>summary<span class="sc">$</span>Recognition_Level[brand_results<span class="sc">$</span>summary<span class="sc">$</span>Brand <span class="sc">==</span> <span class="st">"Microsoft"</span>]</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>mz_mean   <span class="ot">&lt;-</span> brand_results<span class="sc">$</span>summary<span class="sc">$</span>Mean[brand_results<span class="sc">$</span>summary<span class="sc">$</span>Brand <span class="sc">==</span> <span class="st">"Mozilla"</span>]</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>mz_sd     <span class="ot">&lt;-</span> brand_results<span class="sc">$</span>summary<span class="sc">$</span>SD[brand_results<span class="sc">$</span>summary<span class="sc">$</span>Brand <span class="sc">==</span> <span class="st">"Mozilla"</span>]</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>mz_median <span class="ot">&lt;-</span> brand_results<span class="sc">$</span>summary<span class="sc">$</span>Median[brand_results<span class="sc">$</span>summary<span class="sc">$</span>Brand <span class="sc">==</span> <span class="st">"Mozilla"</span>]</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>mz_level  <span class="ot">&lt;-</span> brand_results<span class="sc">$</span>summary<span class="sc">$</span>Recognition_Level[brand_results<span class="sc">$</span>summary<span class="sc">$</span>Brand <span class="sc">==</span> <span class="st">"Mozilla"</span>]</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a><span class="co"># CC familiarity distribution</span></span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>brand_n          <span class="ot">&lt;-</span> <span class="fu">nrow</span>(survey_data)</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>cc_none_pct      <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="fu">sum</span>(survey_data<span class="sc">$</span>BRANDSKILLS_1 <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> brand_n, <span class="dv">1</span>)</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>cc_little_pct    <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="fu">sum</span>(survey_data<span class="sc">$</span>BRANDSKILLS_1 <span class="sc">==</span> <span class="dv">2</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> brand_n, <span class="dv">1</span>)</span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>cc_some_plus_pct <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="fu">sum</span>(survey_data<span class="sc">$</span>BRANDSKILLS_1 <span class="sc">&gt;=</span> <span class="dv">3</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> brand_n, <span class="dv">1</span>)</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a><span class="co"># CC-Byteyield gap (evidence of genuine self-assessment)</span></span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a>cc_by_gap <span class="ot">&lt;-</span> cc_mean <span class="sc">-</span> by_mean</span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a><span class="co"># Between-group test (Kruskal-Wallis for ordinal data)</span></span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a>cc_kw <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(BRANDSKILLS_1 <span class="sc">~</span> GROUP, <span class="at">data =</span> survey_data)</span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a><span class="co"># Logo recognition rates (coding: 1 = Yes, 2 = No)</span></span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a>mcd_recog_n    <span class="ot">&lt;-</span> <span class="fu">sum</span>(survey_data<span class="sc">$</span>IDMcD <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a>mcd_recog_pct  <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> mcd_recog_n <span class="sc">/</span> brand_n, <span class="dv">1</span>)</span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a>fake_recog_n   <span class="ot">&lt;-</span> <span class="fu">sum</span>(survey_data<span class="sc">$</span>IDFAKE <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a>fake_recog_pct <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> fake_recog_n <span class="sc">/</span> brand_n, <span class="dv">1</span>)</span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a>ff_recog_n     <span class="ot">&lt;-</span> <span class="fu">sum</span>(survey_data<span class="sc">$</span>IDFF <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a>ff_recog_pct   <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> ff_recog_n <span class="sc">/</span> brand_n, <span class="dv">1</span>)</span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a>cc_claimed_n   <span class="ot">&lt;-</span> <span class="fu">sum</span>(survey_data<span class="sc">$</span>IDCC <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a>cc_claimed_pct <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> cc_claimed_n <span class="sc">/</span> brand_n, <span class="dv">1</span>)</span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a><span class="co"># CC correct identification (IDCC.CAT == 1 among those who said "Yes")</span></span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a>cc_correct_n   <span class="ot">&lt;-</span> <span class="fu">sum</span>(survey_data<span class="sc">$</span>IDCC.CAT <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a>cc_correct_pct <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> cc_correct_n <span class="sc">/</span> brand_n, <span class="dv">1</span>)</span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a><span class="co"># Misidentification rate among claimants</span></span>
<span id="cb2-69"><a href="#cb2-69" aria-hidden="true" tabindex="-1"></a>cc_wrong_pct <span class="ot">&lt;-</span> <span class="cf">if</span> (cc_claimed_n <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> cc_correct_n <span class="sc">/</span> cc_claimed_n), <span class="dv">1</span>) <span class="cf">else</span> <span class="cn">NA</span></span>
<span id="cb2-70"><a href="#cb2-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-71"><a href="#cb2-71" aria-hidden="true" tabindex="-1"></a><span class="co"># Misidentification breakdown (among those who said "Yes" to IDCC)</span></span>
<span id="cb2-72"><a href="#cb2-72" aria-hidden="true" tabindex="-1"></a>cc_yes_data   <span class="ot">&lt;-</span> survey_data[survey_data<span class="sc">$</span>IDCC <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(survey_data<span class="sc">$</span>IDCC), ]</span>
<span id="cb2-73"><a href="#cb2-73" aria-hidden="true" tabindex="-1"></a>cc_cat_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="fu">factor</span>(cc_yes_data<span class="sc">$</span>IDCC.CAT, <span class="at">levels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>))</span>
<span id="cb2-74"><a href="#cb2-74" aria-hidden="true" tabindex="-1"></a>cc_cat_labels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Creative Commons (correct)"</span>, <span class="st">"Closed Captioning"</span>,</span>
<span id="cb2-75"><a href="#cb2-75" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Comedy Central"</span>, <span class="st">"Chanel"</span>, <span class="st">"Copyright"</span>, <span class="st">"Other"</span>)</span>
<span id="cb2-76"><a href="#cb2-76" aria-hidden="true" tabindex="-1"></a>cc_misid_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb2-77"><a href="#cb2-77" aria-hidden="true" tabindex="-1"></a>  <span class="at">Category =</span> cc_cat_labels,</span>
<span id="cb2-78"><a href="#cb2-78" aria-hidden="true" tabindex="-1"></a>  <span class="at">n        =</span> <span class="fu">as.integer</span>(cc_cat_counts),</span>
<span id="cb2-79"><a href="#cb2-79" aria-hidden="true" tabindex="-1"></a>  <span class="at">Pct      =</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="fu">as.integer</span>(cc_cat_counts) <span class="sc">/</span> <span class="fu">sum</span>(cc_cat_counts), <span class="dv">1</span>)</span>
<span id="cb2-80"><a href="#cb2-80" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-81"><a href="#cb2-81" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-82"><a href="#cb2-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-83"><a href="#cb2-83" aria-hidden="true" tabindex="-1"></a><span class="fu">## Overview {#sec-brand-overview}</span></span>
<span id="cb2-84"><a href="#cb2-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-85"><a href="#cb2-85" aria-hidden="true" tabindex="-1"></a>Both the adoption of Creative Commons licensing and compliance with its terms depend on public recognition of the CC brand. This Chapter reports two complementary measures of CC brand awareness collected *before* respondents were exposed to any experimental treatment: </span>
<span id="cb2-86"><a href="#cb2-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-87"><a href="#cb2-87" aria-hidden="true" tabindex="-1"></a>(1) a logo identification task, in which respondents viewed the CC logo alongside control logos and indicated whether they recognized each brand; and </span>
<span id="cb2-88"><a href="#cb2-88" aria-hidden="true" tabindex="-1"></a>(2) a brand familiarity battery, in which respondents rated their understanding of Creative Commons and three reference brands on a 1–5 Likert-type scale.</span>
<span id="cb2-89"><a href="#cb2-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-90"><a href="#cb2-90" aria-hidden="true" tabindex="-1"></a>Together, these measures establish the baseline level of CC recognition in the sample. Because the brand questions preceded treatment exposure, they capture pre-existing awareness rather than any effect of the experimental manipulation. The results have direct implications for interpreting the scenario analyses in <span class="co">[</span><span class="ot">Chapter 7</span><span class="co">](07-scenarios.qmd)</span>: if most respondents are unfamiliar with Creative Commons at baseline, then observed differences in infringement perceptions between treatment groups reflect the information provided in the experimental vignettes rather than prior knowledge.</span>
<span id="cb2-91"><a href="#cb2-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-92"><a href="#cb2-92" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb2-93"><a href="#cb2-93" aria-hidden="true" tabindex="-1"></a>**Scope and Sample.** This Chapter reports data from Groups A, B, and C (*n* = `r brand_n`). The B1 Educational Use supplement is excluded because B1 participants did not complete the brand recognition battery. *See* <span class="co">[</span><span class="ot">Codebook §2.1.3</span><span class="co">](02-codebook.qmd#sec-b1)</span> for B1 details.</span>
<span id="cb2-94"><a href="#cb2-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-95"><a href="#cb2-95" aria-hidden="true" tabindex="-1"></a>The Chapter covers both **logo recognition** (RQ 1.1: Can respondents identify the CC logo?) and **brand familiarity** (RQ 1.2: How familiar are respondents with Creative Commons as a brand?). *See* <span class="co">[</span><span class="ot">Codebook, Brand Recognition</span><span class="co">](02-codebook.qmd#sec-brand)</span> for variable definitions (<span class="in">`IDCC`</span>, <span class="in">`IDCC-CAT`</span>, <span class="in">`CCREC`</span>, <span class="in">`BRANDSKILLS_1–4`</span>).</span>
<span id="cb2-96"><a href="#cb2-96" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb2-97"><a href="#cb2-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-98"><a href="#cb2-98" aria-hidden="true" tabindex="-1"></a><span class="fu">## Survey Instrument Design {#sec-brand-design}</span></span>
<span id="cb2-99"><a href="#cb2-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-100"><a href="#cb2-100" aria-hidden="true" tabindex="-1"></a>The brand familiarity battery was adapted from Hargittai and Hsieh's (2012) internet skills measure, which embeds target items among reference items to reduce strategic response inflation.^<span class="co">[</span><span class="ot">Eszter Hargittai &amp; Yuli Patrick Hsieh, *Succinct Survey Measures of Web-Use Skills*, 30 **Soc. Sci. Computer Rev.** 95 (2012).</span><span class="co">]</span> Rather than asking about Creative Commons in isolation, which could prime respondents to overstate their familiarity, the instrument presents four brands in random order within a single matrix question:</span>
<span id="cb2-101"><a href="#cb2-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-102"><a href="#cb2-102" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Brand <span class="pp">|</span> Role in Design <span class="pp">|</span></span>
<span id="cb2-103"><a href="#cb2-103" aria-hidden="true" tabindex="-1"></a><span class="pp">|-------|---------------|</span></span>
<span id="cb2-104"><a href="#cb2-104" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Creative Commons <span class="pp">|</span> Brand of interest <span class="pp">|</span></span>
<span id="cb2-105"><a href="#cb2-105" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Byteyield <span class="pp">|</span> Fabricated brand (attention check) <span class="pp">|</span></span>
<span id="cb2-106"><a href="#cb2-106" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Microsoft <span class="pp">|</span> High-recognition ceiling reference <span class="pp">|</span></span>
<span id="cb2-107"><a href="#cb2-107" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Mozilla <span class="pp">|</span> Moderate-recognition comparison <span class="pp">|</span></span>
<span id="cb2-108"><a href="#cb2-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-109"><a href="#cb2-109" aria-hidden="true" tabindex="-1"></a>**Byteyield** is a fabricated brand created for this study. Its name was generated to sound plausible as a technology company and verified through Google search and USPTO TESS trademark search to confirm that no real brand existed under that name. A respondent who reports familiarity with Byteyield is likely responding inattentively or strategically inflating their claimed knowledge.^[*See* Jesse Chandler &amp; Gabriele Paolacci. "Lie for a Dime: When Most Prescreening Responses Are Honest but Most Study Participants Are Impostors." 8 **Soc. Psychological &amp; Personality Sci.** 500 (2017); Katelyn Sharpe Wessling, Joel Huber, &amp; Oded Netzer. "MTurk Character Misrepresentation: Assessment and Solutions." 44 **J. Cons. Res.** 211 (2017).]</span>
<span id="cb2-110"><a href="#cb2-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-111"><a href="#cb2-111" aria-hidden="true" tabindex="-1"></a>**Microsoft** and **Mozilla** serve as anchoring references: Microsoft provides a near-universal recognition ceiling, while Mozilla (the organization behind Firefox) occupies a middle ground because it is well-known among technology users but less universally recognized than Microsoft. Together, these anchors establish a credibility spectrum against which CC familiarity can be meaningfully interpreted. *See* <span class="co">[</span><span class="ot">Codebook, BRANDSKILLS</span><span class="co">](02-codebook.qmd#sec-brandskills)</span> for scale definitions and <span class="co">[</span><span class="ot">§2.6</span><span class="co">](02-codebook.qmd#sec-skills-scale)</span> for the 1–5 response scale (None / Little / Some / Good / Full).</span>
<span id="cb2-112"><a href="#cb2-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-113"><a href="#cb2-113" aria-hidden="true" tabindex="-1"></a><span class="fu">## Logo Recognition {#sec-logo-recognition}</span></span>
<span id="cb2-114"><a href="#cb2-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-115"><a href="#cb2-115" aria-hidden="true" tabindex="-1"></a>Before the brand familiarity battery, respondents completed a logo identification task. Four logos were displayed in random order and respondents answered: *"Do you know the brand associated with this logo?"* (Yes / No). Including multiple logos, such as the McDonald's golden arches as a near-universal reference and a novel fabricated logo as a floor control, reduced the likelihood that respondents would strategically inflate their claimed recognition of any single logo.</span>
<span id="cb2-116"><a href="#cb2-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-117"><a href="#cb2-117" aria-hidden="true" tabindex="-1"></a>Respondents who answered "Yes" for the Creative Commons logo were then prompted with a free-text entry: *"Please identify the brand you associate with this logo."* These responses were hand-coded into six categories. *See* <span class="co">[</span><span class="ot">Codebook, IDCC-CAT</span><span class="co">](02-codebook.qmd#sec-idcc-cat)</span> for the categorization scheme.</span>
<span id="cb2-118"><a href="#cb2-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-121"><a href="#cb2-121" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb2-122"><a href="#cb2-122" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-logo-recognition</span></span>
<span id="cb2-123"><a href="#cb2-123" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Logo recognition rates across all four brands. McDonald's provides a near-ceiling reference; the novel (fabricated) logo provides a floor control."</span></span>
<span id="cb2-124"><a href="#cb2-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-125"><a href="#cb2-125" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb2-126"><a href="#cb2-126" aria-hidden="true" tabindex="-1"></a>  <span class="at">Logo               =</span> <span class="fu">c</span>(<span class="st">"McDonald's"</span>, <span class="st">"Creative Commons"</span>, <span class="st">"Firefox"</span>, <span class="st">"Novel (fabricated)"</span>),</span>
<span id="cb2-127"><a href="#cb2-127" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Recognized (n)</span><span class="st">`</span>   <span class="ot">=</span> <span class="fu">c</span>(mcd_recog_n, cc_claimed_n, ff_recog_n, fake_recog_n),</span>
<span id="cb2-128"><a href="#cb2-128" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Recognized (%)</span><span class="st">`</span>   <span class="ot">=</span> <span class="fu">c</span>(mcd_recog_pct, cc_claimed_pct, ff_recog_pct, fake_recog_pct),</span>
<span id="cb2-129"><a href="#cb2-129" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Not Recognized (%)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">100</span> <span class="sc">-</span> mcd_recog_pct, <span class="dv">100</span> <span class="sc">-</span> cc_claimed_pct,</span>
<span id="cb2-130"><a href="#cb2-130" aria-hidden="true" tabindex="-1"></a>                           <span class="dv">100</span> <span class="sc">-</span> ff_recog_pct, <span class="dv">100</span> <span class="sc">-</span> fake_recog_pct),</span>
<span id="cb2-131"><a href="#cb2-131" aria-hidden="true" tabindex="-1"></a>  <span class="at">check.names =</span> <span class="cn">FALSE</span></span>
<span id="cb2-132"><a href="#cb2-132" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span> knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">1</span>)</span>
<span id="cb2-133"><a href="#cb2-133" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-134"><a href="#cb2-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-135"><a href="#cb2-135" aria-hidden="true" tabindex="-1"></a>Among the <span class="in">`r cc_claimed_n`</span> respondents who claimed to recognize the Creative Commons logo, free-text identification responses were coded into six categories:</span>
<span id="cb2-136"><a href="#cb2-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-139"><a href="#cb2-139" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb2-140"><a href="#cb2-140" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-cc-misid</span></span>
<span id="cb2-141"><a href="#cb2-141" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "CC logo misidentification breakdown. Categorization of free-text responses among respondents who claimed to recognize the Creative Commons logo."</span></span>
<span id="cb2-142"><a href="#cb2-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-143"><a href="#cb2-143" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(cc_misid_df, <span class="at">digits =</span> <span class="dv">1</span>, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Identification"</span>, <span class="st">"n"</span>, <span class="st">"%"</span>))</span>
<span id="cb2-144"><a href="#cb2-144" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-145"><a href="#cb2-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-148"><a href="#cb2-148" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb2-149"><a href="#cb2-149" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-logo-recognition</span></span>
<span id="cb2-150"><a href="#cb2-150" aria-hidden="true" tabindex="-1"></a><span class="co">#| column: page-right</span></span>
<span id="cb2-151"><a href="#cb2-151" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Logo recognition rates. The gap between claimed CC recognition and correct identification highlights the visual ambiguity of the 'CC' mark."</span></span>
<span id="cb2-152"><a href="#cb2-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-153"><a href="#cb2-153" aria-hidden="true" tabindex="-1"></a>logo_recog_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb2-154"><a href="#cb2-154" aria-hidden="true" tabindex="-1"></a>  <span class="at">Logo =</span> <span class="fu">c</span>(<span class="st">"McDonald's"</span>, <span class="st">"Creative Commons</span><span class="sc">\n</span><span class="st">(claimed)"</span>, <span class="st">"Creative Commons</span><span class="sc">\n</span><span class="st">(correct)"</span>,</span>
<span id="cb2-155"><a href="#cb2-155" aria-hidden="true" tabindex="-1"></a>           <span class="st">"Firefox"</span>, <span class="st">"Novel</span><span class="sc">\n</span><span class="st">(fabricated)"</span>),</span>
<span id="cb2-156"><a href="#cb2-156" aria-hidden="true" tabindex="-1"></a>  <span class="at">Rate =</span> <span class="fu">c</span>(mcd_recog_pct, cc_claimed_pct, cc_correct_pct, ff_recog_pct, fake_recog_pct),</span>
<span id="cb2-157"><a href="#cb2-157" aria-hidden="true" tabindex="-1"></a>  <span class="at">Type =</span> <span class="fu">c</span>(<span class="st">"Reference"</span>, <span class="st">"CC (claimed)"</span>, <span class="st">"CC (correct)"</span>, <span class="st">"Reference"</span>, <span class="st">"Control"</span>)</span>
<span id="cb2-158"><a href="#cb2-158" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-159"><a href="#cb2-159" aria-hidden="true" tabindex="-1"></a>logo_recog_df<span class="sc">$</span>Logo <span class="ot">&lt;-</span> <span class="fu">factor</span>(logo_recog_df<span class="sc">$</span>Logo, <span class="at">levels =</span> <span class="fu">rev</span>(logo_recog_df<span class="sc">$</span>Logo))</span>
<span id="cb2-160"><a href="#cb2-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-161"><a href="#cb2-161" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(logo_recog_df, <span class="fu">aes</span>(<span class="at">x =</span> Logo, <span class="at">y =</span> Rate, <span class="at">fill =</span> Type)) <span class="sc">+</span></span>
<span id="cb2-162"><a href="#cb2-162" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">width =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb2-163"><a href="#cb2-163" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(Rate, <span class="st">"%"</span>)), <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.15</span>, <span class="at">size =</span> <span class="fl">3.5</span>,</span>
<span id="cb2-164"><a href="#cb2-164" aria-hidden="true" tabindex="-1"></a>            <span class="at">family =</span> PLOT_FONT) <span class="sc">+</span></span>
<span id="cb2-165"><a href="#cb2-165" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">105</span>)) <span class="sc">+</span></span>
<span id="cb2-166"><a href="#cb2-166" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Reference"</span> <span class="ot">=</span> <span class="st">"#999999"</span>, <span class="st">"CC (claimed)"</span> <span class="ot">=</span> <span class="st">"#E0DCE4"</span>,</span>
<span id="cb2-167"><a href="#cb2-167" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"CC (correct)"</span> <span class="ot">=</span> <span class="st">"#2E1760"</span>, <span class="st">"Control"</span> <span class="ot">=</span> <span class="st">"#CCCCCC"</span>)) <span class="sc">+</span></span>
<span id="cb2-168"><a href="#cb2-168" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Logo Recognition Rates"</span>,</span>
<span id="cb2-169"><a href="#cb2-169" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Recognition Rate (%)"</span>) <span class="sc">+</span></span>
<span id="cb2-170"><a href="#cb2-170" aria-hidden="true" tabindex="-1"></a>  ggthemes<span class="sc">::</span><span class="fu">theme_tufte</span>(<span class="at">base_family =</span> PLOT_FONT, <span class="at">base_size =</span> <span class="dv">11</span>) <span class="sc">+</span></span>
<span id="cb2-171"><a href="#cb2-171" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb2-172"><a href="#cb2-172" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y      =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>, <span class="at">family =</span> PLOT_FONT),</span>
<span id="cb2-173"><a href="#cb2-173" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.background  =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">colour =</span> <span class="cn">NA</span>),</span>
<span id="cb2-174"><a href="#cb2-174" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"transparent"</span>, <span class="at">colour =</span> <span class="cn">NA</span>))</span>
<span id="cb2-175"><a href="#cb2-175" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-176"><a href="#cb2-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-177"><a href="#cb2-177" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true"}</span>
<span id="cb2-178"><a href="#cb2-178" aria-hidden="true" tabindex="-1"></a>**Logo Recognition Interpretation.** McDonald's, as expected, achieved near-ceiling recognition (<span class="in">`r mcd_recog_pct`</span>%), confirming that respondents understood the task and were attending to the logos. The fabricated novel logo serves as a floor control; its recognition rate (<span class="in">`r fake_recog_pct`</span>%) captures the base rate of false positive claims.</span>
<span id="cb2-179"><a href="#cb2-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-180"><a href="#cb2-180" aria-hidden="true" tabindex="-1"></a>For Creative Commons, <span class="in">`r cc_claimed_pct`</span>% of respondents claimed to recognize the logo, but only <span class="in">`r cc_correct_pct`</span>% correctly identified it as Creative Commons — meaning roughly <span class="in">`r round(cc_wrong_pct)`</span>% of claimants were mistaken. The most common misidentification was *Closed Captioning*, reflecting the visual similarity of the "CC" letterform. Other misidentifications included Comedy Central, Chanel, and generic copyright associations. *See* <span class="co">[</span><span class="ot">Codebook, IDCC-CAT</span><span class="co">](02-codebook.qmd#sec-idcc-cat)</span> for the full categorization scheme.</span>
<span id="cb2-181"><a href="#cb2-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-182"><a href="#cb2-182" aria-hidden="true" tabindex="-1"></a>**Key Takeaway:** True CC logo recognition is very low (<span class="in">`r cc_correct_pct`</span>%), even lower than brand name familiarity (<span class="in">`r cc_some_plus_pct`</span>% rated "Some" understanding or better on the BRANDSKILLS scale).</span>
<span id="cb2-183"><a href="#cb2-183" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb2-184"><a href="#cb2-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-185"><a href="#cb2-185" aria-hidden="true" tabindex="-1"></a><span class="fu">## Brands Tested {#sec-brand-brands}</span></span>
<span id="cb2-186"><a href="#cb2-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-187"><a href="#cb2-187" aria-hidden="true" tabindex="-1"></a>Respondents rated their familiarity with four brands on a 1–5 Likert-type scale (1 = None, 5 = Full understanding). The four brands serve distinct roles in the experimental design:</span>
<span id="cb2-188"><a href="#cb2-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-189"><a href="#cb2-189" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Brand <span class="pp">|</span> Variable <span class="pp">|</span> Role <span class="pp">|</span></span>
<span id="cb2-190"><a href="#cb2-190" aria-hidden="true" tabindex="-1"></a><span class="pp">|-------|----------|------|</span></span>
<span id="cb2-191"><a href="#cb2-191" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Creative Commons <span class="pp">|</span> <span class="in">`BRANDSKILLS_1`</span> <span class="pp">|</span> Brand of interest <span class="pp">|</span></span>
<span id="cb2-192"><a href="#cb2-192" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Byteyield <span class="pp">|</span> <span class="in">`BRANDSKILLS_2`</span> <span class="pp">|</span> Fabricated brand (attention check) <span class="pp">|</span></span>
<span id="cb2-193"><a href="#cb2-193" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Microsoft <span class="pp">|</span> <span class="in">`BRANDSKILLS_3`</span> <span class="pp">|</span> High-recognition ceiling <span class="pp">|</span></span>
<span id="cb2-194"><a href="#cb2-194" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Mozilla <span class="pp">|</span> <span class="in">`BRANDSKILLS_4`</span> <span class="pp">|</span> Moderate-recognition comparison <span class="pp">|</span></span>
<span id="cb2-195"><a href="#cb2-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-196"><a href="#cb2-196" aria-hidden="true" tabindex="-1"></a><span class="fu">### How to Read the Likert Plot {#sec-brand-howto}</span></span>
<span id="cb2-197"><a href="#cb2-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-198"><a href="#cb2-198" aria-hidden="true" tabindex="-1"></a>The Likert plot below is a **diverging stacked bar chart** centered at the scale midpoint. Each bar represents one brand, and the colored segments show the proportion of respondents at each familiarity level:</span>
<span id="cb2-199"><a href="#cb2-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-200"><a href="#cb2-200" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Left of center** = lower familiarity (None, Little) — bars extending leftward indicate less recognition</span>
<span id="cb2-201"><a href="#cb2-201" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Right of center** = higher familiarity (Good, Full) — bars extending rightward indicate greater recognition</span>
<span id="cb2-202"><a href="#cb2-202" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Bar width** reflects the proportion of respondents at each level</span>
<span id="cb2-203"><a href="#cb2-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-204"><a href="#cb2-204" aria-hidden="true" tabindex="-1"></a>**Quick Interpretation:** A brand with bars mostly extending to the right is well-known; a brand with bars mostly extending to the left is unfamiliar to most respondents. The relative positions reveal the expected ordering: Microsoft dominates the right side, Byteyield (fabricated) dominates the left, and Creative Commons and Mozilla fall between these anchors.</span>
<span id="cb2-205"><a href="#cb2-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-206"><a href="#cb2-206" aria-hidden="true" tabindex="-1"></a><span class="fu">## Brand Familiarity Analysis {#sec-brand-analysis}</span></span>
<span id="cb2-207"><a href="#cb2-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-208"><a href="#cb2-208" aria-hidden="true" tabindex="-1"></a><span class="fu">### Familiarity Plot {#sec-brand-likert}</span></span>
<span id="cb2-209"><a href="#cb2-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-212"><a href="#cb2-212" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb2-213"><a href="#cb2-213" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-brand-likert</span></span>
<span id="cb2-214"><a href="#cb2-214" aria-hidden="true" tabindex="-1"></a><span class="co">#| column: page-right</span></span>
<span id="cb2-215"><a href="#cb2-215" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Brand familiarity Likert plot. Stacked bars show the distribution of familiarity ratings (1–5 scale) for each brand. Creative Commons (brand of interest), Microsoft (high-recognition baseline), Mozilla (moderate-recognition comparison), Byteyield (fabricated attention check)."</span></span>
<span id="cb2-216"><a href="#cb2-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-217"><a href="#cb2-217" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare labeled factor data for custom styling</span></span>
<span id="cb2-218"><a href="#cb2-218" aria-hidden="true" tabindex="-1"></a>brand_plot_data <span class="ot">&lt;-</span> survey_data</span>
<span id="cb2-219"><a href="#cb2-219" aria-hidden="true" tabindex="-1"></a>brand_cols_plot <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"BRANDSKILLS_1"</span>, <span class="st">"BRANDSKILLS_2"</span>, <span class="st">"BRANDSKILLS_3"</span>, <span class="st">"BRANDSKILLS_4"</span>)</span>
<span id="cb2-220"><a href="#cb2-220" aria-hidden="true" tabindex="-1"></a>brand_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"BRANDSKILLS_1"</span> <span class="ot">=</span> <span class="st">"CC"</span>, <span class="st">"BRANDSKILLS_2"</span> <span class="ot">=</span> <span class="st">"Byteyield"</span>,</span>
<span id="cb2-221"><a href="#cb2-221" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"BRANDSKILLS_3"</span> <span class="ot">=</span> <span class="st">"Microsoft"</span>, <span class="st">"BRANDSKILLS_4"</span> <span class="ot">=</span> <span class="st">"Mozilla"</span>)</span>
<span id="cb2-222"><a href="#cb2-222" aria-hidden="true" tabindex="-1"></a>familiarity_levels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"None"</span>, <span class="st">"Little"</span>, <span class="st">"Some"</span>, <span class="st">"Good"</span>, <span class="st">"Full"</span>)</span>
<span id="cb2-223"><a href="#cb2-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-224"><a href="#cb2-224" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (col <span class="cf">in</span> brand_cols_plot) {</span>
<span id="cb2-225"><a href="#cb2-225" aria-hidden="true" tabindex="-1"></a>  brand_plot_data[[col]] <span class="ot">&lt;-</span> <span class="fu">factor</span>(brand_plot_data[[col]],</span>
<span id="cb2-226"><a href="#cb2-226" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">levels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,</span>
<span id="cb2-227"><a href="#cb2-227" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">labels =</span> familiarity_levels)</span>
<span id="cb2-228"><a href="#cb2-228" aria-hidden="true" tabindex="-1"></a>  <span class="fu">attr</span>(brand_plot_data[[col]], <span class="st">"label"</span>) <span class="ot">&lt;-</span> brand_names[[col]]</span>
<span id="cb2-229"><a href="#cb2-229" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-230"><a href="#cb2-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-231"><a href="#cb2-231" aria-hidden="true" tabindex="-1"></a><span class="co"># Light gray → dark purple gradient (5 steps)</span></span>
<span id="cb2-232"><a href="#cb2-232" aria-hidden="true" tabindex="-1"></a>purple_gray <span class="ot">&lt;-</span> <span class="fu">colorRampPalette</span>(<span class="fu">c</span>(<span class="st">"#E0DCE4"</span>, <span class="st">"#2E1760"</span>))(<span class="dv">5</span>)</span>
<span id="cb2-233"><a href="#cb2-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-234"><a href="#cb2-234" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> ggstats<span class="sc">::</span><span class="fu">gglikert</span>(brand_plot_data, <span class="at">include =</span> <span class="fu">all_of</span>(brand_cols_plot),</span>
<span id="cb2-235"><a href="#cb2-235" aria-hidden="true" tabindex="-1"></a>                       <span class="at">sort =</span> <span class="st">"descending"</span>) <span class="sc">+</span></span>
<span id="cb2-236"><a href="#cb2-236" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> purple_gray) <span class="sc">+</span></span>
<span id="cb2-237"><a href="#cb2-237" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Brand Familiarity Distribution"</span>) <span class="sc">+</span></span>
<span id="cb2-238"><a href="#cb2-238" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb2-239"><a href="#cb2-239" aria-hidden="true" tabindex="-1"></a>    <span class="at">text               =</span> <span class="fu">element_text</span>(<span class="at">family =</span> PLOT_FONT),</span>
<span id="cb2-240"><a href="#cb2-240" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.y        =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>, <span class="at">family =</span> PLOT_FONT),</span>
<span id="cb2-241"><a href="#cb2-241" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.background    =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"#FAFAFA"</span>, <span class="at">colour =</span> <span class="cn">NA</span>),</span>
<span id="cb2-242"><a href="#cb2-242" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.background   =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"#FAFAFA"</span>, <span class="at">colour =</span> <span class="cn">NA</span>),</span>
<span id="cb2-243"><a href="#cb2-243" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position    =</span> <span class="st">"bottom"</span>,</span>
<span id="cb2-244"><a href="#cb2-244" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.background  =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"#FAFAFA"</span>, <span class="at">colour =</span> <span class="cn">NA</span>),</span>
<span id="cb2-245"><a href="#cb2-245" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.key         =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"#FAFAFA"</span>, <span class="at">colour =</span> <span class="cn">NA</span>)</span>
<span id="cb2-246"><a href="#cb2-246" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb2-247"><a href="#cb2-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-248"><a href="#cb2-248" aria-hidden="true" tabindex="-1"></a><span class="co"># Set in-bar percentage labels to PLOT_FONT</span></span>
<span id="cb2-249"><a href="#cb2-249" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(p<span class="sc">$</span>layers)) {</span>
<span id="cb2-250"><a href="#cb2-250" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">inherits</span>(p<span class="sc">$</span>layers[[i]]<span class="sc">$</span>geom, <span class="st">"GeomText"</span>)) {</span>
<span id="cb2-251"><a href="#cb2-251" aria-hidden="true" tabindex="-1"></a>    p<span class="sc">$</span>layers[[i]]<span class="sc">$</span>aes_params<span class="sc">$</span>family <span class="ot">&lt;-</span> PLOT_FONT</span>
<span id="cb2-252"><a href="#cb2-252" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb2-253"><a href="#cb2-253" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-254"><a href="#cb2-254" aria-hidden="true" tabindex="-1"></a>p</span>
<span id="cb2-255"><a href="#cb2-255" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-256"><a href="#cb2-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-257"><a href="#cb2-257" aria-hidden="true" tabindex="-1"></a>The plot confirms the expected brand recognition ordering. Microsoft anchors the high end, with the vast majority of respondents rating their familiarity at "Good" or "Full" (mean = <span class="in">`r fmt(ms_mean)`</span>, <span class="in">`r ms_level`</span>). Mozilla occupies the middle — recognizable to most respondents but with more spread across the familiarity scale (mean = <span class="in">`r fmt(mz_mean)`</span>, <span class="in">`r mz_level`</span>). Creative Commons clusters heavily on the left side of the chart: <span class="in">`r cc_none_pct`</span>% of respondents reported *no* familiarity whatsoever, and only <span class="in">`r cc_some_plus_pct`</span>% rated their understanding at "Some" or better (mean = <span class="in">`r fmt(cc_mean)`</span>, <span class="in">`r cc_level`</span>). Byteyield, the fabricated brand, anchors the lowest end (mean = <span class="in">`r fmt(by_mean)`</span>, <span class="in">`r by_level`</span>), confirming that respondents were not indiscriminately inflating their claimed knowledge.</span>
<span id="cb2-258"><a href="#cb2-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-259"><a href="#cb2-259" aria-hidden="true" tabindex="-1"></a><span class="fu">### Summary Statistics {#sec-brand-summary}</span></span>
<span id="cb2-260"><a href="#cb2-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-263"><a href="#cb2-263" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb2-264"><a href="#cb2-264" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-brand-summary</span></span>
<span id="cb2-265"><a href="#cb2-265" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Brand familiarity summary statistics. Mean, SD, median, and qualitative recognition level for each brand on the 1–5 scale (None / Little / Some / Good / Full)."</span></span>
<span id="cb2-266"><a href="#cb2-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-267"><a href="#cb2-267" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(brand_results<span class="sc">$</span>summary, <span class="at">digits =</span> <span class="dv">2</span>)</span>
<span id="cb2-268"><a href="#cb2-268" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-269"><a href="#cb2-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-270"><a href="#cb2-270" aria-hidden="true" tabindex="-1"></a>The CC familiarity distribution is heavily left-skewed, with a median of <span class="in">`r cc_median`</span> and a mean of <span class="in">`r fmt(cc_mean)`</span>. Most members of the general public have little to no familiarity with Creative Commons licensing. For the experimental design, this low baseline means that most respondents encounter the CC license markings *for the first time* during the treatment vignettes, strengthening the interpretation that between-group differences in the scenario analyses reflect the treatment information rather than prior knowledge.</span>
<span id="cb2-271"><a href="#cb2-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-272"><a href="#cb2-272" aria-hidden="true" tabindex="-1"></a><span class="fu">## Attention Check {#sec-brand-attention}</span></span>
<span id="cb2-273"><a href="#cb2-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-274"><a href="#cb2-274" aria-hidden="true" tabindex="-1"></a>The fabricated brand Byteyield provides an embedded attention check. Because no real brand exists under this name, any reported familiarity beyond the floor suggests either inattentive responding or strategic overclaiming. A meaningful gap between CC familiarity and Byteyield familiarity provides evidence that respondents' CC familiarity ratings reflect genuine self-assessment rather than random or inflated responses.</span>
<span id="cb2-275"><a href="#cb2-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-276"><a href="#cb2-276" aria-hidden="true" tabindex="-1"></a><span class="in">```{r brand-attention}</span></span>
<span id="cb2-277"><a href="#cb2-277" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (brand_results<span class="sc">$</span>attention_check) {</span>
<span id="cb2-278"><a href="#cb2-278" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"✓ Attention check passed: fabricated brand (Byteyield) has appropriately low recognition.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb2-279"><a href="#cb2-279" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb2-280"><a href="#cb2-280" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"⚠ Attention check flag: Byteyield has unexpectedly high recognition. "</span>,</span>
<span id="cb2-281"><a href="#cb2-281" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Review may be needed for inattentive respondents.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb2-282"><a href="#cb2-282" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-283"><a href="#cb2-283" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-284"><a href="#cb2-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-285"><a href="#cb2-285" aria-hidden="true" tabindex="-1"></a>The CC–Byteyield gap in mean familiarity is <span class="in">`r fmt(cc_by_gap)`</span> points (CC mean = <span class="in">`r fmt(cc_mean)`</span> vs. Byteyield mean = <span class="in">`r fmt(by_mean)`</span>). This gap confirms that the modest CC familiarity observed above reflects genuine variation in brand awareness, not response noise. Respondents can and do distinguish between brands they have some awareness of and brands they have never encountered.</span>
<span id="cb2-286"><a href="#cb2-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-287"><a href="#cb2-287" aria-hidden="true" tabindex="-1"></a><span class="fu">## CC Familiarity by Group {#sec-brand-by-group}</span></span>
<span id="cb2-288"><a href="#cb2-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-289"><a href="#cb2-289" aria-hidden="true" tabindex="-1"></a>If randomization succeeded, CC familiarity should not differ systematically across the three treatment groups. The brand familiarity question precedes treatment exposure in the survey flow, so any between-group difference would indicate a pre-treatment confound — a threat to internal validity independent of the demographic balance confirmed in <span class="co">[</span><span class="ot">Chapter 4</span><span class="co">](04-randomization.qmd)</span>. This test parallels the covariate balance logic applied to demographics: just as age, income, and education should be balanced across groups, so too should pre-existing brand awareness.</span>
<span id="cb2-290"><a href="#cb2-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-293"><a href="#cb2-293" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb2-294"><a href="#cb2-294" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-brand-cc-by-group</span></span>
<span id="cb2-295"><a href="#cb2-295" aria-hidden="true" tabindex="-1"></a><span class="co">#| column: page-right</span></span>
<span id="cb2-296"><a href="#cb2-296" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Creative Commons brand familiarity by treatment group. The brand question precedes treatment exposure; a non-significant result confirms that pre-existing CC awareness does not confound the experimental design."</span></span>
<span id="cb2-297"><a href="#cb2-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-298"><a href="#cb2-298" aria-hidden="true" tabindex="-1"></a>cc_by_group <span class="ot">&lt;-</span> ggstatsplot<span class="sc">::</span><span class="fu">ggbetweenstats</span>(</span>
<span id="cb2-299"><a href="#cb2-299" aria-hidden="true" tabindex="-1"></a>  <span class="at">data  =</span> survey_data,</span>
<span id="cb2-300"><a href="#cb2-300" aria-hidden="true" tabindex="-1"></a>  <span class="at">x     =</span> GROUP,</span>
<span id="cb2-301"><a href="#cb2-301" aria-hidden="true" tabindex="-1"></a>  <span class="at">y     =</span> BRANDSKILLS_1,</span>
<span id="cb2-302"><a href="#cb2-302" aria-hidden="true" tabindex="-1"></a>  <span class="at">type  =</span> <span class="st">"np"</span>,</span>
<span id="cb2-303"><a href="#cb2-303" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"CC Brand Familiarity by Treatment Group"</span>,</span>
<span id="cb2-304"><a href="#cb2-304" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab  =</span> <span class="st">"CC Familiarity Rating"</span>,</span>
<span id="cb2-305"><a href="#cb2-305" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab  =</span> <span class="st">"Treatment Group"</span>,</span>
<span id="cb2-306"><a href="#cb2-306" aria-hidden="true" tabindex="-1"></a>  <span class="at">pairwise.display =</span> <span class="st">"none"</span>,</span>
<span id="cb2-307"><a href="#cb2-307" aria-hidden="true" tabindex="-1"></a>  <span class="at">centrality.point.args =</span> <span class="fu">list</span>(<span class="at">size =</span> <span class="dv">5</span>, <span class="at">color =</span> <span class="st">"#2E1760"</span>),</span>
<span id="cb2-308"><a href="#cb2-308" aria-hidden="true" tabindex="-1"></a>  <span class="at">ggtheme =</span> ggthemes<span class="sc">::</span><span class="fu">theme_tufte</span>(<span class="at">base_family =</span> PLOT_FONT, <span class="at">base_size =</span> <span class="dv">15</span>),</span>
<span id="cb2-309"><a href="#cb2-309" aria-hidden="true" tabindex="-1"></a>  <span class="at">point.args =</span> <span class="fu">list</span>(<span class="at">alpha =</span> <span class="dv">0</span>)</span>
<span id="cb2-310"><a href="#cb2-310" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-311"><a href="#cb2-311" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cc_by_group)</span>
<span id="cb2-312"><a href="#cb2-312" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-313"><a href="#cb2-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-314"><a href="#cb2-314" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true"}</span>
<span id="cb2-315"><a href="#cb2-315" aria-hidden="true" tabindex="-1"></a>**CC familiarity by group interpretation.** Kruskal-Wallis *p* = `r fmtp(cc_kw$p.value)`. `r if (cc_kw$p.value &gt; 0.05) "The three treatment groups do not differ significantly in pre-existing CC familiarity, confirming that brand awareness is balanced across conditions. This result, combined with the demographic balance confirmed in [Chapter 4](04-randomization.qmd), supports a causal interpretation of between-group differences in the scenario analyses." else "**Warning:** The groups show a statistically significant difference in pre-existing CC familiarity (*p* &lt; .05). This pre-treatment imbalance should be considered when interpreting between-group differences in the scenario analyses. Consider controlling for baseline CC familiarity as a covariate."`</span>
<span id="cb2-316"><a href="#cb2-316" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb2-317"><a href="#cb2-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-318"><a href="#cb2-318" aria-hidden="true" tabindex="-1"></a><span class="fu">## Summary {#sec-brand-summary-findings}</span></span>
<span id="cb2-319"><a href="#cb2-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-320"><a href="#cb2-320" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip}</span>
<span id="cb2-321"><a href="#cb2-321" aria-hidden="true" tabindex="-1"></a><span class="fu">## Key Findings — Brand Recognition</span></span>
<span id="cb2-322"><a href="#cb2-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-323"><a href="#cb2-323" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**CC familiarity is low.** <span class="in">`r cc_none_pct`</span>% of respondents reported no familiarity with Creative Commons (BRANDSKILLS_1 = 1, "None"), and only <span class="in">`r cc_some_plus_pct`</span>% rated their understanding at "Some" or better (mean = <span class="in">`r fmt(cc_mean)`</span>, recognition level: <span class="in">`r cc_level`</span>).</span>
<span id="cb2-324"><a href="#cb2-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-325"><a href="#cb2-325" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Logo recognition confirms low awareness.** Only <span class="in">`r cc_correct_pct`</span>% of respondents correctly identified the Creative Commons logo — roughly <span class="in">`r round(cc_wrong_pct)`</span>% of those who *claimed* to recognize it were mistaken. Common misidentifications (Closed Captioning, Comedy Central, Chanel) reveal the visual ambiguity of the "CC" mark. True logo recognition is even lower than self-reported brand name familiarity.</span>
<span id="cb2-326"><a href="#cb2-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-327"><a href="#cb2-327" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**The fabricated brand test passes.** Byteyield, the fabricated attention check brand, shows appropriately low familiarity (mean = <span class="in">`r fmt(by_mean)`</span>, <span class="in">`r by_level`</span>). The CC–Byteyield gap of <span class="in">`r fmt(cc_by_gap)`</span> points confirms that respondents' CC familiarity ratings reflect genuine self-assessment rather than random or inflated responses.</span>
<span id="cb2-328"><a href="#cb2-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-329"><a href="#cb2-329" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Microsoft anchors the ceiling; Mozilla occupies the middle.** Microsoft achieves near-universal recognition (mean = <span class="in">`r fmt(ms_mean)`</span>, <span class="in">`r ms_level`</span>), while Mozilla occupies a credible middle position (mean = <span class="in">`r fmt(mz_mean)`</span>, <span class="in">`r mz_level`</span>). These reference points confirm that the 1–5 scale discriminates meaningfully across the recognition spectrum.</span>
<span id="cb2-330"><a href="#cb2-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-331"><a href="#cb2-331" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**CC familiarity is balanced across treatment groups.** Kruskal-Wallis *p* = <span class="in">`r fmtp(cc_kw$p.value)`</span>, confirming that pre-existing CC awareness does not differ significantly across Groups A, B, and C. Combined with <span class="co">[</span><span class="ot">Chapter 4</span><span class="co">](04-randomization.qmd)</span>'s demographic balance results, this supports a causal interpretation of between-group differences in the <span class="co">[</span><span class="ot">scenario analyses</span><span class="co">](07-scenarios.qmd)</span>.</span>
<span id="cb2-332"><a href="#cb2-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-333"><a href="#cb2-333" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**Implications for the scenario analyses.** The low baseline means that most respondents encounter the CC license notice for the first time during the experimental vignettes. Treatment effects therefore operate on a largely uninformed population — a condition that strengthens the ecological validity of the study (most real-world encounters with CC-licensed content likely involve users with little prior CC knowledge) but also means the results reflect *first impressions* rather than informed judgments.</span>
<span id="cb2-334"><a href="#cb2-334" aria-hidden="true" tabindex="-1"></a>:::</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ludist/cc-survey/edit/main/06-brand.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/ludist/cc-survey/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>