<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7&nbsp; Factorial Vignette Analysis Overview – Creative Commons Recognition and Copyright Infringement Perceptions Survey Experiment</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./_scenarios/pd.html" rel="next">
<link href="./06-brand.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-725ff378461d03fdd1d6ea4db46cc69a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./07-scenarios.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Factorial Vignette Analysis Overview</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Creative Commons Recognition and Copyright Infringement Perceptions Survey Experiment</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ludist/cc-survey" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Experimental Design &amp; Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-codebook.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Codebook &amp; Variable Dictionary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Validation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-randomization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Randomization Check</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-population.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sample v. Population Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-brand.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Brand Recognition</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-scenarios.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Factorial Vignette Analysis Overview</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_scenarios/pd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.1 Public Domain</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_scenarios/pu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.2 Personal Use</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_scenarios/eu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.3 Educational Use</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_scenarios/ca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.4 Commercial Advertising</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_scenarios/ls.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.5 Large Scale Copying</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_scenarios/wn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.6 Wikipedia Image Search</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_scenarios/fs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.7 Filesharing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-summaries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Question Summaries</span></span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#analysis-structure" id="toc-analysis-structure" class="nav-link active" data-scroll-target="#analysis-structure"><span class="header-section-number">7.1</span> Analysis Structure</a></li>
  <li><a href="#sec-functions" id="toc-sec-functions" class="nav-link" data-scroll-target="#sec-functions"><span class="header-section-number">7.2</span> Analysis Pipeline</a></li>
  <li><a href="#sec-howto-graphs" id="toc-sec-howto-graphs" class="nav-link" data-scroll-target="#sec-howto-graphs"><span class="header-section-number">7.3</span> How to Read the Scenario Graphs</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/ludist/cc-survey/edit/main/07-scenarios.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/ludist/cc-survey/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Factorial Vignette Analysis Overview</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="analysis-structure" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="analysis-structure"><span class="header-section-number">7.1</span> Analysis Structure</h2>
<p>Each of the seven scenario chapters that follow uses a parallel structure:</p>
<ol type="1">
<li><strong>Scenario Context</strong> — the vignette presented to respondents</li>
<li><strong>Q1: Legal Consequences</strong> — Kruskal-Wallis + Dunn’s post-hoc + VDA (figure and table)</li>
<li><strong>Q2: What the Law Is</strong> — Kruskal-Wallis + Dunn’s + VDA</li>
<li><strong>Q3: What the Law Should Be</strong> — Kruskal-Wallis + Dunn’s + VDA</li>
<li><strong>Δ (Delta, Q2 − Q3)</strong> — within-group Wilcoxon signed-rank tests</li>
<li><strong>Q4: Price estimate</strong> — Kruskal-Wallis + Dunn’s</li>
</ol>
<p>Data: Groups A, B, C (n = 1,222) for all scenarios except <a href="./_scenarios/eu.html">Educational Use</a>, which filters to Groups A, B1, C (<em>n</em> = 905) due to a supplemental data collection. See <a href="./02-codebook.html#sec-b1">§3.1 (Codebook)</a> for the B1 substitution.</p>
<p>Statistical methods are detailed in the <a href="./01-methods.html#sec-statistical-methods">Methods chapter</a>. Effect sizes (VDA) are interpreted using the thresholds in <a href="./01-methods.html#tbl-vda-thresholds">Table 2.1</a>.</p>
<p>Cross-reference format: figures are labeled <code>@fig-[scenario]-q[N]</code> (e.g., <code>@fig-pd-q1</code>); tables are labeled <code>@tbl-[scenario]-q[N]-stats</code> (e.g., <code>@tbl-pd-q1-stats</code>).</p>
</section>
<section id="sec-functions" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="sec-functions"><span class="header-section-number">7.2</span> Analysis Pipeline</h2>
<p>Every scenario chapter (§§7.1–7.7) calls a single function, <code>analyze_full_scenario()</code>, and receives back a complete set of plots, descriptive statistics, and test results. That one call sets in motion a coordinated pipeline of seven R modules, each responsible for a distinct layer of the analysis. This section documents those modules: what each one does, why it was designed the way it was, and how the pieces fit together.</p>
<p>All seven files live in <code>analysis/functions/</code> and are sourced at book startup by <code>_common.R</code>. The source code for each module is folded below its description; click <strong>Show source</strong> to expand it. Code results are cached for HTML display but can be manually run as an R or Positron Notebook.</p>
<section id="sec-fn-overview" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="sec-fn-overview"><span class="header-section-number">7.2.1</span> Pipeline Overview</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pipeline" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pipeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-pipeline">flowchart TD
  CSV["rousse-cc-survey-2024.csv\n(1,319 obs, all groups)"]

  subgraph common ["_common.R  (book startup)"]
    CSV --&gt; dp["data_prep.R\nload_survey_data()\ncreate_all_deltas()"]
    dp --&gt; sdA["survey_data\nGROUP ∈ {A, B, C}\nn = 1,222"]
    dp --&gt; sdB["survey_data_eu\nGROUP ∈ {A, B1, C}\nn = 905"]
  end

  subgraph chapter ["Per-scenario chapter  (§7.1 – §7.7)"]
    sdA --&gt; ma["master_analysis.R\nanalyze_full_scenario()"]
    sdB --&gt; ma
    ma --&gt; af["analysis_functions.R\nanalyze_scenario_question()\ncreate_scenario_plot()\ncreate_delta_plot()\ncreate_price_plot()"]
    af --&gt; sh["stats_helpers.R\nvalidate_group_data()\nKruskal-Wallis · Dunn's post-hoc\nVDA effect sizes\nWilcoxon signed-rank (delta)"]
    af --&gt; pt["plotting_themes.R\nget_standard_theme()\nget_standard_plot_args()\nget_price_plot_args()"]
    af --&gt; ex["export_helpers.R\nexport_plot_to_tiff()\ndata / figures / v2 /"]
    ma --&gt; out["Returns nested list:\n$plots · $statistics · $tests"]
  end

  rc["randomization_checks.R\ncheck_continuous_covariate()\ncheck_categorical_covariate()\ncheck_brand_recognition()"] -.-&gt;|"Ch. 4–5 only"| sdA
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pipeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.1: Analysis pipeline: from raw CSV to scenario chapter outputs.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The pipeline separates cleanly into three tiers: <em>data</em> (Module 1), <em>statistics and visualization</em> (Modules 2–5), and <em>orchestration</em> (Module 7). Module 6 supports only Chapters 4 and 5 and is never called by the scenario analysis chain.</p>
</section>
<section id="sec-fn-data-prep" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="sec-fn-data-prep"><span class="header-section-number">7.2.2</span> Module 1: <code>data_prep.R</code> — Data Ingestion</h3>
<p><code>data_prep.R</code> handles everything that must happen before any statistics can be run: loading the CSV, constructing computed columns, and producing the two analysis views that the rest of the book uses.</p>
<p>The central design decision is <strong>single-file architecture</strong>. The two analysis views are created in <code>_common.R</code> by filtering on <code>GROUP</code>: <code>survey_data</code> keeps Groups A, B, and C (<em>n</em> = 1,222); <code>survey_data_eu</code> keeps Groups A, B1, and C (<em>n</em> = 905). The <code>prepare_eu_data()</code> function in this module handles the original two-file workflow and is preserved for provenance, but it is not called at book startup.</p>
<p>The other key contribution is <strong>delta variable creation</strong>. Each scenario includes a question about what the law currently permits (Q2) and a question about what respondents prefer (Q3). Their difference (Δ = Q2 − Q3) is stored in a column named <code>[SCENARIO]25</code> (e.g., <code>PD25</code>). A positive delta means the law is stricter than respondents prefer; a negative delta means the law is more permissive. <code>create_all_deltas()</code> loops over all seven scenario codes and creates these columns in a single pass, and it gracefully skips any scenario whose Q2/Q3 columns are absent.</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Function</th>
<th>Key Parameters</th>
<th>Returns</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>load_survey_data()</code></td>
<td><code>filepath</code>, <code>filter_groups</code></td>
<td>data frame</td>
<td>Load and optionally filter CSV</td>
</tr>
<tr class="even">
<td><code>create_delta_variable()</code></td>
<td><code>data</code>, <code>var1</code>, <code>var2</code>, <code>new_var_name</code></td>
<td>data frame</td>
<td>Compute single Δ column</td>
</tr>
<tr class="odd">
<td><code>create_all_deltas()</code></td>
<td><code>data</code>, <code>scenarios</code></td>
<td>data frame</td>
<td>Batch-create all seven Δ columns</td>
</tr>
<tr class="even">
<td><code>validate_data_structure()</code></td>
<td><code>data</code>, <code>required_cols</code></td>
<td>logical</td>
<td>Check that required columns exist</td>
</tr>
<tr class="odd">
<td><code>get_scenario_columns()</code></td>
<td><code>scenario_code</code>, <code>include_delta</code></td>
<td>character vector</td>
<td>Return column names for a scenario</td>
</tr>
<tr class="even">
<td><code>check_data_quality()</code></td>
<td><code>data</code>, <code>columns</code></td>
<td>data frame</td>
<td>Report missing-value rates</td>
</tr>
<tr class="odd">
<td><code>prepare_all_data()</code></td>
<td><code>main_filepath</code>, <code>b1_filepath</code></td>
<td>list</td>
<td>Master prep: load + delta + optional EU</td>
</tr>
<tr class="even">
<td><code>filter_by_group()</code></td>
<td><code>data</code>, <code>group</code></td>
<td>data frame</td>
<td>Extract a single group</td>
</tr>
<tr class="odd">
<td><code>split_by_groups()</code></td>
<td><code>data</code>, <code>group_var</code></td>
<td>list</td>
<td>Split data into per-group data frames</td>
</tr>
</tbody>
</table>
</section>
<section id="sec-fn-stats-helpers" class="level3" data-number="7.2.3">
<h3 data-number="7.2.3" class="anchored" data-anchor-id="sec-fn-stats-helpers"><span class="header-section-number">7.2.3</span> Module 2: <code>stats_helpers.R</code> — Statistical Calculations</h3>
<p><code>stats_helpers.R</code> provides the statistical layer: validation, descriptive summaries, hypothesis tests, and effect sizes. Its design philosophy is to keep statistical decisions in one place so that all seven scenario chapters are guaranteed to use identical methods.</p>
<p>The non-parametric choice is deliberate. The outcome variables are 7-point Likert scales: ordinal, bounded, and typically non-normal in distribution. Kruskal-Wallis is the appropriate omnibus test, and <strong>Dunn’s test</strong> (via <code>rstatix::dunn_test()</code>, Holm correction) is the appropriate post-hoc. Pairwise Wilcoxon was considered but rejected: Dunn’s test is specifically designed for post-hoc comparisons following a Kruskal-Wallis test and uses rank-sum scores from the full dataset, which gives it more appropriate statistical properties in this context.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Design note: Why Vargha &amp; Delaney’s A over Cohen’s <em>d</em> or <em>r</em>?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Effect sizes based on means (Cohen’s <em>d</em>) assume interval-level data. For ordinal scales, Vargha &amp; Delaney’s <em>A</em> is the recommended alternative: it is a rank-based probability that a randomly selected observation from Group X exceeds a randomly selected observation from Group Y. A value of 0.50 indicates no difference; values above 0.50 indicate Group 1 dominance, values below 0.50 indicate Group 2 dominance. Thresholds used throughout this appendix follow Vargha &amp; Delaney (2000) and are given in <a href="01-methods.html#tbl-vda-thresholds" class="quarto-xref">Table&nbsp;<span>1.1</span></a>.</p>
</div>
</div>
</div>
<p>The <strong>delta analysis</strong> uses a different test: <code>test_delta_nonzero()</code> runs a one-sample Wilcoxon signed-rank test for each group separately, testing whether that group’s median delta is significantly different from zero. A non-zero median delta indicates a gap between respondents’ perception of current law and their normative preference.</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Function</th>
<th>Key Parameters</th>
<th>Returns</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>validate_group_data()</code></td>
<td><code>data</code>, <code>dv</code>, <code>min_n</code></td>
<td>list</td>
<td>Check that each group has ≥ <em>n</em> observations</td>
</tr>
<tr class="even">
<td><code>calculate_descriptive_stats()</code></td>
<td><code>data</code>, <code>dv</code>, <code>group_var</code>, <code>stats</code></td>
<td>data frame</td>
<td>Mean, SD, median by group</td>
</tr>
<tr class="odd">
<td><code>run_dunn_test()</code></td>
<td><code>data</code>, <code>formula</code>, <code>p_adjust</code></td>
<td>data frame</td>
<td>Dunn’s post-hoc with Holm correction</td>
</tr>
<tr class="even">
<td><code>calculate_vda()</code></td>
<td><code>data</code>, <code>dv</code>, <code>group_var</code></td>
<td>list</td>
<td>Vargha &amp; Delaney’s A for all pairs</td>
</tr>
<tr class="odd">
<td><code>format_vda_caption()</code></td>
<td><code>dunn_results</code>, <code>vda_results</code></td>
<td>character</td>
<td>Build plot caption with effect sizes</td>
</tr>
<tr class="even">
<td><code>remove_outliers_by_group()</code></td>
<td><code>data</code>, <code>dv</code>, <code>percentile</code></td>
<td>data frame</td>
<td>Trim top <em>p</em>% within each group</td>
</tr>
<tr class="odd">
<td><code>test_delta_nonzero()</code></td>
<td><code>data</code>, <code>dv</code>, <code>mu</code></td>
<td>list</td>
<td>One-sample Wilcoxon (Δ ≠ 0) per group</td>
</tr>
<tr class="even">
<td><code>run_chisq_test()</code></td>
<td><code>data</code>, <code>var1</code>, <code>var2</code></td>
<td>list</td>
<td>Contingency table + χ² test</td>
</tr>
<tr class="odd">
<td><code>compare_groups()</code></td>
<td><code>data</code>, <code>dv</code>, <code>test_type</code></td>
<td>test object</td>
<td>ANOVA or Kruskal-Wallis omnibus</td>
</tr>
<tr class="even">
<td><code>compute_scenario_price_row()</code></td>
<td><code>data</code>, <code>scenario_code</code></td>
<td>data frame</td>
<td>Price summary row (median, outlier-trimmed)</td>
</tr>
<tr class="odd">
<td><code>build_price_summary_table()</code></td>
<td><code>data_main</code>, <code>data_eu</code></td>
<td>data frame</td>
<td>Cross-scenario price summary</td>
</tr>
<tr class="even">
<td><code>build_price_vda_table()</code></td>
<td><code>data_main</code>, <code>data_eu</code></td>
<td>data frame</td>
<td>Cross-scenario price VDA (outlier-trimmed)</td>
</tr>
<tr class="odd">
<td><code>build_wilcoxon_table()</code></td>
<td><code>data_main</code>, <code>data_eu</code></td>
<td>data frame</td>
<td>Cross-scenario Wilcoxon signed-rank (Δ ≠ 0)</td>
</tr>
</tbody>
</table>
</section>
<section id="sec-fn-plotting-themes" class="level3" data-number="7.2.4">
<h3 data-number="7.2.4" class="anchored" data-anchor-id="sec-fn-plotting-themes"><span class="header-section-number">7.2.4</span> Module 3: <code>plotting_themes.R</code> — Visual Consistency</h3>
<p><code>plotting_themes.R</code> is the style guide for every figure in this Appendix. By centralizing all <code>ggplot2</code> theme and argument settings, the module guarantees that every plot across all seven scenario chapters shares the same fonts, sizes, color choices, significance bracket styling, and central tendency markers.</p>
<p>The base theme is <strong>Tufte</strong> (via <code>ggthemes::theme_tufte()</code>), following Edward Tufte’s principle of maximizing the data-to-ink ratio. Unnecessary gridlines and borders are removed; the statistical signal is left to speak for itself. Font resolution is handled through the <code>PLOT_FONT</code> global variable, which is set in <code>_common.R</code> before this module is sourced; all functions default to <code>base_family = PLOT_FONT</code> so that the book-level font choice propagates everywhere automatically.</p>
<p>Two argument-list functions address the structural difference between Likert-scale questions and the price question.</p>
<p><code>get_standard_plot_args()</code> configures the standard Q1/Q2/Q3/delta plots: no individual points shown, means displayed (parametric centrality), and significance brackets limited to statistically significant pairs.</p>
<p><code>get_price_plot_args()</code> modifies the recipe for price data: individual estimates are shown as semi-transparent jittered dots, and the central tendency switches to <strong>median</strong> (50th percentile) because price distributions are right-skewed and means are not robust to the outliers that remain after the 99th-percentile trim.</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Function</th>
<th>Key Parameters</th>
<th>Returns</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>get_standard_theme()</code></td>
<td><code>base_family</code>, <code>base_size</code></td>
<td>ggplot theme</td>
<td>Tufte theme with global font</td>
</tr>
<tr class="even">
<td><code>get_standard_plot_args()</code></td>
<td><code>show_points</code>, <code>base_family</code></td>
<td>list</td>
<td>ggbetweenstats args for Likert plots</td>
</tr>
<tr class="odd">
<td><code>get_price_plot_args()</code></td>
<td><code>base_family</code></td>
<td>list</td>
<td>ggbetweenstats args for price plots</td>
</tr>
<tr class="even">
<td><code>apply_standard_formatting()</code></td>
<td><code>plot</code>, <code>center_caption</code></td>
<td>ggplot</td>
<td>Center caption on existing plot</td>
</tr>
<tr class="odd">
<td><code>get_group_colors()</code></td>
<td><code>n_groups</code></td>
<td>character vector</td>
<td>Okabe-Ito colorblind-safe palette</td>
</tr>
<tr class="even">
<td><code>set_global_plot_options()</code></td>
<td><code>base_family</code></td>
<td>NULL (side effect)</td>
<td>Set session-wide ggplot2 defaults</td>
</tr>
<tr class="odd">
<td><code>get_axis_labels()</code></td>
<td><code>scenario_code</code>, <code>question_type</code></td>
<td>list</td>
<td>Standardized x/y axis labels</td>
</tr>
<tr class="even">
<td><code>format_plot_title()</code></td>
<td><code>scenario_name</code>, <code>question_type</code></td>
<td>character</td>
<td>Two-line title for each question type</td>
</tr>
</tbody>
</table>
</section>
<section id="sec-fn-analysis-functions" class="level3" data-number="7.2.5">
<h3 data-number="7.2.5" class="anchored" data-anchor-id="sec-fn-analysis-functions"><span class="header-section-number">7.2.5</span> Module 4: <code>analysis_functions.R</code> — Per-Question Plots</h3>
<p><code>analysis_functions.R</code> is where statistical tests and visualizations are actually assembled. Its four functions correspond to the four structural plot types that appear across the scenario chapters: standard questions (Q1/Q2/Q3), delta questions (Δ = Q2 − Q3), price questions (Q4), and a master dispatcher that routes each question to the appropriate specialized function.</p>
<p>The core plot engine throughout is <code>ggstatsplot::ggbetweenstats()</code>. This function was chosen because it combines group-level box plots, individual jitter (optional), pairwise significance brackets, and statistical test results in a single, opinionated call. The tradeoff is that the function’s defaults are opinionated and occasionally need to be overridden, leading to <code>plotting_themes.R</code> as a separate layer.</p>
<p>A critical detail shared by all three plot functions is <strong>group factor reordering</strong>. The raw <code>GROUP</code> column contains the strings <code>"A"</code>, <code>"B"</code>, <code>"C"</code>, and (for EU) <code>"B1"</code>. Left to its default, R would display these alphabetically. Each function refactors the column to display order C → A → B (Control first, then treatments in ascending information density), and maps the codes to human-readable labels: <code>"Control (C)"</code>, <code>"Short (A)"</code>, <code>"Full + Primer (B)"</code>, and <code>"Full + Primer (B1)"</code>. This ordering is applied consistently before any statistical test is run, so all group comparisons and labels in the output match this canonical ordering.</p>
<p><code>create_delta_plot()</code> adds one step beyond the standard plot: after producing the between-group visualization, it runs a one-sample Wilcoxon signed-rank test for each group separately. The test result finding whether each group’s median delta is significantly different from zero is returned alongside the plot and appears in the scenario chapters as the Wilcoxon results table.</p>
<p><code>create_price_plot()</code> adds outlier removal via <code>remove_outliers_by_group()</code> before any statistics are run. Price estimates are right-skewed and occasionally extreme; removing the top 1% within each group independently (rather than across the full sample) prevents any one group’s outliers from distorting the visual scale.</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Function</th>
<th>Key Parameters</th>
<th>Returns</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>create_scenario_plot()</code></td>
<td><code>data</code>, <code>dv</code>, <code>ylab</code>, <code>title</code>, <code>show_points</code></td>
<td>ggplot</td>
<td>Standard Likert plot (Q1/Q2/Q3)</td>
</tr>
<tr class="even">
<td><code>create_delta_plot()</code></td>
<td><code>data</code>, <code>dv</code>, <code>title</code>, <code>test_by_group</code></td>
<td>list (plot + Wilcoxon)</td>
<td>Delta plot with per-group zero test</td>
</tr>
<tr class="odd">
<td><code>create_price_plot()</code></td>
<td><code>data</code>, <code>dv</code>, <code>title</code>, <code>percentile</code></td>
<td>list (plot + filtered data)</td>
<td>Price plot with outlier trimming</td>
</tr>
<tr class="even">
<td><code>analyze_scenario_question()</code></td>
<td><code>data</code>, <code>dv</code>, <code>question_type</code>, <code>scenario_name</code>, <code>export_tiff</code></td>
<td>list</td>
<td>Dispatcher: routes to appropriate function</td>
</tr>
</tbody>
</table>
</section>
<section id="sec-fn-export-helpers" class="level3" data-number="7.2.6">
<h3 data-number="7.2.6" class="anchored" data-anchor-id="sec-fn-export-helpers"><span class="header-section-number">7.2.6</span> Module 5: <code>export_helpers.R</code> — Figure Export</h3>
<p><code>export_helpers.R</code> handles the mechanics of saving analysis outputs to disk. <code>export_plot_to_tiff()</code> is the function called by <code>analyze_scenario_question()</code> whenever <code>export_tiff = TRUE</code>. It uses R’s base graphics device system—<code>tiff()</code> → <code>print(plot)</code> → <code>dev.off()</code>—to write a 300 DPI TIFF suitable for journal submission.</p>
<p>The default output path uses <code>here::here("data", "figures", "v2")</code>, which resolves relative to the project root regardless of the working directory at the time of rendering. The filename convention is <code>[SCENARIO][QUESTION][WIDTH×10].tiff</code> — for example, <code>PD165.tiff</code> for the Public Domain Q1 plot at 6.5 inches wide. The <code>generate_filename()</code> function encodes this convention explicitly.</p>
<p>The remaining functions (<code>export_plots_batch()</code>, <code>save_analysis_results()</code>, <code>export_stats_to_csv()</code>, <code>export_all_results()</code>) support the standalone batch workflow and the <code>generate_full_report()</code> orchestrator. They are not called during normal book rendering.</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Function</th>
<th>Key Parameters</th>
<th>Returns</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>export_plot_to_tiff()</code></td>
<td><code>plot</code>, <code>filename</code>, <code>width</code>, <code>height</code>, <code>res</code>, <code>path</code></td>
<td>NULL</td>
<td>Save ggplot to 300 DPI TIFF</td>
</tr>
<tr class="even">
<td><code>export_results_table()</code></td>
<td><code>stats_df</code>, <code>format</code>, <code>caption</code></td>
<td>kable</td>
<td>Format stats table for document</td>
</tr>
<tr class="odd">
<td><code>export_plots_batch()</code></td>
<td><code>plots</code>, <code>prefix</code>, <code>width</code>, <code>height</code></td>
<td>NULL</td>
<td>Batch-export named list of plots</td>
</tr>
<tr class="even">
<td><code>save_analysis_results()</code></td>
<td><code>results</code>, <code>filename</code>, <code>path</code></td>
<td>NULL</td>
<td>Serialize results list to RDS</td>
</tr>
<tr class="odd">
<td><code>export_stats_to_csv()</code></td>
<td><code>stats_list</code>, <code>filename</code>, <code>path</code></td>
<td>NULL</td>
<td>Write all scenario stats to CSV</td>
</tr>
<tr class="even">
<td><code>generate_filename()</code></td>
<td><code>scenario_code</code>, <code>question</code>, <code>width</code></td>
<td>character</td>
<td>Build canonical TIFF filename</td>
</tr>
</tbody>
</table>
</section>
<section id="sec-fn-randomization-checks" class="level3" data-number="7.2.7">
<h3 data-number="7.2.7" class="anchored" data-anchor-id="sec-fn-randomization-checks"><span class="header-section-number">7.2.7</span> Module 6: <code>randomization_checks.R</code> — Covariate Balance</h3>
<p><code>randomization_checks.R</code> is deliberately isolated from the scenario analysis chain. Its functions appear in Chapter 4 (<span class="quarto-unresolved-ref">?sec-randomization</span>) and Chapter 5 (<a href="02-codebook.html#sec-brand" class="quarto-xref"><span>Section 2.6</span></a>), and they are never called by <code>analyze_full_scenario()</code>. Keeping balance checks in their own module prevents the scenario chapters from accumulating diagnostic overhead, and it makes the covariate-balance logic easy to find and audit independently.</p>
<p><code>check_continuous_covariate()</code> handles numeric variables (Age, Income, Education). The test selection is adaptive: Age and Income are tested with ANOVA; scale-based variables (Internet skills) use Kruskal-Wallis. <code>check_categorical_covariate()</code> handles nominal variables (Race, Gender) via chi-square test. The <code>$proportions</code> component gives within-group proportions, which are more interpretable for balance assessment than raw counts.</p>
<p>The module also contains <code>check_brand_recognition()</code>, which analyzes the four-item brand recognition battery (Creative Commons, Byteyield, Microsoft, Mozilla). Byteyield is a fictitious brand included as an attention check; its recognition mean should be well below the 2.5 threshold.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why isolate randomization checks from scenario analysis?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>If <code>randomization_checks.R</code> were sourced inside each scenario chapter, every chapter would re-run the balance tests — repeating the same checks seven times with no additional information. Placing the checks in dedicated chapters (4 and 5) and in a standalone module makes the one-time nature of the diagnostic explicit.</p>
</div>
</div>
</div>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Function</th>
<th>Key Parameters</th>
<th>Returns</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>check_continuous_covariate()</code></td>
<td><code>data</code>, <code>covariate</code>, <code>test_type</code>, <code>create_plot</code></td>
<td>list</td>
<td>ANOVA or K-W + optional plot</td>
</tr>
<tr class="even">
<td><code>check_categorical_covariate()</code></td>
<td><code>data</code>, <code>covariate</code>, <code>create_table</code></td>
<td>list</td>
<td>χ² test + contingency table</td>
</tr>
<tr class="odd">
<td><code>run_all_randomization_checks()</code></td>
<td><code>data</code>, <code>continuous_vars</code>, <code>categorical_vars</code></td>
<td>list</td>
<td>Batch all covariate checks</td>
</tr>
<tr class="even">
<td><code>summarize_randomization_checks()</code></td>
<td><code>check_results</code></td>
<td>data frame</td>
<td>Tidy summary table of all tests</td>
</tr>
<tr class="odd">
<td><code>plot_randomization_grid()</code></td>
<td><code>check_results</code>, <code>ncol</code></td>
<td>patchwork / list</td>
<td>Arrange all check plots in a grid</td>
</tr>
<tr class="even">
<td><code>check_brand_recognition()</code></td>
<td><code>data</code>, <code>brand_cols</code>, <code>create_plot</code></td>
<td>list</td>
<td>Brand recognition summary + likert plot</td>
</tr>
</tbody>
</table>
</section>
<section id="sec-fn-master-analysis" class="level3" data-number="7.2.8">
<h3 data-number="7.2.8" class="anchored" data-anchor-id="sec-fn-master-analysis"><span class="header-section-number">7.2.8</span> Module 7: <code>master_analysis.R</code> — Orchestration</h3>
<p><code>master_analysis.R</code> is the top of the call stack. Its central function, <code>analyze_full_scenario()</code>, is what each scenario chapter calls. It takes a scenario code (e.g., <code>"PD"</code>), a full scenario name (e.g., <code>"Public Domain"</code>), the data, and an <code>export_tiffs</code> flag, then runs all five question types (Q1, Q2, Q3, Delta, Price) through the pipeline and collects the results into a named list.</p>
<p>The module’s hierarchy is explicit in the source comments: <code>generate_full_report()</code> → <code>analyze_all_scenarios()</code> → <code>analyze_full_scenario()</code> → <code>analyze_scenario_question()</code> → specialist plot functions. The Quarto book uses only the third level—<code>analyze_full_scenario()</code>—because each chapter handles one scenario and the book structure itself provides the “all scenarios” organization.</p>
<p>The EU scenario receives special handling: if <code>scenario_code == "EU"</code> and a <code>data_b1</code> argument is provided, the function swaps in the EU-specific dataset. In the Quarto book, <code>_common.R</code> pre-computes both <code>survey_data</code> and <code>survey_data_eu</code>, so each scenario chapter passes the correct dataset directly.</p>
<p><strong>Return structure:</strong></p>
<pre><code>results
├── $plots        — ggplot objects: $q1, $q2, $q3, $delta, $price
├── $statistics   — data frames (mean, SD, median by group): $q1 … $price
├── $tests        — $delta: list of wilcox.test() per group
│                   $price: outlier-trimmed data frame
├── $summary      — long-format table combining all $statistics entries
├── $scenario_code
└── $scenario_name</code></pre>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Function</th>
<th>Key Parameters</th>
<th>Returns</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>analyze_full_scenario()</code></td>
<td><code>data</code>, <code>scenario_code</code>, <code>scenario_name</code>, <code>export_tiffs</code>, <code>data_b1</code></td>
<td>named list</td>
<td>Run all 5 questions; return plots + stats + tests</td>
</tr>
<tr class="even">
<td><code>analyze_all_scenarios()</code></td>
<td><code>main_data</code>, <code>b1_data</code>, <code>scenarios</code></td>
<td>named list</td>
<td>Loop over all 7 scenarios</td>
</tr>
<tr class="odd">
<td><code>create_scenario_summary()</code></td>
<td><code>stats_list</code></td>
<td>data frame</td>
<td>Combine per-question stats into one table</td>
</tr>
<tr class="even">
<td><code>compare_across_scenarios()</code></td>
<td><code>results_list</code></td>
<td>data frame</td>
<td>Cross-scenario Q1 mean comparison</td>
</tr>
<tr class="odd">
<td><code>generate_full_report()</code></td>
<td><code>data_paths</code>, <code>output_dir</code></td>
<td>named list</td>
<td>Full pipeline: load → check → analyze → save</td>
</tr>
<tr class="even">
<td><code>quick_analyze()</code></td>
<td><code>data</code>, <code>scenario_code</code>, <code>question</code></td>
<td>list</td>
<td>Single question without TIFF export</td>
</tr>
</tbody>
</table>
</section>
<section id="sec-fn-putting-together" class="level3" data-number="7.2.9">
<h3 data-number="7.2.9" class="anchored" data-anchor-id="sec-fn-putting-together"><span class="header-section-number">7.2.9</span> Call-Site Pattern</h3>
<p>With all seven modules loaded, every scenario chapter reduces to a single call:</p>
<p>The EU scenario passes <code>survey_data_eu</code> (Groups A/B1/C, n = 905) instead of <code>survey_data</code>. The pipeline’s modularity means that changing any single layer, replacing the theme in <code>plotting_themes.R</code>, adding an effect size in <code>stats_helpers.R</code>, or switching export format in <code>export_helpers.R</code> propagates automatically to all seven scenario chapters without touching the chapter files themselves.</p>
</section>
</section>
<section id="sec-howto-graphs" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="sec-howto-graphs"><span class="header-section-number">7.3</span> How to Read the Scenario Graphs</h2>
<p>The scenario chapters use the same <code>ggbetweenstats</code> engine from <a href="https://indrajeetpatil.github.io/ggstatsplot/"><code>ggstatsplot</code></a> described in <a href="./04-randomization.html#sec-rand-howto">§4.3</a>, which explains the basic visual elements: the violin shape (probability density), the box plot (quartiles and median), the centrality point (large dot with numeric label), and the subtitle (omnibus test results). This section covers what is <em>new</em> in the scenario graphs. The key interpretive shift is directional: in Chapter 4, a non-significant result (<em>p</em> &gt; 0.05) confirmed successful randomization. Here, a significant result (<em>p</em> &lt; 0.05) indicates a treatment effect, statistical evidence that CC license information changed how respondents answered.</p>
<section id="group-ordering-and-labels" class="level3" data-number="7.3.1">
<h3 data-number="7.3.1" class="anchored" data-anchor-id="group-ordering-and-labels"><span class="header-section-number">7.3.1</span> Group Ordering and Labels</h3>
<p>Groups are displayed left-to-right, beginning with the control and then moving through two increasing intensities of treatment exposure to CC’s license marking: <strong>Control (C)</strong> → <strong>Short (A)</strong> → <strong>Full + Primer (B)</strong>. Control respondents received a standard copyright marking or similar standard variant; Short received a brief, abbreviated CC label with logos; Full + Primer received a full text license name along with mandatory exposure to an educational primer for at least 20 seconds.</p>
</section>
<section id="new-visual-elements" class="level3" data-number="7.3.2">
<h3 data-number="7.3.2" class="anchored" data-anchor-id="new-visual-elements"><span class="header-section-number">7.3.2</span> New Visual Elements</h3>
<p>Two elements appear in the scenario graphs that are absent from the randomization checks:</p>
<ul>
<li><p><strong>Significance brackets.</strong> After the Kruskal-Wallis omnibus test, Dunn’s post-hoc test (with Holm correction) identifies <em>which</em> group pairs differ. Brackets connecting two groups appear above the plot, with Holm-adjusted <em>p</em>-values displayed at the bracket midpoint. Only statistically significant pairs are shown; if no bracket connects two groups, their difference was not significant after correction for multiple comparisons.</p></li>
<li><p><strong>Caption with VDA effect sizes.</strong> Below each figure, the caption reports pairwise Vargha &amp; Delaney’s <em>A</em> (VDA) effect sizes. VDA is a probability: it estimates the chance that a randomly selected observation from one group exceeds a randomly selected observation from the other. A value of 0.50 means no difference; departures from 0.50 indicate the direction and magnitude of the effect. Interpretation thresholds (small, medium, large) follow Vargha &amp; Delaney (2000) and are given in <a href="./01-methods.html#tbl-vda-thresholds">Table 2.1</a>.</p></li>
</ul>
</section>
<section id="three-plot-types" class="level3" data-number="7.3.3">
<h3 data-number="7.3.3" class="anchored" data-anchor-id="three-plot-types"><span class="header-section-number">7.3.3</span> Three Plot Types</h3>
<p>The scenario chapters produce three structurally distinct graph types:</p>
<p><strong>Q1, Q2, Q3 (Likert-scale questions).</strong> These plots display responses on a 7-point scale. Individual data points are hidden to reduce clutter. The centrality point marks the group <strong>mean</strong>, even when the test statistics are nonparametric for ease of interpretation.</p>
<p><strong>Delta (Δ = Q2 − Q3).</strong> Delta plots visualize the <em>difference</em> between each respondent’s perception of current law (Q2) and their normative preference (Q3). A positive delta means the respondent sees the law as stricter than they prefer; a negative delta means the law is more permissive than preferred. The Y-axis is the Q2–Q3 difference rather than a raw survey response. Each delta plot is accompanied by a <strong>Wilcoxon signed-rank table</strong> reporting whether each group’s median delta is significantly different from zero — that is, whether there is a measurable gap between “what the law is” and “what the law should be” within that group.</p>
<p><strong>Price (Q4).</strong> Price plots show respondents’ dollar estimates of the value of the copyrighted work in the scenario. Individual estimates are displayed as semi-transparent jittered dots because the distribution shape is substantively informative. The centrality point marks the group <strong>median</strong> rather than the mean, because price distributions are right-skewed and the median is more robust to extreme values. Before any statistics are computed, the <strong>top 1% of estimates within each group</strong> are trimmed as outliers to prevent a handful of extreme responses from distorting the visual scale and test results.</p>
</section>
<section id="quick-interpretation" class="level3" data-number="7.3.4">
<h3 data-number="7.3.4" class="anchored" data-anchor-id="quick-interpretation"><span class="header-section-number">7.3.4</span> Quick Interpretation</h3>
<p>For any scenario graph: if the subtitle shows <em>p</em> &lt; 0.05, the groups differ overall. Check the <strong>brackets</strong> to see which specific pairs drive the difference, and consult the <strong>caption</strong> for the effect size. For delta plots, the accompanying Wilcoxon table reveals whether each group’s gap between perceived and preferred law is itself significant. The first example the reader will encounter is <a href="_scenarios/pd.html#fig-pd-q1" class="quarto-xref">Figure&nbsp;<span>1</span></a> in the <a href="./_scenarios/pd.html">Public Domain</a> scenario.</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script>
/*
 * sidebar-toc.js — CC Survey Online Appendix
 *
 * Quarto Book sidebar accordion for within-page sections.
 *
 * Actual Quarto behavior (confirmed from rendered HTML):
 *   - toc-location: left places the TOC as <nav id="TOC"> inside #quarto-sidebar,
 *     AFTER the chapter list. The <ul> has class="collapse" (Bootstrap-hidden).
 *   - There is NO #quarto-sidebar-toc-left element in Quarto 1.8.
 *   - CSS hides the nav#TOC block; this script moves the links to nest under
 *     the active chapter <li>, achieving accordion display.
 *
 * Edge case handled: chapters with a body H1 (e.g. {.unnumbered} intro) produce
 * a TOC where the H1 is the sole top-level link and H2s are nested under it.
 * In that case we skip the H1 (which duplicates the sidebar chapter entry) and
 * promote the nested H2 links instead.
 */
(function () {
  'use strict';

  function injectAuthorLine() {
    // Add author name below the book title/subtitle, above the search bar
    if (document.querySelector('.sidebar-author')) return;

    var sidebar = document.getElementById('quarto-sidebar');
    if (!sidebar) return;

    // Insert after subtitle if present, else after title
    var anchor = sidebar.querySelector('.sidebar-subtitle')
              || sidebar.querySelector('.sidebar-title');
    if (!anchor) return;

    var authorDiv = document.createElement('div');
    authorDiv.className = 'sidebar-author';
    authorDiv.innerHTML = 'Thomas H. Rousse<br>J.D., Ph.D.';

    // Insert between subtitle/title and search bar (equidistant)
    var search = sidebar.querySelector('#quarto-search');
    if (search) {
      search.parentNode.insertBefore(authorDiv, search);
    } else {
      anchor.parentNode.insertBefore(authorDiv, anchor.nextSibling);
    }
  }

  function injectSections() {
    // 1. Find the active chapter <li> in the sidebar
    var activeLink = document.querySelector('#quarto-sidebar .sidebar-link.active');
    if (!activeLink) return;
    var activeItem = activeLink.closest('li.sidebar-item');
    if (!activeItem) return;

    // 2. Find the TOC nav that Quarto placed inside the sidebar
    var tocNav = document.querySelector('#quarto-sidebar nav#TOC');
    if (!tocNav) return;

    // 3. Get all section links (already depth-filtered by Quarto's toc-depth: 2)
    var allLinks = Array.from(tocNav.querySelectorAll('a[data-scroll-target]'));

    // Keep only top-level links (no grandparent <li>)
    var topLevelLinks = allLinks.filter(function (link) {
      var parentLi = link.closest('li');
      if (!parentLi) return false;
      var grandparentLi = parentLi.parentElement && parentLi.parentElement.closest('li');
      return !grandparentLi;
    });

    // Edge case: body-H1 chapters (e.g. {.unnumbered} intro).
    // The sole top-level link IS the chapter title — injecting it would duplicate
    // the sidebar chapter entry. Detect this and promote the nested H2 links instead.
    var chapterText = activeLink.textContent.replace(/^\d+[\.\s]+/, '').trim();
    if (
      topLevelLinks.length === 1 &&
      topLevelLinks[0].textContent.trim() === chapterText
    ) {
      // Promote one level deeper (the H2s nested under the H1)
      topLevelLinks = allLinks.filter(function (link) {
        var parentLi = link.closest('li');
        if (!parentLi) return false;
        var grandparentLi = parentLi.parentElement && parentLi.parentElement.closest('li');
        if (!grandparentLi) return false;
        var greatGrandparentLi = grandparentLi.parentElement && grandparentLi.parentElement.closest('li');
        return !greatGrandparentLi;
      });
    }

    if (topLevelLinks.length === 0) return;

    // 4. Build the nested section list
    var sectionList = document.createElement('ul');
    sectionList.className = 'sidebar-sections list-unstyled';

    topLevelLinks.forEach(function (link) {
      var li = document.createElement('li');
      li.className = 'sidebar-section-item';
      // Replace nav-link class with our sidebar class; keep data-scroll-target
      link.className = 'sidebar-section-link';
      li.appendChild(link); // move (not clone) to preserve Quarto scroll-tracking refs
      sectionList.appendChild(li);
    });

    // 5. Insert immediately after the active chapter <li>
    activeItem.parentNode.insertBefore(sectionList, activeItem.nextSibling);

    // 6. tocNav is already hidden via CSS; no further action needed
  }

  function init() {
    injectAuthorLine();
    injectSections();
  }

  if (document.readyState === 'complete') {
    init();
  } else {
    window.addEventListener('load', init);
  }
}());
</script>
<script>
/*
 * scenario-numbering.js — CC Survey Online Appendix
 *
 * Renumbers tables, figures, and cross-reference links in unnumbered
 * scenario sub-chapters from bare sequential numbers (Table 1, Figure 1)
 * to 3-level format (Table 7.1.1, Figure 7.1.1).
 *
 * Parent chapter: 07-scenarios.qmd = Chapter 7
 * Sub-chapters: pd=1, pu=2, eu=3, ca=4, ls=5, wn=6, fs=7
 *
 * Runs after DOM load. Only modifies scenario pages.
 */
document.addEventListener('DOMContentLoaded', function() {
  var scenarios = {pd:1, pu:2, eu:3, ca:4, ls:5, wn:6, fs:7};
  var path = window.location.pathname;
  var scenarioIdx = null;

  for (var code in scenarios) {
    if (path.match(new RegExp('[/\\\\]' + code + '\\.html$'))) {
      scenarioIdx = scenarios[code];
      break;
    }
  }

  if (!scenarioIdx) return;

  var prefix = '7.' + scenarioIdx + '.';

  // ── Figure captions ──────────────────────────────────────────
  // Quarto renders: Figure&nbsp;N: caption text
  document.querySelectorAll('figcaption').forEach(function(cap) {
    cap.innerHTML = cap.innerHTML.replace(
      /Figure(&nbsp;|\u00A0|\s)(\d+)(?![\d.])/g,
      function(m, sp, n) { return 'Figure' + sp + prefix + n; }
    );
  });

  // ── Cross-reference links ────────────────────────────────────
  // Quarto renders: <a class="quarto-xref">Table&nbsp;<span>N</span></a>
  // or:             <a class="quarto-xref">Figure&nbsp;<span>N</span></a>
  document.querySelectorAll('a.quarto-xref').forEach(function(link) {
    var spans = link.querySelectorAll('span');
    if (spans.length === 0) return;

    // The last span contains the bare number
    var numSpan = spans[spans.length - 1];
    var num = numSpan.textContent.trim();
    if (/^\d+$/.test(num) && !num.includes('.')) {
      // Check the text before the span is "Table" or "Figure"
      var text = link.textContent;
      if (/^(Table|Figure)/.test(text)) {
        numSpan.textContent = prefix + num;
      }
    }
  });
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./06-brand.html" class="pagination-link" aria-label="Brand Recognition">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Brand Recognition</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./_scenarios/pd.html" class="pagination-link" aria-label="7.1 Public Domain">
        <span class="nav-page-text">7.1 Public Domain</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Factorial Vignette Analysis Overview"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="in">```{r setup, include=FALSE}</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"_common.R"</span>))</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">## Analysis Structure</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>Each of the seven scenario chapters that follow uses a parallel structure:</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Scenario Context** — the vignette presented to respondents</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Q1: Legal Consequences** — Kruskal-Wallis + Dunn's post-hoc + VDA (figure and table)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Q2: What the Law Is** — Kruskal-Wallis + Dunn's + VDA</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Q3: What the Law Should Be** — Kruskal-Wallis + Dunn's + VDA</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**Δ (Delta, Q2 − Q3)** — within-group Wilcoxon signed-rank tests</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**Q4: Price estimate** — Kruskal-Wallis + Dunn's</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>Data: Groups A, B, C (n = 1,222) for all scenarios except <span class="co">[</span><span class="ot">Educational Use</span><span class="co">](_scenarios/eu.qmd)</span>, which filters to Groups A, B1, C (*n* = 905) due to a supplemental data collection. See <span class="co">[</span><span class="ot">§3.1 (Codebook)</span><span class="co">](02-codebook.qmd#sec-b1)</span> for the B1 substitution.</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>Statistical methods are detailed in the <span class="co">[</span><span class="ot">Methods chapter</span><span class="co">](01-methods.qmd#sec-statistical-methods)</span>. Effect sizes (VDA) are interpreted using the thresholds in <span class="co">[</span><span class="ot">Table 2.1</span><span class="co">](01-methods.qmd#tbl-vda-thresholds)</span>.</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>Cross-reference format: figures are labeled <span class="in">`@fig-[scenario]-q[N]`</span> (e.g., <span class="in">`@fig-pd-q1`</span>); tables are labeled <span class="in">`@tbl-[scenario]-q[N]-stats`</span> (e.g., <span class="in">`@tbl-pd-q1-stats`</span>).</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="fu">## Analysis Pipeline {#sec-functions}</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>Every scenario chapter (§§7.1–7.7) calls a single function,</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a><span class="in">`analyze_full_scenario()`</span>, and receives back a complete set of plots, descriptive statistics, and test results. That one call sets in motion a coordinated pipeline of seven R modules, each responsible for a distinct layer of the analysis. This section documents those modules: what each one does, why it was designed the way it was, and how the pieces fit together.</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>All seven files live in <span class="in">`analysis/functions/`</span> and are sourced at book startup by <span class="in">`_common.R`</span>. The source code for each module is folded below its description; click **Show source** to expand it. Code results are cached for HTML display but can be manually run as an R or Positron Notebook.</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a><span class="fu">### Pipeline Overview {#sec-fn-overview}</span></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a><span class="in">```{mermaid}</span></span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>%%| label: fig-pipeline</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>%%| fig-cap: <span class="ot">"</span><span class="st">Analysis pipeline: from raw CSV to scenario chapter outputs.</span><span class="ot">"</span></span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>flowchart TD</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>  CSV[<span class="ot">"</span><span class="st">rousse-cc-survey-2024.csv</span><span class="ch">\n</span><span class="st">(1,319 obs, all groups)</span><span class="ot">"</span>]</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>  subgraph common [<span class="ot">"</span><span class="st">_common.R  (book startup)</span><span class="ot">"</span>]</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>    CSV --&gt; dp[<span class="ot">"</span><span class="st">data_prep.R</span><span class="ch">\n</span><span class="st">load_survey_data()</span><span class="ch">\n</span><span class="st">create_all_deltas()</span><span class="ot">"</span>]</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>    dp --&gt; sdA[<span class="ot">"</span><span class="st">survey_data</span><span class="ch">\n</span><span class="st">GROUP ∈ {A, B, C}</span><span class="ch">\n</span><span class="st">n = 1,222</span><span class="ot">"</span>]</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a>    dp --&gt; sdB[<span class="ot">"</span><span class="st">survey_data_eu</span><span class="ch">\n</span><span class="st">GROUP ∈ {A, B1, C}</span><span class="ch">\n</span><span class="st">n = 905</span><span class="ot">"</span>]</span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>  end</span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a>  subgraph chapter [<span class="ot">"</span><span class="st">Per-scenario chapter  (§7.1 – §7.7)</span><span class="ot">"</span>]</span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a>    sdA --&gt; ma[<span class="ot">"</span><span class="st">master_analysis.R</span><span class="ch">\n</span><span class="st">analyze_full_scenario()</span><span class="ot">"</span>]</span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a>    sdB --&gt; ma</span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a>    ma --&gt; af[<span class="ot">"</span><span class="st">analysis_functions.R</span><span class="ch">\n</span><span class="st">analyze_scenario_question()</span><span class="ch">\n</span><span class="st">create_scenario_plot()</span><span class="ch">\n</span><span class="st">create_delta_plot()</span><span class="ch">\n</span><span class="st">create_price_plot()</span><span class="ot">"</span>]</span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a>    af --&gt; sh[<span class="ot">"</span><span class="st">stats_helpers.R</span><span class="ch">\n</span><span class="st">validate_group_data()</span><span class="ch">\n</span><span class="st">Kruskal-Wallis · Dunn's post-hoc</span><span class="ch">\n</span><span class="st">VDA effect sizes</span><span class="ch">\n</span><span class="st">Wilcoxon signed-rank (delta)</span><span class="ot">"</span>]</span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a>    af --&gt; pt[<span class="ot">"</span><span class="st">plotting_themes.R</span><span class="ch">\n</span><span class="st">get_standard_theme()</span><span class="ch">\n</span><span class="st">get_standard_plot_args()</span><span class="ch">\n</span><span class="st">get_price_plot_args()</span><span class="ot">"</span>]</span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a>    af --&gt; ex[<span class="ot">"</span><span class="st">export_helpers.R</span><span class="ch">\n</span><span class="st">export_plot_to_tiff()</span><span class="ch">\n</span><span class="st">data / figures / v2 /</span><span class="ot">"</span>]</span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a>    ma --&gt; out[<span class="ot">"</span><span class="st">Returns nested list:</span><span class="ch">\n</span><span class="dt">$plots</span><span class="st"> · </span><span class="dt">$statistics</span><span class="st"> · </span><span class="dt">$tests</span><span class="ot">"</span>]</span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a>  end</span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a>  rc[<span class="ot">"</span><span class="st">randomization_checks.R</span><span class="ch">\n</span><span class="st">check_continuous_covariate()</span><span class="ch">\n</span><span class="st">check_categorical_covariate()</span><span class="ch">\n</span><span class="st">check_brand_recognition()</span><span class="ot">"</span>] -.-&gt;|<span class="ot">"</span><span class="st">Ch. 4–5 only</span><span class="ot">"</span>| sdA</span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a>The pipeline separates cleanly into three tiers: *data* (Module 1), *statistics and visualization* (Modules 2–5), and *orchestration* (Module 7). Module 6 supports only Chapters 4 and 5 and is never called by the scenario analysis chain.</span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a><span class="fu">### Module 1: `data_prep.R` — Data Ingestion {#sec-fn-data-prep}</span></span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a><span class="in">`data_prep.R`</span> handles everything that must happen before any statistics can be run: loading the CSV, constructing computed columns, and producing the two analysis views that the rest of the book uses.</span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a>The central design decision is **single-file architecture**.  The two analysis views are created in <span class="in">`_common.R`</span> by filtering on <span class="in">`GROUP`</span>: <span class="in">`survey_data`</span> keeps Groups A, B, and C (*n* = 1,222); `survey_data_eu` keeps Groups A, B1, and C (*n* = 905). The <span class="in">`prepare_eu_data()`</span> function in this module handles the original</span>
<span id="cb2-69"><a href="#cb2-69" aria-hidden="true" tabindex="-1"></a>two-file workflow and is preserved for provenance, but it is not called at book startup.</span>
<span id="cb2-70"><a href="#cb2-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-71"><a href="#cb2-71" aria-hidden="true" tabindex="-1"></a>The other key contribution is **delta variable creation**. Each scenario includes a question about what the law currently permits (Q2) and a question about what respondents prefer (Q3). Their difference (Δ = Q2 − Q3) is stored in a column named <span class="in">`[SCENARIO]25`</span> (e.g., <span class="in">`PD25`</span>). A positive delta means the law is stricter than</span>
<span id="cb2-72"><a href="#cb2-72" aria-hidden="true" tabindex="-1"></a>respondents prefer; a negative delta means the law is more permissive. <span class="in">`create_all_deltas()`</span> loops over all seven scenario codes and creates these columns in a single pass, and it</span>
<span id="cb2-73"><a href="#cb2-73" aria-hidden="true" tabindex="-1"></a>gracefully skips any scenario whose Q2/Q3 columns are absent.</span>
<span id="cb2-74"><a href="#cb2-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-75"><a href="#cb2-75" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Function <span class="pp">|</span> Key Parameters <span class="pp">|</span> Returns <span class="pp">|</span> Role <span class="pp">|</span></span>
<span id="cb2-76"><a href="#cb2-76" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb2-77"><a href="#cb2-77" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`load_survey_data()`</span> <span class="pp">|</span> <span class="in">`filepath`</span>, <span class="in">`filter_groups`</span> <span class="pp">|</span> data frame <span class="pp">|</span> Load and optionally filter CSV <span class="pp">|</span></span>
<span id="cb2-78"><a href="#cb2-78" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`create_delta_variable()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`var1`</span>, <span class="in">`var2`</span>, <span class="in">`new_var_name`</span> <span class="pp">|</span> data frame <span class="pp">|</span> Compute single Δ column <span class="pp">|</span></span>
<span id="cb2-79"><a href="#cb2-79" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`create_all_deltas()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`scenarios`</span> <span class="pp">|</span> data frame <span class="pp">|</span> Batch-create all seven Δ columns <span class="pp">|</span></span>
<span id="cb2-80"><a href="#cb2-80" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`validate_data_structure()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`required_cols`</span> <span class="pp">|</span> logical <span class="pp">|</span> Check that required columns exist <span class="pp">|</span></span>
<span id="cb2-81"><a href="#cb2-81" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`get_scenario_columns()`</span> <span class="pp">|</span> <span class="in">`scenario_code`</span>, <span class="in">`include_delta`</span> <span class="pp">|</span> character vector <span class="pp">|</span> Return column names for a scenario <span class="pp">|</span></span>
<span id="cb2-82"><a href="#cb2-82" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`check_data_quality()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`columns`</span> <span class="pp">|</span> data frame <span class="pp">|</span> Report missing-value rates <span class="pp">|</span></span>
<span id="cb2-83"><a href="#cb2-83" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`prepare_all_data()`</span> <span class="pp">|</span> <span class="in">`main_filepath`</span>, <span class="in">`b1_filepath`</span> <span class="pp">|</span> list <span class="pp">|</span> Master prep: load + delta + optional EU <span class="pp">|</span></span>
<span id="cb2-84"><a href="#cb2-84" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`filter_by_group()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`group`</span> <span class="pp">|</span> data frame <span class="pp">|</span> Extract a single group <span class="pp">|</span></span>
<span id="cb2-85"><a href="#cb2-85" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`split_by_groups()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`group_var`</span> <span class="pp">|</span> list <span class="pp">|</span> Split data into per-group data frames <span class="pp">|</span></span>
<span id="cb2-86"><a href="#cb2-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-87"><a href="#cb2-87" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fn-data-prep-source}</span></span>
<span id="cb2-88"><a href="#cb2-88" aria-hidden="true" tabindex="-1"></a><span class="co">#| file: analysis/functions/data_prep.R</span></span>
<span id="cb2-89"><a href="#cb2-89" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb2-90"><a href="#cb2-90" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb2-91"><a href="#cb2-91" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Show source: data_prep.R (365 lines)"</span></span>
<span id="cb2-92"><a href="#cb2-92" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-93"><a href="#cb2-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-94"><a href="#cb2-94" aria-hidden="true" tabindex="-1"></a><span class="fu">### Module 2: `stats_helpers.R` — Statistical Calculations {#sec-fn-stats-helpers}</span></span>
<span id="cb2-95"><a href="#cb2-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-96"><a href="#cb2-96" aria-hidden="true" tabindex="-1"></a><span class="in">`stats_helpers.R`</span> provides the statistical layer: validation, descriptive summaries, hypothesis tests, and effect sizes. Its design philosophy is to keep statistical decisions in one place so that all seven scenario chapters are guaranteed to use identical methods.</span>
<span id="cb2-97"><a href="#cb2-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-98"><a href="#cb2-98" aria-hidden="true" tabindex="-1"></a>The non-parametric choice is deliberate. The outcome variables are 7-point Likert scales: ordinal, bounded, and typically non-normal in distribution. Kruskal-Wallis is the appropriate omnibus test, and **Dunn's test** (via <span class="in">`rstatix::dunn_test()`</span>, Holm correction) is the appropriate post-hoc. Pairwise Wilcoxon was considered but rejected: Dunn's test is specifically designed for post-hoc comparisons following a Kruskal-Wallis test and uses rank-sum scores from the full dataset, which gives it more appropriate statistical properties in this context.</span>
<span id="cb2-99"><a href="#cb2-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-100"><a href="#cb2-100" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true"}</span>
<span id="cb2-101"><a href="#cb2-101" aria-hidden="true" tabindex="-1"></a><span class="fu">## Design note: Why Vargha &amp; Delaney's A over Cohen's *d* or *r*?</span></span>
<span id="cb2-102"><a href="#cb2-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-103"><a href="#cb2-103" aria-hidden="true" tabindex="-1"></a>Effect sizes based on means (Cohen's *d*) assume interval-level data. For ordinal scales, Vargha &amp; Delaney's *A* is the recommended alternative: it is a rank-based probability that a randomly selected observation from Group X exceeds a randomly selected observation from Group Y. A value of 0.50 indicates no difference; values above 0.50 indicate Group 1 dominance, values below 0.50 indicate Group 2 dominance. Thresholds used throughout this appendix follow Vargha &amp; Delaney (2000) and are given in @tbl-vda-thresholds.</span>
<span id="cb2-104"><a href="#cb2-104" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb2-105"><a href="#cb2-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-106"><a href="#cb2-106" aria-hidden="true" tabindex="-1"></a>The **delta analysis** uses a different test: <span class="in">`test_delta_nonzero()`</span> runs a one-sample Wilcoxon signed-rank test for each group separately, testing whether that group's median delta is significantly different from zero. A non-zero median delta indicates a gap between respondents' perception of current law and their normative preference.</span>
<span id="cb2-107"><a href="#cb2-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-108"><a href="#cb2-108" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Function <span class="pp">|</span> Key Parameters <span class="pp">|</span> Returns <span class="pp">|</span> Role <span class="pp">|</span></span>
<span id="cb2-109"><a href="#cb2-109" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb2-110"><a href="#cb2-110" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`validate_group_data()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`dv`</span>, <span class="in">`min_n`</span> <span class="pp">|</span> list <span class="pp">|</span> Check that each group has ≥ *n* observations <span class="pp">|</span></span>
<span id="cb2-111"><a href="#cb2-111" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`calculate_descriptive_stats()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`dv`</span>, <span class="in">`group_var`</span>, <span class="in">`stats`</span> <span class="pp">|</span> data frame <span class="pp">|</span> Mean, SD, median by group <span class="pp">|</span></span>
<span id="cb2-112"><a href="#cb2-112" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`run_dunn_test()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`formula`</span>, <span class="in">`p_adjust`</span> <span class="pp">|</span> data frame <span class="pp">|</span> Dunn's post-hoc with Holm correction <span class="pp">|</span></span>
<span id="cb2-113"><a href="#cb2-113" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`calculate_vda()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`dv`</span>, <span class="in">`group_var`</span> <span class="pp">|</span> list <span class="pp">|</span> Vargha &amp; Delaney's A for all pairs <span class="pp">|</span></span>
<span id="cb2-114"><a href="#cb2-114" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`format_vda_caption()`</span> <span class="pp">|</span> <span class="in">`dunn_results`</span>, <span class="in">`vda_results`</span> <span class="pp">|</span> character <span class="pp">|</span> Build plot caption with effect sizes <span class="pp">|</span></span>
<span id="cb2-115"><a href="#cb2-115" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`remove_outliers_by_group()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`dv`</span>, <span class="in">`percentile`</span> <span class="pp">|</span> data frame <span class="pp">|</span> Trim top *p*% within each group <span class="pp">|</span></span>
<span id="cb2-116"><a href="#cb2-116" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`test_delta_nonzero()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`dv`</span>, <span class="in">`mu`</span> <span class="pp">|</span> list <span class="pp">|</span> One-sample Wilcoxon (Δ ≠ 0) per group <span class="pp">|</span></span>
<span id="cb2-117"><a href="#cb2-117" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`run_chisq_test()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`var1`</span>, <span class="in">`var2`</span> <span class="pp">|</span> list <span class="pp">|</span> Contingency table + χ² test <span class="pp">|</span></span>
<span id="cb2-118"><a href="#cb2-118" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`compare_groups()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`dv`</span>, <span class="in">`test_type`</span> <span class="pp">|</span> test object <span class="pp">|</span> ANOVA or Kruskal-Wallis omnibus <span class="pp">|</span></span>
<span id="cb2-119"><a href="#cb2-119" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`compute_scenario_price_row()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`scenario_code`</span> <span class="pp">|</span> data frame <span class="pp">|</span> Price summary row (median, outlier-trimmed) <span class="pp">|</span></span>
<span id="cb2-120"><a href="#cb2-120" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`build_price_summary_table()`</span> <span class="pp">|</span> <span class="in">`data_main`</span>, <span class="in">`data_eu`</span> <span class="pp">|</span> data frame <span class="pp">|</span> Cross-scenario price summary <span class="pp">|</span></span>
<span id="cb2-121"><a href="#cb2-121" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`build_price_vda_table()`</span> <span class="pp">|</span> <span class="in">`data_main`</span>, <span class="in">`data_eu`</span> <span class="pp">|</span> data frame <span class="pp">|</span> Cross-scenario price VDA (outlier-trimmed) <span class="pp">|</span></span>
<span id="cb2-122"><a href="#cb2-122" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`build_wilcoxon_table()`</span> <span class="pp">|</span> <span class="in">`data_main`</span>, <span class="in">`data_eu`</span> <span class="pp">|</span> data frame <span class="pp">|</span> Cross-scenario Wilcoxon signed-rank (Δ ≠ 0) <span class="pp">|</span></span>
<span id="cb2-123"><a href="#cb2-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-124"><a href="#cb2-124" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fn-stats-helpers-source}</span></span>
<span id="cb2-125"><a href="#cb2-125" aria-hidden="true" tabindex="-1"></a><span class="co">#| file: analysis/functions/stats_helpers.R</span></span>
<span id="cb2-126"><a href="#cb2-126" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb2-127"><a href="#cb2-127" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb2-128"><a href="#cb2-128" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Show source: stats_helpers.R (877 lines)"</span></span>
<span id="cb2-129"><a href="#cb2-129" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-130"><a href="#cb2-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-131"><a href="#cb2-131" aria-hidden="true" tabindex="-1"></a><span class="fu">### Module 3: `plotting_themes.R` — Visual Consistency {#sec-fn-plotting-themes}</span></span>
<span id="cb2-132"><a href="#cb2-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-133"><a href="#cb2-133" aria-hidden="true" tabindex="-1"></a><span class="in">`plotting_themes.R`</span> is the style guide for every figure in this Appendix. By centralizing all <span class="in">`ggplot2`</span> theme and argument settings, the module guarantees that every plot across all</span>
<span id="cb2-134"><a href="#cb2-134" aria-hidden="true" tabindex="-1"></a>seven scenario chapters shares the same fonts, sizes, color choices, significance bracket styling, and central tendency markers.</span>
<span id="cb2-135"><a href="#cb2-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-136"><a href="#cb2-136" aria-hidden="true" tabindex="-1"></a>The base theme is **Tufte** (via <span class="in">`ggthemes::theme_tufte()`</span>), following Edward Tufte's principle of maximizing the data-to-ink ratio. Unnecessary gridlines and borders are removed; the statistical signal is left to speak for itself. Font resolution is handled through the <span class="in">`PLOT_FONT`</span> global variable, which is set in <span class="in">`_common.R`</span> before this module is sourced; all functions default to <span class="in">`base_family = PLOT_FONT`</span> so that the book-level font choice propagates everywhere automatically.</span>
<span id="cb2-137"><a href="#cb2-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-138"><a href="#cb2-138" aria-hidden="true" tabindex="-1"></a>Two argument-list functions address the structural difference between Likert-scale questions and the price question. </span>
<span id="cb2-139"><a href="#cb2-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-140"><a href="#cb2-140" aria-hidden="true" tabindex="-1"></a><span class="in">`get_standard_plot_args()`</span> configures the standard Q1/Q2/Q3/delta</span>
<span id="cb2-141"><a href="#cb2-141" aria-hidden="true" tabindex="-1"></a>plots: no individual points shown, means displayed (parametric centrality), and significance brackets limited to statistically significant pairs. </span>
<span id="cb2-142"><a href="#cb2-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-143"><a href="#cb2-143" aria-hidden="true" tabindex="-1"></a><span class="in">`get_price_plot_args()`</span> modifies the recipe for price data: individual estimates are shown as semi-transparent jittered dots,</span>
<span id="cb2-144"><a href="#cb2-144" aria-hidden="true" tabindex="-1"></a>and the central tendency switches to **median** (50th percentile) because price distributions are right-skewed and means are not robust to the outliers that remain after the 99th-percentile</span>
<span id="cb2-145"><a href="#cb2-145" aria-hidden="true" tabindex="-1"></a>trim.</span>
<span id="cb2-146"><a href="#cb2-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-147"><a href="#cb2-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-148"><a href="#cb2-148" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Function <span class="pp">|</span> Key Parameters <span class="pp">|</span> Returns <span class="pp">|</span> Role <span class="pp">|</span></span>
<span id="cb2-149"><a href="#cb2-149" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb2-150"><a href="#cb2-150" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`get_standard_theme()`</span> <span class="pp">|</span> <span class="in">`base_family`</span>, <span class="in">`base_size`</span> <span class="pp">|</span> ggplot theme <span class="pp">|</span> Tufte theme with global font <span class="pp">|</span></span>
<span id="cb2-151"><a href="#cb2-151" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`get_standard_plot_args()`</span> <span class="pp">|</span> <span class="in">`show_points`</span>, <span class="in">`base_family`</span> <span class="pp">|</span> list <span class="pp">|</span> ggbetweenstats args for Likert plots <span class="pp">|</span></span>
<span id="cb2-152"><a href="#cb2-152" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`get_price_plot_args()`</span> <span class="pp">|</span> <span class="in">`base_family`</span> <span class="pp">|</span> list <span class="pp">|</span> ggbetweenstats args for price plots <span class="pp">|</span></span>
<span id="cb2-153"><a href="#cb2-153" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`apply_standard_formatting()`</span> <span class="pp">|</span> <span class="in">`plot`</span>, <span class="in">`center_caption`</span> <span class="pp">|</span> ggplot <span class="pp">|</span> Center caption on existing plot <span class="pp">|</span></span>
<span id="cb2-154"><a href="#cb2-154" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`get_group_colors()`</span> <span class="pp">|</span> <span class="in">`n_groups`</span> <span class="pp">|</span> character vector <span class="pp">|</span> Okabe-Ito colorblind-safe palette <span class="pp">|</span></span>
<span id="cb2-155"><a href="#cb2-155" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`set_global_plot_options()`</span> <span class="pp">|</span> <span class="in">`base_family`</span> <span class="pp">|</span> NULL (side effect) <span class="pp">|</span> Set session-wide ggplot2 defaults <span class="pp">|</span></span>
<span id="cb2-156"><a href="#cb2-156" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`get_axis_labels()`</span> <span class="pp">|</span> <span class="in">`scenario_code`</span>, <span class="in">`question_type`</span> <span class="pp">|</span> list <span class="pp">|</span> Standardized x/y axis labels <span class="pp">|</span></span>
<span id="cb2-157"><a href="#cb2-157" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`format_plot_title()`</span> <span class="pp">|</span> <span class="in">`scenario_name`</span>, <span class="in">`question_type`</span> <span class="pp">|</span> character <span class="pp">|</span> Two-line title for each question type <span class="pp">|</span></span>
<span id="cb2-158"><a href="#cb2-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-159"><a href="#cb2-159" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fn-plotting-themes-source}</span></span>
<span id="cb2-160"><a href="#cb2-160" aria-hidden="true" tabindex="-1"></a><span class="co">#| file: analysis/functions/plotting_themes.R</span></span>
<span id="cb2-161"><a href="#cb2-161" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb2-162"><a href="#cb2-162" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb2-163"><a href="#cb2-163" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Show source: plotting_themes.R (372 lines)"</span></span>
<span id="cb2-164"><a href="#cb2-164" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-165"><a href="#cb2-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-166"><a href="#cb2-166" aria-hidden="true" tabindex="-1"></a><span class="fu">### Module 4: `analysis_functions.R` — Per-Question Plots {#sec-fn-analysis-functions}</span></span>
<span id="cb2-167"><a href="#cb2-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-168"><a href="#cb2-168" aria-hidden="true" tabindex="-1"></a><span class="in">`analysis_functions.R`</span> is where statistical tests and visualizations are actually assembled. Its four functions correspond to the four structural plot types that appear across the</span>
<span id="cb2-169"><a href="#cb2-169" aria-hidden="true" tabindex="-1"></a>scenario chapters: standard questions (Q1/Q2/Q3), delta questions (Δ = Q2 − Q3), price questions (Q4), and a master dispatcher that routes each question to the appropriate specialized function.</span>
<span id="cb2-170"><a href="#cb2-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-171"><a href="#cb2-171" aria-hidden="true" tabindex="-1"></a>The core plot engine throughout is <span class="in">`ggstatsplot::ggbetweenstats()`</span>. This function was chosen because it combines group-level box plots, individual jitter (optional), pairwise significance brackets, and statistical test results in a single, opinionated call. The</span>
<span id="cb2-172"><a href="#cb2-172" aria-hidden="true" tabindex="-1"></a>tradeoff is that the function's defaults are opinionated and occasionally need to be overridden, leading to <span class="in">`plotting_themes.R`</span> as a separate layer.</span>
<span id="cb2-173"><a href="#cb2-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-174"><a href="#cb2-174" aria-hidden="true" tabindex="-1"></a>A critical detail shared by all three plot functions is **group factor reordering**. The raw <span class="in">`GROUP`</span> column contains the strings <span class="in">`"A"`</span>, <span class="in">`"B"`</span>, <span class="in">`"C"`</span>, and (for EU) <span class="in">`"B1"`</span>. Left</span>
<span id="cb2-175"><a href="#cb2-175" aria-hidden="true" tabindex="-1"></a>to its default, R would display these alphabetically. Each function refactors the column to display order C → A → B (Control first, then treatments in ascending information density), and maps the codes to human-readable labels: <span class="in">`"Control (C)"`</span>, <span class="in">`"Short (A)"`</span>,</span>
<span id="cb2-176"><a href="#cb2-176" aria-hidden="true" tabindex="-1"></a><span class="in">`"Full + Primer (B)"`</span>, and <span class="in">`"Full + Primer (B1)"`</span>. This ordering is applied consistently before any statistical test is run, so all group comparisons and labels in the output match this canonical ordering.</span>
<span id="cb2-177"><a href="#cb2-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-178"><a href="#cb2-178" aria-hidden="true" tabindex="-1"></a><span class="in">`create_delta_plot()`</span> adds one step beyond the standard plot: after producing the between-group visualization, it runs a one-sample Wilcoxon signed-rank test for each group separately. The test result finding whether each group's median delta is significantly different from zero is returned alongside the plot and appears in the scenario chapters as the Wilcoxon results table.</span>
<span id="cb2-179"><a href="#cb2-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-180"><a href="#cb2-180" aria-hidden="true" tabindex="-1"></a><span class="in">`create_price_plot()`</span> adds outlier removal via <span class="in">`remove_outliers_by_group()`</span> before any statistics are run. Price estimates are right-skewed and occasionally extreme; removing</span>
<span id="cb2-181"><a href="#cb2-181" aria-hidden="true" tabindex="-1"></a>the top 1% within each group independently (rather than across the full sample) prevents any one group's outliers from distorting the visual scale.</span>
<span id="cb2-182"><a href="#cb2-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-183"><a href="#cb2-183" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Function <span class="pp">|</span> Key Parameters <span class="pp">|</span> Returns <span class="pp">|</span> Role <span class="pp">|</span></span>
<span id="cb2-184"><a href="#cb2-184" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb2-185"><a href="#cb2-185" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`create_scenario_plot()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`dv`</span>, <span class="in">`ylab`</span>, <span class="in">`title`</span>, <span class="in">`show_points`</span> <span class="pp">|</span> ggplot <span class="pp">|</span> Standard Likert plot (Q1/Q2/Q3) <span class="pp">|</span></span>
<span id="cb2-186"><a href="#cb2-186" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`create_delta_plot()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`dv`</span>, <span class="in">`title`</span>, <span class="in">`test_by_group`</span> <span class="pp">|</span> list (plot + Wilcoxon) <span class="pp">|</span> Delta plot with per-group zero test <span class="pp">|</span></span>
<span id="cb2-187"><a href="#cb2-187" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`create_price_plot()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`dv`</span>, <span class="in">`title`</span>, <span class="in">`percentile`</span> <span class="pp">|</span> list (plot + filtered data) <span class="pp">|</span> Price plot with outlier trimming <span class="pp">|</span></span>
<span id="cb2-188"><a href="#cb2-188" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`analyze_scenario_question()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`dv`</span>, <span class="in">`question_type`</span>, <span class="in">`scenario_name`</span>, <span class="in">`export_tiff`</span> <span class="pp">|</span> list <span class="pp">|</span> Dispatcher: routes to appropriate function <span class="pp">|</span></span>
<span id="cb2-189"><a href="#cb2-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-190"><a href="#cb2-190" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fn-analysis-functions-source}</span></span>
<span id="cb2-191"><a href="#cb2-191" aria-hidden="true" tabindex="-1"></a><span class="co">#| file: analysis/functions/analysis_functions.R</span></span>
<span id="cb2-192"><a href="#cb2-192" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb2-193"><a href="#cb2-193" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb2-194"><a href="#cb2-194" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Show source: analysis_functions.R (534 lines)"</span></span>
<span id="cb2-195"><a href="#cb2-195" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-196"><a href="#cb2-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-197"><a href="#cb2-197" aria-hidden="true" tabindex="-1"></a><span class="fu">### Module 5: `export_helpers.R` — Figure Export {#sec-fn-export-helpers}</span></span>
<span id="cb2-198"><a href="#cb2-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-199"><a href="#cb2-199" aria-hidden="true" tabindex="-1"></a><span class="in">`export_helpers.R`</span> handles the mechanics of saving analysis outputs to disk.</span>
<span id="cb2-200"><a href="#cb2-200" aria-hidden="true" tabindex="-1"></a><span class="in">`export_plot_to_tiff()`</span> is the function called by <span class="in">`analyze_scenario_question()`</span> whenever <span class="in">`export_tiff = TRUE`</span>. It uses R's base graphics device system—<span class="in">`tiff()`</span> → <span class="in">`print(plot)`</span></span>
<span id="cb2-201"><a href="#cb2-201" aria-hidden="true" tabindex="-1"></a>→ <span class="in">`dev.off()`</span>—to write a 300 DPI TIFF suitable for journal submission.</span>
<span id="cb2-202"><a href="#cb2-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-203"><a href="#cb2-203" aria-hidden="true" tabindex="-1"></a>The default output path uses <span class="in">`here::here("data", "figures", "v2")`</span>, which resolves relative to the project root regardless of the working directory at the time of rendering. The filename convention is <span class="in">`[SCENARIO][QUESTION][WIDTH×10].tiff`</span> — for example,</span>
<span id="cb2-204"><a href="#cb2-204" aria-hidden="true" tabindex="-1"></a><span class="in">`PD165.tiff`</span> for the Public Domain Q1 plot at 6.5 inches wide. The <span class="in">`generate_filename()`</span> function encodes this convention explicitly.</span>
<span id="cb2-205"><a href="#cb2-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-206"><a href="#cb2-206" aria-hidden="true" tabindex="-1"></a>The remaining functions (<span class="in">`export_plots_batch()`</span>, <span class="in">`save_analysis_results()`</span>,</span>
<span id="cb2-207"><a href="#cb2-207" aria-hidden="true" tabindex="-1"></a><span class="in">`export_stats_to_csv()`</span>, <span class="in">`export_all_results()`</span>) support the standalone batch workflow and the <span class="in">`generate_full_report()`</span> orchestrator. They are not called during normal book rendering.</span>
<span id="cb2-208"><a href="#cb2-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-209"><a href="#cb2-209" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Function <span class="pp">|</span> Key Parameters <span class="pp">|</span> Returns <span class="pp">|</span> Role <span class="pp">|</span></span>
<span id="cb2-210"><a href="#cb2-210" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb2-211"><a href="#cb2-211" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`export_plot_to_tiff()`</span> <span class="pp">|</span> <span class="in">`plot`</span>, <span class="in">`filename`</span>, <span class="in">`width`</span>, <span class="in">`height`</span>, <span class="in">`res`</span>, <span class="in">`path`</span> <span class="pp">|</span> NULL <span class="pp">|</span> Save ggplot to 300 DPI TIFF <span class="pp">|</span></span>
<span id="cb2-212"><a href="#cb2-212" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`export_results_table()`</span> <span class="pp">|</span> <span class="in">`stats_df`</span>, <span class="in">`format`</span>, <span class="in">`caption`</span> <span class="pp">|</span> kable <span class="pp">|</span> Format stats table for document <span class="pp">|</span></span>
<span id="cb2-213"><a href="#cb2-213" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`export_plots_batch()`</span> <span class="pp">|</span> <span class="in">`plots`</span>, <span class="in">`prefix`</span>, <span class="in">`width`</span>, <span class="in">`height`</span> <span class="pp">|</span> NULL <span class="pp">|</span> Batch-export named list of plots <span class="pp">|</span></span>
<span id="cb2-214"><a href="#cb2-214" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`save_analysis_results()`</span> <span class="pp">|</span> <span class="in">`results`</span>, <span class="in">`filename`</span>, <span class="in">`path`</span> <span class="pp">|</span> NULL <span class="pp">|</span> Serialize results list to RDS <span class="pp">|</span></span>
<span id="cb2-215"><a href="#cb2-215" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`export_stats_to_csv()`</span> <span class="pp">|</span> <span class="in">`stats_list`</span>, <span class="in">`filename`</span>, <span class="in">`path`</span> <span class="pp">|</span> NULL <span class="pp">|</span> Write all scenario stats to CSV <span class="pp">|</span></span>
<span id="cb2-216"><a href="#cb2-216" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`generate_filename()`</span> <span class="pp">|</span> <span class="in">`scenario_code`</span>, <span class="in">`question`</span>, <span class="in">`width`</span> <span class="pp">|</span> character <span class="pp">|</span> Build canonical TIFF filename <span class="pp">|</span></span>
<span id="cb2-217"><a href="#cb2-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-218"><a href="#cb2-218" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fn-export-helpers-source}</span></span>
<span id="cb2-219"><a href="#cb2-219" aria-hidden="true" tabindex="-1"></a><span class="co">#| file: analysis/functions/export_helpers.R</span></span>
<span id="cb2-220"><a href="#cb2-220" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb2-221"><a href="#cb2-221" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb2-222"><a href="#cb2-222" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Show source: export_helpers.R (515 lines)"</span></span>
<span id="cb2-223"><a href="#cb2-223" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-224"><a href="#cb2-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-225"><a href="#cb2-225" aria-hidden="true" tabindex="-1"></a><span class="fu">### Module 6: `randomization_checks.R` — Covariate Balance {#sec-fn-randomization-checks}</span></span>
<span id="cb2-226"><a href="#cb2-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-227"><a href="#cb2-227" aria-hidden="true" tabindex="-1"></a><span class="in">`randomization_checks.R`</span> is deliberately isolated from the scenario analysis chain. Its functions appear in Chapter 4 (@sec-randomization) and Chapter 5 (@sec-brand), and they</span>
<span id="cb2-228"><a href="#cb2-228" aria-hidden="true" tabindex="-1"></a>are never called by <span class="in">`analyze_full_scenario()`</span>. Keeping balance checks in their own module prevents the scenario chapters from accumulating diagnostic overhead, and it makes the covariate-balance logic easy to find and audit independently.</span>
<span id="cb2-229"><a href="#cb2-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-230"><a href="#cb2-230" aria-hidden="true" tabindex="-1"></a><span class="in">`check_continuous_covariate()`</span> handles numeric variables (Age, Income, Education). The test selection is adaptive: Age and Income are tested with ANOVA; scale-based variables (Internet skills) use Kruskal-Wallis. <span class="in">`check_categorical_covariate()`</span> handles nominal</span>
<span id="cb2-231"><a href="#cb2-231" aria-hidden="true" tabindex="-1"></a>variables (Race, Gender) via chi-square test. The <span class="in">`$proportions`</span> component gives within-group proportions, which are more interpretable for balance assessment than raw counts.</span>
<span id="cb2-232"><a href="#cb2-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-233"><a href="#cb2-233" aria-hidden="true" tabindex="-1"></a>The module also contains <span class="in">`check_brand_recognition()`</span>, which analyzes the four-item brand recognition battery (Creative Commons, Byteyield, Microsoft, Mozilla). Byteyield is a fictitious brand included as an attention check; its recognition mean should be well below the 2.5 threshold.</span>
<span id="cb2-234"><a href="#cb2-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-235"><a href="#cb2-235" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true"}</span>
<span id="cb2-236"><a href="#cb2-236" aria-hidden="true" tabindex="-1"></a><span class="fu">## Why isolate randomization checks from scenario analysis?</span></span>
<span id="cb2-237"><a href="#cb2-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-238"><a href="#cb2-238" aria-hidden="true" tabindex="-1"></a>If <span class="in">`randomization_checks.R`</span> were sourced inside each scenario chapter, every chapter would re-run the balance tests — repeating the same checks seven times with no additional</span>
<span id="cb2-239"><a href="#cb2-239" aria-hidden="true" tabindex="-1"></a>information. Placing the checks in dedicated chapters (4 and 5) and in a standalone module makes the one-time nature of the diagnostic explicit.</span>
<span id="cb2-240"><a href="#cb2-240" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb2-241"><a href="#cb2-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-242"><a href="#cb2-242" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Function <span class="pp">|</span> Key Parameters <span class="pp">|</span> Returns <span class="pp">|</span> Role <span class="pp">|</span></span>
<span id="cb2-243"><a href="#cb2-243" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb2-244"><a href="#cb2-244" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`check_continuous_covariate()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`covariate`</span>, <span class="in">`test_type`</span>, <span class="in">`create_plot`</span> <span class="pp">|</span> list <span class="pp">|</span> ANOVA or K-W + optional plot <span class="pp">|</span></span>
<span id="cb2-245"><a href="#cb2-245" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`check_categorical_covariate()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`covariate`</span>, <span class="in">`create_table`</span> <span class="pp">|</span> list <span class="pp">|</span> χ² test + contingency table <span class="pp">|</span></span>
<span id="cb2-246"><a href="#cb2-246" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`run_all_randomization_checks()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`continuous_vars`</span>, <span class="in">`categorical_vars`</span> <span class="pp">|</span> list <span class="pp">|</span> Batch all covariate checks <span class="pp">|</span></span>
<span id="cb2-247"><a href="#cb2-247" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`summarize_randomization_checks()`</span> <span class="pp">|</span> <span class="in">`check_results`</span> <span class="pp">|</span> data frame <span class="pp">|</span> Tidy summary table of all tests <span class="pp">|</span></span>
<span id="cb2-248"><a href="#cb2-248" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`plot_randomization_grid()`</span> <span class="pp">|</span> <span class="in">`check_results`</span>, <span class="in">`ncol`</span> <span class="pp">|</span> patchwork / list <span class="pp">|</span> Arrange all check plots in a grid <span class="pp">|</span></span>
<span id="cb2-249"><a href="#cb2-249" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`check_brand_recognition()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`brand_cols`</span>, <span class="in">`create_plot`</span> <span class="pp">|</span> list <span class="pp">|</span> Brand recognition summary + likert plot <span class="pp">|</span></span>
<span id="cb2-250"><a href="#cb2-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-251"><a href="#cb2-251" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fn-randomization-checks-source}</span></span>
<span id="cb2-252"><a href="#cb2-252" aria-hidden="true" tabindex="-1"></a><span class="co">#| file: analysis/functions/randomization_checks.R</span></span>
<span id="cb2-253"><a href="#cb2-253" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb2-254"><a href="#cb2-254" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb2-255"><a href="#cb2-255" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Show source: randomization_checks.R (556 lines)"</span></span>
<span id="cb2-256"><a href="#cb2-256" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-257"><a href="#cb2-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-258"><a href="#cb2-258" aria-hidden="true" tabindex="-1"></a><span class="fu">### Module 7: `master_analysis.R` — Orchestration {#sec-fn-master-analysis}</span></span>
<span id="cb2-259"><a href="#cb2-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-260"><a href="#cb2-260" aria-hidden="true" tabindex="-1"></a><span class="in">`master_analysis.R`</span> is the top of the call stack. Its central function, <span class="in">`analyze_full_scenario()`</span>, is what each scenario chapter calls. It takes a scenario code (e.g., <span class="in">`"PD"`</span>), a full scenario name (e.g., <span class="in">`"Public Domain"`</span>), the data, and an <span class="in">`export_tiffs`</span> flag, then runs all five question types (Q1, Q2, Q3, Delta, Price) through the pipeline and collects the results into a named list.</span>
<span id="cb2-261"><a href="#cb2-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-262"><a href="#cb2-262" aria-hidden="true" tabindex="-1"></a>The module's hierarchy is explicit in the source comments:</span>
<span id="cb2-263"><a href="#cb2-263" aria-hidden="true" tabindex="-1"></a><span class="in">`generate_full_report()`</span> → <span class="in">`analyze_all_scenarios()`</span> → <span class="in">`analyze_full_scenario()`</span> →</span>
<span id="cb2-264"><a href="#cb2-264" aria-hidden="true" tabindex="-1"></a><span class="in">`analyze_scenario_question()`</span> → specialist plot functions. The Quarto book uses only the third level—<span class="in">`analyze_full_scenario()`</span>—because each chapter handles one scenario and</span>
<span id="cb2-265"><a href="#cb2-265" aria-hidden="true" tabindex="-1"></a>the book structure itself provides the "all scenarios" organization.</span>
<span id="cb2-266"><a href="#cb2-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-267"><a href="#cb2-267" aria-hidden="true" tabindex="-1"></a>The EU scenario receives special handling: if <span class="in">`scenario_code == "EU"`</span> and a <span class="in">`data_b1`</span> argument is provided, the function swaps in the EU-specific dataset. In the Quarto book, <span class="in">`_common.R`</span> pre-computes both <span class="in">`survey_data`</span> and <span class="in">`survey_data_eu`</span>, so each scenario chapter passes the correct dataset directly.</span>
<span id="cb2-268"><a href="#cb2-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-269"><a href="#cb2-269" aria-hidden="true" tabindex="-1"></a>**Return structure:**</span>
<span id="cb2-270"><a href="#cb2-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-271"><a href="#cb2-271" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-272"><a href="#cb2-272" aria-hidden="true" tabindex="-1"></a><span class="in">results</span></span>
<span id="cb2-273"><a href="#cb2-273" aria-hidden="true" tabindex="-1"></a><span class="in">├── $plots        — ggplot objects: $q1, $q2, $q3, $delta, $price</span></span>
<span id="cb2-274"><a href="#cb2-274" aria-hidden="true" tabindex="-1"></a><span class="in">├── $statistics   — data frames (mean, SD, median by group): $q1 … $price</span></span>
<span id="cb2-275"><a href="#cb2-275" aria-hidden="true" tabindex="-1"></a><span class="in">├── $tests        — $delta: list of wilcox.test() per group</span></span>
<span id="cb2-276"><a href="#cb2-276" aria-hidden="true" tabindex="-1"></a><span class="in">│                   $price: outlier-trimmed data frame</span></span>
<span id="cb2-277"><a href="#cb2-277" aria-hidden="true" tabindex="-1"></a><span class="in">├── $summary      — long-format table combining all $statistics entries</span></span>
<span id="cb2-278"><a href="#cb2-278" aria-hidden="true" tabindex="-1"></a><span class="in">├── $scenario_code</span></span>
<span id="cb2-279"><a href="#cb2-279" aria-hidden="true" tabindex="-1"></a><span class="in">└── $scenario_name</span></span>
<span id="cb2-280"><a href="#cb2-280" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-281"><a href="#cb2-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-282"><a href="#cb2-282" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Function <span class="pp">|</span> Key Parameters <span class="pp">|</span> Returns <span class="pp">|</span> Role <span class="pp">|</span></span>
<span id="cb2-283"><a href="#cb2-283" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb2-284"><a href="#cb2-284" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`analyze_full_scenario()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`scenario_code`</span>, <span class="in">`scenario_name`</span>, <span class="in">`export_tiffs`</span>, <span class="in">`data_b1`</span> <span class="pp">|</span> named list <span class="pp">|</span> Run all 5 questions; return plots + stats + tests <span class="pp">|</span></span>
<span id="cb2-285"><a href="#cb2-285" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`analyze_all_scenarios()`</span> <span class="pp">|</span> <span class="in">`main_data`</span>, <span class="in">`b1_data`</span>, <span class="in">`scenarios`</span> <span class="pp">|</span> named list <span class="pp">|</span> Loop over all 7 scenarios <span class="pp">|</span></span>
<span id="cb2-286"><a href="#cb2-286" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`create_scenario_summary()`</span> <span class="pp">|</span> <span class="in">`stats_list`</span> <span class="pp">|</span> data frame <span class="pp">|</span> Combine per-question stats into one table <span class="pp">|</span></span>
<span id="cb2-287"><a href="#cb2-287" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`compare_across_scenarios()`</span> <span class="pp">|</span> <span class="in">`results_list`</span> <span class="pp">|</span> data frame <span class="pp">|</span> Cross-scenario Q1 mean comparison <span class="pp">|</span></span>
<span id="cb2-288"><a href="#cb2-288" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`generate_full_report()`</span> <span class="pp">|</span> <span class="in">`data_paths`</span>, <span class="in">`output_dir`</span> <span class="pp">|</span> named list <span class="pp">|</span> Full pipeline: load → check → analyze → save <span class="pp">|</span></span>
<span id="cb2-289"><a href="#cb2-289" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`quick_analyze()`</span> <span class="pp">|</span> <span class="in">`data`</span>, <span class="in">`scenario_code`</span>, <span class="in">`question`</span> <span class="pp">|</span> list <span class="pp">|</span> Single question without TIFF export <span class="pp">|</span></span>
<span id="cb2-290"><a href="#cb2-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-291"><a href="#cb2-291" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fn-master-analysis-source}</span></span>
<span id="cb2-292"><a href="#cb2-292" aria-hidden="true" tabindex="-1"></a><span class="co">#| file: analysis/functions/master_analysis.R</span></span>
<span id="cb2-293"><a href="#cb2-293" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb2-294"><a href="#cb2-294" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb2-295"><a href="#cb2-295" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-summary: "Show source: master_analysis.R (542 lines)"</span></span>
<span id="cb2-296"><a href="#cb2-296" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-297"><a href="#cb2-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-298"><a href="#cb2-298" aria-hidden="true" tabindex="-1"></a><span class="fu">### Call-Site Pattern {#sec-fn-putting-together}</span></span>
<span id="cb2-299"><a href="#cb2-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-300"><a href="#cb2-300" aria-hidden="true" tabindex="-1"></a>With all seven modules loaded, every scenario chapter reduces to a single call:</span>
<span id="cb2-301"><a href="#cb2-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-302"><a href="#cb2-302" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fn-call-example}</span></span>
<span id="cb2-303"><a href="#cb2-303" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb2-304"><a href="#cb2-304" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: false</span></span>
<span id="cb2-305"><a href="#cb2-305" aria-hidden="true" tabindex="-1"></a><span class="co"># Pattern used in each scenario chapter (shown here, not re-run).</span></span>
<span id="cb2-306"><a href="#cb2-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-307"><a href="#cb2-307" aria-hidden="true" tabindex="-1"></a>pd_results <span class="ot">&lt;-</span> <span class="fu">analyze_full_scenario</span>(</span>
<span id="cb2-308"><a href="#cb2-308" aria-hidden="true" tabindex="-1"></a>  <span class="at">data          =</span> survey_data,       <span class="co"># Groups A/B/C, n = 1,222 — from _common.R</span></span>
<span id="cb2-309"><a href="#cb2-309" aria-hidden="true" tabindex="-1"></a>  <span class="at">scenario_code =</span> <span class="st">"PD"</span>,</span>
<span id="cb2-310"><a href="#cb2-310" aria-hidden="true" tabindex="-1"></a>  <span class="at">scenario_name =</span> <span class="st">"Public Domain"</span>,</span>
<span id="cb2-311"><a href="#cb2-311" aria-hidden="true" tabindex="-1"></a>  <span class="at">export_tiffs  =</span> <span class="cn">TRUE</span>               <span class="co"># Write to data/figures/v2/</span></span>
<span id="cb2-312"><a href="#cb2-312" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-313"><a href="#cb2-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-314"><a href="#cb2-314" aria-hidden="true" tabindex="-1"></a><span class="co"># Access results:</span></span>
<span id="cb2-315"><a href="#cb2-315" aria-hidden="true" tabindex="-1"></a>pd_results<span class="sc">$</span>plots<span class="sc">$</span>q1        <span class="co"># ggplot for Q1 (likelihood)</span></span>
<span id="cb2-316"><a href="#cb2-316" aria-hidden="true" tabindex="-1"></a>pd_results<span class="sc">$</span>plots<span class="sc">$</span>delta     <span class="co"># ggplot for Δ = Q2 − Q3</span></span>
<span id="cb2-317"><a href="#cb2-317" aria-hidden="true" tabindex="-1"></a>pd_results<span class="sc">$</span>statistics<span class="sc">$</span>q1   <span class="co"># data frame: mean, SD, median by group</span></span>
<span id="cb2-318"><a href="#cb2-318" aria-hidden="true" tabindex="-1"></a>pd_results<span class="sc">$</span>tests<span class="sc">$</span>delta     <span class="co"># named list of wilcox.test() objects, one per group</span></span>
<span id="cb2-319"><a href="#cb2-319" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-320"><a href="#cb2-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-321"><a href="#cb2-321" aria-hidden="true" tabindex="-1"></a>The EU scenario passes <span class="in">`survey_data_eu`</span> (Groups A/B1/C, n = 905) instead of <span class="in">`survey_data`</span>. The pipeline's modularity means that changing any single layer, replacing the theme in <span class="in">`plotting_themes.R`</span>, adding an effect size in <span class="in">`stats_helpers.R`</span>,</span>
<span id="cb2-322"><a href="#cb2-322" aria-hidden="true" tabindex="-1"></a>or switching export format in <span class="in">`export_helpers.R`</span> propagates automatically to all seven scenario chapters without touching the chapter files themselves.</span>
<span id="cb2-323"><a href="#cb2-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-324"><a href="#cb2-324" aria-hidden="true" tabindex="-1"></a><span class="fu">## How to Read the Scenario Graphs {#sec-howto-graphs}</span></span>
<span id="cb2-325"><a href="#cb2-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-326"><a href="#cb2-326" aria-hidden="true" tabindex="-1"></a>The scenario chapters use the same <span class="in">`ggbetweenstats`</span> engine from <span class="co">[</span><span class="ot">`ggstatsplot`</span><span class="co">](https://indrajeetpatil.github.io/ggstatsplot/)</span> described in <span class="co">[</span><span class="ot">§4.3</span><span class="co">](04-randomization.qmd#sec-rand-howto)</span>, which explains the basic visual elements: the violin shape (probability density), the box plot (quartiles and median), the centrality point (large dot with numeric label), and the subtitle (omnibus test results). This section covers what is *new* in the scenario graphs. The key interpretive shift is directional: in Chapter 4, a non-significant result (*p* &gt; 0.05) confirmed successful randomization. Here, a significant result (*p* &lt; 0.05) indicates a treatment effect, statistical evidence that CC license information changed how respondents answered.</span>
<span id="cb2-327"><a href="#cb2-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-328"><a href="#cb2-328" aria-hidden="true" tabindex="-1"></a><span class="fu">### Group Ordering and Labels</span></span>
<span id="cb2-329"><a href="#cb2-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-330"><a href="#cb2-330" aria-hidden="true" tabindex="-1"></a>Groups are displayed left-to-right, beginning with the control and then moving through two increasing intensities of treatment exposure to CC's license marking: **Control (C)** → **Short (A)** → **Full + Primer (B)**. Control respondents received a standard copyright marking or similar standard variant; Short received a brief, abbreviated CC label with logos; Full + Primer received a full text license name along with mandatory exposure to an educational primer for at least 20 seconds.</span>
<span id="cb2-331"><a href="#cb2-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-332"><a href="#cb2-332" aria-hidden="true" tabindex="-1"></a><span class="fu">### New Visual Elements</span></span>
<span id="cb2-333"><a href="#cb2-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-334"><a href="#cb2-334" aria-hidden="true" tabindex="-1"></a>Two elements appear in the scenario graphs that are absent from the randomization checks:</span>
<span id="cb2-335"><a href="#cb2-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-336"><a href="#cb2-336" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Significance brackets.** After the Kruskal-Wallis omnibus test, Dunn's post-hoc test (with Holm correction) identifies *which* group pairs differ. Brackets connecting two groups appear above the plot, with Holm-adjusted *p*-values displayed at the bracket midpoint. Only statistically significant pairs are shown; if no bracket connects two groups, their difference was not significant after correction for multiple comparisons.</span>
<span id="cb2-337"><a href="#cb2-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-338"><a href="#cb2-338" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Caption with VDA effect sizes.** Below each figure, the caption reports pairwise Vargha &amp; Delaney's *A* (VDA) effect sizes. VDA is a probability: it estimates the chance that a randomly selected observation from one group exceeds a randomly selected observation from the other. A value of 0.50 means no difference; departures from 0.50 indicate the direction and magnitude of the effect. Interpretation thresholds (small, medium, large) follow Vargha &amp; Delaney (2000) and are given in <span class="co">[</span><span class="ot">Table 2.1</span><span class="co">](01-methods.qmd#tbl-vda-thresholds)</span>.</span>
<span id="cb2-339"><a href="#cb2-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-340"><a href="#cb2-340" aria-hidden="true" tabindex="-1"></a><span class="fu">### Three Plot Types</span></span>
<span id="cb2-341"><a href="#cb2-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-342"><a href="#cb2-342" aria-hidden="true" tabindex="-1"></a>The scenario chapters produce three structurally distinct graph types:</span>
<span id="cb2-343"><a href="#cb2-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-344"><a href="#cb2-344" aria-hidden="true" tabindex="-1"></a>**Q1, Q2, Q3 (Likert-scale questions).** These plots display responses on a 7-point scale. Individual data points are hidden to reduce clutter. The centrality point marks the group **mean**, even when the test statistics are nonparametric for ease of interpretation.</span>
<span id="cb2-345"><a href="#cb2-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-346"><a href="#cb2-346" aria-hidden="true" tabindex="-1"></a>**Delta (Δ = Q2 − Q3).** Delta plots visualize the *difference* between each respondent's perception of current law (Q2) and their normative preference (Q3). A positive delta means the respondent sees the law as stricter than they prefer; a negative delta means the law is more permissive than preferred. The Y-axis is the Q2–Q3 difference rather than a raw survey response. Each delta plot is accompanied by a **Wilcoxon signed-rank table** reporting whether each group's median delta is significantly different from zero — that is, whether there is a measurable gap between "what the law is" and "what the law should be" within that group.</span>
<span id="cb2-347"><a href="#cb2-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-348"><a href="#cb2-348" aria-hidden="true" tabindex="-1"></a>**Price (Q4).** Price plots show respondents' dollar estimates of the value of the copyrighted work in the scenario. Individual estimates are displayed as semi-transparent jittered dots because the distribution shape is substantively informative. The centrality point marks the group **median** rather than the mean, because price distributions are right-skewed and the median is more robust to extreme values. Before any statistics are computed, the **top 1% of estimates within each group** are trimmed as outliers to prevent a handful of extreme responses from distorting the visual scale and test results.</span>
<span id="cb2-349"><a href="#cb2-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-350"><a href="#cb2-350" aria-hidden="true" tabindex="-1"></a><span class="fu">### Quick Interpretation</span></span>
<span id="cb2-351"><a href="#cb2-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-352"><a href="#cb2-352" aria-hidden="true" tabindex="-1"></a>For any scenario graph: if the subtitle shows *p* &lt; 0.05, the groups differ overall. Check the **brackets** to see which specific pairs drive the difference, and consult the **caption** for the effect size. For delta plots, the accompanying Wilcoxon table reveals whether each group's gap between perceived and preferred law is itself significant. The first example the reader will encounter is @fig-pd-q1 in the <span class="co">[</span><span class="ot">Public Domain</span><span class="co">](_scenarios/pd.qmd)</span> scenario.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ludist/cc-survey/edit/main/07-scenarios.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/ludist/cc-survey/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>