<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Sample v. Population Analysis – Creative Commons Recognition and Copyright Infringement Perceptions Survey Experiment</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06-brand.html" rel="next">
<link href="./04-randomization.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-df8e7534cb4cb7c4e956089768985eef.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked slimcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-population.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sample v. Population Analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Creative Commons Recognition and Copyright Infringement Perceptions Survey Experiment</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ludist/cc-survey" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Experimental Design &amp; Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-codebook.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Codebook &amp; Variable Dictionary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Validation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-randomization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Randomization Check</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-population.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sample v. Population Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-brand.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Brand Recognition</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-scenarios.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Scenario Analysis Overview</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_scenarios/pd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.1 Public Domain</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_scenarios/pu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.2 Personal Use</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_scenarios/eu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.3 Educational Use</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_scenarios/ca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.4 Commercial Advertising</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_scenarios/ls.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.5 Large Scale Copying</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_scenarios/wn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.6 Wikipedia Image Search</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./_scenarios/fs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.7 Filesharing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-summaries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Question Summaries</span></span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#sec-pop-overview" id="toc-sec-pop-overview" class="nav-link active" data-scroll-target="#sec-pop-overview"><span class="header-section-number">5.1</span> Overview</a></li>
  <li><a href="#sec-pop-age" id="toc-sec-pop-age" class="nav-link" data-scroll-target="#sec-pop-age"><span class="header-section-number">5.2</span> Age</a></li>
  <li><a href="#sec-pop-gender" id="toc-sec-pop-gender" class="nav-link" data-scroll-target="#sec-pop-gender"><span class="header-section-number">5.3</span> Gender</a></li>
  <li><a href="#sec-pop-race" id="toc-sec-pop-race" class="nav-link" data-scroll-target="#sec-pop-race"><span class="header-section-number">5.4</span> Race and Ethnicity</a></li>
  <li><a href="#sec-pop-edu" id="toc-sec-pop-edu" class="nav-link" data-scroll-target="#sec-pop-edu"><span class="header-section-number">5.5</span> Education</a></li>
  <li><a href="#sec-pop-income" id="toc-sec-pop-income" class="nav-link" data-scroll-target="#sec-pop-income"><span class="header-section-number">5.6</span> Income</a></li>
  <li><a href="#sec-pop-politics" id="toc-sec-pop-politics" class="nav-link" data-scroll-target="#sec-pop-politics"><span class="header-section-number">5.7</span> Political Orientation</a></li>
  <li><a href="#sec-pop-summary" id="toc-sec-pop-summary" class="nav-link" data-scroll-target="#sec-pop-summary"><span class="header-section-number">5.8</span> Summary</a></li>
  <li><a href="#sec-pop-repro" id="toc-sec-pop-repro" class="nav-link" data-scroll-target="#sec-pop-repro"><span class="header-section-number">5.9</span> Reproducibility Note</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/ludist/cc-survey/edit/main/05-population.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/ludist/cc-survey/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sample v. Population Analysis</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-pop-overview" class="level2 page-columns page-full" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="sec-pop-overview"><span class="header-section-number">5.1</span> Overview</h2>
<p>This Chapter compares the survey sample demographics against population benchmarks to assess external validity: How does the sample resemble the American adult population? The analysis covers five demographic characteristics — age, gender, race/ethnicity, education, and income — benchmarked against the American Community Survey (ACS), plus two political orientation measures — party affiliation and ideology — benchmarked against Gallup’s 2024 annual tracking poll. Full source details for both benchmarks appear below.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Study design note:</strong> The survey used a CloudResearch Connect<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> panel. This service provides a quota-sampled convenience panel, not a probability sample. Like most online survey experiments, the study prioritizes <em>internal validity</em> (clean randomization between treatment groups) over <em>representational sampling</em>. The ACS comparison documents where the sample diverges from the general population, enabling readers to assess how findings might or might not generalize. In sum, CloudResearch’s “nationally representative” designation is a marketing term that does not reflect probability sampling or representativeness in the statistical sense.</p>
<p>Divergences in this chapter fall into three categories: (1) <em>quota-controlled demographic variables</em> (age, gender, race, and Hispanic/Latino origin), where the sample follows CloudResearch Connect’s standard preset quotas, which depart from ACS proportions; (2) <em>uncontrolled demographic variables</em> (education and income), where no quota was set and the distribution reflects the organic composition of opt-in online survey participants; and (3) <em>political orientation variables</em> (party affiliation and ideology), benchmarked against Gallup’s 2024 annual tracking poll rather than the ACS, which does not collect political data.</p>
<p>Randomization balance (internal validity) is confirmed separately in <a href="./04-randomization.html">Chapter 4</a>. The analysis here uses Groups A, B, and C (<em>n</em> = 1,222).</p>
</div>
</div>
<div class="no-row-height column-margin column-container"><div id="fn1"><p><sup>1</sup>&nbsp;Rachel Hartman, Aaron J. Moss, Shalom N. Jaffe, Cheskie Rosenzweig, Leib Litman &amp; Jonathan Robinson, <em>Introducing Connect by CloudResearch: Advancing Online Participant Recruitment in the Digital Age</em> (2023), https://doi.org/10.31234/osf.io/ksgyr; CloudResearch, <em>Connect for Researchers</em>, https://www.cloudresearch.com/products/connect-for-researchers/.</p></div></div><div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Reference populations:</strong> <em>Demographics</em> (§§5.1–5.5): ACS 2023 1-year estimates, U.S. civilian non-institutionalized population. Source tables: B01001 (sex by age), B03002 (Hispanic/Latino origin by race), B15003 (educational attainment, 25+), B19001 (household income). Data retrieved from data.gov via the <code>tidycensus</code> R package. See <code>data/population/acs-source-notes.md</code> for complete retrieval details and cell-level recoding decisions. <em>Political orientation</em> (§5.6): Gallup 2024 annual averages, based on telephone surveys of more than 14,000 U.S. adults conducted throughout 2024.</p>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>Benchmarks loaded for variables: AGE, EDU, GENDER, HISPLAT, INCOME, LIBCON, POLPARTY, RACE_ETH, RACE_ONLY </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Total benchmark rows: 33 </code></pre>
</div>
</div>
<hr>
</section>
<section id="sec-pop-age" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="sec-pop-age"><span class="header-section-number">5.2</span> Age</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pop-age" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pop-age-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-population_files/figure-html/fig-pop-age-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pop-age-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: Age distribution: survey sample vs.&nbsp;ACS 2023 benchmark
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-pop-age-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-pop-age-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<caption>Age Distribution Comparison. χ²(3) = 79.44, p &lt; .001, Cohen’s h = 0.119</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Age Group</th>
<th style="text-align: left;">Survey</th>
<th style="text-align: left;">ACS</th>
<th style="text-align: left;">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">18-29</td>
<td style="text-align: left;"> 16.9%</td>
<td style="text-align: left;"> 20.0%</td>
<td style="text-align: left;">− 3.1%** </td>
</tr>
<tr class="even">
<td style="text-align: left;">30-44</td>
<td style="text-align: left;"> 25.0%</td>
<td style="text-align: left;"> 26.0%</td>
<td style="text-align: left;">− 1.0%   </td>
</tr>
<tr class="odd">
<td style="text-align: left;">45-59</td>
<td style="text-align: left;"> 33.6%</td>
<td style="text-align: left;"> 23.2%</td>
<td style="text-align: left;">+10.4%***</td>
</tr>
<tr class="even">
<td style="text-align: left;">60+</td>
<td style="text-align: left;"> 24.6%</td>
<td style="text-align: left;"> 30.9%</td>
<td style="text-align: left;">− 6.3%***</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Wt. Average</strong></td>
<td style="text-align: left;"> 25.2%</td>
<td style="text-align: left;"> 25.6%</td>
<td style="text-align: left;">− 0.4%***</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-pop-age-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.1: Age: Survey vs.&nbsp;ACS Proportions with Chi-Square Goodness-of-Fit
</figcaption>
</figure>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Age interpretation:</strong> χ²(3) = 79.44, p &lt; .001, Cohen’s h = 0.119. Despite the highly significant test statistic (driven by <em>n</em> = 1,222), the effect size is small (<em>h</em> &lt; 0.20). The observed age distribution closely tracks CloudResearch Connect’s preset quota targets (18–29: 16.7% preset / 16.9% observed; 30–44: 25.0% / 25.0%; 45–59: 33.3% / 33.6%; 60+: 25.0% / 24.6%) rather than the ACS. The divergence from Census proportions, such as the overrepresentation of 45–59 respondents (33.6% vs.&nbsp;23.2% ACS) and underrepresentation of 60+ adults (24.6% vs.&nbsp;30.9% ACS), is therefore an artifact of the CloudResearch preset, not sampling error or panel self-selection.</p>
</div>
</div>
</div>
<hr>
</section>
<section id="sec-pop-gender" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="sec-pop-gender"><span class="header-section-number">5.3</span> Gender</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Measurement note:</strong> ACS reports binary sex (male/female). The survey offered a third response option for respondents who identified outside the male/female binary or preferred not to answer. Those respondents are excluded from the ACS comparison below; the two-category comparison uses only male/female responses.</p>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pop-gender" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pop-gender-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-population_files/figure-html/fig-pop-gender-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pop-gender-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.2: Gender distribution: survey sample vs.&nbsp;ACS 2023 benchmark
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-pop-gender-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-pop-gender-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<caption>Gender Distribution Comparison. χ²(1) = 0.28, p = 0.597, Cohen’s h = 0.015</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Gender</th>
<th style="text-align: left;">Survey</th>
<th style="text-align: left;">ACS</th>
<th style="text-align: left;">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Female</td>
<td style="text-align: left;"> 50.2%</td>
<td style="text-align: left;"> 51.0%</td>
<td style="text-align: left;">− 0.8%   </td>
</tr>
<tr class="even">
<td style="text-align: left;">Male</td>
<td style="text-align: left;"> 49.8%</td>
<td style="text-align: left;"> 49.0%</td>
<td style="text-align: left;">+ 0.8%   </td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-pop-gender-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.2: Gender: Survey vs.&nbsp;ACS Proportions with Chi-Square Goodness-of-Fit
</figcaption>
</figure>
</div>
</div>
<hr>
</section>
<section id="sec-pop-race" class="level2 page-columns page-full" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="sec-pop-race"><span class="header-section-number">5.4</span> Race and Ethnicity</h2>
<p>The survey asked Hispanic/Latino origin and race as separate questions, consistent with the Census Bureau approach. This section presents three complementary comparisons: (1) Hispanic/Latino origin alone, (2) racial identification alone, and (3) a combined race/ethnicity classification.</p>
<section id="sec-pop-hisplat" class="level3 page-columns page-full" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="sec-pop-hisplat"><span class="header-section-number">5.4.1</span> Hispanic/Latino Origin</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pop-hisplat" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pop-hisplat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-population_files/figure-html/fig-pop-hisplat-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pop-hisplat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.3: Hispanic/Latino origin: survey sample vs.&nbsp;ACS 2023 benchmark
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-pop-hisplat-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-pop-hisplat-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<caption>Hispanic/Latino Origin Comparison. χ²(1) = 97.38, p &lt; .001, Cohen’s h = 0.330</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Category</th>
<th style="text-align: left;">Survey</th>
<th style="text-align: left;">ACS</th>
<th style="text-align: left;">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Hispanic/Latino</td>
<td style="text-align: left;">  8.3%</td>
<td style="text-align: left;"> 19.4%</td>
<td style="text-align: left;">−11.2%***</td>
</tr>
<tr class="even">
<td style="text-align: left;">Not Hispanic/Latino</td>
<td style="text-align: left;"> 91.7%</td>
<td style="text-align: left;"> 80.6%</td>
<td style="text-align: left;">+11.2%***</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-pop-hisplat-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.3: Hispanic/Latino Origin: Survey vs.&nbsp;ACS Proportions
</figcaption>
</figure>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Quota note:</strong> The CloudResearch Connect standard panel preset, not the nationally representative ACS, set the Hispanic/Latino target at 8.3% (99.6 of 1,200 participants), compared to the ACS 2023 1-year estimate of approximately 19.4% for the U.S. adult population. CloudResearch’s preset applies equal 8.3% allocations across three non-White racial/ethnic groups (Black, Hispanic/Latino, and Other), with the remaining 83.3% allocated to White participants. This simplified stratification departs substantially from current Census proportions. The Author followed this preset without modification to facilitate cross-study comparability with other Connect panels, a design decision documented in the pre-registration (OSF: <a href="https://osf.io/snxyt/">https://osf.io/snxyt/</a>). This represents a deliberate methodological choice and a tradeoff of inexpensive survey participant pools against external validity, not a sampling error. The lack of representative racial and ethnic diversity is a well-known limitation of opt-in online survey platforms generally, which tend to underrepresent minorities and over-represent White respondents.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
</div>
</div>
<div class="no-row-height column-margin column-container"><div id="fn2"><p><sup>2</sup>&nbsp;<em>See</em> Courtney Kennedy, Andrew Mercer, Nick Hatley, and Scott Keeter, <em>Evaluating Online Nonprobability Surveys</em>, <strong>Pew Research Center</strong> (2016); Taylor C. Boas, Dino P. Chirsttenson, and David M. Glick, <em>Recruiting Subjects to Survey Researchers: A Comparison of MTurk, Luc.id, and SurveyMonkey</em>, 8 <strong>Pol. Sci. Res. &amp; Methods</strong> 422, 427 (2020) (finding that MTurk-based samples significantly over-represent White respondents compared to Census benchmarks).</p></div></div></section>
<section id="sec-pop-race-only" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="sec-pop-race-only"><span class="header-section-number">5.4.2</span> Racial Identification</h3>
<p>Race is reported independently of Hispanic/Latino origin, using the survey’s race selection question. For ACS comparison, the race-alone table (B02001) is used. Multi-selection responses and categories other than White, Black, and Asian are collapsed into “Other / Multiracial.”</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pop-race-only" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pop-race-only-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-population_files/figure-html/fig-pop-race-only-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pop-race-only-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.4: Racial identification: survey sample vs.&nbsp;ACS 2023 benchmark (B02001, race alone)
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-pop-race-only-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-pop-race-only-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<caption>Racial Identification Comparison. χ²(3) = 284.31, p &lt; .001, Cohen’s h = 0.296</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Race</th>
<th style="text-align: left;">Survey</th>
<th style="text-align: left;">ACS</th>
<th style="text-align: left;">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Asian alone</td>
<td style="text-align: left;">  6.1%</td>
<td style="text-align: left;">  6.0%</td>
<td style="text-align: left;">+ 0.1%   </td>
</tr>
<tr class="even">
<td style="text-align: left;">Black or African American</td>
<td style="text-align: left;">  8.0%</td>
<td style="text-align: left;"> 12.1%</td>
<td style="text-align: left;">− 4.1%***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Other / Multiracial</td>
<td style="text-align: left;">  3.9%</td>
<td style="text-align: left;"> 21.4%</td>
<td style="text-align: left;">−17.4%***</td>
</tr>
<tr class="even">
<td style="text-align: left;">White alone</td>
<td style="text-align: left;"> 82.0%</td>
<td style="text-align: left;"> 60.5%</td>
<td style="text-align: left;">+21.5%***</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-pop-race-only-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.4: Racial Identification: Survey vs.&nbsp;ACS Proportions
</figcaption>
</figure>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Quota note:</strong> The White overrepresentation (82.0% vs.&nbsp;60.5% ACS) directly reflects CloudResearch Connect’s 83.3% White preset quota. The preset allocates the remaining 16.7% equally across three non-White groups (8.3% each for Black, Hispanic/Latino, and Other), without distinguishing Asian as a separate category — which explains why the Asian alone estimate (6.1% vs.&nbsp;6.0% ACS) achieves near-exact alignment despite no explicit Asian quota: Asian respondents were absorbed into the residual “Other” pool alongside AIAN, NHPI, and multiracial respondents, whose collective underrepresentation drives the large “Other / Multiracial” gap (3.9% vs.&nbsp;21.4% ACS). <em>See</em> the pre-registration (OSF: <a href="https://osf.io/snxyt/">https://osf.io/snxyt/</a>) for the quota rationale.</p>
</div>
</div>
</section>
<section id="sec-pop-race-eth" class="level3" data-number="5.4.3">
<h3 data-number="5.4.3" class="anchored" data-anchor-id="sec-pop-race-eth"><span class="header-section-number">5.4.3</span> Combined Race/Ethnicity</h3>
<p>The combined classification uses the B03002 table (Hispanic/Latino origin by race) to construct mutually exclusive categories: Hispanic/Latino respondents are classified under that category regardless of racial identification; non-Hispanic respondents are classified by race.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pop-race" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pop-race-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-population_files/figure-html/fig-pop-race-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pop-race-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.5: Combined race/ethnicity: survey sample vs.&nbsp;ACS 2023 benchmark (B03002)
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-pop-race-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-pop-race-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<caption>Combined Race/Ethnicity Comparison. χ²(4) = 192.26, p &lt; .001, Cohen’s h = 0.207</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Race/Ethnicity</th>
<th style="text-align: left;">Survey</th>
<th style="text-align: left;">ACS</th>
<th style="text-align: left;">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Asian</td>
<td style="text-align: left;">  6.0%</td>
<td style="text-align: left;">  5.9%</td>
<td style="text-align: left;">+ 0.1%   </td>
</tr>
<tr class="even">
<td style="text-align: left;">Hispanic/Latino</td>
<td style="text-align: left;">  8.3%</td>
<td style="text-align: left;"> 19.4%</td>
<td style="text-align: left;">−11.2%***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Non-Hispanic Black</td>
<td style="text-align: left;">  7.5%</td>
<td style="text-align: left;"> 11.8%</td>
<td style="text-align: left;">− 4.3%***</td>
</tr>
<tr class="even">
<td style="text-align: left;">Non-Hispanic White</td>
<td style="text-align: left;"> 75.7%</td>
<td style="text-align: left;"> 57.1%</td>
<td style="text-align: left;">+18.5%***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Other</td>
<td style="text-align: left;">  2.5%</td>
<td style="text-align: left;">  5.7%</td>
<td style="text-align: left;">− 3.2%***</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-pop-race-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.5: Combined Race/Ethnicity: Survey vs.&nbsp;ACS Proportions
</figcaption>
</figure>
</div>
</div>
<hr>
</section>
</section>
<section id="sec-pop-edu" class="level2 page-columns page-full" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="sec-pop-edu"><span class="header-section-number">5.5</span> Education</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Measurement note:</strong> The ACS educational attainment table (B15003) covers the population aged <strong>25</strong> and older, while the survey targets adults <strong>18</strong> and older. The ACS proportions used here may over-represent higher education levels relative to the full 18+ population, since adults aged 18–24 are more likely to have not yet completed post-secondary education. No quota was set on educational attainment; the observed distribution reflects the organic composition of the CloudResearch Connect panel.</p>
<p>The heavy overrepresentation of college-educated respondents (70.5% Bachelor’s or higher vs.&nbsp;35.7% ACS 25+) is a well-documented characteristic of opt-in online survey platforms generally.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
</div>
</div>
<div class="no-row-height column-margin column-container"><div id="fn3"><p><sup>3</sup>&nbsp;<em>See</em> Courtney Kennedy, Andrew Mercer, Nick Hatley, and Scott Keeter, <em>Evaluating Online Nonprobability Surveys</em>, <strong>Pew Research Center</strong> (2016); Taylor C. Boas, Dino P. Chirsttenson, and David M. Glick, <em>Recruiting Subjects to Survey Researchers: A Comparison of MTurk, Luc.id, and SurveyMonkey</em>, 8 <strong>Pol. Sci. Res. &amp; Methods</strong> 422, 427 (2020) (finding that MTurk-based samples are significantly more educated than Census benchmarks).</p></div></div><div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pop-edu" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pop-edu-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-population_files/figure-html/fig-pop-edu-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pop-edu-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.6: Education distribution: survey sample vs.&nbsp;ACS 2023 benchmark
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-pop-edu-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-pop-edu-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<caption>Education Distribution Comparison. χ²(3) = 352.19, p &lt; .001, Cohen’s h = 0.459</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Education Level</th>
<th style="text-align: left;">Survey</th>
<th style="text-align: left;">ACS</th>
<th style="text-align: left;">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Bachelor’s</td>
<td style="text-align: left;"> 43.2%</td>
<td style="text-align: left;"> 21.8%</td>
<td style="text-align: left;">+21.4%***</td>
</tr>
<tr class="even">
<td style="text-align: left;">Graduate</td>
<td style="text-align: left;"> 27.3%</td>
<td style="text-align: left;"> 14.3%</td>
<td style="text-align: left;">+12.9%***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HS or less</td>
<td style="text-align: left;">  1.5%</td>
<td style="text-align: left;"> 36.2%</td>
<td style="text-align: left;">−34.7%***</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some college</td>
<td style="text-align: left;"> 28.0%</td>
<td style="text-align: left;"> 27.7%</td>
<td style="text-align: left;">+ 0.4%   </td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Wt. Average</strong></td>
<td style="text-align: left;"> 21.6%</td>
<td style="text-align: left;"> 27.6%</td>
<td style="text-align: left;">− 5.9%***</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-pop-edu-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.6: Education: Survey vs.&nbsp;ACS Proportions with Chi-Square Goodness-of-Fit
</figcaption>
</figure>
</div>
</div>
<hr>
</section>
<section id="sec-pop-income" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="sec-pop-income"><span class="header-section-number">5.6</span> Income</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Sampling Note:</strong> No quota was set on household income; the observed distribution reflects the organic composition of the CloudResearch Connect panel. The concentration in the $25k–$99.9k range and underrepresentation of the highest earners ($150k+: 9.5% vs.&nbsp;21.5% ACS) likely reflects participation patterns in paid online surveys, where high-income individuals have lower rates of panel enrollment and survey completion. The ACS income benchmark uses household-level estimates (B19001), consistent with the survey’s household income question.</p>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pop-income" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pop-income-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-population_files/figure-html/fig-pop-income-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pop-income-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.7: Income distribution: survey sample vs.&nbsp;ACS 2023 benchmark
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-pop-income-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-pop-income-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<caption>Income Distribution Comparison. χ²(5) = 164.19, p &lt; .001, Cohen’s h = 0.152</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Income Bracket</th>
<th style="text-align: left;">Survey</th>
<th style="text-align: left;">ACS</th>
<th style="text-align: left;">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">&lt; $25k</td>
<td style="text-align: left;"> 12.8%</td>
<td style="text-align: left;"> 15.2%</td>
<td style="text-align: left;">− 2.4%*  </td>
</tr>
<tr class="even">
<td style="text-align: left;">$100k–$149.9k</td>
<td style="text-align: left;"> 14.9%</td>
<td style="text-align: left;"> 17.4%</td>
<td style="text-align: left;">− 2.5%*  </td>
</tr>
<tr class="odd">
<td style="text-align: left;">$150k+</td>
<td style="text-align: left;">  9.5%</td>
<td style="text-align: left;"> 21.5%</td>
<td style="text-align: left;">−12.0%***</td>
</tr>
<tr class="even">
<td style="text-align: left;">$25k–$49.9k</td>
<td style="text-align: left;"> 24.1%</td>
<td style="text-align: left;"> 17.1%</td>
<td style="text-align: left;">+ 7.0%***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">$50k–$74.9k</td>
<td style="text-align: left;"> 22.0%</td>
<td style="text-align: left;"> 16.1%</td>
<td style="text-align: left;">+ 5.9%***</td>
</tr>
<tr class="even">
<td style="text-align: left;">$75k–$99.9k</td>
<td style="text-align: left;"> 16.6%</td>
<td style="text-align: left;"> 12.7%</td>
<td style="text-align: left;">+ 3.9%***</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Wt. Average</strong></td>
<td style="text-align: left;"> 16.4%</td>
<td style="text-align: left;"> 17.1%</td>
<td style="text-align: left;">− 0.7%***</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-pop-income-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.7: Income: Survey vs.&nbsp;ACS Proportions with Chi-Square Goodness-of-Fit
</figcaption>
</figure>
</div>
</div>
<hr>
</section>
<section id="sec-pop-politics" class="level2 page-columns page-full" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="sec-pop-politics"><span class="header-section-number">5.7</span> Political Orientation</h2>
<p>Political orientation is examined through two measures: party affiliation (POLPARTY) and political ideology on a liberal–conservative spectrum (LIBCON). Because the Census Bureau does not collect political data, this section uses Gallup’s annual tracking poll as the population benchmark rather than the ACS.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Benchmark source note:</strong> The American Community Survey does not include questions about political orientation. The benchmarks here are drawn from Gallup’s 2024 annual tracking poll, which surveys more than 14,000 U.S. adults by telephone throughout the year.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> The survey’s three-category party split (Republican, Democrat, Independent — excluding “Other” and “Prefer not to say”) maps directly to Gallup’s initial party identification question. For ideology, the survey’s five-point LIBCON scale (Very Liberal through Very Conservative) is collapsed to three categories (Liberal, Moderate, Conservative) to match Gallup’s published annual breakdown. Because the benchmark source differs from the ACS used in preceding sections, chi-square results and effect sizes for political variables should not be directly compared to the demographic variables above.</p>
</div>
</div>
<div class="no-row-height column-margin column-container"><div id="fn4"><p><sup>4</sup>&nbsp;Gallup, <em>GOP Holds Edge in Party Affiliation for Third Straight Year</em> (Jan.&nbsp;16, 2025); Gallup, <em>U.S. Political Parties Historically Polarized Ideologically</em> (Jan.&nbsp;24, 2025). Data available at https://news.gallup.com/poll/15370/party-affiliation.aspx.</p></div></div><section id="sec-pop-polparty" class="level3 page-columns page-full" data-number="5.7.1">
<h3 data-number="5.7.1" class="anchored" data-anchor-id="sec-pop-polparty"><span class="header-section-number">5.7.1</span> Party Affiliation</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pop-polparty" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pop-polparty-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-population_files/figure-html/fig-pop-polparty-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pop-polparty-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.8: Party affiliation: survey sample vs.&nbsp;Gallup 2024 benchmark
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-pop-polparty-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-pop-polparty-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<caption>Party Affiliation Comparison. χ²(2) = 194.36, p &lt; .001, Cohen’s h = 0.240. Benchmark: Gallup 2024 annual averages (U.S. adults).</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Party</th>
<th style="text-align: left;">Survey</th>
<th style="text-align: left;">Gallup</th>
<th style="text-align: left;">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Democrat</td>
<td style="text-align: left;"> 45.4%</td>
<td style="text-align: left;"> 28.3%</td>
<td style="text-align: left;">+17.1%***</td>
</tr>
<tr class="even">
<td style="text-align: left;">Independent</td>
<td style="text-align: left;"> 27.5%</td>
<td style="text-align: left;"> 43.4%</td>
<td style="text-align: left;">−15.9%***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Republican</td>
<td style="text-align: left;"> 27.1%</td>
<td style="text-align: left;"> 28.3%</td>
<td style="text-align: left;">− 1.2%   </td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-pop-polparty-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.8: Party Affiliation: Survey vs.&nbsp;Gallup 2024 Proportions with Chi-Square Goodness-of-Fit
</figcaption>
</figure>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Party affiliation interpretation:</strong> χ²(2) = 194.36, p &lt; .001, Cohen’s h = 0.240. The survey sample’s partisan composition is compared against Gallup’s 2024 annual averages (28% Republican, 28% Democrat, 43% Independent). Respondents who selected “Other” or “Prefer not to say” are excluded from this comparison. The direction and magnitude of any divergence reflects the organic composition of the CloudResearch Connect panel, as no quota was set on party affiliation. Online survey panels are known to skew somewhat more Democratic/liberal than the general population, though the extent varies by platform.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
</div>
</div>
</div>
<div class="no-row-height column-margin column-container"><div id="fn5"><p><sup>5</sup>&nbsp;<em>See</em> Adam J. Berinsky, Gregory A. Huber &amp; Gabriel S. Lenz, <em>Evaluating Online Labor Markets for Experimental Research: Amazon.com’s Mechanical Turk</em>, 20 <strong>Pol. Analysis</strong> 351, 363 (2012); Kevin J. Mullinix, Thomas J. Leeper, James N. Druckman &amp; Jeremy Freese, <em>The Generalizability of Survey Experiments</em>, 2 <strong>J. Experimental Pol. Sci.</strong> 109 (2015).</p></div></div></section>
<section id="sec-pop-libcon" class="level3" data-number="5.7.2">
<h3 data-number="5.7.2" class="anchored" data-anchor-id="sec-pop-libcon"><span class="header-section-number">5.7.2</span> Political Ideology</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Measurement note:</strong> The survey’s five-point LIBCON scale (Very Liberal, Somewhat Liberal, Moderate, Somewhat Conservative, Very Conservative) is collapsed to three categories to match Gallup’s published annual breakdown: Liberal (Very Liberal + Somewhat Liberal), Moderate, and Conservative (Somewhat Conservative + Very Conservative). No quota was set on political ideology.</p>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pop-libcon" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pop-libcon-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-population_files/figure-html/fig-pop-libcon-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pop-libcon-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.9: Political ideology: survey sample vs.&nbsp;Gallup 2024 benchmark
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-pop-libcon-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-pop-libcon-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<caption>Political Ideology Comparison. χ²(2) = 247.80, p &lt; .001, Cohen’s h = 0.280. Benchmark: Gallup 2024 annual averages (U.S. adults).</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Ideology</th>
<th style="text-align: left;">Survey</th>
<th style="text-align: left;">Gallup</th>
<th style="text-align: left;">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Conservative</td>
<td style="text-align: left;"> 29.3%</td>
<td style="text-align: left;"> 38.5%</td>
<td style="text-align: left;">− 9.2%***</td>
</tr>
<tr class="even">
<td style="text-align: left;">Liberal</td>
<td style="text-align: left;"> 45.8%</td>
<td style="text-align: left;"> 26.0%</td>
<td style="text-align: left;">+19.7%***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;"> 24.9%</td>
<td style="text-align: left;"> 35.4%</td>
<td style="text-align: left;">−10.5%***</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-pop-libcon-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.9: Political Ideology: Survey vs.&nbsp;Gallup 2024 Proportions with Chi-Square Goodness-of-Fit
</figcaption>
</figure>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Ideology interpretation:</strong> χ²(2) = 247.80, p &lt; .001, Cohen’s h = 0.280. The survey sample’s ideological distribution is compared against Gallup’s 2024 annual averages (37% Conservative, 34% Moderate, 25% Liberal; renormalized to three-category proportions after excluding “Don’t know” responses). The observed divergence is consistent with the well-documented liberal skew of opt-in online survey panels, particularly among younger and more-educated participants — both of which characterize this sample (see <a href="#sec-pop-edu">§5.4, Education</a>). As with party affiliation, the study’s primary claims rest on internal validity (randomized treatment comparisons) rather than ideological representativeness.</p>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="sec-pop-summary" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="sec-pop-summary"><span class="header-section-number">5.8</span> Summary</h2>
<div class="cell" data-layout-align="center">
<div id="tbl-pop-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-pop-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<caption>Chi-Square Goodness-of-Fit Tests Comparing Survey Sample to Population Benchmarks. Cohen’s h: small &lt; .20, medium .20–.50, large &gt; .50. Demographic variables (Age–Income): ACS 2023 1-Year Estimates (U.S. Census Bureau). Political variables (Party Affiliation, Ideology): Gallup 2024 Annual Averages.</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 31%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 3%">
<col style="width: 8%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">N</th>
<th style="text-align: left;">χ²</th>
<th style="text-align: left;">df</th>
<th style="text-align: left;"><em>p</em></th>
<th style="text-align: left;">Cohen’s <em>h</em></th>
<th style="text-align: left;">Effect Size</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">X-squared</td>
<td style="text-align: left;">Age</td>
<td style="text-align: right;">1221</td>
<td style="text-align: left;">79.44</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">0.119</td>
<td style="text-align: left;">Small</td>
</tr>
<tr class="even">
<td style="text-align: left;">X-squared1</td>
<td style="text-align: left;">Gender (binary)</td>
<td style="text-align: right;">1214</td>
<td style="text-align: left;">0.28</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">0.597</td>
<td style="text-align: left;">0.015</td>
<td style="text-align: left;">Small</td>
</tr>
<tr class="odd">
<td style="text-align: left;">X-squared2</td>
<td style="text-align: left;">Hispanic/Latino Origin</td>
<td style="text-align: right;">1221</td>
<td style="text-align: left;">97.38</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">0.330</td>
<td style="text-align: left;">Medium</td>
</tr>
<tr class="even">
<td style="text-align: left;">X-squared3</td>
<td style="text-align: left;">Race (B02001)</td>
<td style="text-align: right;">1222</td>
<td style="text-align: left;">284.31</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">0.296</td>
<td style="text-align: left;">Medium</td>
</tr>
<tr class="odd">
<td style="text-align: left;">X-squared4</td>
<td style="text-align: left;">Race/Ethnicity (Combined)</td>
<td style="text-align: right;">1221</td>
<td style="text-align: left;">192.26</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">0.207</td>
<td style="text-align: left;">Medium</td>
</tr>
<tr class="even">
<td style="text-align: left;">X-squared5</td>
<td style="text-align: left;">Education</td>
<td style="text-align: right;">535</td>
<td style="text-align: left;">352.19</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">0.459</td>
<td style="text-align: left;">Medium</td>
</tr>
<tr class="odd">
<td style="text-align: left;">X-squared6</td>
<td style="text-align: left;">Income</td>
<td style="text-align: right;">1198</td>
<td style="text-align: left;">164.19</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">0.152</td>
<td style="text-align: left;">Small</td>
</tr>
<tr class="even">
<td style="text-align: left;">X-squared7</td>
<td style="text-align: left;">Party Affiliation</td>
<td style="text-align: right;">1196</td>
<td style="text-align: left;">194.36</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">0.240</td>
<td style="text-align: left;">Medium</td>
</tr>
<tr class="odd">
<td style="text-align: left;">X-squared8</td>
<td style="text-align: left;">Ideology (Lib-Con)</td>
<td style="text-align: right;">1221</td>
<td style="text-align: left;">247.80</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">0.280</td>
<td style="text-align: left;">Medium</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-pop-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.10: Population Representativeness Summary: Chi-Square Goodness-of-Fit Tests
</figcaption>
</figure>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Summary interpretation:</strong> Divergences from population benchmarks fall into three structurally distinct categories.</p>
<p><em>Quota-controlled variables</em> (age, gender, race, Hispanic/Latino origin): divergences from the ACS reflect CloudResearch Connect’s standard panel preset, not sampling error. Gender is essentially aligned (h = 0.015) because the preset targets 50% female — nearly identical to the ACS. Age diverges modestly (h = 0.119, small) because the preset allocates 33.3% to the 45–59 cohort (vs.&nbsp;23.2% ACS), producing the observed overrepresentation of that group; the observed age distribution tracks the preset quotas within 0.4 percentage points across all four bins. Race and Hispanic/Latino origin show medium divergences (HISPLAT h = 0.330; RACE_ETH h = 0.207; RACE_ONLY h = 0.296) that follow directly from the preset’s symmetric 83.3% White / 8.3% Black / 8.3% Hispanic / 8.3% Other structure — a heuristic that departs substantially from current Census proportions. These racial/ethnic divergences are documented in the pre-registration as a deliberate choice to follow CloudResearch’s standard preset for cross-study comparability (OSF: <a href="https://osf.io/snxyt/">https://osf.io/snxyt/</a>).</p>
<p><em>Uncontrolled demographic variables</em> (education and income): no quotas were set; distributions reflect the organic composition of the Connect panel. Education shows the largest divergence overall (h = 0.459, approaching large): the sample is heavily college-educated (70.5% Bachelor’s or higher vs.&nbsp;35.7% ACS 25+), with HS-or-less respondents nearly absent (1.5% vs.&nbsp;36.2%) — a well-documented characteristic of opt-in online survey panels. Note also that the ACS education benchmark covers adults 25+, while the survey targets 18+, modestly amplifying the apparent gap. Income diverges modestly (h = 0.152, small), with the sample concentrated in the $25k–$99.9k range and high earners underrepresented ($150k+: 9.5% vs.&nbsp;21.5% ACS), consistent with lower participation rates among high-income individuals in paid online surveys.</p>
<p><em>Political orientation variables</em> (party affiliation and ideology): benchmarked against Gallup 2024 annual averages rather than ACS (which does not collect political data). No quotas were set on political orientation. Online opt-in panels typically skew liberal and Democratic relative to the general adult population, a well-documented feature of these platforms driven in part by the educational and age composition of panel participants. The political comparisons use a different source population and methodology (Gallup telephone survey vs.&nbsp;ACS census survey) than the demographic variables, so direct effect-size comparisons across the two benchmark sources should be interpreted with appropriate caution.</p>
<p>The study’s primary claims rest on internal validity — clean randomization between treatment groups (confirmed in Chapter 4) — rather than representational sampling. These comparisons enable readers to assess which subpopulations are and are not well-represented and to calibrate the external generalizability of the findings accordingly.</p>
</div>
</div>
</div>
<hr>
</section>
<section id="sec-pop-repro" class="level2" data-number="5.9">
<h2 data-number="5.9" class="anchored" data-anchor-id="sec-pop-repro"><span class="header-section-number">5.9</span> Reproducibility Note</h2>
<p>The population benchmark data in <code>data/population/acs-benchmarks.csv</code> is committed to the repository. This file contains both ACS 2023 benchmarks (demographic variables) and Gallup 2024 annual averages (political orientation variables). Readers who clone the repository can reproduce all analyses in this chapter without a Census API key.</p>
<p>To regenerate the benchmark file from the Census API directly:</p>


<!-- -->

</section>


</main> <!-- /main -->
<script>
/*
 * sidebar-toc.js — CC Survey Online Appendix
 *
 * Quarto Book sidebar accordion for within-page sections.
 *
 * Actual Quarto behavior (confirmed from rendered HTML):
 *   - toc-location: left places the TOC as <nav id="TOC"> inside #quarto-sidebar,
 *     AFTER the chapter list. The <ul> has class="collapse" (Bootstrap-hidden).
 *   - There is NO #quarto-sidebar-toc-left element in Quarto 1.8.
 *   - CSS hides the nav#TOC block; this script moves the links to nest under
 *     the active chapter <li>, achieving accordion display.
 *
 * Edge case handled: chapters with a body H1 (e.g. {.unnumbered} intro) produce
 * a TOC where the H1 is the sole top-level link and H2s are nested under it.
 * In that case we skip the H1 (which duplicates the sidebar chapter entry) and
 * promote the nested H2 links instead.
 */
(function () {
  'use strict';

  function injectAuthorLine() {
    // Add author name below the book title/subtitle, above the search bar
    if (document.querySelector('.sidebar-author')) return;

    var sidebar = document.getElementById('quarto-sidebar');
    if (!sidebar) return;

    // Insert after subtitle if present, else after title
    var anchor = sidebar.querySelector('.sidebar-subtitle')
              || sidebar.querySelector('.sidebar-title');
    if (!anchor) return;

    var authorDiv = document.createElement('div');
    authorDiv.className = 'sidebar-author';
    authorDiv.innerHTML = '<span class="sidebar-author-label">inquiry by</span><br>Thomas H. Rousse<br>J.D., Ph.D.';

    // Insert between subtitle/title and search bar (equidistant)
    var search = sidebar.querySelector('#quarto-search');
    if (search) {
      search.parentNode.insertBefore(authorDiv, search);
    } else {
      anchor.parentNode.insertBefore(authorDiv, anchor.nextSibling);
    }
  }

  function injectSections() {
    // 1. Find the active chapter <li> in the sidebar
    var activeLink = document.querySelector('#quarto-sidebar .sidebar-link.active');
    if (!activeLink) return;
    var activeItem = activeLink.closest('li.sidebar-item');
    if (!activeItem) return;

    // 2. Find the TOC nav that Quarto placed inside the sidebar
    var tocNav = document.querySelector('#quarto-sidebar nav#TOC');
    if (!tocNav) return;

    // 3. Get all section links (already depth-filtered by Quarto's toc-depth: 2)
    var allLinks = Array.from(tocNav.querySelectorAll('a[data-scroll-target]'));

    // Keep only top-level links (no grandparent <li>)
    var topLevelLinks = allLinks.filter(function (link) {
      var parentLi = link.closest('li');
      if (!parentLi) return false;
      var grandparentLi = parentLi.parentElement && parentLi.parentElement.closest('li');
      return !grandparentLi;
    });

    // Edge case: body-H1 chapters (e.g. {.unnumbered} intro).
    // The sole top-level link IS the chapter title — injecting it would duplicate
    // the sidebar chapter entry. Detect this and promote the nested H2 links instead.
    var chapterText = activeLink.textContent.replace(/^\d+[\.\s]+/, '').trim();
    if (
      topLevelLinks.length === 1 &&
      topLevelLinks[0].textContent.trim() === chapterText
    ) {
      // Promote one level deeper (the H2s nested under the H1)
      topLevelLinks = allLinks.filter(function (link) {
        var parentLi = link.closest('li');
        if (!parentLi) return false;
        var grandparentLi = parentLi.parentElement && parentLi.parentElement.closest('li');
        if (!grandparentLi) return false;
        var greatGrandparentLi = grandparentLi.parentElement && grandparentLi.parentElement.closest('li');
        return !greatGrandparentLi;
      });
    }

    if (topLevelLinks.length === 0) return;

    // 4. Build the nested section list
    var sectionList = document.createElement('ul');
    sectionList.className = 'sidebar-sections list-unstyled';

    topLevelLinks.forEach(function (link) {
      var li = document.createElement('li');
      li.className = 'sidebar-section-item';
      // Replace nav-link class with our sidebar class; keep data-scroll-target
      link.className = 'sidebar-section-link';
      li.appendChild(link); // move (not clone) to preserve Quarto scroll-tracking refs
      sectionList.appendChild(li);
    });

    // 5. Insert immediately after the active chapter <li>
    activeItem.parentNode.insertBefore(sectionList, activeItem.nextSibling);

    // 6. tocNav is already hidden via CSS; no further action needed
  }

  function init() {
    injectAuthorLine();
    injectSections();
  }

  if (document.readyState === 'complete') {
    init();
  } else {
    window.addEventListener('load', init);
  }
}());
</script>
<script>
/*
 * section-numbering.js — CC Survey Online Appendix
 *
 * Renumbers ALL tables and figures to use section-level numbering:
 *   Table 7.1.1.1 = Chapter 7, Scenario 1, Subsection 1, Table 1
 *   Figure 3.2.1  = Chapter 3, Section 2, Figure 1
 *
 * Works on ALL pages:
 *   - Numbered chapters: reads Quarto's .header-section-number spans
 *   - Unnumbered scenario chapters: parses manual section numbers from
 *     heading text (e.g., "## 7.1.1 Q1: ...")
 *
 * Fixes both same-page AND cross-page cross-reference links.
 * Cross-page xrefs are resolved by fetching the target page, computing
 * its section-level numbering, and patching the link text. Each target
 * page is fetched at most once (results are cached per session).
 *
 * Replaces the original scenario-numbering.html (which only handled
 * 3-level numbering for figures on scenario pages).
 *
 * Runs after DOM load.
 */
document.addEventListener('DOMContentLoaded', function() {

  // ── Shared: compute section-level numbering for a root element ──
  // Returns { elementId: { type: 'Table'|'Figure', number: '6.3.1' } }
  // If mutate=true, also rewrites captions and wraps manual heading
  // numbers in .header-section-number spans (only for the live page).
  function computeNumbering(root, mutate) {
    var nodes = root.querySelectorAll(
      'h1, h2, h3, h4, [id^="tbl-"], [id^="fig-"]'
    );

    var currentSection = '';
    var tblCount = {};
    var figCount = {};
    var map = {};

    nodes.forEach(function(el) {
      var tag = el.tagName;

      // ── Heading: update current section number ───────────────
      if (/^H[1-4]$/i.test(tag)) {
        var numSpan = el.querySelector('.header-section-number');
        if (numSpan) {
          currentSection = numSpan.textContent.trim();
          return;
        }
        var m = el.textContent.trim().match(/^(\d+(?:\.\d+)*)/);
        if (m) {
          currentSection = m[1];
          if (mutate) {
            var secId = el.querySelector('.quarto-section-identifier');
            var target = secId || el;
            var html = target.innerHTML;
            if (html.indexOf('header-section-number') === -1) {
              target.innerHTML = html.replace(
                /^(\d+(?:\.\d+)*)\s*/,
                '<span class="header-section-number">$1</span> '
              );
            }
          }
        }
        return;
      }

      // ── Float container: compute new number ─────────────────
      if (!currentSection) return;

      var cap = el.querySelector('figcaption') || el.querySelector('caption');
      if (!cap) return;

      var id = (el.id || '').toLowerCase();
      var type, counter;
      if (id.startsWith('tbl-')) {
        type = 'Table';
        counter = tblCount;
      } else if (id.startsWith('fig-')) {
        type = 'Figure';
        counter = figCount;
      } else {
        return;
      }

      if (!counter[currentSection]) counter[currentSection] = 0;
      counter[currentSection]++;
      var newNum = currentSection + '.' + counter[currentSection];

      map[el.id] = { type: type, number: newNum };

      if (mutate) {
        var re = new RegExp(
          '(' + type + ')(&#160;|&nbsp;|\\u00A0|\\s)(\\d+(?:\\.\\d+)*)'
        );
        cap.innerHTML = cap.innerHTML.replace(
          re, '<span class="float-label">$1$2' + newNum + '</span>'
        );
        el.setAttribute('data-section-num', newNum);
        el.setAttribute('data-section-type', type);
      }
    });

    return map;
  }

  // ── Helper: update a cross-reference link with new numbering ──
  function patchXrefLink(link, info) {
    var spans = link.querySelectorAll('span');
    if (spans.length > 0) {
      spans[spans.length - 1].textContent = info.number;
    } else {
      link.innerHTML = info.type + '&nbsp;' + info.number;
    }
  }

  // ══════════════════════════════════════════════════════════════
  // 1. Renumber the current page (mutate captions + headings)
  // ══════════════════════════════════════════════════════════════
  var main = document.getElementById('quarto-document-content');
  if (!main) return;

  var localMap = computeNumbering(main, true);

  // ══════════════════════════════════════════════════════════════
  // 2. Fix same-page cross-reference links
  // ══════════════════════════════════════════════════════════════
  document.querySelectorAll('a.quarto-xref').forEach(function(link) {
    var href = link.getAttribute('href');
    if (!href || !href.startsWith('#')) return;

    var targetId = href.substring(1);
    var info = localMap[targetId];
    if (!info) return;

    patchXrefLink(link, info);
  });

  // ══════════════════════════════════════════════════════════════
  // 3. Fix cross-page cross-reference links
  //    Group by target page URL, fetch each once, compute
  //    numbering on the fetched DOM, patch all links to that page.
  // ══════════════════════════════════════════════════════════════
  var crossPageGroups = {};   // pageUrl → [{link, targetId}]

  document.querySelectorAll('a.quarto-xref').forEach(function(link) {
    var href = link.getAttribute('href');
    if (!href || href.startsWith('#')) return;

    var hashIdx = href.indexOf('#');
    if (hashIdx === -1) return;

    var pageUrl  = href.substring(0, hashIdx);
    var targetId = href.substring(hashIdx + 1);

    // Skip if target ID doesn't look like a table/figure
    if (!targetId.startsWith('tbl-') && !targetId.startsWith('fig-')) return;

    if (!crossPageGroups[pageUrl]) crossPageGroups[pageUrl] = [];
    crossPageGroups[pageUrl].push({ link: link, targetId: targetId });
  });

  // Fetch each unique target page and resolve its numbering
  Object.keys(crossPageGroups).forEach(function(pageUrl) {
    fetch(pageUrl)
      .then(function(response) {
        if (!response.ok) throw new Error(response.status);
        return response.text();
      })
      .then(function(html) {
        var parser = new DOMParser();
        var doc = parser.parseFromString(html, 'text/html');
        var remoteMain = doc.getElementById('quarto-document-content');
        if (!remoteMain) return;

        // Compute numbering on the fetched page (read-only, no mutation)
        var remoteMap = computeNumbering(remoteMain, false);

        // Patch all links pointing to this page
        crossPageGroups[pageUrl].forEach(function(entry) {
          var info = remoteMap[entry.targetId];
          if (!info) return;
          patchXrefLink(entry.link, info);
        });
      })
      .catch(function(err) {
        // Graceful degradation: cross-page links keep Quarto-native numbers
        console.warn('[section-numbering] Could not resolve xrefs for '
          + pageUrl + ':', err.message || err);
      });
  });
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./04-randomization.html" class="pagination-link" aria-label="Randomization Check">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Randomization Check</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06-brand.html" class="pagination-link" aria-label="Brand Recognition">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Brand Recognition</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Sample v. Population Analysis"</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="in">```{r setup, include=FALSE}</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"_common.R"</span>))</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">## Overview {#sec-pop-overview}</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>This Chapter compares the survey sample demographics against population benchmarks to assess external validity: How does the sample resemble the American adult population? The analysis covers five demographic characteristics — age, gender, race/ethnicity, education, and income — benchmarked against the American Community Survey (ACS), plus two political orientation measures — party affiliation and ideology — benchmarked against Gallup's 2024 annual tracking poll. Full source details for both benchmarks appear below.</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>**Study design note:** The survey used a CloudResearch Connect^[Rachel Hartman, Aaron J. Moss, Shalom N. Jaffe, Cheskie Rosenzweig, Leib Litman &amp; Jonathan Robinson, *Introducing Connect by</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>  CloudResearch: Advancing Online Participant Recruitment in the Digital Age* (2023), https://doi.org/10.31234/osf.io/ksgyr; CloudResearch, *Connect for Researchers*, https://www.cloudresearch.com/products/connect-for-researchers/.]</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a> panel. This service provides a quota-sampled convenience panel, not a probability sample. Like most online survey experiments, the study prioritizes *internal validity* (clean randomization between treatment groups) over *representational sampling*. The ACS comparison documents where the sample diverges from the general population, enabling readers to assess how findings might or might not generalize. In sum, CloudResearch's "nationally representative" designation is a marketing term that does not reflect probability sampling or representativeness in the statistical sense.</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>Divergences in this chapter fall into three categories: (1) *quota-controlled demographic variables* (age, gender, race, and Hispanic/Latino origin), where the sample follows CloudResearch Connect's standard preset quotas, which depart from ACS proportions; (2) *uncontrolled demographic variables* (education and income), where no quota was set and the distribution reflects the organic composition of opt-in online survey participants; and (3) *political orientation variables* (party affiliation and ideology), benchmarked against Gallup's 2024 annual tracking poll rather than the ACS, which does not collect political data.</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>Randomization balance (internal validity) is confirmed separately in <span class="co">[</span><span class="ot">Chapter 4</span><span class="co">](04-randomization.qmd)</span>. The analysis here uses Groups A, B, and C (*n* = 1,222).</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>**Reference populations:** *Demographics* (§§5.1–5.5): ACS 2023 1-year estimates, U.S. civilian non-institutionalized population. Source tables: B01001 (sex by age), B03002 (Hispanic/Latino origin by race), B15003 (educational attainment, 25+), B19001 (household income). Data retrieved from data.gov via the `tidycensus` R package. See `data/population/acs-source-notes.md` for complete retrieval details and cell-level recoding decisions. *Political orientation* (§5.6): Gallup 2024 annual averages, based on telephone surveys of more than 14,000 U.S. adults conducted throughout 2024.</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a><span class="in">```{r pop-setup}</span></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Load pre-generated benchmarks (committed CSV; no API key required)</span></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Contains ACS 2023 (demographics) + Gallup 2024 (political orientation)</span></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>benchmarks <span class="ot">&lt;-</span> <span class="fu">load_population_benchmarks</span>()</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Confirm benchmark structure</span></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Benchmarks loaded for variables:"</span>,</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste</span>(<span class="fu">names</span>(benchmarks), <span class="at">collapse =</span> <span class="st">", "</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Total benchmark rows:"</span>, <span class="fu">sum</span>(<span class="fu">sapply</span>(benchmarks, nrow)), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a><span class="fu">## Age {#sec-pop-age}</span></span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fig-pop-age}</span></span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-pop-age</span></span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Age distribution: survey sample vs. ACS 2023 benchmark"</span></span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5.5</span></span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 8</span></span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a>result_age <span class="ot">&lt;-</span> <span class="fu">run_population_chisq</span>(survey_data, benchmarks, <span class="st">"AGE"</span>)</span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-50"><a href="#cb3-50" aria-hidden="true" tabindex="-1"></a>p_age <span class="ot">&lt;-</span> <span class="fu">plot_population_comparison</span>(</span>
<span id="cb3-51"><a href="#cb3-51" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey_data    =</span> survey_data,</span>
<span id="cb3-52"><a href="#cb3-52" aria-hidden="true" tabindex="-1"></a>  <span class="at">benchmarks     =</span> benchmarks,</span>
<span id="cb3-53"><a href="#cb3-53" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable       =</span> <span class="st">"AGE"</span>,</span>
<span id="cb3-54"><a href="#cb3-54" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable_label =</span> <span class="st">"Age Group"</span>,</span>
<span id="cb3-55"><a href="#cb3-55" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_average   =</span> <span class="cn">TRUE</span>,</span>
<span id="cb3-56"><a href="#cb3-56" aria-hidden="true" tabindex="-1"></a>  <span class="at">omnibus_p      =</span> result_age<span class="sc">$</span>p_value</span>
<span id="cb3-57"><a href="#cb3-57" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-58"><a href="#cb3-58" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p_age)</span>
<span id="cb3-59"><a href="#cb3-59" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-60"><a href="#cb3-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-61"><a href="#cb3-61" aria-hidden="true" tabindex="-1"></a><span class="in">```{r tbl-pop-age-stats}</span></span>
<span id="cb3-62"><a href="#cb3-62" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-pop-age-stats</span></span>
<span id="cb3-63"><a href="#cb3-63" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Age: Survey vs. ACS Proportions with Chi-Square Goodness-of-Fit"</span></span>
<span id="cb3-64"><a href="#cb3-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-65"><a href="#cb3-65" aria-hidden="true" tabindex="-1"></a>ct_age <span class="ot">&lt;-</span> <span class="fu">format_pop_table</span>(result_age)</span>
<span id="cb3-66"><a href="#cb3-66" aria-hidden="true" tabindex="-1"></a>avg_row <span class="ot">&lt;-</span> <span class="fu">make_weighted_avg_row</span>(result_age<span class="sc">$</span>comparison_table, result_age)</span>
<span id="cb3-67"><a href="#cb3-67" aria-hidden="true" tabindex="-1"></a>ct_age <span class="ot">&lt;-</span> <span class="fu">rbind</span>(ct_age, avg_row)</span>
<span id="cb3-68"><a href="#cb3-68" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb3-69"><a href="#cb3-69" aria-hidden="true" tabindex="-1"></a>  ct_age,</span>
<span id="cb3-70"><a href="#cb3-70" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Age Group"</span>, <span class="st">"Survey"</span>, <span class="st">"ACS"</span>, <span class="st">"Difference"</span>),</span>
<span id="cb3-71"><a href="#cb3-71" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="fu">fmt_chisq_caption</span>(result_age, <span class="st">"Age Distribution"</span>)</span>
<span id="cb3-72"><a href="#cb3-72" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-73"><a href="#cb3-73" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-74"><a href="#cb3-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-75"><a href="#cb3-75" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true"}</span>
<span id="cb3-76"><a href="#cb3-76" aria-hidden="true" tabindex="-1"></a>**Age interpretation:** <span class="in">`r sprintf("χ²(%d) = %.2f, p %s, Cohen's h = %.3f.", result_age$df, result_age$chisq_stat, ifelse(result_age$p_value &lt; .001, "&lt; .001", sprintf("= %.3f", result_age$p_value)), result_age$cohens_h)`</span> Despite the highly significant test statistic (driven by *n* = 1,222), the effect size is small (*h* &lt; 0.20). The observed age distribution closely tracks CloudResearch Connect's preset quota targets (18–29: 16.7% preset / 16.9% observed; 30–44: 25.0% / 25.0%; 45–59: 33.3% / 33.6%; 60+: 25.0% / 24.6%) rather than the ACS. The divergence from Census proportions, such as the overrepresentation of 45–59 respondents (33.6% vs. 23.2% ACS) and underrepresentation of 60+ adults (24.6% vs. 30.9% ACS), is therefore an artifact of the CloudResearch preset, not sampling error or panel self-selection.</span>
<span id="cb3-77"><a href="#cb3-77" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-78"><a href="#cb3-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-79"><a href="#cb3-79" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb3-80"><a href="#cb3-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-81"><a href="#cb3-81" aria-hidden="true" tabindex="-1"></a><span class="fu">## Gender {#sec-pop-gender}</span></span>
<span id="cb3-82"><a href="#cb3-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-83"><a href="#cb3-83" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb3-84"><a href="#cb3-84" aria-hidden="true" tabindex="-1"></a>**Measurement note:** ACS reports binary sex (male/female). The survey offered a third response option for respondents who identified outside the male/female binary or preferred not to answer. Those respondents are excluded from the ACS comparison below; the two-category comparison uses only male/female responses.</span>
<span id="cb3-85"><a href="#cb3-85" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-86"><a href="#cb3-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-87"><a href="#cb3-87" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fig-pop-gender}</span></span>
<span id="cb3-88"><a href="#cb3-88" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-pop-gender</span></span>
<span id="cb3-89"><a href="#cb3-89" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Gender distribution: survey sample vs. ACS 2023 benchmark"</span></span>
<span id="cb3-90"><a href="#cb3-90" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 3.5</span></span>
<span id="cb3-91"><a href="#cb3-91" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 8</span></span>
<span id="cb3-92"><a href="#cb3-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-93"><a href="#cb3-93" aria-hidden="true" tabindex="-1"></a>p_gender <span class="ot">&lt;-</span> <span class="fu">plot_population_comparison</span>(</span>
<span id="cb3-94"><a href="#cb3-94" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey_data    =</span> survey_data,</span>
<span id="cb3-95"><a href="#cb3-95" aria-hidden="true" tabindex="-1"></a>  <span class="at">benchmarks     =</span> benchmarks,</span>
<span id="cb3-96"><a href="#cb3-96" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable       =</span> <span class="st">"GENDER"</span>,</span>
<span id="cb3-97"><a href="#cb3-97" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable_label =</span> <span class="st">"Gender"</span></span>
<span id="cb3-98"><a href="#cb3-98" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-99"><a href="#cb3-99" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p_gender)</span>
<span id="cb3-100"><a href="#cb3-100" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-101"><a href="#cb3-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-102"><a href="#cb3-102" aria-hidden="true" tabindex="-1"></a><span class="in">```{r tbl-pop-gender-stats}</span></span>
<span id="cb3-103"><a href="#cb3-103" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-pop-gender-stats</span></span>
<span id="cb3-104"><a href="#cb3-104" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Gender: Survey vs. ACS Proportions with Chi-Square Goodness-of-Fit"</span></span>
<span id="cb3-105"><a href="#cb3-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-106"><a href="#cb3-106" aria-hidden="true" tabindex="-1"></a>result_gender <span class="ot">&lt;-</span> <span class="fu">run_population_chisq</span>(survey_data, benchmarks, <span class="st">"GENDER"</span>)</span>
<span id="cb3-107"><a href="#cb3-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-108"><a href="#cb3-108" aria-hidden="true" tabindex="-1"></a>ct_gender <span class="ot">&lt;-</span> <span class="fu">format_pop_table</span>(result_gender)</span>
<span id="cb3-109"><a href="#cb3-109" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb3-110"><a href="#cb3-110" aria-hidden="true" tabindex="-1"></a>  ct_gender,</span>
<span id="cb3-111"><a href="#cb3-111" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Gender"</span>, <span class="st">"Survey"</span>, <span class="st">"ACS"</span>, <span class="st">"Difference"</span>),</span>
<span id="cb3-112"><a href="#cb3-112" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="fu">fmt_chisq_caption</span>(result_gender, <span class="st">"Gender Distribution"</span>)</span>
<span id="cb3-113"><a href="#cb3-113" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-114"><a href="#cb3-114" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-115"><a href="#cb3-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-116"><a href="#cb3-116" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb3-117"><a href="#cb3-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-118"><a href="#cb3-118" aria-hidden="true" tabindex="-1"></a><span class="fu">## Race and Ethnicity {#sec-pop-race}</span></span>
<span id="cb3-119"><a href="#cb3-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-120"><a href="#cb3-120" aria-hidden="true" tabindex="-1"></a>The survey asked Hispanic/Latino origin and race as separate questions, consistent with the Census Bureau approach. This section presents three complementary comparisons: (1) Hispanic/Latino origin alone, (2) racial identification alone, and (3) a combined race/ethnicity classification.</span>
<span id="cb3-121"><a href="#cb3-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-122"><a href="#cb3-122" aria-hidden="true" tabindex="-1"></a><span class="fu">### Hispanic/Latino Origin {#sec-pop-hisplat}</span></span>
<span id="cb3-123"><a href="#cb3-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-124"><a href="#cb3-124" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fig-pop-hisplat}</span></span>
<span id="cb3-125"><a href="#cb3-125" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-pop-hisplat</span></span>
<span id="cb3-126"><a href="#cb3-126" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Hispanic/Latino origin: survey sample vs. ACS 2023 benchmark"</span></span>
<span id="cb3-127"><a href="#cb3-127" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 3.5</span></span>
<span id="cb3-128"><a href="#cb3-128" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 8</span></span>
<span id="cb3-129"><a href="#cb3-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-130"><a href="#cb3-130" aria-hidden="true" tabindex="-1"></a>p_hisplat <span class="ot">&lt;-</span> <span class="fu">plot_population_comparison</span>(</span>
<span id="cb3-131"><a href="#cb3-131" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey_data    =</span> survey_data,</span>
<span id="cb3-132"><a href="#cb3-132" aria-hidden="true" tabindex="-1"></a>  <span class="at">benchmarks     =</span> benchmarks,</span>
<span id="cb3-133"><a href="#cb3-133" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable       =</span> <span class="st">"HISPLAT"</span>,</span>
<span id="cb3-134"><a href="#cb3-134" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable_label =</span> <span class="st">"Hispanic/Latino Origin"</span></span>
<span id="cb3-135"><a href="#cb3-135" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-136"><a href="#cb3-136" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p_hisplat)</span>
<span id="cb3-137"><a href="#cb3-137" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-138"><a href="#cb3-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-139"><a href="#cb3-139" aria-hidden="true" tabindex="-1"></a><span class="in">```{r tbl-pop-hisplat-stats}</span></span>
<span id="cb3-140"><a href="#cb3-140" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-pop-hisplat-stats</span></span>
<span id="cb3-141"><a href="#cb3-141" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Hispanic/Latino Origin: Survey vs. ACS Proportions"</span></span>
<span id="cb3-142"><a href="#cb3-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-143"><a href="#cb3-143" aria-hidden="true" tabindex="-1"></a>result_hisplat <span class="ot">&lt;-</span> <span class="fu">run_population_chisq</span>(survey_data, benchmarks, <span class="st">"HISPLAT"</span>)</span>
<span id="cb3-144"><a href="#cb3-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-145"><a href="#cb3-145" aria-hidden="true" tabindex="-1"></a>ct_hisplat <span class="ot">&lt;-</span> <span class="fu">format_pop_table</span>(result_hisplat)</span>
<span id="cb3-146"><a href="#cb3-146" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb3-147"><a href="#cb3-147" aria-hidden="true" tabindex="-1"></a>  ct_hisplat,</span>
<span id="cb3-148"><a href="#cb3-148" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Category"</span>, <span class="st">"Survey"</span>, <span class="st">"ACS"</span>, <span class="st">"Difference"</span>),</span>
<span id="cb3-149"><a href="#cb3-149" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="fu">fmt_chisq_caption</span>(result_hisplat, <span class="st">"Hispanic/Latino Origin"</span>)</span>
<span id="cb3-150"><a href="#cb3-150" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-151"><a href="#cb3-151" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-152"><a href="#cb3-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-153"><a href="#cb3-153" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb3-154"><a href="#cb3-154" aria-hidden="true" tabindex="-1"></a>**Quota note:** The CloudResearch Connect standard panel preset, not the nationally representative ACS, set the Hispanic/Latino target at 8.3% (99.6 of 1,200 participants), compared to the ACS 2023 1-year estimate of approximately 19.4% for the U.S. adult population. CloudResearch's preset applies equal 8.3% allocations across three non-White racial/ethnic groups (Black, Hispanic/Latino, and Other), with the remaining 83.3% allocated to White participants. This simplified stratification departs substantially from current Census proportions. The Author followed this preset without modification to facilitate cross-study comparability with other Connect panels, a design decision documented in the pre-registration (OSF: [https://osf.io/snxyt/](https://osf.io/snxyt/)). This represents a deliberate methodological choice and a tradeoff of inexpensive survey participant pools against external validity, not a sampling error. The lack of representative racial and ethnic diversity is a well-known limitation of opt-in online survey platforms generally, which tend to underrepresent minorities and over-represent White respondents.^[*See* Courtney Kennedy, Andrew Mercer, Nick Hatley, and Scott Keeter, *Evaluating Online Nonprobability Surveys*, **Pew Research Center** (2016); Taylor C. Boas, Dino P. Chirsttenson, and David M. Glick,</span>
<span id="cb3-155"><a href="#cb3-155" aria-hidden="true" tabindex="-1"></a> *Recruiting Subjects to Survey Researchers: A Comparison of MTurk, Luc.id, and SurveyMonkey*, 8 **Pol. Sci. Res. &amp; Methods** 422,</span>
<span id="cb3-156"><a href="#cb3-156" aria-hidden="true" tabindex="-1"></a> 427 (2020) (finding that MTurk-based samples significantly over-represent White respondents compared to Census benchmarks).]</span>
<span id="cb3-157"><a href="#cb3-157" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-158"><a href="#cb3-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-159"><a href="#cb3-159" aria-hidden="true" tabindex="-1"></a><span class="fu">### Racial Identification {#sec-pop-race-only}</span></span>
<span id="cb3-160"><a href="#cb3-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-161"><a href="#cb3-161" aria-hidden="true" tabindex="-1"></a>Race is reported independently of Hispanic/Latino origin, using the survey's race selection question. For ACS comparison, the race-alone table (B02001) is used. Multi-selection responses and categories other than White, Black, and Asian are collapsed into "Other / Multiracial."</span>
<span id="cb3-162"><a href="#cb3-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-163"><a href="#cb3-163" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fig-pop-race-only}</span></span>
<span id="cb3-164"><a href="#cb3-164" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-pop-race-only</span></span>
<span id="cb3-165"><a href="#cb3-165" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Racial identification: survey sample vs. ACS 2023 benchmark (B02001, race alone)"</span></span>
<span id="cb3-166"><a href="#cb3-166" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb3-167"><a href="#cb3-167" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 8</span></span>
<span id="cb3-168"><a href="#cb3-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-169"><a href="#cb3-169" aria-hidden="true" tabindex="-1"></a>p_race_only <span class="ot">&lt;-</span> <span class="fu">plot_population_comparison</span>(</span>
<span id="cb3-170"><a href="#cb3-170" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey_data    =</span> survey_data,</span>
<span id="cb3-171"><a href="#cb3-171" aria-hidden="true" tabindex="-1"></a>  <span class="at">benchmarks     =</span> benchmarks,</span>
<span id="cb3-172"><a href="#cb3-172" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable       =</span> <span class="st">"RACE_ONLY"</span>,</span>
<span id="cb3-173"><a href="#cb3-173" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable_label =</span> <span class="st">"Race"</span></span>
<span id="cb3-174"><a href="#cb3-174" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-175"><a href="#cb3-175" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p_race_only)</span>
<span id="cb3-176"><a href="#cb3-176" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-177"><a href="#cb3-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-178"><a href="#cb3-178" aria-hidden="true" tabindex="-1"></a><span class="in">```{r tbl-pop-race-only-stats}</span></span>
<span id="cb3-179"><a href="#cb3-179" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-pop-race-only-stats</span></span>
<span id="cb3-180"><a href="#cb3-180" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Racial Identification: Survey vs. ACS Proportions"</span></span>
<span id="cb3-181"><a href="#cb3-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-182"><a href="#cb3-182" aria-hidden="true" tabindex="-1"></a>result_race_only <span class="ot">&lt;-</span> <span class="fu">run_population_chisq</span>(survey_data, benchmarks, <span class="st">"RACE_ONLY"</span>)</span>
<span id="cb3-183"><a href="#cb3-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-184"><a href="#cb3-184" aria-hidden="true" tabindex="-1"></a>ct_race_only <span class="ot">&lt;-</span> <span class="fu">format_pop_table</span>(result_race_only)</span>
<span id="cb3-185"><a href="#cb3-185" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb3-186"><a href="#cb3-186" aria-hidden="true" tabindex="-1"></a>  ct_race_only,</span>
<span id="cb3-187"><a href="#cb3-187" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Race"</span>, <span class="st">"Survey"</span>, <span class="st">"ACS"</span>, <span class="st">"Difference"</span>),</span>
<span id="cb3-188"><a href="#cb3-188" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="fu">fmt_chisq_caption</span>(result_race_only, <span class="st">"Racial Identification"</span>)</span>
<span id="cb3-189"><a href="#cb3-189" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-190"><a href="#cb3-190" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-191"><a href="#cb3-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-192"><a href="#cb3-192" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb3-193"><a href="#cb3-193" aria-hidden="true" tabindex="-1"></a>**Quota note:** The White overrepresentation (82.0% vs. 60.5% ACS) directly reflects CloudResearch Connect's 83.3% White preset quota. The preset allocates the remaining 16.7% equally across three non-White groups (8.3% each for Black, Hispanic/Latino, and Other), without distinguishing Asian as a separate category — which explains why the Asian alone estimate (6.1% vs. 6.0% ACS) achieves near-exact alignment despite no explicit Asian quota: Asian respondents were absorbed into the residual "Other" pool alongside AIAN, NHPI, and multiracial respondents, whose collective underrepresentation drives the large "Other / Multiracial" gap (3.9% vs. 21.4% ACS). *See* the pre-registration (OSF: <span class="co">[</span><span class="ot">https://osf.io/snxyt/</span><span class="co">](https://osf.io/snxyt/)</span>) for the quota rationale.</span>
<span id="cb3-194"><a href="#cb3-194" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-195"><a href="#cb3-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-196"><a href="#cb3-196" aria-hidden="true" tabindex="-1"></a><span class="fu">### Combined Race/Ethnicity {#sec-pop-race-eth}</span></span>
<span id="cb3-197"><a href="#cb3-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-198"><a href="#cb3-198" aria-hidden="true" tabindex="-1"></a>The combined classification uses the B03002 table (Hispanic/Latino origin by race) to construct mutually exclusive categories: Hispanic/Latino respondents are classified under that category regardless of racial identification; non-Hispanic respondents are classified by race.</span>
<span id="cb3-199"><a href="#cb3-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-200"><a href="#cb3-200" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fig-pop-race}</span></span>
<span id="cb3-201"><a href="#cb3-201" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-pop-race</span></span>
<span id="cb3-202"><a href="#cb3-202" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Combined race/ethnicity: survey sample vs. ACS 2023 benchmark (B03002)"</span></span>
<span id="cb3-203"><a href="#cb3-203" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5.5</span></span>
<span id="cb3-204"><a href="#cb3-204" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 8</span></span>
<span id="cb3-205"><a href="#cb3-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-206"><a href="#cb3-206" aria-hidden="true" tabindex="-1"></a>p_race <span class="ot">&lt;-</span> <span class="fu">plot_population_comparison</span>(</span>
<span id="cb3-207"><a href="#cb3-207" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey_data    =</span> survey_data,</span>
<span id="cb3-208"><a href="#cb3-208" aria-hidden="true" tabindex="-1"></a>  <span class="at">benchmarks     =</span> benchmarks,</span>
<span id="cb3-209"><a href="#cb3-209" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable       =</span> <span class="st">"RACE_ETH"</span>,</span>
<span id="cb3-210"><a href="#cb3-210" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable_label =</span> <span class="st">"Race/Ethnicity (Combined)"</span></span>
<span id="cb3-211"><a href="#cb3-211" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-212"><a href="#cb3-212" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p_race)</span>
<span id="cb3-213"><a href="#cb3-213" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-214"><a href="#cb3-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-215"><a href="#cb3-215" aria-hidden="true" tabindex="-1"></a><span class="in">```{r tbl-pop-race-stats}</span></span>
<span id="cb3-216"><a href="#cb3-216" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-pop-race-stats</span></span>
<span id="cb3-217"><a href="#cb3-217" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Combined Race/Ethnicity: Survey vs. ACS Proportions"</span></span>
<span id="cb3-218"><a href="#cb3-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-219"><a href="#cb3-219" aria-hidden="true" tabindex="-1"></a>result_race <span class="ot">&lt;-</span> <span class="fu">run_population_chisq</span>(survey_data, benchmarks, <span class="st">"RACE_ETH"</span>)</span>
<span id="cb3-220"><a href="#cb3-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-221"><a href="#cb3-221" aria-hidden="true" tabindex="-1"></a>ct_race <span class="ot">&lt;-</span> <span class="fu">format_pop_table</span>(result_race)</span>
<span id="cb3-222"><a href="#cb3-222" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb3-223"><a href="#cb3-223" aria-hidden="true" tabindex="-1"></a>  ct_race,</span>
<span id="cb3-224"><a href="#cb3-224" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Race/Ethnicity"</span>, <span class="st">"Survey"</span>, <span class="st">"ACS"</span>, <span class="st">"Difference"</span>),</span>
<span id="cb3-225"><a href="#cb3-225" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="fu">fmt_chisq_caption</span>(result_race, <span class="st">"Combined Race/Ethnicity"</span>)</span>
<span id="cb3-226"><a href="#cb3-226" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-227"><a href="#cb3-227" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-228"><a href="#cb3-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-229"><a href="#cb3-229" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb3-230"><a href="#cb3-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-231"><a href="#cb3-231" aria-hidden="true" tabindex="-1"></a><span class="fu">## Education {#sec-pop-edu}</span></span>
<span id="cb3-232"><a href="#cb3-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-233"><a href="#cb3-233" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb3-234"><a href="#cb3-234" aria-hidden="true" tabindex="-1"></a>**Measurement note:** The ACS educational attainment table (B15003) covers the population aged **25** and older, while the survey targets adults **18** and older. The ACS proportions used here may over-represent higher education levels relative to the full 18+ population, since adults aged 18–24 are more likely to have not yet completed post-secondary education. No quota was set on educational attainment; the observed distribution reflects the organic composition of the CloudResearch Connect panel. </span>
<span id="cb3-235"><a href="#cb3-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-236"><a href="#cb3-236" aria-hidden="true" tabindex="-1"></a>The heavy overrepresentation of college-educated respondents (70.5% Bachelor's or higher vs. 35.7% ACS 25+) is a well-documented characteristic of opt-in online survey platforms generally.^[*See* Courtney Kennedy, Andrew Mercer, Nick Hatley, and Scott Keeter, *Evaluating Online Nonprobability Surveys*, **Pew Research Center** (2016); Taylor C. Boas, Dino P. Chirsttenson, and David M. Glick,</span>
<span id="cb3-237"><a href="#cb3-237" aria-hidden="true" tabindex="-1"></a> *Recruiting Subjects to Survey Researchers: A Comparison of MTurk, Luc.id, and SurveyMonkey*, 8 **Pol. Sci. Res. &amp; Methods** 422,</span>
<span id="cb3-238"><a href="#cb3-238" aria-hidden="true" tabindex="-1"></a> 427 (2020) (finding that MTurk-based samples are significantly more educated than Census benchmarks).]</span>
<span id="cb3-239"><a href="#cb3-239" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-240"><a href="#cb3-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-241"><a href="#cb3-241" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fig-pop-edu}</span></span>
<span id="cb3-242"><a href="#cb3-242" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-pop-edu</span></span>
<span id="cb3-243"><a href="#cb3-243" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Education distribution: survey sample vs. ACS 2023 benchmark"</span></span>
<span id="cb3-244"><a href="#cb3-244" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5.5</span></span>
<span id="cb3-245"><a href="#cb3-245" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 8</span></span>
<span id="cb3-246"><a href="#cb3-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-247"><a href="#cb3-247" aria-hidden="true" tabindex="-1"></a>result_edu <span class="ot">&lt;-</span> <span class="fu">run_population_chisq</span>(survey_data, benchmarks, <span class="st">"EDU"</span>)</span>
<span id="cb3-248"><a href="#cb3-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-249"><a href="#cb3-249" aria-hidden="true" tabindex="-1"></a>p_edu <span class="ot">&lt;-</span> <span class="fu">plot_population_comparison</span>(</span>
<span id="cb3-250"><a href="#cb3-250" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey_data    =</span> survey_data,</span>
<span id="cb3-251"><a href="#cb3-251" aria-hidden="true" tabindex="-1"></a>  <span class="at">benchmarks     =</span> benchmarks,</span>
<span id="cb3-252"><a href="#cb3-252" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable       =</span> <span class="st">"EDU"</span>,</span>
<span id="cb3-253"><a href="#cb3-253" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable_label =</span> <span class="st">"Educational Attainment"</span>,</span>
<span id="cb3-254"><a href="#cb3-254" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_average   =</span> <span class="cn">TRUE</span>,</span>
<span id="cb3-255"><a href="#cb3-255" aria-hidden="true" tabindex="-1"></a>  <span class="at">omnibus_p      =</span> result_edu<span class="sc">$</span>p_value</span>
<span id="cb3-256"><a href="#cb3-256" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-257"><a href="#cb3-257" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p_edu)</span>
<span id="cb3-258"><a href="#cb3-258" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-259"><a href="#cb3-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-260"><a href="#cb3-260" aria-hidden="true" tabindex="-1"></a><span class="in">```{r tbl-pop-edu-stats}</span></span>
<span id="cb3-261"><a href="#cb3-261" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-pop-edu-stats</span></span>
<span id="cb3-262"><a href="#cb3-262" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Education: Survey vs. ACS Proportions with Chi-Square Goodness-of-Fit"</span></span>
<span id="cb3-263"><a href="#cb3-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-264"><a href="#cb3-264" aria-hidden="true" tabindex="-1"></a>ct_edu <span class="ot">&lt;-</span> <span class="fu">format_pop_table</span>(result_edu)</span>
<span id="cb3-265"><a href="#cb3-265" aria-hidden="true" tabindex="-1"></a>avg_row <span class="ot">&lt;-</span> <span class="fu">make_weighted_avg_row</span>(result_edu<span class="sc">$</span>comparison_table, result_edu)</span>
<span id="cb3-266"><a href="#cb3-266" aria-hidden="true" tabindex="-1"></a>ct_edu <span class="ot">&lt;-</span> <span class="fu">rbind</span>(ct_edu, avg_row)</span>
<span id="cb3-267"><a href="#cb3-267" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb3-268"><a href="#cb3-268" aria-hidden="true" tabindex="-1"></a>  ct_edu,</span>
<span id="cb3-269"><a href="#cb3-269" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Education Level"</span>, <span class="st">"Survey"</span>, <span class="st">"ACS"</span>, <span class="st">"Difference"</span>),</span>
<span id="cb3-270"><a href="#cb3-270" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="fu">fmt_chisq_caption</span>(result_edu, <span class="st">"Education Distribution"</span>)</span>
<span id="cb3-271"><a href="#cb3-271" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-272"><a href="#cb3-272" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-273"><a href="#cb3-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-274"><a href="#cb3-274" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb3-275"><a href="#cb3-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-276"><a href="#cb3-276" aria-hidden="true" tabindex="-1"></a><span class="fu">## Income {#sec-pop-income}</span></span>
<span id="cb3-277"><a href="#cb3-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-278"><a href="#cb3-278" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb3-279"><a href="#cb3-279" aria-hidden="true" tabindex="-1"></a>**Sampling Note:** No quota was set on household income; the observed distribution reflects the organic composition of the CloudResearch Connect panel. The concentration in the $25k–$99.9k range and underrepresentation of the highest earners ($150k+: 9.5% vs. 21.5% ACS) likely reflects participation patterns in paid online surveys, where high-income individuals have lower rates of panel enrollment and survey completion. The ACS income benchmark uses household-level estimates (B19001), consistent with the survey's household income question.</span>
<span id="cb3-280"><a href="#cb3-280" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-281"><a href="#cb3-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-282"><a href="#cb3-282" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fig-pop-income}</span></span>
<span id="cb3-283"><a href="#cb3-283" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-pop-income</span></span>
<span id="cb3-284"><a href="#cb3-284" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Income distribution: survey sample vs. ACS 2023 benchmark"</span></span>
<span id="cb3-285"><a href="#cb3-285" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 7</span></span>
<span id="cb3-286"><a href="#cb3-286" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 8</span></span>
<span id="cb3-287"><a href="#cb3-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-288"><a href="#cb3-288" aria-hidden="true" tabindex="-1"></a>result_income <span class="ot">&lt;-</span> <span class="fu">run_population_chisq</span>(survey_data, benchmarks, <span class="st">"INCOME"</span>)</span>
<span id="cb3-289"><a href="#cb3-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-290"><a href="#cb3-290" aria-hidden="true" tabindex="-1"></a>p_income <span class="ot">&lt;-</span> <span class="fu">plot_population_comparison</span>(</span>
<span id="cb3-291"><a href="#cb3-291" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey_data    =</span> survey_data,</span>
<span id="cb3-292"><a href="#cb3-292" aria-hidden="true" tabindex="-1"></a>  <span class="at">benchmarks     =</span> benchmarks,</span>
<span id="cb3-293"><a href="#cb3-293" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable       =</span> <span class="st">"INCOME"</span>,</span>
<span id="cb3-294"><a href="#cb3-294" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable_label =</span> <span class="st">"Household Income"</span>,</span>
<span id="cb3-295"><a href="#cb3-295" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_average   =</span> <span class="cn">TRUE</span>,</span>
<span id="cb3-296"><a href="#cb3-296" aria-hidden="true" tabindex="-1"></a>  <span class="at">omnibus_p      =</span> result_income<span class="sc">$</span>p_value</span>
<span id="cb3-297"><a href="#cb3-297" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-298"><a href="#cb3-298" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p_income)</span>
<span id="cb3-299"><a href="#cb3-299" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-300"><a href="#cb3-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-301"><a href="#cb3-301" aria-hidden="true" tabindex="-1"></a><span class="in">```{r tbl-pop-income-stats}</span></span>
<span id="cb3-302"><a href="#cb3-302" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-pop-income-stats</span></span>
<span id="cb3-303"><a href="#cb3-303" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Income: Survey vs. ACS Proportions with Chi-Square Goodness-of-Fit"</span></span>
<span id="cb3-304"><a href="#cb3-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-305"><a href="#cb3-305" aria-hidden="true" tabindex="-1"></a>ct_income <span class="ot">&lt;-</span> <span class="fu">format_pop_table</span>(result_income)</span>
<span id="cb3-306"><a href="#cb3-306" aria-hidden="true" tabindex="-1"></a>avg_row <span class="ot">&lt;-</span> <span class="fu">make_weighted_avg_row</span>(result_income<span class="sc">$</span>comparison_table, result_income)</span>
<span id="cb3-307"><a href="#cb3-307" aria-hidden="true" tabindex="-1"></a>ct_income <span class="ot">&lt;-</span> <span class="fu">rbind</span>(ct_income, avg_row)</span>
<span id="cb3-308"><a href="#cb3-308" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb3-309"><a href="#cb3-309" aria-hidden="true" tabindex="-1"></a>  ct_income,</span>
<span id="cb3-310"><a href="#cb3-310" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Income Bracket"</span>, <span class="st">"Survey"</span>, <span class="st">"ACS"</span>, <span class="st">"Difference"</span>),</span>
<span id="cb3-311"><a href="#cb3-311" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="fu">fmt_chisq_caption</span>(result_income, <span class="st">"Income Distribution"</span>)</span>
<span id="cb3-312"><a href="#cb3-312" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-313"><a href="#cb3-313" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-314"><a href="#cb3-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-315"><a href="#cb3-315" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb3-316"><a href="#cb3-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-317"><a href="#cb3-317" aria-hidden="true" tabindex="-1"></a><span class="fu">## Political Orientation {#sec-pop-politics}</span></span>
<span id="cb3-318"><a href="#cb3-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-319"><a href="#cb3-319" aria-hidden="true" tabindex="-1"></a>Political orientation is examined through two measures: party affiliation (POLPARTY) and political ideology on a liberal–conservative spectrum (LIBCON). Because the Census Bureau does not collect political data, this section uses Gallup's annual tracking poll as the population benchmark rather than the ACS.</span>
<span id="cb3-320"><a href="#cb3-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-321"><a href="#cb3-321" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb3-322"><a href="#cb3-322" aria-hidden="true" tabindex="-1"></a>**Benchmark source note:** The American Community Survey does not include questions about political orientation. The benchmarks here are drawn from Gallup's 2024 annual tracking poll, which surveys more than 14,000 U.S. adults by telephone throughout the year.^<span class="co">[</span><span class="ot">Gallup, *GOP Holds Edge in Party Affiliation for Third Straight Year* (Jan. 16, 2025); Gallup, *U.S. Political Parties Historically Polarized Ideologically* (Jan. 24, 2025). Data available at https://news.gallup.com/poll/15370/party-affiliation.aspx.</span><span class="co">]</span> The survey's three-category party split (Republican, Democrat, Independent — excluding "Other" and "Prefer not to say") maps directly to Gallup's initial party identification question. For ideology, the survey's five-point LIBCON scale (Very Liberal through Very Conservative) is collapsed to three categories (Liberal, Moderate, Conservative) to match Gallup's published annual breakdown. Because the benchmark source differs from the ACS used in preceding sections, chi-square results and effect sizes for political variables should not be directly compared to the demographic variables above.</span>
<span id="cb3-323"><a href="#cb3-323" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-324"><a href="#cb3-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-325"><a href="#cb3-325" aria-hidden="true" tabindex="-1"></a><span class="fu">### Party Affiliation {#sec-pop-polparty}</span></span>
<span id="cb3-326"><a href="#cb3-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-327"><a href="#cb3-327" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fig-pop-polparty}</span></span>
<span id="cb3-328"><a href="#cb3-328" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-pop-polparty</span></span>
<span id="cb3-329"><a href="#cb3-329" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Party affiliation: survey sample vs. Gallup 2024 benchmark"</span></span>
<span id="cb3-330"><a href="#cb3-330" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 4.5</span></span>
<span id="cb3-331"><a href="#cb3-331" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 8</span></span>
<span id="cb3-332"><a href="#cb3-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-333"><a href="#cb3-333" aria-hidden="true" tabindex="-1"></a>result_polparty <span class="ot">&lt;-</span> <span class="fu">run_population_chisq</span>(survey_data, benchmarks, <span class="st">"POLPARTY"</span>)</span>
<span id="cb3-334"><a href="#cb3-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-335"><a href="#cb3-335" aria-hidden="true" tabindex="-1"></a>p_polparty <span class="ot">&lt;-</span> <span class="fu">plot_population_comparison</span>(</span>
<span id="cb3-336"><a href="#cb3-336" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey_data      =</span> survey_data,</span>
<span id="cb3-337"><a href="#cb3-337" aria-hidden="true" tabindex="-1"></a>  <span class="at">benchmarks       =</span> benchmarks,</span>
<span id="cb3-338"><a href="#cb3-338" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable         =</span> <span class="st">"POLPARTY"</span>,</span>
<span id="cb3-339"><a href="#cb3-339" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable_label   =</span> <span class="st">"Party Affiliation"</span>,</span>
<span id="cb3-340"><a href="#cb3-340" aria-hidden="true" tabindex="-1"></a>  <span class="at">benchmark_source =</span> <span class="st">"Gallup 2024"</span></span>
<span id="cb3-341"><a href="#cb3-341" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-342"><a href="#cb3-342" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p_polparty)</span>
<span id="cb3-343"><a href="#cb3-343" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-344"><a href="#cb3-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-345"><a href="#cb3-345" aria-hidden="true" tabindex="-1"></a><span class="in">```{r tbl-pop-polparty-stats}</span></span>
<span id="cb3-346"><a href="#cb3-346" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-pop-polparty-stats</span></span>
<span id="cb3-347"><a href="#cb3-347" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Party Affiliation: Survey vs. Gallup 2024 Proportions with Chi-Square Goodness-of-Fit"</span></span>
<span id="cb3-348"><a href="#cb3-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-349"><a href="#cb3-349" aria-hidden="true" tabindex="-1"></a>ct_polparty <span class="ot">&lt;-</span> <span class="fu">format_pop_table</span>(result_polparty)</span>
<span id="cb3-350"><a href="#cb3-350" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb3-351"><a href="#cb3-351" aria-hidden="true" tabindex="-1"></a>  ct_polparty,</span>
<span id="cb3-352"><a href="#cb3-352" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Party"</span>, <span class="st">"Survey"</span>, <span class="st">"Gallup"</span>, <span class="st">"Difference"</span>),</span>
<span id="cb3-353"><a href="#cb3-353" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="fu">paste0</span>(<span class="fu">fmt_chisq_caption</span>(result_polparty, <span class="st">"Party Affiliation"</span>),</span>
<span id="cb3-354"><a href="#cb3-354" aria-hidden="true" tabindex="-1"></a>                   <span class="st">". Benchmark: Gallup 2024 annual averages (U.S. adults)."</span>)</span>
<span id="cb3-355"><a href="#cb3-355" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-356"><a href="#cb3-356" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-357"><a href="#cb3-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-358"><a href="#cb3-358" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true"}</span>
<span id="cb3-359"><a href="#cb3-359" aria-hidden="true" tabindex="-1"></a>**Party affiliation interpretation:** `r sprintf("χ²(%d) = %.2f, p %s, Cohen's h = %.3f.", result_polparty$df, result_polparty$chisq_stat, ifelse(result_polparty$p_value &lt; .001, "&lt; .001", sprintf("= %.3f", result_polparty$p_value)), result_polparty$cohens_h)` The survey sample's partisan composition is compared against Gallup's 2024 annual averages (28% Republican, 28% Democrat, 43% Independent). Respondents who selected "Other" or "Prefer not to say" are excluded from this comparison. The direction and magnitude of any divergence reflects the organic composition of the CloudResearch Connect panel, as no quota was set on party affiliation. Online survey panels are known to skew somewhat more Democratic/liberal than the general population, though the extent varies by platform.^[*See* Adam J. Berinsky, Gregory A. Huber &amp; Gabriel S. Lenz, *Evaluating Online Labor Markets for Experimental Research: Amazon.com's Mechanical Turk*, 20 **Pol. Analysis** 351, 363 (2012); Kevin J. Mullinix, Thomas J. Leeper, James N. Druckman &amp; Jeremy Freese, *The Generalizability of Survey Experiments*, 2 **J. Experimental Pol. Sci.** 109 (2015).]</span>
<span id="cb3-360"><a href="#cb3-360" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-361"><a href="#cb3-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-362"><a href="#cb3-362" aria-hidden="true" tabindex="-1"></a><span class="fu">### Political Ideology {#sec-pop-libcon}</span></span>
<span id="cb3-363"><a href="#cb3-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-364"><a href="#cb3-364" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb3-365"><a href="#cb3-365" aria-hidden="true" tabindex="-1"></a>**Measurement note:** The survey's five-point LIBCON scale (Very Liberal, Somewhat Liberal, Moderate, Somewhat Conservative, Very Conservative) is collapsed to three categories to match Gallup's published annual breakdown: Liberal (Very Liberal + Somewhat Liberal), Moderate, and Conservative (Somewhat Conservative + Very Conservative). No quota was set on political ideology.</span>
<span id="cb3-366"><a href="#cb3-366" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-367"><a href="#cb3-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-368"><a href="#cb3-368" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fig-pop-libcon}</span></span>
<span id="cb3-369"><a href="#cb3-369" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-pop-libcon</span></span>
<span id="cb3-370"><a href="#cb3-370" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Political ideology: survey sample vs. Gallup 2024 benchmark"</span></span>
<span id="cb3-371"><a href="#cb3-371" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 4.5</span></span>
<span id="cb3-372"><a href="#cb3-372" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 8</span></span>
<span id="cb3-373"><a href="#cb3-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-374"><a href="#cb3-374" aria-hidden="true" tabindex="-1"></a>result_libcon <span class="ot">&lt;-</span> <span class="fu">run_population_chisq</span>(survey_data, benchmarks, <span class="st">"LIBCON"</span>)</span>
<span id="cb3-375"><a href="#cb3-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-376"><a href="#cb3-376" aria-hidden="true" tabindex="-1"></a>p_libcon <span class="ot">&lt;-</span> <span class="fu">plot_population_comparison</span>(</span>
<span id="cb3-377"><a href="#cb3-377" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey_data      =</span> survey_data,</span>
<span id="cb3-378"><a href="#cb3-378" aria-hidden="true" tabindex="-1"></a>  <span class="at">benchmarks       =</span> benchmarks,</span>
<span id="cb3-379"><a href="#cb3-379" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable         =</span> <span class="st">"LIBCON"</span>,</span>
<span id="cb3-380"><a href="#cb3-380" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable_label   =</span> <span class="st">"Political Ideology"</span>,</span>
<span id="cb3-381"><a href="#cb3-381" aria-hidden="true" tabindex="-1"></a>  <span class="at">benchmark_source =</span> <span class="st">"Gallup 2024"</span></span>
<span id="cb3-382"><a href="#cb3-382" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-383"><a href="#cb3-383" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p_libcon)</span>
<span id="cb3-384"><a href="#cb3-384" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-385"><a href="#cb3-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-386"><a href="#cb3-386" aria-hidden="true" tabindex="-1"></a><span class="in">```{r tbl-pop-libcon-stats}</span></span>
<span id="cb3-387"><a href="#cb3-387" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-pop-libcon-stats</span></span>
<span id="cb3-388"><a href="#cb3-388" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Political Ideology: Survey vs. Gallup 2024 Proportions with Chi-Square Goodness-of-Fit"</span></span>
<span id="cb3-389"><a href="#cb3-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-390"><a href="#cb3-390" aria-hidden="true" tabindex="-1"></a>ct_libcon <span class="ot">&lt;-</span> <span class="fu">format_pop_table</span>(result_libcon)</span>
<span id="cb3-391"><a href="#cb3-391" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb3-392"><a href="#cb3-392" aria-hidden="true" tabindex="-1"></a>  ct_libcon,</span>
<span id="cb3-393"><a href="#cb3-393" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Ideology"</span>, <span class="st">"Survey"</span>, <span class="st">"Gallup"</span>, <span class="st">"Difference"</span>),</span>
<span id="cb3-394"><a href="#cb3-394" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="fu">paste0</span>(<span class="fu">fmt_chisq_caption</span>(result_libcon, <span class="st">"Political Ideology"</span>),</span>
<span id="cb3-395"><a href="#cb3-395" aria-hidden="true" tabindex="-1"></a>                   <span class="st">". Benchmark: Gallup 2024 annual averages (U.S. adults)."</span>)</span>
<span id="cb3-396"><a href="#cb3-396" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-397"><a href="#cb3-397" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-398"><a href="#cb3-398" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-399"><a href="#cb3-399" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true"}</span>
<span id="cb3-400"><a href="#cb3-400" aria-hidden="true" tabindex="-1"></a>**Ideology interpretation:** <span class="in">`r sprintf("χ²(%d) = %.2f, p %s, Cohen's h = %.3f.", result_libcon$df, result_libcon$chisq_stat, ifelse(result_libcon$p_value &lt; .001, "&lt; .001", sprintf("= %.3f", result_libcon$p_value)), result_libcon$cohens_h)`</span> The survey sample's ideological distribution is compared against Gallup's 2024 annual averages (37% Conservative, 34% Moderate, 25% Liberal; renormalized to three-category proportions after excluding "Don't know" responses). The observed divergence is consistent with the well-documented liberal skew of opt-in online survey panels, particularly among younger and more-educated participants — both of which characterize this sample (see <span class="co">[</span><span class="ot">§5.4, Education</span><span class="co">](#sec-pop-edu)</span>). As with party affiliation, the study's primary claims rest on internal validity (randomized treatment comparisons) rather than ideological representativeness.</span>
<span id="cb3-401"><a href="#cb3-401" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-402"><a href="#cb3-402" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-403"><a href="#cb3-403" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb3-404"><a href="#cb3-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-405"><a href="#cb3-405" aria-hidden="true" tabindex="-1"></a><span class="fu">## Summary {#sec-pop-summary}</span></span>
<span id="cb3-406"><a href="#cb3-406" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-407"><a href="#cb3-407" aria-hidden="true" tabindex="-1"></a><span class="in">```{r tbl-pop-summary}</span></span>
<span id="cb3-408"><a href="#cb3-408" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-pop-summary</span></span>
<span id="cb3-409"><a href="#cb3-409" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Population Representativeness Summary: Chi-Square Goodness-of-Fit Tests"</span></span>
<span id="cb3-410"><a href="#cb3-410" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-411"><a href="#cb3-411" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine all results</span></span>
<span id="cb3-412"><a href="#cb3-412" aria-hidden="true" tabindex="-1"></a>all_results <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb3-413"><a href="#cb3-413" aria-hidden="true" tabindex="-1"></a>  <span class="at">AGE       =</span> result_age,</span>
<span id="cb3-414"><a href="#cb3-414" aria-hidden="true" tabindex="-1"></a>  <span class="at">GENDER    =</span> result_gender,</span>
<span id="cb3-415"><a href="#cb3-415" aria-hidden="true" tabindex="-1"></a>  <span class="at">HISPLAT   =</span> result_hisplat,</span>
<span id="cb3-416"><a href="#cb3-416" aria-hidden="true" tabindex="-1"></a>  <span class="at">RACE_ONLY =</span> result_race_only,</span>
<span id="cb3-417"><a href="#cb3-417" aria-hidden="true" tabindex="-1"></a>  <span class="at">RACE_ETH  =</span> result_race,</span>
<span id="cb3-418"><a href="#cb3-418" aria-hidden="true" tabindex="-1"></a>  <span class="at">EDU       =</span> result_edu,</span>
<span id="cb3-419"><a href="#cb3-419" aria-hidden="true" tabindex="-1"></a>  <span class="at">INCOME    =</span> result_income,</span>
<span id="cb3-420"><a href="#cb3-420" aria-hidden="true" tabindex="-1"></a>  <span class="at">POLPARTY  =</span> result_polparty,</span>
<span id="cb3-421"><a href="#cb3-421" aria-hidden="true" tabindex="-1"></a>  <span class="at">LIBCON    =</span> result_libcon</span>
<span id="cb3-422"><a href="#cb3-422" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-423"><a href="#cb3-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-424"><a href="#cb3-424" aria-hidden="true" tabindex="-1"></a>summary_tbl <span class="ot">&lt;-</span> <span class="fu">summarize_population_comparisons</span>(all_results)</span>
<span id="cb3-425"><a href="#cb3-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-426"><a href="#cb3-426" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb3-427"><a href="#cb3-427" aria-hidden="true" tabindex="-1"></a>  summary_tbl,</span>
<span id="cb3-428"><a href="#cb3-428" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Variable"</span>, <span class="st">"N"</span>, <span class="st">"χ²"</span>, <span class="st">"df"</span>, <span class="st">"*p*"</span>, <span class="st">"Cohen's *h*"</span>, <span class="st">"Effect Size"</span>),</span>
<span id="cb3-429"><a href="#cb3-429" aria-hidden="true" tabindex="-1"></a>  <span class="at">escape    =</span> <span class="cn">FALSE</span>,</span>
<span id="cb3-430"><a href="#cb3-430" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption   =</span> <span class="fu">paste0</span>(</span>
<span id="cb3-431"><a href="#cb3-431" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Chi-Square Goodness-of-Fit Tests Comparing Survey Sample to Population Benchmarks. "</span>,</span>
<span id="cb3-432"><a href="#cb3-432" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Cohen's h: small &lt; .20, medium .20–.50, large &gt; .50. "</span>,</span>
<span id="cb3-433"><a href="#cb3-433" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Demographic variables (Age–Income): ACS 2023 1-Year Estimates (U.S. Census Bureau). "</span>,</span>
<span id="cb3-434"><a href="#cb3-434" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Political variables (Party Affiliation, Ideology): Gallup 2024 Annual Averages."</span></span>
<span id="cb3-435"><a href="#cb3-435" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-436"><a href="#cb3-436" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-437"><a href="#cb3-437" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-438"><a href="#cb3-438" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-439"><a href="#cb3-439" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true"}</span>
<span id="cb3-440"><a href="#cb3-440" aria-hidden="true" tabindex="-1"></a>**Summary interpretation:** Divergences from population benchmarks fall into three structurally distinct categories.</span>
<span id="cb3-441"><a href="#cb3-441" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-442"><a href="#cb3-442" aria-hidden="true" tabindex="-1"></a>*Quota-controlled variables* (age, gender, race, Hispanic/Latino origin): divergences from the ACS reflect CloudResearch Connect's standard panel preset, not sampling error. Gender is essentially aligned (h = 0.015) because the preset targets 50% female — nearly identical to the ACS. Age diverges modestly (h = 0.119, small) because the preset allocates 33.3% to the 45–59 cohort (vs. 23.2% ACS), producing the observed overrepresentation of that group; the observed age distribution tracks the preset quotas within 0.4 percentage points across all four bins. Race and Hispanic/Latino origin show medium divergences (HISPLAT h = 0.330; RACE_ETH h = 0.207; RACE_ONLY h = 0.296) that follow directly from the preset's symmetric 83.3% White / 8.3% Black / 8.3% Hispanic / 8.3% Other structure — a heuristic that departs substantially from current Census proportions. These racial/ethnic divergences are documented in the pre-registration as a deliberate choice to follow CloudResearch's standard preset for cross-study comparability (OSF: <span class="co">[</span><span class="ot">https://osf.io/snxyt/</span><span class="co">](https://osf.io/snxyt/)</span>).</span>
<span id="cb3-443"><a href="#cb3-443" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-444"><a href="#cb3-444" aria-hidden="true" tabindex="-1"></a>*Uncontrolled demographic variables* (education and income): no quotas were set; distributions reflect the organic composition of the Connect panel. Education shows the largest divergence overall (h = 0.459, approaching large): the sample is heavily college-educated (70.5% Bachelor's or higher vs. 35.7% ACS 25+), with HS-or-less respondents nearly absent (1.5% vs. 36.2%) — a well-documented characteristic of opt-in online survey panels. Note also that the ACS education benchmark covers adults 25+, while the survey targets 18+, modestly amplifying the apparent gap. Income diverges modestly (h = 0.152, small), with the sample concentrated in the $25k–$99.9k range and high earners underrepresented ($150k+: 9.5% vs. 21.5% ACS), consistent with lower participation rates among high-income individuals in paid online surveys.</span>
<span id="cb3-445"><a href="#cb3-445" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-446"><a href="#cb3-446" aria-hidden="true" tabindex="-1"></a>*Political orientation variables* (party affiliation and ideology): benchmarked against Gallup 2024 annual averages rather than ACS (which does not collect political data). No quotas were set on political orientation. Online opt-in panels typically skew liberal and Democratic relative to the general adult population, a well-documented feature of these platforms driven in part by the educational and age composition of panel participants. The political comparisons use a different source population and methodology (Gallup telephone survey vs. ACS census survey) than the demographic variables, so direct effect-size comparisons across the two benchmark sources should be interpreted with appropriate caution.</span>
<span id="cb3-447"><a href="#cb3-447" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-448"><a href="#cb3-448" aria-hidden="true" tabindex="-1"></a>The study's primary claims rest on internal validity — clean randomization between treatment groups (confirmed in Chapter 4) — rather than representational sampling. These comparisons enable readers to assess which subpopulations are and are not well-represented and to calibrate the external generalizability of the findings accordingly.</span>
<span id="cb3-449"><a href="#cb3-449" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb3-450"><a href="#cb3-450" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-451"><a href="#cb3-451" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb3-452"><a href="#cb3-452" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-453"><a href="#cb3-453" aria-hidden="true" tabindex="-1"></a><span class="fu">## Reproducibility Note {#sec-pop-repro}</span></span>
<span id="cb3-454"><a href="#cb3-454" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-455"><a href="#cb3-455" aria-hidden="true" tabindex="-1"></a>The population benchmark data in <span class="in">`data/population/acs-benchmarks.csv`</span> is committed to the repository. This file contains both ACS 2023 benchmarks (demographic variables) and Gallup 2024 annual averages (political orientation variables). Readers who clone the repository can reproduce all analyses in this chapter without a Census API key.</span>
<span id="cb3-456"><a href="#cb3-456" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-457"><a href="#cb3-457" aria-hidden="true" tabindex="-1"></a>To regenerate the benchmark file from the Census API directly:</span>
<span id="cb3-458"><a href="#cb3-458" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-459"><a href="#cb3-459" aria-hidden="true" tabindex="-1"></a><span class="in">```{r fetch-benchmarks, eval=FALSE}</span></span>
<span id="cb3-460"><a href="#cb3-460" aria-hidden="true" tabindex="-1"></a><span class="co"># Requires CENSUS_API_KEY in ~/.Renviron</span></span>
<span id="cb3-461"><a href="#cb3-461" aria-hidden="true" tabindex="-1"></a><span class="co"># Register free at: https://api.census.gov/data/key_signup.html</span></span>
<span id="cb3-462"><a href="#cb3-462" aria-hidden="true" tabindex="-1"></a><span class="co"># Then: usethis::edit_r_environ()  →  add: CENSUS_API_KEY=your_key_here</span></span>
<span id="cb3-463"><a href="#cb3-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-464"><a href="#cb3-464" aria-hidden="true" tabindex="-1"></a><span class="fu">fetch_acs_benchmarks</span>(<span class="at">year =</span> <span class="dv">2023</span>)</span>
<span id="cb3-465"><a href="#cb3-465" aria-hidden="true" tabindex="-1"></a><span class="co"># Writes data/population/acs-benchmarks.csv</span></span>
<span id="cb3-466"><a href="#cb3-466" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-467"><a href="#cb3-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-468"><a href="#cb3-468" aria-hidden="true" tabindex="-1"></a><span class="in">```{r pop-session-info, include=FALSE}</span></span>
<span id="cb3-469"><a href="#cb3-469" aria-hidden="true" tabindex="-1"></a><span class="co"># Verify data availability (diagnostic, not displayed)</span></span>
<span id="cb3-470"><a href="#cb3-470" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">file.exists</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"population"</span>, <span class="st">"acs-benchmarks.csv"</span>)))</span>
<span id="cb3-471"><a href="#cb3-471" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ludist/cc-survey/edit/main/05-population.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/ludist/cc-survey/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>