<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7.3 Educational Use – Creative Commons Recognition and Copyright Infringement Perceptions Survey Experiment</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../_scenarios/ca.html" rel="next">
<link href="../_scenarios/pu.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-df8e7534cb4cb7c4e956089768985eef.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked slimcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../_scenarios/eu.html">7.3 Educational Use</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Creative Commons Recognition and Copyright Infringement Perceptions Survey Experiment</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ludist/cc-survey" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Experimental Design &amp; Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02-codebook.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Codebook &amp; Variable Dictionary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../03-validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Validation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../04-randomization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Randomization Check</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../05-population.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sample v. Population Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../06-brand.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Brand Recognition</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../07-scenarios.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Scenario Analysis Overview</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_scenarios/pd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.1 Public Domain</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_scenarios/pu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.2 Personal Use</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_scenarios/eu.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">7.3 Educational Use</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_scenarios/ca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.4 Commercial Advertising</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_scenarios/ls.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.5 Large Scale Copying</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_scenarios/wn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.6 Wikipedia Image Search</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_scenarios/fs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.7 Filesharing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../08-summaries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Question Summaries</span></span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#scenario-presentation" id="toc-scenario-presentation" class="nav-link active" data-scroll-target="#scenario-presentation">7.3.0 Scenario Presentation</a></li>
  <li><a href="#sec-eu-q1" id="toc-sec-eu-q1" class="nav-link" data-scroll-target="#sec-eu-q1">7.3.1 Q1: Educational Use Risk Perception</a></li>
  <li><a href="#sec-eu-q2" id="toc-sec-eu-q2" class="nav-link" data-scroll-target="#sec-eu-q2">7.3.2 Q2: Perceived Legal Consequences Under Current Law</a></li>
  <li><a href="#sec-eu-q3" id="toc-sec-eu-q3" class="nav-link" data-scroll-target="#sec-eu-q3">7.3.3 Q3: Normative Preferences</a></li>
  <li><a href="#sec-eu-delta" id="toc-sec-eu-delta" class="nav-link" data-scroll-target="#sec-eu-delta">7.3.4 Delta (Q2 - Q3): Law–Preference Gap</a></li>
  <li><a href="#sec-eu-price" id="toc-sec-eu-price" class="nav-link" data-scroll-target="#sec-eu-price">7.3.5 Q4: Educational License Pricing</a></li>
  <li><a href="#sec-eu-summary" id="toc-sec-eu-summary" class="nav-link" data-scroll-target="#sec-eu-summary">7.3.6 Summary</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/ludist/cc-survey/edit/main/_scenarios/eu.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/ludist/cc-survey/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-eu" class="quarto-section-identifier">7.3 Educational Use</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Data Note — B1 Group Substitution
</div>
</div>
<div class="callout-body-container callout-body">
<p>This scenario uses a different group filter than the other six scenarios. Group B was replaced by <strong>Group B1</strong> — a supplemental collection of 97 participants — due to a data quality issue in the original Group B data for this scenario. The analysis filters to Groups <strong>A, B1, and C</strong> (n = 905), excluding Group B entirely.</p>
<p>See <a href="../02-codebook.html#sec-b1">Section 2.1 (Codebook)</a> for full documentation of the B1 substitution.</p>
</div>
</div>
<section id="scenario-presentation" class="level2">
<h2 class="anchored" data-anchor-id="scenario-presentation">7.3.0 Scenario Presentation</h2>
<p>Respondents saw the following scenario. Because this scenario involves a book rather than an image, the instrument is <strong>text-only</strong> — no image was displayed. Only the <strong>caption</strong> beneath the book title varied across conditions.</p>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>An author writes and self-publishes a book of nursery rhymes, “Pretty Pink Piggies.” On the inside of the book’s front cover, they include this notice:</p>
</div>
</div>
</div>
<div id="eu-instrument">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Control (C)</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Short (A)</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false" href="">Full + Primer (B1)</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p>Pretty Pink Piggies © 2018 S. Baker. All Rights Reserved.</p>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>Pretty Pink Piggies © 2018 by S. Baker is licensed under CC BY-NC-SA 4.0</p>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<p>Full + Primer (B1) respondents first reviewed a <strong>CC Education</strong> page explaining all six Creative Commons license types and the CC0 Public Domain Dedication before seeing this scenario.</p>
<p>Pretty Pink Piggies © 2018 by S. Baker is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International</p>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>A commercial publishing company reprints copies of the author’s book and sells 200,000 copies to schools for profit without permission or an agreement with the author. The author’s name remains on the book.</p>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">Q1: Likelihood</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">Q2: Current Law</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-3" role="tab" aria-controls="tabset-2-3" aria-selected="false" href="">Q3: Normative</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-4" role="tab" aria-controls="tabset-2-4" aria-selected="false" href="">Q4: License Price</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<p><em>In your opinion, how likely is the publishing company to face legal consequences for this use?</em> <br>7-point scale: 1 “Extremely unlikely” <em>to</em> 7 “Extremely likely”</p>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<p><em>In your opinion, if the publishing company were sued for these actions, what legal consequences do you think it <strong>would</strong> face?</em> <br>7-point scale: 1 “No consequences” <em>—</em> 4 “Some negative consequences, such as a court order to stop and/or a moderate fine” <em>—</em> 7 “Very negative consequences, such as incarceration and/or a large fine”</p>
</div>
<div id="tabset-2-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-3-tab">
<p><em>In your opinion, what legal consequences <strong>should</strong> the publishing company face for these actions?</em> <br>7-point scale: 1 “No consequences” <em>—</em> 4 “Some negative consequences, such as a court order to stop and/or a moderate fine” <em>—</em> 7 “Very negative consequences, such as incarceration and/or a large fine”</p>
</div>
<div id="tabset-2-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-4-tab">
<p><em>Now imagine that <strong>before</strong> the use described above, the publishing company and the owner of this work agreed on a price for a non-exclusive license. In your opinion, what do you think would be a reasonable price for that license?</em> <br>Open response in US dollars</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Scenario Context
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Legal Context:</strong> This is a <strong>divergent</strong> scenario — the legal outcome changes across conditions. Under the Control’s standard copyright notice, unauthorized mass reproduction and sale is straightforward infringement. Under the treatment conditions’ CC BY-NC-SA 4.0 license, however, the analysis turns on the meaning of “NonCommercial.” The CC BY-NC-SA 4.0 license permits reproduction and redistribution for non-commercial purposes. Educational distribution to schools — even at scale — can fall within the license’s permissions if the use is primarily educational rather than commercial. This ambiguity is precisely the issue litigated in <em>Great Minds v. FedEx Office &amp; Print Services</em> (2019), where the Second Circuit held that the NonCommercial clause focuses on the <em>nature of the use</em>, not the identity of the user. Under that reasoning, a for-profit publisher distributing educational materials to schools could be engaged in a non-commercial use.</p>
<p><strong>Expected Pattern:</strong> Strong treatment effect with the pre-registered ordering C &gt; A &gt; B. Treatment respondents should perceive substantially lower risk than the Control, since the CC license signals permission for educational reuse. Full + Primer (B1) (full-text license + educational primer) should show the strongest reduction.</p>
<p><strong>Design Note:</strong> The scenario describes mass commercial reproduction and sale of a children’s book to schools. The “NonCommercial” element of the CC BY-NC-SA 4.0 license creates legal ambiguity: respondents must weigh whether distributing educational materials to schools for profit is a “commercial” or “non-commercial” use. This tension between commercial scale and educational purpose is central to the scenario’s design.</p>
</div>
</div>
</section>
<section id="sec-eu-q1" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="sec-eu-q1">7.3.1 Q1: Educational Use Risk Perception</h2>
<p>Do CC license symbols reduce perceived risk for educational use?</p>
<div class="cell" data-layout-align="center">
<div id="tbl-eu-q1-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-eu-q1-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Std. Dev.</th>
<th style="text-align: right;">Median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control (C)</td>
<td style="text-align: right;">5.62</td>
<td style="text-align: right;">1.76</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Short (A)</td>
<td style="text-align: right;">6.07 (+8.0%)</td>
<td style="text-align: right;">1.52</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Full + Primer (B1)</td>
<td style="text-align: right;">5.33 (−5.2%)</td>
<td style="text-align: right;">1.98</td>
<td style="text-align: right;">6</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-eu-q1-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Educational Use Q1: Descriptive Statistics by Group
</figcaption>
</figure>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>* <em>p</em> &lt; .05, ** <em>p</em> &lt; .01, *** <em>p</em> &lt; .001</p>
</div></div><div class="cell" data-layout-align="center">
<div id="tbl-eu-q1-vda" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-eu-q1-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: left;">P(1st &gt; 2nd)</th>
<th style="text-align: left;">Effect Size</th>
<th style="text-align: left;">Sig.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">C &gt; A</td>
<td style="text-align: left;"> 46.2%</td>
<td style="text-align: left;">negligible</td>
<td style="text-align: left;">n.s.</td>
</tr>
<tr class="even">
<td style="text-align: left;">C &gt; B</td>
<td style="text-align: left;"> 37.8%</td>
<td style="text-align: left;">small</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A &gt; B</td>
<td style="text-align: left;"> 41.5%</td>
<td style="text-align: left;">small</td>
<td style="text-align: left;">***</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-eu-q1-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Educational Use Q1: Pairwise Effect Sizes
</figcaption>
</figure>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>* <em>p</em> &lt; .05, ** <em>p</em> &lt; .01, *** <em>p</em> &lt; .001<br> n.s. = not significant</p>
</div></div><div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-eu-q1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" width="100%">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-eu-q1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="eu_files/figure-html/fig-eu-q1-1.png" id="fig-eu-q1" class="img-fluid quarto-figure quarto-figure-center anchored figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-eu-q1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1
</figcaption>
</figure>
</div>
</div>
</div>
<p>Educational Use is one of two <strong>divergent</strong> scenarios in the study (alongside Filesharing): the depicted use is infringing under the Control’s standard copyright but non-infringing under the treatment conditions’ CC BY-NC-SA 4.0 license. This divergence makes EU a strong test of treatment effects — well-informed respondents in the treatment groups should recognize that the CC license permits the described educational distribution and perceive substantially lower legal risk than those in the Control.</p>
<p>The results confound the prediction. Instead of the pre-registered C &gt; A &gt; B ordering, Q1 produces <strong>A &gt; C &gt; B1</strong>: Short (A) respondents perceive the <em>highest</em> likelihood of legal consequences (M = 6.07, SD = 1.52), significantly above both the Control (M = 5.62, SD = 1.76) and Full + Primer (B1) (M = 5.33, SD = 1.98). The Kruskal-Wallis test is highly significant (<span class="math inline">\(\chi^2\)</span>(2) = 27.48, <em>p</em> = &lt; .001). Dunn’s post-hoc tests (Holm-adjusted) reveal that the C–A (<em>p</em> &lt; .001) and A–B1 (<em>p</em> &lt; .001) comparisons are significant, while the C–B1 comparison does not reach significance. Pairwise VDA effect sizes are reported in <a href="#tbl-eu-q1-vda" class="quarto-xref">Table&nbsp;<span>2</span></a>.</p>
<p>The counterintuitive finding is that the CC symbol — without accompanying explanation — appears to <em>increase</em> perceived risk rather than reduce it. Only Full + Primer (B1) respondents, who read the full-text license and educational primer, show the lowest risk perception, consistent with more detailed information helping respondents recognize the permissions the CC license grants.</p>
</section>
<section id="sec-eu-q2" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="sec-eu-q2">7.3.2 Q2: Perceived Legal Consequences Under Current Law</h2>
<p>What consequences do respondents believe would follow from unauthorized educational reprinting?</p>
<div class="cell" data-layout-align="center">
<div id="tbl-eu-q2-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-eu-q2-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Std. Dev.</th>
<th style="text-align: right;">Median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control (C)</td>
<td style="text-align: right;">4.91</td>
<td style="text-align: right;">1.58</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Short (A)</td>
<td style="text-align: right;">5.21 (+6.1%)</td>
<td style="text-align: right;">1.39</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Full + Primer (B1)</td>
<td style="text-align: right;">4.31 (−12.2%)</td>
<td style="text-align: right;">1.36</td>
<td style="text-align: right;">4</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-eu-q2-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Educational Use Q2: Descriptive Statistics by Group
</figcaption>
</figure>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>* <em>p</em> &lt; .05, ** <em>p</em> &lt; .01, *** <em>p</em> &lt; .001</p>
</div></div><div class="cell" data-layout-align="center">
<div id="tbl-eu-q2-vda" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-eu-q2-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: left;">P(1st &gt; 2nd)</th>
<th style="text-align: left;">Effect Size</th>
<th style="text-align: left;">Sig.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">C &gt; A</td>
<td style="text-align: left;"> 36.1%</td>
<td style="text-align: left;">small</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">C &gt; B</td>
<td style="text-align: left;"> 31.0%</td>
<td style="text-align: left;">moderate</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A &gt; B</td>
<td style="text-align: left;"> 45.3%</td>
<td style="text-align: left;">negligible</td>
<td style="text-align: left;">*</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-eu-q2-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Educational Use Q2: Pairwise Effect Sizes
</figcaption>
</figure>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>* <em>p</em> &lt; .05, ** <em>p</em> &lt; .01, *** <em>p</em> &lt; .001<br> n.s. = not significant</p>
</div></div><div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-eu-q2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" width="100%">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-eu-q2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="eu_files/figure-html/fig-eu-q2-1.png" id="fig-eu-q2" class="img-fluid quarto-figure quarto-figure-center anchored figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-eu-q2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2
</figcaption>
</figure>
</div>
</div>
</div>
<p>Q2 asks what consequences respondents believe <em>would</em> follow under current law — setting aside the likelihood question to focus on severity. The A &gt; C &gt; B1 pattern holds with all three pairwise comparisons reaching significance (<span class="math inline">\(\chi^2\)</span>(2) = 34.97, <em>p</em> = &lt; .001). Short (A) perceives the harshest consequences (M = 5.21, SD = 1.39), followed by Control (M = 4.91, SD = 1.58), with Full + Primer (B1) perceiving the mildest (M = 4.31, SD = 1.36). Pairwise VDA effect sizes are reported in <a href="#tbl-eu-q2-vda" class="quarto-xref">Table&nbsp;<span>4</span></a>. The pattern is clear: the full-text license communicates permissiveness in a way that the abbreviated CC symbol does not. Respondents shown only “CC BY-NC-SA 4.0” appear to register the presence of a formal licensing regime — reinforcing the sense that the use is <em>governed</em> by legal rules — without absorbing the specific permissions that regime grants.</p>
</section>
<section id="sec-eu-q3" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="sec-eu-q3">7.3.3 Q3: Normative Preferences</h2>
<p>What consequences do respondents believe <em>should</em> follow for educational use? Normative views on educational fair use.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-eu-q3-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-eu-q3-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Std. Dev.</th>
<th style="text-align: right;">Median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control (C)</td>
<td style="text-align: right;">5.04</td>
<td style="text-align: right;">1.61</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Short (A)</td>
<td style="text-align: right;">5.50 (+9.1%)</td>
<td style="text-align: right;">1.36</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Full + Primer (B1)</td>
<td style="text-align: right;">4.52 (−10.3%)</td>
<td style="text-align: right;">1.60</td>
<td style="text-align: right;">5</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-eu-q3-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Educational Use Q3: Descriptive Statistics by Group
</figcaption>
</figure>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>* <em>p</em> &lt; .05, ** <em>p</em> &lt; .01, *** <em>p</em> &lt; .001</p>
</div></div><div class="cell" data-layout-align="center">
<div id="tbl-eu-q3-vda" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-eu-q3-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: left;">P(1st &gt; 2nd)</th>
<th style="text-align: left;">Effect Size</th>
<th style="text-align: left;">Sig.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">C &gt; A</td>
<td style="text-align: left;"> 39.2%</td>
<td style="text-align: left;">small</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">C &gt; B</td>
<td style="text-align: left;"> 31.1%</td>
<td style="text-align: left;">moderate</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A &gt; B</td>
<td style="text-align: left;"> 41.9%</td>
<td style="text-align: left;">small</td>
<td style="text-align: left;">***</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-eu-q3-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Educational Use Q3: Pairwise Effect Sizes
</figcaption>
</figure>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>* <em>p</em> &lt; .05, ** <em>p</em> &lt; .01, *** <em>p</em> &lt; .001<br> n.s. = not significant</p>
</div></div><div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-eu-q3" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" width="100%">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-eu-q3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="eu_files/figure-html/fig-eu-q3-1.png" id="fig-eu-q3" class="img-fluid quarto-figure quarto-figure-center anchored figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-eu-q3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3
</figcaption>
</figure>
</div>
</div>
</div>
<p>Q3 shifts from descriptive to normative: not what consequences <em>would</em> follow, but what <em>should</em> follow. This question produces the strongest between-group effect in the EU scenario (<span class="math inline">\(\chi^2\)</span>(2) = 40.80, <em>p</em> = &lt; .001 — the largest effect size across Q1–Q3). All three pairwise comparisons are significant (see <a href="#tbl-eu-q3-vda" class="quarto-xref">Table&nbsp;<span>6</span></a>).</p>
<p>Short (A) respondents wanted <em>more</em> consequences (M = 5.50, SD = 1.36) than the Control (M = 5.04, SD = 1.61) — the CC symbol paradoxically heightened the perceived wrongfulness of the use. Full + Primer (B1) respondents, who read the full license text, wanted the least severe consequences (M = 4.52, SD = 1.60), but their mean still falls above the scale midpoint. The pattern is consistent: mass commercial reproduction of a children’s book is viewed unfavorably regardless of licensing condition, but the abbreviated CC mark makes it feel <em>worse</em> while the full-text license tempers the judgment.</p>
</section>
<section id="sec-eu-delta" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="sec-eu-delta">7.3.4 Delta (Q2 - Q3): Law–Preference Gap</h2>
<p>Is there a gap between what respondents believe the law says (Q2) and what they believe it should say (Q3)?</p>
<p>Delta = Q2 - Q3. Positive values indicate the law is perceived as stricter than preferred; negative values indicate the law is perceived as more lenient than preferred; zero indicates alignment.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-eu-delta-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-eu-delta-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Std. Dev.</th>
<th style="text-align: right;">Median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control (C)</td>
<td style="text-align: right;">-0.13</td>
<td style="text-align: right;">0.81</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Short (A)</td>
<td style="text-align: right;">-0.29 (−123.1%)</td>
<td style="text-align: right;">0.78</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Full + Primer (B1)</td>
<td style="text-align: right;">-0.21 (−61.5%)</td>
<td style="text-align: right;">1.20</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-eu-delta-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Educational Use Delta: Descriptive Statistics by Group
</figcaption>
</figure>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>* <em>p</em> &lt; .05, ** <em>p</em> &lt; .01, *** <em>p</em> &lt; .001</p>
</div></div><div class="cell" data-layout-align="center">
<div id="tbl-eu-delta-vda" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-eu-delta-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: left;">P(1st &gt; 2nd)</th>
<th style="text-align: left;">Effect Size</th>
<th style="text-align: left;">Sig.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">C &gt; A</td>
<td style="text-align: left;"> 46.7%</td>
<td style="text-align: left;">negligible</td>
<td style="text-align: left;">n.s.</td>
</tr>
<tr class="even">
<td style="text-align: left;">C &gt; B</td>
<td style="text-align: left;"> 50.9%</td>
<td style="text-align: left;">negligible</td>
<td style="text-align: left;">n.s.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A &gt; B</td>
<td style="text-align: left;"> 54.7%</td>
<td style="text-align: left;">negligible</td>
<td style="text-align: left;">*</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-eu-delta-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Educational Use Delta: Pairwise Effect Sizes
</figcaption>
</figure>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>* <em>p</em> &lt; .05, ** <em>p</em> &lt; .01, *** <em>p</em> &lt; .001<br> n.s. = not significant</p>
</div></div><div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-eu-delta" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" width="100%">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-eu-delta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="eu_files/figure-html/fig-eu-delta-1.png" id="fig-eu-delta" class="img-fluid quarto-figure quarto-figure-center anchored figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-eu-delta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4
</figcaption>
</figure>
</div>
</div>
</div>
<p>All three group deltas are negative: Short (A) (-0.29), Full + Primer (B1) (-0.21), and Control (C) (-0.13). Respondents across all conditions believe the law should impose <em>greater</em> consequences for this use than it currently does — the opposite direction from most scenarios, where deltas tend positive (law perceived as too strict). The between-group Kruskal-Wallis test is significant (<span class="math inline">\(\chi^2\)</span>(2) = 7.87, <em>p</em> = 0.020), but only the C–A pairwise comparison reaches significance (see <a href="#tbl-eu-delta-vda" class="quarto-xref">Table&nbsp;<span>8</span></a>). Short (A) respondents show the largest gap between perceived and preferred consequences, consistent with the pattern across Q1–Q3 in which the abbreviated CC symbol heightens the sense of transgression. The small effect size and limited pairwise significance suggest that, while the <em>direction</em> of the law-preference gap is consistent across groups, the <em>magnitude</em> of that gap is not strongly differentiated by treatment condition — all groups want more consequences, and the CC license manipulations do not dramatically change how much more.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-eu-delta-wilcox" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-eu-delta-wilcox-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: right;">V</th>
<th style="text-align: left;">Non-Zero</th>
<th style="text-align: left;">Dir.</th>
<th style="text-align: left;">Sig.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control (C)</td>
<td style="text-align: right;">2380</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">−</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">Short (A)</td>
<td style="text-align: right;">1317</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">−</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Full + Primer (B1)</td>
<td style="text-align: right;">329</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">−</td>
<td style="text-align: left;">*</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-eu-delta-wilcox-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: Educational Use Delta: Wilcoxon Signed-Rank Tests by Group
</figcaption>
</figure>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>* <em>p</em> &lt; .05, ** <em>p</em> &lt; .01, *** <em>p</em> &lt; .001<br> n.s. = not significant</p>
</div></div><p>All three groups’ deltas differ significantly from zero. Short (A) shows the strongest gap, indicating that Short (A) respondents systematically want consequences increased by roughly one full scale point. Control (C) and Full + Primer (B1) both show significant but smaller gaps. That even the full-text license group wants <em>more</em> consequences suggests that the educational reprinting described in this scenario — 200,000 copies sold commercially — strikes respondents as sufficiently exploitative that no amount of licensing information fully assuages their concern. The negative deltas across all conditions stand in sharp contrast to most other scenarios, where respondents perceive the law as <em>too strict</em>. For Educational Use, the combination of mass commercial reproduction and sale to schools triggers a punitive impulse that the CC license — even in its most informative B1 form — cannot fully overcome.</p>
</section>
<section id="sec-eu-price" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="sec-eu-price">7.3.5 Q4: Educational License Pricing</h2>
<p>What do respondents estimate a non-exclusive educational license would cost?</p>
<div class="cell" data-layout-align="center">
<div id="tbl-eu-price-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-eu-price-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Std. Dev.</th>
<th style="text-align: right;">Median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control (C)</td>
<td style="text-align: right;">143999.97</td>
<td style="text-align: right;">511858.70</td>
<td style="text-align: right;">10000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Short (A)</td>
<td style="text-align: right;">117379.89 (−18.5%)</td>
<td style="text-align: right;">329920.58</td>
<td style="text-align: right;">10000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Full + Primer (B1)</td>
<td style="text-align: right;">94028.83 (−34.7%)</td>
<td style="text-align: right;">249532.21</td>
<td style="text-align: right;">10000</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-eu-price-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10: Educational Use Q4: Descriptive Statistics by Group
</figcaption>
</figure>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>* <em>p</em> &lt; .05, ** <em>p</em> &lt; .01, *** <em>p</em> &lt; .001</p>
</div></div><div class="cell" data-layout-align="center">
<div id="tbl-eu-price-vda" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-eu-price-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: left;">P(1st &gt; 2nd)</th>
<th style="text-align: left;">Effect Size</th>
<th style="text-align: left;">Sig.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">C &gt; A</td>
<td style="text-align: left;"> 50.5%</td>
<td style="text-align: left;">negligible</td>
<td style="text-align: left;">n.s.</td>
</tr>
<tr class="even">
<td style="text-align: left;">C &gt; B</td>
<td style="text-align: left;"> 49.5%</td>
<td style="text-align: left;">negligible</td>
<td style="text-align: left;">n.s.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A &gt; B</td>
<td style="text-align: left;"> 48.9%</td>
<td style="text-align: left;">negligible</td>
<td style="text-align: left;">n.s.</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-eu-price-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11: Educational Use Q4: Pairwise Effect Sizes
</figcaption>
</figure>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>* <em>p</em> &lt; .05, ** <em>p</em> &lt; .01, *** <em>p</em> &lt; .001<br> n.s. = not significant</p>
</div></div><div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-eu-price" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" width="100%">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-eu-price-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="eu_files/figure-html/fig-eu-price-1.png" id="fig-eu-price" class="img-fluid quarto-figure quarto-figure-center anchored figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-eu-price-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5
</figcaption>
</figure>
</div>
</div>
</div>
<p>The Kruskal-Wallis test reveals no significant between-group differences in license price estimates (<span class="math inline">\(\chi^2\)</span>(2) = 0.30, <em>p</em> = 0.861). All three group medians converge at $10,000, even as the means spread widely — Control ($144,000), Short (A) ($117,380), and Full + Primer (B1) ($94,029) — driven by extreme right skew from outlier responses. VDA values hover near 0.50 across all pairwise comparisons, confirming the absence of any dominance pattern (see <a href="#tbl-eu-price-vda" class="quarto-xref">Table&nbsp;<span>11</span></a>).</p>
<p>The null result on pricing is noteworthy given the strong treatment effects observed on Q1–Q3. CC license exposure significantly shifts risk perception, perceived consequences, and normative preferences — yet it does <em>not</em> affect respondents’ estimates of the economic value of the use itself. This dissociation suggests that respondents anchor their price estimates on the <em>scale</em> of the described use (200,000 copies sold to schools for profit) rather than on the licensing condition. The commercial magnitude of the transaction dominates respondents’ economic intuition, overriding whatever signaling effect the CC license exerts on perceptions of legal risk and wrongfulness. This pattern is consistent with the broader finding across scenarios that pricing is the question least sensitive to the treatment manipulation.</p>
</section>
<section id="sec-eu-summary" class="level2">
<h2 class="anchored" data-anchor-id="sec-eu-summary">7.3.6 Summary</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Key Findings — Educational Use
</div>
</div>
<div class="callout-body-container callout-body">
<p>Educational Use is a <strong>divergent</strong> scenario: the depicted use — a commercial publisher reprinting a children’s book and selling 200,000 copies to schools — is <strong>infringing</strong> under the Control’s standard copyright notice but <strong>non-infringing</strong> under the treatment conditions’ CC BY-NC-SA 4.0 license. This makes EU one of the study’s strongest tests of treatment effects.</p>
<ol type="1">
<li><p><strong>Reversed ordering: A &gt; C &gt; B1.</strong> Instead of the pre-registered C &gt; A &gt; B pattern, all four ordinal questions produce A &gt; C &gt; B1. Short (A) respondents perceive the <em>highest</em> risk and want the <em>most</em> consequences; Full + Primer (B1) respondents perceive the lowest risk. The abbreviated CC symbol paradoxically <em>heightens</em> perceived transgression rather than signaling permission.</p></li>
<li><p><strong>CC symbol paradox.</strong> Respondents shown only “CC BY-NC-SA 4.0” appear to register the presence of a formal licensing regime — reinforcing the sense that the use is <em>governed</em> by legal rules — without absorbing the specific permissions that regime grants. The CC mark makes unauthorized commercial reproduction feel <em>more</em> wrongful, not less.</p></li>
<li><p><strong>Full + Primer (B1) education effect.</strong> Only Full + Primer (B1) respondents, who read the full-text license and educational primer, show reduced risk perception consistent with the license’s actual permissions. The full-text explanation communicates permissiveness in a way the abbreviated symbol does not, but even Full + Primer (B1) means remain above the scale midpoint across Q1–Q3.</p></li>
<li><p><strong>Negative deltas — respondents want MORE consequences.</strong> All three group deltas are negative, meaning respondents believe the law should impose <em>greater</em> consequences than it currently does. This is the opposite direction from most scenarios. The combination of mass commercial reproduction and sale to schools triggers a punitive impulse that no amount of licensing information fully overcomes.</p></li>
<li><p><strong>Null price result.</strong> No significant between-group differences in license price estimates (<span class="math inline">\(\chi^2\)</span>(2) = 0.30, <em>p</em> = 0.861). Respondents anchor on the commercial scale of the use (200,000 copies), not the licensing condition — pricing is the question least sensitive to the treatment manipulation.</p></li>
<li><p><strong>B1 sample size caveat.</strong> The EU scenario uses Group B1 (n = 97) rather than the original Group B (n = 414). B1 participants completed only the EU scenario, and the smaller sample size reduces statistical power for detecting effects in the B1 condition. Results involving B1 should be interpreted with this limitation in mind.</p></li>
</ol>
</div>
</div>


<!-- -->

</section>

</main> <!-- /main -->
<script>
/*
 * sidebar-toc.js — CC Survey Online Appendix
 *
 * Quarto Book sidebar accordion for within-page sections.
 *
 * Actual Quarto behavior (confirmed from rendered HTML):
 *   - toc-location: left places the TOC as <nav id="TOC"> inside #quarto-sidebar,
 *     AFTER the chapter list. The <ul> has class="collapse" (Bootstrap-hidden).
 *   - There is NO #quarto-sidebar-toc-left element in Quarto 1.8.
 *   - CSS hides the nav#TOC block; this script moves the links to nest under
 *     the active chapter <li>, achieving accordion display.
 *
 * Edge case handled: chapters with a body H1 (e.g. {.unnumbered} intro) produce
 * a TOC where the H1 is the sole top-level link and H2s are nested under it.
 * In that case we skip the H1 (which duplicates the sidebar chapter entry) and
 * promote the nested H2 links instead.
 */
(function () {
  'use strict';

  function injectAuthorLine() {
    // Add author name below the book title/subtitle, above the search bar
    if (document.querySelector('.sidebar-author')) return;

    var sidebar = document.getElementById('quarto-sidebar');
    if (!sidebar) return;

    // Insert after subtitle if present, else after title
    var anchor = sidebar.querySelector('.sidebar-subtitle')
              || sidebar.querySelector('.sidebar-title');
    if (!anchor) return;

    var authorDiv = document.createElement('div');
    authorDiv.className = 'sidebar-author';
    authorDiv.innerHTML = '<span class="sidebar-author-label">inquiry by</span><br>Thomas H. Rousse<br>J.D., Ph.D.';

    // Insert between subtitle/title and search bar (equidistant)
    var search = sidebar.querySelector('#quarto-search');
    if (search) {
      search.parentNode.insertBefore(authorDiv, search);
    } else {
      anchor.parentNode.insertBefore(authorDiv, anchor.nextSibling);
    }
  }

  function injectSections() {
    // 1. Find the active chapter <li> in the sidebar
    var activeLink = document.querySelector('#quarto-sidebar .sidebar-link.active');
    if (!activeLink) return;
    var activeItem = activeLink.closest('li.sidebar-item');
    if (!activeItem) return;

    // 2. Find the TOC nav that Quarto placed inside the sidebar
    var tocNav = document.querySelector('#quarto-sidebar nav#TOC');
    if (!tocNav) return;

    // 3. Get all section links (already depth-filtered by Quarto's toc-depth: 2)
    var allLinks = Array.from(tocNav.querySelectorAll('a[data-scroll-target]'));

    // Keep only top-level links (no grandparent <li>)
    var topLevelLinks = allLinks.filter(function (link) {
      var parentLi = link.closest('li');
      if (!parentLi) return false;
      var grandparentLi = parentLi.parentElement && parentLi.parentElement.closest('li');
      return !grandparentLi;
    });

    // Edge case: body-H1 chapters (e.g. {.unnumbered} intro).
    // The sole top-level link IS the chapter title — injecting it would duplicate
    // the sidebar chapter entry. Detect this and promote the nested H2 links instead.
    var chapterText = activeLink.textContent.replace(/^\d+[\.\s]+/, '').trim();
    if (
      topLevelLinks.length === 1 &&
      topLevelLinks[0].textContent.trim() === chapterText
    ) {
      // Promote one level deeper (the H2s nested under the H1)
      topLevelLinks = allLinks.filter(function (link) {
        var parentLi = link.closest('li');
        if (!parentLi) return false;
        var grandparentLi = parentLi.parentElement && parentLi.parentElement.closest('li');
        if (!grandparentLi) return false;
        var greatGrandparentLi = grandparentLi.parentElement && grandparentLi.parentElement.closest('li');
        return !greatGrandparentLi;
      });
    }

    if (topLevelLinks.length === 0) return;

    // 4. Build the nested section list
    var sectionList = document.createElement('ul');
    sectionList.className = 'sidebar-sections list-unstyled';

    topLevelLinks.forEach(function (link) {
      var li = document.createElement('li');
      li.className = 'sidebar-section-item';
      // Replace nav-link class with our sidebar class; keep data-scroll-target
      link.className = 'sidebar-section-link';
      li.appendChild(link); // move (not clone) to preserve Quarto scroll-tracking refs
      sectionList.appendChild(li);
    });

    // 5. Insert immediately after the active chapter <li>
    activeItem.parentNode.insertBefore(sectionList, activeItem.nextSibling);

    // 6. tocNav is already hidden via CSS; no further action needed
  }

  function init() {
    injectAuthorLine();
    injectSections();
  }

  if (document.readyState === 'complete') {
    init();
  } else {
    window.addEventListener('load', init);
  }
}());
</script>
<script>
/*
 * section-numbering.js — CC Survey Online Appendix
 *
 * Renumbers ALL tables and figures to use section-level numbering:
 *   Table 7.1.1.1 = Chapter 7, Scenario 1, Subsection 1, Table 1
 *   Figure 3.2.1  = Chapter 3, Section 2, Figure 1
 *
 * Works on ALL pages:
 *   - Numbered chapters: reads Quarto's .header-section-number spans
 *   - Unnumbered scenario chapters: parses manual section numbers from
 *     heading text (e.g., "## 7.1.1 Q1: ...")
 *
 * Fixes both same-page AND cross-page cross-reference links.
 * Cross-page xrefs are resolved by fetching the target page, computing
 * its section-level numbering, and patching the link text. Each target
 * page is fetched at most once (results are cached per session).
 *
 * Replaces the original scenario-numbering.html (which only handled
 * 3-level numbering for figures on scenario pages).
 *
 * Runs after DOM load.
 */
document.addEventListener('DOMContentLoaded', function() {

  // ── Shared: compute section-level numbering for a root element ──
  // Returns { elementId: { type: 'Table'|'Figure', number: '6.3.1' } }
  // If mutate=true, also rewrites captions and wraps manual heading
  // numbers in .header-section-number spans (only for the live page).
  function computeNumbering(root, mutate) {
    var nodes = root.querySelectorAll(
      'h1, h2, h3, h4, [id^="tbl-"], [id^="fig-"]'
    );

    var currentSection = '';
    var tblCount = {};
    var figCount = {};
    var map = {};

    nodes.forEach(function(el) {
      var tag = el.tagName;

      // ── Heading: update current section number ───────────────
      if (/^H[1-4]$/i.test(tag)) {
        var numSpan = el.querySelector('.header-section-number');
        if (numSpan) {
          currentSection = numSpan.textContent.trim();
          return;
        }
        var m = el.textContent.trim().match(/^(\d+(?:\.\d+)*)/);
        if (m) {
          currentSection = m[1];
          if (mutate) {
            var secId = el.querySelector('.quarto-section-identifier');
            var target = secId || el;
            var html = target.innerHTML;
            if (html.indexOf('header-section-number') === -1) {
              target.innerHTML = html.replace(
                /^(\d+(?:\.\d+)*)\s*/,
                '<span class="header-section-number">$1</span> '
              );
            }
          }
        }
        return;
      }

      // ── Float container: compute new number ─────────────────
      if (!currentSection) return;

      var cap = el.querySelector('figcaption') || el.querySelector('caption');
      if (!cap) return;

      var id = (el.id || '').toLowerCase();
      var type, counter;
      if (id.startsWith('tbl-')) {
        type = 'Table';
        counter = tblCount;
      } else if (id.startsWith('fig-')) {
        type = 'Figure';
        counter = figCount;
      } else {
        return;
      }

      if (!counter[currentSection]) counter[currentSection] = 0;
      counter[currentSection]++;
      var newNum = currentSection + '.' + counter[currentSection];

      map[el.id] = { type: type, number: newNum };

      if (mutate) {
        var re = new RegExp(
          '(' + type + ')(&#160;|&nbsp;|\\u00A0|\\s)(\\d+(?:\\.\\d+)*)'
        );
        cap.innerHTML = cap.innerHTML.replace(
          re, '<span class="float-label">$1$2' + newNum + '</span>'
        );
        el.setAttribute('data-section-num', newNum);
        el.setAttribute('data-section-type', type);
      }
    });

    return map;
  }

  // ── Helper: update a cross-reference link with new numbering ──
  function patchXrefLink(link, info) {
    var spans = link.querySelectorAll('span');
    if (spans.length > 0) {
      spans[spans.length - 1].textContent = info.number;
    } else {
      link.innerHTML = info.type + '&nbsp;' + info.number;
    }
  }

  // ══════════════════════════════════════════════════════════════
  // 1. Renumber the current page (mutate captions + headings)
  // ══════════════════════════════════════════════════════════════
  var main = document.getElementById('quarto-document-content');
  if (!main) return;

  var localMap = computeNumbering(main, true);

  // ══════════════════════════════════════════════════════════════
  // 2. Fix same-page cross-reference links
  // ══════════════════════════════════════════════════════════════
  document.querySelectorAll('a.quarto-xref').forEach(function(link) {
    var href = link.getAttribute('href');
    if (!href || !href.startsWith('#')) return;

    var targetId = href.substring(1);
    var info = localMap[targetId];
    if (!info) return;

    patchXrefLink(link, info);
  });

  // ══════════════════════════════════════════════════════════════
  // 3. Fix cross-page cross-reference links
  //    Group by target page URL, fetch each once, compute
  //    numbering on the fetched DOM, patch all links to that page.
  // ══════════════════════════════════════════════════════════════
  var crossPageGroups = {};   // pageUrl → [{link, targetId}]

  document.querySelectorAll('a.quarto-xref').forEach(function(link) {
    var href = link.getAttribute('href');
    if (!href || href.startsWith('#')) return;

    var hashIdx = href.indexOf('#');
    if (hashIdx === -1) return;

    var pageUrl  = href.substring(0, hashIdx);
    var targetId = href.substring(hashIdx + 1);

    // Skip if target ID doesn't look like a table/figure
    if (!targetId.startsWith('tbl-') && !targetId.startsWith('fig-')) return;

    if (!crossPageGroups[pageUrl]) crossPageGroups[pageUrl] = [];
    crossPageGroups[pageUrl].push({ link: link, targetId: targetId });
  });

  // Fetch each unique target page and resolve its numbering
  Object.keys(crossPageGroups).forEach(function(pageUrl) {
    fetch(pageUrl)
      .then(function(response) {
        if (!response.ok) throw new Error(response.status);
        return response.text();
      })
      .then(function(html) {
        var parser = new DOMParser();
        var doc = parser.parseFromString(html, 'text/html');
        var remoteMain = doc.getElementById('quarto-document-content');
        if (!remoteMain) return;

        // Compute numbering on the fetched page (read-only, no mutation)
        var remoteMap = computeNumbering(remoteMain, false);

        // Patch all links pointing to this page
        crossPageGroups[pageUrl].forEach(function(entry) {
          var info = remoteMap[entry.targetId];
          if (!info) return;
          patchXrefLink(entry.link, info);
        });
      })
      .catch(function(err) {
        // Graceful degradation: cross-page links keep Quarto-native numbers
        console.warn('[section-numbering] Could not resolve xrefs for '
          + pageUrl + ':', err.message || err);
      });
  });
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../_scenarios/pu.html" class="pagination-link" aria-label="7.2 Personal Use">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">7.2 Personal Use</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../_scenarios/ca.html" class="pagination-link" aria-label="7.4 Commercial Advertising">
        <span class="nav-page-text">7.4 Commercial Advertising</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r setup, include=FALSE}</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"_common.R"</span>))</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu"># 7.3 Educational Use {.unnumbered #sec-eu}</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>::: {.callout-warning}</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data Note --- B1 Group Substitution</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>This scenario uses a different group filter than the other six scenarios. Group B was replaced by **Group B1** --- a supplemental collection of 97 participants --- due to a data quality issue in the original Group B data for this scenario. The analysis filters to Groups **A, B1, and C** (n = 905), excluding Group B entirely.</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>See <span class="co">[</span><span class="ot">Section 2.1 (Codebook)</span><span class="co">](../02-codebook.qmd#sec-b1)</span> for full documentation of the B1 substitution.</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.3.0 Scenario Presentation</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>Respondents saw the following scenario. Because this scenario involves a book rather than an image, the instrument is **text-only** --- no image was displayed. Only the **caption** beneath the book title varied across conditions.</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>::: {.callout-important appearance="simple" icon=false}</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>An author writes and self-publishes a book of nursery rhymes, "Pretty Pink Piggies." On the inside of the book's front cover, they include this notice:</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>::: {#eu-instrument}</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>::: {.panel-tabset}</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="fu">### Control (C)</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>Pretty Pink Piggies <span class="dv">&amp;copy;</span> 2018 S. Baker. All Rights Reserved.</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="fu">### Short (A)</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>Pretty Pink Piggies <span class="dv">&amp;copy;</span> 2018 by S. Baker is licensed under CC BY-NC-SA 4.0</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="fu">### Full + Primer (B1)</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>Full + Primer (B1) respondents first reviewed a **CC Education** page explaining all six Creative Commons license types and the CC0 Public Domain Dedication before seeing this scenario.</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>Pretty Pink Piggies <span class="dv">&amp;copy;</span> 2018 by S. Baker is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>::: {.callout-important appearance="simple" icon=false}</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>A commercial publishing company reprints copies of the author's book and sells 200,000 copies to schools for profit without permission or an agreement with the author. The author's name remains on the book.</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>::: {.panel-tabset}</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a><span class="fu">### Q1: Likelihood</span></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>*In your opinion, how likely is the publishing company to face legal consequences for this use?*</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span>7-point scale: 1 "Extremely unlikely" *to* 7 "Extremely likely"</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="fu">### Q2: Current Law</span></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>*In your opinion, if the publishing company were sued for these actions, what legal consequences do you think it **would** face?*</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span>7-point scale: 1 "No consequences" *---* 4 "Some negative consequences, such as a court order to stop and/or a moderate fine" *---* 7 "Very negative consequences, such as incarceration and/or a large fine"</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a><span class="fu">### Q3: Normative</span></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>*In your opinion, what legal consequences **should** the publishing company face for these actions?*</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span>7-point scale: 1 "No consequences" *---* 4 "Some negative consequences, such as a court order to stop and/or a moderate fine" *---* 7 "Very negative consequences, such as incarceration and/or a large fine"</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="fu">### Q4: License Price</span></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>*Now imagine that **before** the use described above, the publishing company and the owner of this work agreed on a price for a non-exclusive license. In your opinion, what do you think would be a reasonable price for that license?*</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span>Open response in US dollars</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a><span class="fu">## Scenario Context</span></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>**Legal Context:** This is a **divergent** scenario --- the legal outcome changes across conditions. Under the Control's standard copyright notice, unauthorized mass reproduction and sale is straightforward infringement. Under the treatment conditions' CC BY-NC-SA 4.0 license, however, the analysis turns on the meaning of "NonCommercial." The CC BY-NC-SA 4.0 license permits reproduction and redistribution for non-commercial purposes. Educational distribution to schools --- even at scale --- can fall within the license's permissions if the use is primarily educational rather than commercial. This ambiguity is precisely the issue litigated in *Great Minds v. FedEx Office &amp; Print Services* (2019), where the Second Circuit held that the NonCommercial clause focuses on the *nature of the use*, not the identity of the user. Under that reasoning, a for-profit publisher distributing educational materials to schools could be engaged in a non-commercial use.</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>**Expected Pattern:** Strong treatment effect with the pre-registered ordering C &gt; A &gt; B. Treatment respondents should perceive substantially lower risk than the Control, since the CC license signals permission for educational reuse. Full + Primer (B1) (full-text license + educational primer) should show the strongest reduction.</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>**Design Note:** The scenario describes mass commercial reproduction and sale of a children's book to schools. The "NonCommercial" element of the CC BY-NC-SA 4.0 license creates legal ambiguity: respondents must weigh whether distributing educational materials to schools for profit is a "commercial" or "non-commercial" use. This tension between commercial scale and educational purpose is central to the scenario's design.</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a><span class="in">```{r eu-analysis}</span></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>eu_results <span class="ot">&lt;-</span> <span class="fu">analyze_full_scenario</span>(</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>  <span class="at">data         =</span> survey_data_eu,</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>  <span class="at">scenario_code =</span> <span class="st">"EU"</span>,</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>  <span class="at">scenario_name =</span> <span class="st">"Educational Use"</span>,</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>  <span class="at">questions    =</span> <span class="fu">c</span>(<span class="st">"q1"</span>, <span class="st">"q2"</span>, <span class="st">"q3"</span>, <span class="st">"delta"</span>, <span class="st">"price"</span>),</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>  <span class="at">export_tiffs =</span> <span class="cn">TRUE</span></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a><span class="in">```{r eu-extract, include=FALSE}</span></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>SC  <span class="ot">&lt;-</span> <span class="st">"EU"</span></span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> survey_data_eu</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> eu_results</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>treat_b <span class="ot">&lt;-</span> <span class="st">"B1"</span></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Q1 ──</span></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>eu_q1_c    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q1, <span class="st">"Control (C)"</span>))</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>eu_q1_a    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q1, <span class="st">"Short (A)"</span>))</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>eu_q1_b    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q1, <span class="st">"Full + Primer (B1)"</span>))</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>eu_q1_sd_c <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q1, <span class="st">"Control (C)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>eu_q1_sd_a <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q1, <span class="st">"Short (A)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>eu_q1_sd_b <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q1, <span class="st">"Full + Primer (B1)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>eu_kw_q1   <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(<span class="fu">as.formula</span>(<span class="fu">paste0</span>(SC, <span class="st">"1 ~ GROUP"</span>)), <span class="at">data =</span> dat)</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Q2 ──</span></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>eu_q2_c    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q2, <span class="st">"Control (C)"</span>))</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>eu_q2_a    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q2, <span class="st">"Short (A)"</span>))</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>eu_q2_b    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q2, <span class="st">"Full + Primer (B1)"</span>))</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>eu_q2_sd_c <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q2, <span class="st">"Control (C)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>eu_q2_sd_a <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q2, <span class="st">"Short (A)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>eu_q2_sd_b <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q2, <span class="st">"Full + Primer (B1)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>eu_kw_q2   <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(<span class="fu">as.formula</span>(<span class="fu">paste0</span>(SC, <span class="st">"2 ~ GROUP"</span>)), <span class="at">data =</span> dat)</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Q3 ──</span></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>eu_q3_c    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q3, <span class="st">"Control (C)"</span>))</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>eu_q3_a    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q3, <span class="st">"Short (A)"</span>))</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>eu_q3_b    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q3, <span class="st">"Full + Primer (B1)"</span>))</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>eu_q3_sd_c <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q3, <span class="st">"Control (C)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>eu_q3_sd_a <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q3, <span class="st">"Short (A)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>eu_q3_sd_b <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q3, <span class="st">"Full + Primer (B1)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>eu_kw_q3   <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(<span class="fu">as.formula</span>(<span class="fu">paste0</span>(SC, <span class="st">"3 ~ GROUP"</span>)), <span class="at">data =</span> dat)</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Delta ──</span></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>eu_delta_c    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>delta, <span class="st">"Control (C)"</span>))</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>eu_delta_a    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>delta, <span class="st">"Short (A)"</span>))</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>eu_delta_b    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>delta, <span class="st">"Full + Primer (B1)"</span>))</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>eu_delta_sd_c <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>delta, <span class="st">"Control (C)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>eu_delta_sd_a <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>delta, <span class="st">"Short (A)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>eu_delta_sd_b <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>delta, <span class="st">"Full + Primer (B1)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>eu_kw_delta   <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(<span class="fu">as.formula</span>(<span class="fu">paste0</span>(SC, <span class="st">"25 ~ GROUP"</span>)), <span class="at">data =</span> dat)</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>eu_wilcox_ps      <span class="ot">&lt;-</span> <span class="fu">sapply</span>(res<span class="sc">$</span>tests<span class="sc">$</span>delta, <span class="cf">function</span>(t) t<span class="sc">$</span>p.value)</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>eu_wilcox_all_sig <span class="ot">&lt;-</span> <span class="fu">all</span>(eu_wilcox_ps <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>eu_wilcox_any_sig <span class="ot">&lt;-</span> <span class="fu">any</span>(eu_wilcox_ps <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Q4 (Price) ──</span></span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>eu_price_md_c <span class="ot">&lt;-</span> <span class="fu">fmtd</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>price, <span class="st">"Control (C)"</span>, <span class="st">"median"</span>))</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>eu_price_md_a <span class="ot">&lt;-</span> <span class="fu">fmtd</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>price, <span class="st">"Short (A)"</span>, <span class="st">"median"</span>))</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>eu_price_md_b <span class="ot">&lt;-</span> <span class="fu">fmtd</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>price, <span class="st">"Full + Primer (B1)"</span>, <span class="st">"median"</span>))</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>eu_price_m_c  <span class="ot">&lt;-</span> <span class="fu">fmtd</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>price, <span class="st">"Control (C)"</span>))</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a>eu_price_m_a  <span class="ot">&lt;-</span> <span class="fu">fmtd</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>price, <span class="st">"Short (A)"</span>))</span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>eu_price_m_b  <span class="ot">&lt;-</span> <span class="fu">fmtd</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>price, <span class="st">"Full + Primer (B1)"</span>))</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a>eu_kw_price   <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.formula</span>(<span class="fu">paste0</span>(SC, <span class="st">"4 ~ GROUP"</span>)),</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> res<span class="sc">$</span>tests<span class="sc">$</span>price</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a><span class="co"># ── VDA pairwise tables ──</span></span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>eu_vda_q1    <span class="ot">&lt;-</span> <span class="fu">format_vda_table</span>(res<span class="sc">$</span>dunn<span class="sc">$</span>q1,    res<span class="sc">$</span>vda<span class="sc">$</span>q1)</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>eu_vda_q2    <span class="ot">&lt;-</span> <span class="fu">format_vda_table</span>(res<span class="sc">$</span>dunn<span class="sc">$</span>q2,    res<span class="sc">$</span>vda<span class="sc">$</span>q2)</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a>eu_vda_q3    <span class="ot">&lt;-</span> <span class="fu">format_vda_table</span>(res<span class="sc">$</span>dunn<span class="sc">$</span>q3,    res<span class="sc">$</span>vda<span class="sc">$</span>q3)</span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>eu_vda_delta <span class="ot">&lt;-</span> <span class="fu">format_vda_table</span>(res<span class="sc">$</span>dunn<span class="sc">$</span>delta, res<span class="sc">$</span>vda<span class="sc">$</span>delta)</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a>eu_vda_price <span class="ot">&lt;-</span> <span class="fu">format_vda_table</span>(res<span class="sc">$</span>dunn<span class="sc">$</span>price, res<span class="sc">$</span>vda<span class="sc">$</span>price)</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.3.1 Q1: Educational Use Risk Perception {#sec-eu-q1}</span></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>Do CC license symbols reduce perceived risk for educational use?</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-eu-q1-stats</span></span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Educational Use Q1: Descriptive Statistics by Group"</span></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">fmt_stats_table</span>(eu_results<span class="sc">$</span>statistics<span class="sc">$</span>q1, <span class="at">dunn =</span> eu_results<span class="sc">$</span>dunn<span class="sc">$</span>q1), <span class="at">align =</span> <span class="st">"lrrr"</span>)</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a>::: {.column-margin}</span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a><span class="sc">\*</span> *p* &lt; .05, \*\* *p* &lt; .01, \*\*\* *p* &lt; .001</span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-eu-q1-vda</span></span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Educational Use Q1: Pairwise Effect Sizes"</span></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(eu_vda_q1)</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a>::: {.column-margin}</span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a><span class="sc">\*</span> *p* &lt; .05, \*\* *p* &lt; .01, \*\*\* *p* &lt; .001<span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span></span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a>n.s. = not significant</span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-eu-q1</span></span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Educational Use Q1: Likelihood of Legal Consequences by Group"</span></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(eu_results<span class="sc">$</span>plots<span class="sc">$</span>q1)</span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a>Educational Use is one of two **divergent** scenarios in the study (alongside Filesharing): the depicted use is infringing under the Control's standard copyright but non-infringing under the treatment conditions' CC BY-NC-SA 4.0 license. This divergence makes EU a strong test of treatment effects --- well-informed respondents in the treatment groups should recognize that the CC license permits the described educational distribution and perceive substantially lower legal risk than those in the Control.</span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a>The results confound the prediction. Instead of the pre-registered C &gt; A &gt; B ordering, Q1 produces **A &gt; C &gt; B1**: Short (A) respondents perceive the *highest* likelihood of legal consequences (M = `r eu_q1_a`, SD = `r eu_q1_sd_a`), significantly above both the Control (M = `r eu_q1_c`, SD = `r eu_q1_sd_c`) and Full + Primer (B1) (M = `r eu_q1_b`, SD = `r eu_q1_sd_b`). The Kruskal-Wallis test is highly significant ($\chi^2$(`r eu_kw_q1$parameter`) = `r fmt(eu_kw_q1$statistic)`, *p* = `r fmtp(eu_kw_q1$p.value)`). Dunn's post-hoc tests (Holm-adjusted) reveal that the C--A (*p* &lt; .001) and A--B1 (*p* &lt; .001) comparisons are significant, while the C--B1 comparison does not reach significance. Pairwise VDA effect sizes are reported in @tbl-eu-q1-vda.</span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a>The counterintuitive finding is that the CC symbol --- without accompanying explanation --- appears to *increase* perceived risk rather than reduce it. Only Full + Primer (B1) respondents, who read the full-text license and educational primer, show the lowest risk perception, consistent with more detailed information helping respondents recognize the permissions the CC license grants.</span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.3.2 Q2: Perceived Legal Consequences Under Current Law {#sec-eu-q2}</span></span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a>What consequences do respondents believe would follow from unauthorized educational reprinting?</span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-eu-q2-stats</span></span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Educational Use Q2: Descriptive Statistics by Group"</span></span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">fmt_stats_table</span>(eu_results<span class="sc">$</span>statistics<span class="sc">$</span>q2, <span class="at">dunn =</span> eu_results<span class="sc">$</span>dunn<span class="sc">$</span>q2), <span class="at">align =</span> <span class="st">"lrrr"</span>)</span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a>::: {.column-margin}</span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a><span class="sc">\*</span> *p* &lt; .05, \*\* *p* &lt; .01, \*\*\* *p* &lt; .001</span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-eu-q2-vda</span></span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Educational Use Q2: Pairwise Effect Sizes"</span></span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(eu_vda_q2)</span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a>::: {.column-margin}</span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a><span class="sc">\*</span> *p* &lt; .05, \*\* *p* &lt; .01, \*\*\* *p* &lt; .001<span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span></span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a>n.s. = not significant</span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-eu-q2</span></span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Educational Use Q2: Estimated Legal Consequences (Current) by Group"</span></span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(eu_results<span class="sc">$</span>plots<span class="sc">$</span>q2)</span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a>Q2 asks what consequences respondents believe *would* follow under current law --- setting aside the likelihood question to focus on severity. The A &gt; C &gt; B1 pattern holds with all three pairwise comparisons reaching significance ($\chi^2$(`r eu_kw_q2$parameter`) = `r fmt(eu_kw_q2$statistic)`, *p* = `r fmtp(eu_kw_q2$p.value)`). Short (A) perceives the harshest consequences (M = `r eu_q2_a`, SD = `r eu_q2_sd_a`), followed by Control (M = `r eu_q2_c`, SD = `r eu_q2_sd_c`), with Full + Primer (B1) perceiving the mildest (M = `r eu_q2_b`, SD = `r eu_q2_sd_b`). Pairwise VDA effect sizes are reported in @tbl-eu-q2-vda. The pattern is clear: the full-text license communicates permissiveness in a way that the abbreviated CC symbol does not. Respondents shown only "CC BY-NC-SA 4.0" appear to register the presence of a formal licensing regime --- reinforcing the sense that the use is *governed* by legal rules --- without absorbing the specific permissions that regime grants.</span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.3.3 Q3: Normative Preferences {#sec-eu-q3}</span></span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a>What consequences do respondents believe *should* follow for educational use? Normative views on educational fair use.</span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-eu-q3-stats</span></span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Educational Use Q3: Descriptive Statistics by Group"</span></span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">fmt_stats_table</span>(eu_results<span class="sc">$</span>statistics<span class="sc">$</span>q3, <span class="at">dunn =</span> eu_results<span class="sc">$</span>dunn<span class="sc">$</span>q3), <span class="at">align =</span> <span class="st">"lrrr"</span>)</span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a>::: {.column-margin}</span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a><span class="sc">\*</span> *p* &lt; .05, \*\* *p* &lt; .01, \*\*\* *p* &lt; .001</span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-eu-q3-vda</span></span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Educational Use Q3: Pairwise Effect Sizes"</span></span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(eu_vda_q3)</span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a>::: {.column-margin}</span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a><span class="sc">\*</span> *p* &lt; .05, \*\* *p* &lt; .01, \*\*\* *p* &lt; .001<span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span></span>
<span id="cb1-284"><a href="#cb1-284" aria-hidden="true" tabindex="-1"></a>n.s. = not significant</span>
<span id="cb1-285"><a href="#cb1-285" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-eu-q3</span></span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb1-293"><a href="#cb1-293" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Educational Use Q3: Estimated Legal Consequences (Preferred) by Group"</span></span>
<span id="cb1-294"><a href="#cb1-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(eu_results<span class="sc">$</span>plots<span class="sc">$</span>q3)</span>
<span id="cb1-296"><a href="#cb1-296" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-297"><a href="#cb1-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-298"><a href="#cb1-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-299"><a href="#cb1-299" aria-hidden="true" tabindex="-1"></a>Q3 shifts from descriptive to normative: not what consequences *would* follow, but what *should* follow. This question produces the strongest between-group effect in the EU scenario ($\chi^2$(`r eu_kw_q3$parameter`) = `r fmt(eu_kw_q3$statistic)`, *p* = <span class="in">`r fmtp(eu_kw_q3$p.value)`</span> --- the largest effect size across Q1--Q3). All three pairwise comparisons are significant (see @tbl-eu-q3-vda).</span>
<span id="cb1-300"><a href="#cb1-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-301"><a href="#cb1-301" aria-hidden="true" tabindex="-1"></a>Short (A) respondents wanted *more* consequences (M = `r eu_q3_a`, SD = `r eu_q3_sd_a`) than the Control (M = `r eu_q3_c`, SD = `r eu_q3_sd_c`) --- the CC symbol paradoxically heightened the perceived wrongfulness of the use. Full + Primer (B1) respondents, who read the full license text, wanted the least severe consequences (M = `r eu_q3_b`, SD = `r eu_q3_sd_b`), but their mean still falls above the scale midpoint. The pattern is consistent: mass commercial reproduction of a children's book is viewed unfavorably regardless of licensing condition, but the abbreviated CC mark makes it feel *worse* while the full-text license tempers the judgment.</span>
<span id="cb1-302"><a href="#cb1-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-303"><a href="#cb1-303" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.3.4 Delta (Q2 - Q3): Law--Preference Gap {#sec-eu-delta}</span></span>
<span id="cb1-304"><a href="#cb1-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-305"><a href="#cb1-305" aria-hidden="true" tabindex="-1"></a>Is there a gap between what respondents believe the law says (Q2) and what they believe it should say (Q3)?</span>
<span id="cb1-306"><a href="#cb1-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-307"><a href="#cb1-307" aria-hidden="true" tabindex="-1"></a>Delta = Q2 - Q3. Positive values indicate the law is perceived as stricter than preferred; negative values indicate the law is perceived as more lenient than preferred; zero indicates alignment.</span>
<span id="cb1-308"><a href="#cb1-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-311"><a href="#cb1-311" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-312"><a href="#cb1-312" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-eu-delta-stats</span></span>
<span id="cb1-313"><a href="#cb1-313" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Educational Use Delta: Descriptive Statistics by Group"</span></span>
<span id="cb1-314"><a href="#cb1-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-315"><a href="#cb1-315" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">fmt_stats_table</span>(eu_results<span class="sc">$</span>statistics<span class="sc">$</span>delta, <span class="at">dunn =</span> eu_results<span class="sc">$</span>dunn<span class="sc">$</span>delta), <span class="at">align =</span> <span class="st">"lrrr"</span>)</span>
<span id="cb1-316"><a href="#cb1-316" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-317"><a href="#cb1-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-318"><a href="#cb1-318" aria-hidden="true" tabindex="-1"></a>::: {.column-margin}</span>
<span id="cb1-319"><a href="#cb1-319" aria-hidden="true" tabindex="-1"></a><span class="sc">\*</span> *p* &lt; .05, \*\* *p* &lt; .01, \*\*\* *p* &lt; .001</span>
<span id="cb1-320"><a href="#cb1-320" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-321"><a href="#cb1-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-324"><a href="#cb1-324" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-325"><a href="#cb1-325" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-eu-delta-vda</span></span>
<span id="cb1-326"><a href="#cb1-326" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Educational Use Delta: Pairwise Effect Sizes"</span></span>
<span id="cb1-327"><a href="#cb1-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-328"><a href="#cb1-328" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(eu_vda_delta)</span>
<span id="cb1-329"><a href="#cb1-329" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-330"><a href="#cb1-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-331"><a href="#cb1-331" aria-hidden="true" tabindex="-1"></a>::: {.column-margin}</span>
<span id="cb1-332"><a href="#cb1-332" aria-hidden="true" tabindex="-1"></a><span class="sc">\*</span> *p* &lt; .05, \*\* *p* &lt; .01, \*\*\* *p* &lt; .001<span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span></span>
<span id="cb1-333"><a href="#cb1-333" aria-hidden="true" tabindex="-1"></a>n.s. = not significant</span>
<span id="cb1-334"><a href="#cb1-334" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-335"><a href="#cb1-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-338"><a href="#cb1-338" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-339"><a href="#cb1-339" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-eu-delta</span></span>
<span id="cb1-340"><a href="#cb1-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-341"><a href="#cb1-341" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb1-342"><a href="#cb1-342" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Educational Use Delta: Current\u2013Preferred Legal Consequences by Group"</span></span>
<span id="cb1-343"><a href="#cb1-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-344"><a href="#cb1-344" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(eu_results<span class="sc">$</span>plots<span class="sc">$</span>delta)</span>
<span id="cb1-345"><a href="#cb1-345" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-346"><a href="#cb1-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-347"><a href="#cb1-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-348"><a href="#cb1-348" aria-hidden="true" tabindex="-1"></a>All three group deltas are negative: Short (A) (<span class="in">`r eu_delta_a`</span>), Full + Primer (B1) (<span class="in">`r eu_delta_b`</span>), and Control (C) (<span class="in">`r eu_delta_c`</span>). Respondents across all conditions believe the law should impose *greater* consequences for this use than it currently does --- the opposite direction from most scenarios, where deltas tend positive (law perceived as too strict). The between-group Kruskal-Wallis test is `r ifelse(eu_kw_delta$p.value &lt; 0.05, "significant", "not significant")` ($\chi^2$(`r eu_kw_delta$parameter`) = `r fmt(eu_kw_delta$statistic)`, *p* = `r fmtp(eu_kw_delta$p.value)`), but only the C--A pairwise comparison reaches significance (see @tbl-eu-delta-vda). Short (A) respondents show the largest gap between perceived and preferred consequences, consistent with the pattern across Q1--Q3 in which the abbreviated CC symbol heightens the sense of transgression. The small effect size and limited pairwise significance suggest that, while the *direction* of the law-preference gap is consistent across groups, the *magnitude* of that gap is not strongly differentiated by treatment condition --- all groups want more consequences, and the CC license manipulations do not dramatically change how much more.</span>
<span id="cb1-349"><a href="#cb1-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-352"><a href="#cb1-352" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-353"><a href="#cb1-353" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-eu-delta-wilcox</span></span>
<span id="cb1-354"><a href="#cb1-354" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Educational Use Delta: Wilcoxon Signed-Rank Tests by Group"</span></span>
<span id="cb1-355"><a href="#cb1-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-356"><a href="#cb1-356" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(eu_results<span class="sc">$</span>tests<span class="sc">$</span>delta)) {</span>
<span id="cb1-357"><a href="#cb1-357" aria-hidden="true" tabindex="-1"></a>  grp_order <span class="ot">&lt;-</span> <span class="fu">intersect</span>(<span class="fu">c</span>(<span class="st">"Control (C)"</span>, <span class="st">"Short (A)"</span>, <span class="st">"Full + Primer (B)"</span>, <span class="st">"Full + Primer (B1)"</span>), <span class="fu">names</span>(eu_results<span class="sc">$</span>tests<span class="sc">$</span>delta))</span>
<span id="cb1-358"><a href="#cb1-358" aria-hidden="true" tabindex="-1"></a>  wilcox_rows <span class="ot">&lt;-</span> <span class="fu">lapply</span>(grp_order, <span class="cf">function</span>(grp) {</span>
<span id="cb1-359"><a href="#cb1-359" aria-hidden="true" tabindex="-1"></a>    tr <span class="ot">&lt;-</span> eu_results<span class="sc">$</span>tests<span class="sc">$</span>delta[[grp]]</span>
<span id="cb1-360"><a href="#cb1-360" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(</span>
<span id="cb1-361"><a href="#cb1-361" aria-hidden="true" tabindex="-1"></a>      <span class="at">Group      =</span> grp,</span>
<span id="cb1-362"><a href="#cb1-362" aria-hidden="true" tabindex="-1"></a>      <span class="at">V          =</span> <span class="fu">unname</span>(tr<span class="sc">$</span>statistic),</span>
<span id="cb1-363"><a href="#cb1-363" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Non-Zero</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">ifelse</span>(tr<span class="sc">$</span>p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>),</span>
<span id="cb1-364"><a href="#cb1-364" aria-hidden="true" tabindex="-1"></a>      <span class="at">Dir.       =</span> <span class="fu">ifelse</span>(tr<span class="sc">$</span>estimate <span class="sc">&gt;=</span> <span class="dv">0</span>, <span class="st">"+"</span>, <span class="st">"\u2212"</span>),</span>
<span id="cb1-365"><a href="#cb1-365" aria-hidden="true" tabindex="-1"></a>      <span class="at">Sig.       =</span> <span class="fu">ifelse</span>(tr<span class="sc">$</span>p.value <span class="sc">&lt;</span> <span class="fl">0.001</span>, <span class="st">"***"</span>,</span>
<span id="cb1-366"><a href="#cb1-366" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">ifelse</span>(tr<span class="sc">$</span>p.value <span class="sc">&lt;</span> <span class="fl">0.01</span>, <span class="st">"**"</span>,</span>
<span id="cb1-367"><a href="#cb1-367" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">ifelse</span>(tr<span class="sc">$</span>p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>, <span class="st">"*"</span>, <span class="st">"n.s."</span>))),</span>
<span id="cb1-368"><a href="#cb1-368" aria-hidden="true" tabindex="-1"></a>      <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>,</span>
<span id="cb1-369"><a href="#cb1-369" aria-hidden="true" tabindex="-1"></a>      <span class="at">check.names =</span> <span class="cn">FALSE</span></span>
<span id="cb1-370"><a href="#cb1-370" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-371"><a href="#cb1-371" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb1-372"><a href="#cb1-372" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">do.call</span>(rbind, wilcox_rows), <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-373"><a href="#cb1-373" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-374"><a href="#cb1-374" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-375"><a href="#cb1-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-376"><a href="#cb1-376" aria-hidden="true" tabindex="-1"></a>::: {.column-margin}</span>
<span id="cb1-377"><a href="#cb1-377" aria-hidden="true" tabindex="-1"></a><span class="sc">\*</span> *p* &lt; .05, \*\* *p* &lt; .01, \*\*\* *p* &lt; .001<span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span></span>
<span id="cb1-378"><a href="#cb1-378" aria-hidden="true" tabindex="-1"></a>n.s. = not significant</span>
<span id="cb1-379"><a href="#cb1-379" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-380"><a href="#cb1-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-381"><a href="#cb1-381" aria-hidden="true" tabindex="-1"></a><span class="in">`r if (eu_wilcox_all_sig) "All three groups' deltas differ significantly from zero." else if (eu_wilcox_any_sig) "At least one group's delta differs significantly from zero (see table above)." else "No group's delta differs significantly from zero."`</span> Short (A) shows the strongest gap, indicating that Short (A) respondents systematically want consequences increased by roughly one full scale point. Control (C) and Full + Primer (B1) both show significant but smaller gaps. That even the full-text license group wants *more* consequences suggests that the educational reprinting described in this scenario --- 200,000 copies sold commercially --- strikes respondents as sufficiently exploitative that no amount of licensing information fully assuages their concern. The negative deltas across all conditions stand in sharp contrast to most other scenarios, where respondents perceive the law as *too strict*. For Educational Use, the combination of mass commercial reproduction and sale to schools triggers a punitive impulse that the CC license --- even in its most informative B1 form --- cannot fully overcome.</span>
<span id="cb1-382"><a href="#cb1-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-383"><a href="#cb1-383" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.3.5 Q4: Educational License Pricing {#sec-eu-price}</span></span>
<span id="cb1-384"><a href="#cb1-384" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-385"><a href="#cb1-385" aria-hidden="true" tabindex="-1"></a>What do respondents estimate a non-exclusive educational license would cost?</span>
<span id="cb1-386"><a href="#cb1-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-389"><a href="#cb1-389" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-390"><a href="#cb1-390" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-eu-price-stats</span></span>
<span id="cb1-391"><a href="#cb1-391" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Educational Use Q4: Descriptive Statistics by Group"</span></span>
<span id="cb1-392"><a href="#cb1-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-393"><a href="#cb1-393" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">fmt_stats_table</span>(eu_results<span class="sc">$</span>statistics<span class="sc">$</span>price, <span class="at">dunn =</span> eu_results<span class="sc">$</span>dunn<span class="sc">$</span>price), <span class="at">align =</span> <span class="st">"lrrr"</span>)</span>
<span id="cb1-394"><a href="#cb1-394" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-395"><a href="#cb1-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-396"><a href="#cb1-396" aria-hidden="true" tabindex="-1"></a>::: {.column-margin}</span>
<span id="cb1-397"><a href="#cb1-397" aria-hidden="true" tabindex="-1"></a><span class="sc">\*</span> *p* &lt; .05, \*\* *p* &lt; .01, \*\*\* *p* &lt; .001</span>
<span id="cb1-398"><a href="#cb1-398" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-399"><a href="#cb1-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-402"><a href="#cb1-402" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-403"><a href="#cb1-403" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-eu-price-vda</span></span>
<span id="cb1-404"><a href="#cb1-404" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Educational Use Q4: Pairwise Effect Sizes"</span></span>
<span id="cb1-405"><a href="#cb1-405" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-406"><a href="#cb1-406" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(eu_vda_price)</span>
<span id="cb1-407"><a href="#cb1-407" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-408"><a href="#cb1-408" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-409"><a href="#cb1-409" aria-hidden="true" tabindex="-1"></a>::: {.column-margin}</span>
<span id="cb1-410"><a href="#cb1-410" aria-hidden="true" tabindex="-1"></a><span class="sc">\*</span> *p* &lt; .05, \*\* *p* &lt; .01, \*\*\* *p* &lt; .001<span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span></span>
<span id="cb1-411"><a href="#cb1-411" aria-hidden="true" tabindex="-1"></a>n.s. = not significant</span>
<span id="cb1-412"><a href="#cb1-412" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-413"><a href="#cb1-413" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-416"><a href="#cb1-416" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-417"><a href="#cb1-417" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-eu-price</span></span>
<span id="cb1-418"><a href="#cb1-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-419"><a href="#cb1-419" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb1-420"><a href="#cb1-420" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Educational Use Q4: License Price Estimate by Group"</span></span>
<span id="cb1-421"><a href="#cb1-421" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-422"><a href="#cb1-422" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(eu_results<span class="sc">$</span>plots<span class="sc">$</span>price)</span>
<span id="cb1-423"><a href="#cb1-423" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-424"><a href="#cb1-424" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-425"><a href="#cb1-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-426"><a href="#cb1-426" aria-hidden="true" tabindex="-1"></a>The Kruskal-Wallis test reveals no significant between-group differences in license price estimates ($\chi^2$(<span class="in">`r eu_kw_price$parameter`</span>) = <span class="in">`r fmt(eu_kw_price$statistic)`</span>, *p* = <span class="in">`r fmtp(eu_kw_price$p.value)`</span>). All three group medians converge at <span class="in">`r eu_price_md_c`</span>, even as the means spread widely --- Control (<span class="in">`r eu_price_m_c`</span>), Short (A) (<span class="in">`r eu_price_m_a`</span>), and Full + Primer (B1) (<span class="in">`r eu_price_m_b`</span>) --- driven by extreme right skew from outlier responses. VDA values hover near 0.50 across all pairwise comparisons, confirming the absence of any dominance pattern (see @tbl-eu-price-vda).</span>
<span id="cb1-427"><a href="#cb1-427" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-428"><a href="#cb1-428" aria-hidden="true" tabindex="-1"></a>The null result on pricing is noteworthy given the strong treatment effects observed on Q1--Q3. CC license exposure significantly shifts risk perception, perceived consequences, and normative preferences --- yet it does *not* affect respondents' estimates of the economic value of the use itself. This dissociation suggests that respondents anchor their price estimates on the *scale* of the described use (200,000 copies sold to schools for profit) rather than on the licensing condition. The commercial magnitude of the transaction dominates respondents' economic intuition, overriding whatever signaling effect the CC license exerts on perceptions of legal risk and wrongfulness. This pattern is consistent with the broader finding across scenarios that pricing is the question least sensitive to the treatment manipulation.</span>
<span id="cb1-429"><a href="#cb1-429" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-430"><a href="#cb1-430" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.3.6 Summary {#sec-eu-summary}</span></span>
<span id="cb1-431"><a href="#cb1-431" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-432"><a href="#cb1-432" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip}</span>
<span id="cb1-433"><a href="#cb1-433" aria-hidden="true" tabindex="-1"></a><span class="fu">## Key Findings --- Educational Use</span></span>
<span id="cb1-434"><a href="#cb1-434" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-435"><a href="#cb1-435" aria-hidden="true" tabindex="-1"></a>Educational Use is a **divergent** scenario: the depicted use --- a commercial publisher reprinting a children's book and selling 200,000 copies to schools --- is **infringing** under the Control's standard copyright notice but **non-infringing** under the treatment conditions' CC BY-NC-SA 4.0 license. This makes EU one of the study's strongest tests of treatment effects.</span>
<span id="cb1-436"><a href="#cb1-436" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-437"><a href="#cb1-437" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Reversed ordering: A &gt; C &gt; B1.** Instead of the pre-registered C &gt; A &gt; B pattern, all four ordinal questions produce A &gt; C &gt; B1. Short (A) respondents perceive the *highest* risk and want the *most* consequences; Full + Primer (B1) respondents perceive the lowest risk. The abbreviated CC symbol paradoxically *heightens* perceived transgression rather than signaling permission.</span>
<span id="cb1-438"><a href="#cb1-438" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-439"><a href="#cb1-439" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**CC symbol paradox.** Respondents shown only "CC BY-NC-SA 4.0" appear to register the presence of a formal licensing regime --- reinforcing the sense that the use is *governed* by legal rules --- without absorbing the specific permissions that regime grants. The CC mark makes unauthorized commercial reproduction feel *more* wrongful, not less.</span>
<span id="cb1-440"><a href="#cb1-440" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-441"><a href="#cb1-441" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Full + Primer (B1) education effect.** Only Full + Primer (B1) respondents, who read the full-text license and educational primer, show reduced risk perception consistent with the license's actual permissions. The full-text explanation communicates permissiveness in a way the abbreviated symbol does not, but even Full + Primer (B1) means remain above the scale midpoint across Q1--Q3.</span>
<span id="cb1-442"><a href="#cb1-442" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-443"><a href="#cb1-443" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Negative deltas --- respondents want MORE consequences.** All three group deltas are negative, meaning respondents believe the law should impose *greater* consequences than it currently does. This is the opposite direction from most scenarios. The combination of mass commercial reproduction and sale to schools triggers a punitive impulse that no amount of licensing information fully overcomes.</span>
<span id="cb1-444"><a href="#cb1-444" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-445"><a href="#cb1-445" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**Null price result.** No significant between-group differences in license price estimates ($\chi^2$(<span class="in">`r eu_kw_price$parameter`</span>) = <span class="in">`r fmt(eu_kw_price$statistic)`</span>, *p* = <span class="in">`r fmtp(eu_kw_price$p.value)`</span>). Respondents anchor on the commercial scale of the use (200,000 copies), not the licensing condition --- pricing is the question least sensitive to the treatment manipulation.</span>
<span id="cb1-446"><a href="#cb1-446" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-447"><a href="#cb1-447" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**B1 sample size caveat.** The EU scenario uses Group B1 (n = 97) rather than the original Group B (n = 414). B1 participants completed only the EU scenario, and the smaller sample size reduces statistical power for detecting effects in the B1 condition. Results involving B1 should be interpreted with this limitation in mind.</span>
<span id="cb1-448"><a href="#cb1-448" aria-hidden="true" tabindex="-1"></a>:::</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ludist/cc-survey/edit/main/_scenarios/eu.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/ludist/cc-survey/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>