<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7.1 Public Domain – Creative Commons Recognition and Copyright Infringement Perceptions Survey Experiment</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../_scenarios/pu.html" rel="next">
<link href="../07-scenarios.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-664e88c2e30ea4214729cb615bfd1c94.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../_scenarios/pd.html">7.1 Public Domain</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Creative Commons Recognition and Copyright Infringement Perceptions Survey Experiment</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ludist/cc-survey" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Experimental Design &amp; Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02-codebook.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Codebook &amp; Variable Dictionary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../03-validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Validation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../04-randomization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Randomization Check</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../05-population.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sample v. Population Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../06-brand.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Brand Recognition</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../07-scenarios.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Factorial Vignette Analysis Overview</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_scenarios/pd.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">7.1 Public Domain</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_scenarios/pu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.2 Personal Use</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_scenarios/eu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.3 Educational Use</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_scenarios/ca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.4 Commercial Advertising</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_scenarios/ls.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.5 Large Scale Copying</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_scenarios/wn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.6 Wikipedia Image Search</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_scenarios/fs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.7 Filesharing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../08-summaries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Question Summaries</span></span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#scenario-presentation" id="toc-scenario-presentation" class="nav-link active" data-scroll-target="#scenario-presentation">7.1.0 Scenario Presentation</a></li>
  <li><a href="#sec-pd-q1" id="toc-sec-pd-q1" class="nav-link" data-scroll-target="#sec-pd-q1">7.1.1 Q1: Likelihood of Legal Consequences</a></li>
  <li><a href="#sec-pd-q2" id="toc-sec-pd-q2" class="nav-link" data-scroll-target="#sec-pd-q2">7.1.2 Q2: Perceived Legal Consequences Under Current Law</a></li>
  <li><a href="#sec-pd-q3" id="toc-sec-pd-q3" class="nav-link" data-scroll-target="#sec-pd-q3">7.1.3 Q3: Normative Preferences</a></li>
  <li><a href="#sec-pd-delta" id="toc-sec-pd-delta" class="nav-link" data-scroll-target="#sec-pd-delta">7.1.4 Delta (Q2 - Q3): Law–Preference Gap</a></li>
  <li><a href="#sec-pd-price" id="toc-sec-pd-price" class="nav-link" data-scroll-target="#sec-pd-price">7.1.5 Q4: License Price Estimate</a></li>
  <li><a href="#sec-pd-summary" id="toc-sec-pd-summary" class="nav-link" data-scroll-target="#sec-pd-summary">7.1.6 Summary</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/ludist/cc-survey/edit/main/_scenarios/pd.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/ludist/cc-survey/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-pd" class="quarto-section-identifier">7.1 Public Domain</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="scenario-presentation" class="level2">
<h2 class="anchored" data-anchor-id="scenario-presentation">7.1.0 Scenario Presentation</h2>
<p>Respondents saw the following vignette. The text and image were identical across conditions; only the <strong>caption</strong> beneath the image varied.</p>
<div class="callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>An advertising executive at a large company wants to use a picture of Planet Earth for an advertisement. The executive goes to NASA.gov and finds the following image and caption and uses only the image in a full-page print advertisement printed in nationally distributed magazines and newspapers.</p>
</div>
</div>
</div>
<div id="pd-instrument">
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Control (C)</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Short (A)</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false" href="">Full + Primer (B)</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../data/survey-images/Vignette Images/The Blue Marble.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
<p>U.S. Government Work</p>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../data/survey-images/Vignette Images/The Blue Marble.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
<p><img src="../data/survey-images/Vignette Images/PD Mark.png" height="20"> The Blue Marble by NASA</p>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<p>Group B respondents first reviewed a <strong>CC Education</strong> page explaining all six Creative Commons license types and the CC0 Public Domain Dedication before seeing this vignette.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../data/survey-images/Vignette Images/The Blue Marble.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
<p><img src="../data/survey-images/Vignette Images/PD Mark.png" height="20"> This work (The Blue Marble, by NASA) is free of known copyright restrictions.</p>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">Q1: Likelihood</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">Q2: Current Law</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-3" role="tab" aria-controls="tabset-2-3" aria-selected="false" href="">Q3: Normative</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-4" role="tab" aria-controls="tabset-2-4" aria-selected="false" href="">Q4: License Price</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<p><em>In your opinion, how likely is the executive’s company to face legal consequences for this use?</em> <br>7-point scale: 1 “Extremely unlikely” to 7 “Extremely likely”</p>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<p><em>In your opinion, if the executive’s company were sued for these actions, what legal consequences do you think it <strong>would</strong> face?</em> <br>7-point scale: 1 “No consequences” — 4 “Some negative consequences, such as a court order to stop and/or a moderate fine” — 7 “Very negative consequences, such as incarceration and/or a large fine”</p>
</div>
<div id="tabset-2-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-3-tab">
<p><em>In your opinion, what legal consequences <strong>should</strong> the executive’s company face for these actions?</em> <br>7-point scale: 1 “No consequences” — 4 “Some negative consequences, such as a court order to stop and/or a moderate fine” — 7 “Very negative consequences, such as incarceration and/or a large fine”</p>
</div>
<div id="tabset-2-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-4-tab">
<p><em>Now imagine that <strong>before</strong> the use described above, the executive’s company and the owner of this work agreed on a price for a non-exclusive license. In your opinion, what do you think would be a reasonable price for that license?</em> <br>Open response in US dollars</p>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Scenario Context
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Legal Context:</strong> Works created by the U.S. federal government are not subject to copyright protection under 17 U.S.C. § 105. The depicted use is <strong>non-infringing across all conditions</strong>. There is no copyright to infringe regardless of whether the caption says “U.S. Government Work,” bears a public domain mark, or explains the absence of copyright restrictions. This makes the Public Domain scenario the study’s <strong>baseline</strong>. Any between-group differences reflect informational framing effects rather than differences in legal status.</p>
<p><strong>Expected Pattern:</strong> Low scores across all groups, with the pre-registered ordering C &gt; A &gt; B. The explicit statement that the work is “free of known copyright restrictions” (Treatment B) should produce the strongest floor effect, driving responses toward the minimum of the scale.</p>
<p><strong>Design Note:</strong> The vignette deliberately does not include attribution credit for the NASA photograph. Some respondents may perceive the omission of attribution as relevant, even though attribution has no bearing on copyright infringement for a public domain work.</p>
</div>
</div>
</section>
<section id="sec-pd-q1" class="level2">
<h2 class="anchored" data-anchor-id="sec-pd-q1">7.1.1 Q1: Likelihood of Legal Consequences</h2>
<p><em>Do respondents correctly perceive that public domain use carries no legal risk?</em></p>
<div class="cell" data-layout-align="center">
<div id="tbl-pd-q1-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-pd-q1-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Std. Dev.</th>
<th style="text-align: right;">Median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control (C)</td>
<td style="text-align: right;">2.95</td>
<td style="text-align: right;">2.06</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Short (A)</td>
<td style="text-align: right;">2.50</td>
<td style="text-align: right;">2.09</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Full + Primer (B)</td>
<td style="text-align: right;">1.47</td>
<td style="text-align: right;">1.31</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-pd-q1-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Public Domain — Q1 descriptive statistics by group.
</figcaption>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-pd-q1-vda" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-pd-q1-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: left;">VDA</th>
<th style="text-align: left;">Effect Size</th>
<th style="text-align: left;">Sig.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control (C) vs.&nbsp;Short (A)</td>
<td style="text-align: left;">0.581</td>
<td style="text-align: left;">small</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">Control (C) vs.&nbsp;Full + Primer (B)</td>
<td style="text-align: left;">0.736</td>
<td style="text-align: left;">large</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Short (A) vs.&nbsp;Full + Primer (B)</td>
<td style="text-align: left;">0.644</td>
<td style="text-align: left;">moderate</td>
<td style="text-align: left;">***</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-pd-q1-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Public Domain — Q1 pairwise VDA effect sizes (Vargha &amp; Delaney 2000).<br>Sig.: *** <em>p</em> &lt; .001, ** <em>p</em> &lt; .01, * <em>p</em> &lt; .05.
</figcaption>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pd-q1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pd-q1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pd_files/figure-html/fig-pd-q1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pd-q1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Public Domain — Q1: Perceived likelihood of legal consequences by treatment group.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Q1 asks respondents how likely the advertising executive’s company is to face legal consequences for using the Blue Marble photograph without permission. Because the photograph is a U.S. government work not subject to copyright the correct answer is that legal consequences are very unlikely regardless of the caption.</p>
<p>The results confirm the pre-registered C &gt; A &gt; B ordering: Control respondents rated the likelihood of legal consequences highest (M = 2.95, SD = 2.06), followed by Treatment A (M = 2.50, SD = 2.09) and Treatment B (M = 1.47, SD = 1.31). Treatment A respondents estimated a likelihood approximately 15% lower than the Control, while Treatment B respondents estimated a likelihood more than 50% lower. As visible in <a href="#fig-pd-q1" class="quarto-xref">Figure&nbsp;<span>1</span></a>, the Kruskal-Wallis test is highly significant with a large effect size, and all pairwise comparisons are significant (<em>p</em> &lt; 0.001). Pairwise VDA effect sizes are reported in <a href="#tbl-pd-q1-vda" class="quarto-xref">Table&nbsp;<span>2</span></a>.</p>
<p>These results demonstrate that the American public generally understands that U.S. government work is free from copyright infringement and, as a result, the perceived likelihood of legal consequences is low. Respondents who are told that a work is in the public domain perceive legal consequences as even less likely, and respondents’ understanding of the likelihood of legal consequences is lowest when an explicit statement that the work is free from copyright restrictions is included. Despite Public Domain being a baseline scenario, the significant between-group differences indicate that even for non-infringing use, the <em>framing</em> of copyright information materially affects risk perception.</p>
</section>
<section id="sec-pd-q2" class="level2">
<h2 class="anchored" data-anchor-id="sec-pd-q2">7.1.2 Q2: Perceived Legal Consequences Under Current Law</h2>
<p><em>What consequences do respondents believe would follow from using a public domain work?</em></p>
<div class="cell" data-layout-align="center">
<div id="tbl-pd-q2-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-pd-q2-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Std. Dev.</th>
<th style="text-align: right;">Median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control (C)</td>
<td style="text-align: right;">2.78</td>
<td style="text-align: right;">1.70</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Short (A)</td>
<td style="text-align: right;">2.37</td>
<td style="text-align: right;">1.77</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Full + Primer (B)</td>
<td style="text-align: right;">1.40</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-pd-q2-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Public Domain — Q2 descriptive statistics by group.
</figcaption>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-pd-q2-vda" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-pd-q2-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: left;">VDA</th>
<th style="text-align: left;">Effect Size</th>
<th style="text-align: left;">Sig.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control (C) vs.&nbsp;Short (A)</td>
<td style="text-align: left;">0.582</td>
<td style="text-align: left;">small</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">Control (C) vs.&nbsp;Full + Primer (B)</td>
<td style="text-align: left;">0.749</td>
<td style="text-align: left;">large</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Short (A) vs.&nbsp;Full + Primer (B)</td>
<td style="text-align: left;">0.652</td>
<td style="text-align: left;">moderate</td>
<td style="text-align: left;">***</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-pd-q2-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Public Domain — Q2 pairwise VDA effect sizes (Vargha &amp; Delaney 2000).<br>Sig.: *** <em>p</em> &lt; .001, ** <em>p</em> &lt; .01, * <em>p</em> &lt; .05.
</figcaption>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pd-q2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pd-q2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pd_files/figure-html/fig-pd-q2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pd-q2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Public Domain — Q2: Perceived legal consequences under current law by treatment group.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Q2 shifts from likelihood to <em>severity</em>: if the executive’s company were sued, what legal consequences do respondents believe would result under the current law? The response scale runs from 1 (“No consequences”) to 7 (“Very negative consequences, such as incarceration and/or a large fine”), with 4 anchored at “Some negative consequences, such as a court order to stop and/or a moderate fine.”</p>
<p>The C &gt; A &gt; B pattern holds with even stronger effect. As reported in <a href="#tbl-pd-q2-stats" class="quarto-xref">Table&nbsp;<span>3</span></a>, the Control mean is 2.78 (SD = 1.70), Treatment A is 2.37 (SD = 1.77), and Treatment B is 1.40 (SD = 1.00). The most explicit explanation of the work’s copyright status produces the lowest estimate of legal consequences: Treatment B’s mean is approximately 50% lower than the Control. The Kruskal-Wallis test returns a large effect size, and all pairwise comparisons are significant (<em>p</em> &lt; 0.001). Pairwise VDA effect sizes are reported in <a href="#tbl-pd-q2-vda" class="quarto-xref">Table&nbsp;<span>4</span></a>.</p>
<p>Treatment B’s violin plot in <a href="#fig-pd-q2" class="quarto-xref">Figure&nbsp;<span>2</span></a> is particularly instructive: the wide base at the bottom of the scale and few selections above it make clear that respondents recognized re-using the public domain work, even for commercial purposes, is not infringement. The explicit statement that a work is “free of known copyright restrictions” collapses uncertainty. Treatment B’s standard deviation (1.00) is roughly 40% smaller than the Control’s (1.70), indicating not just a lower mean but substantially greater consensus among respondents.</p>
</section>
<section id="sec-pd-q3" class="level2">
<h2 class="anchored" data-anchor-id="sec-pd-q3">7.1.3 Q3: Normative Preferences</h2>
<p><em>What consequences do respondents believe</em> should <em>follow from public domain use? For a true public domain scenario, Q3 should closely track Q2.</em></p>
<div class="cell" data-layout-align="center">
<div id="tbl-pd-q3-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-pd-q3-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Std. Dev.</th>
<th style="text-align: right;">Median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control (C)</td>
<td style="text-align: right;">2.60</td>
<td style="text-align: right;">1.67</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Short (A)</td>
<td style="text-align: right;">2.21</td>
<td style="text-align: right;">1.70</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Full + Primer (B)</td>
<td style="text-align: right;">1.38</td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-pd-q3-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Public Domain — Q3 descriptive statistics by group.
</figcaption>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-pd-q3-vda" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-pd-q3-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: left;">VDA</th>
<th style="text-align: left;">Effect Size</th>
<th style="text-align: left;">Sig.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control (C) vs.&nbsp;Short (A)</td>
<td style="text-align: left;">0.576</td>
<td style="text-align: left;">small</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">Control (C) vs.&nbsp;Full + Primer (B)</td>
<td style="text-align: left;">0.721</td>
<td style="text-align: left;">large</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Short (A) vs.&nbsp;Full + Primer (B)</td>
<td style="text-align: left;">0.639</td>
<td style="text-align: left;">small</td>
<td style="text-align: left;">***</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-pd-q3-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Public Domain — Q3 pairwise VDA effect sizes (Vargha &amp; Delaney 2000).<br>Sig.: *** <em>p</em> &lt; .001, ** <em>p</em> &lt; .01, * <em>p</em> &lt; .05.
</figcaption>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pd-q3" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pd-q3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pd_files/figure-html/fig-pd-q3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pd-q3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Public Domain — Q3: Respondent preferences for legal consequences by treatment group.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Q3 uses the same severity scale as Q2 but asks what consequences respondents think <em>should</em> follow, measuring normative preferences rather than perceptions of current law. For the Public Domain scenario, where the use is non-infringing under all conditions, Q3 responses should closely mirror Q2: respondents who believe there are no legal consequences under current law should also believe there should be none.</p>
<p>The results confirm this pattern. Treatment B again anchors the bottom of the scale (M = 1.38, SD = 1.02), approximately 47% lower than the Control (M = 2.60, SD = 1.67). Treatment A falls between (M = 2.21, SD = 1.70), approximately 15% lower than the Control. The ordering C &gt; A &gt; B is maintained, and the means track Q2 closely — explaining that a work is free from copyright restrictions leads respondents to estimate lesser punishment to a moderate degree for Treatment A and to a moderate-to-large degree for Treatment B. The pairwise effect sizes mirror Q2: all comparisons are significant (<em>p</em> &lt; 0.001), with VDA values indicating a consistent treatment gradient (see <a href="#tbl-pd-q3-vda" class="quarto-xref">Table&nbsp;<span>6</span></a>).</p>
<p>The close correspondence between Q2 and Q3 is itself a finding: for the Public Domain scenario, respondents’ perceptions of current law align with their normative preferences. This is exactly what one would expect for a baseline scenario where the use does not infringe. There is no tension between “what the law says” and “what respondents think the law should say.”</p>
</section>
<section id="sec-pd-delta" class="level2">
<h2 class="anchored" data-anchor-id="sec-pd-delta">7.1.4 Delta (Q2 - Q3): Law–Preference Gap</h2>
<p><em>Is there a gap between what respondents believe the law says (Q2) and what they believe it should say (Q3)?</em></p>
<p>Delta = Q2 - Q3. Positive values indicate the law is perceived as stricter than preferred; negative values indicate the law is perceived as more lenient than preferred; zero indicates alignment.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-pd-delta-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-pd-delta-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Std. Dev.</th>
<th style="text-align: right;">Median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control (C)</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Short (A)</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">0.69</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Full + Primer (B)</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.48</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-pd-delta-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Public Domain — Delta descriptive statistics by group.
</figcaption>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-pd-delta-vda" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-pd-delta-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: left;">VDA</th>
<th style="text-align: left;">Effect Size</th>
<th style="text-align: left;">Sig.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control (C) vs.&nbsp;Short (A)</td>
<td style="text-align: left;">0.494</td>
<td style="text-align: left;">negligible</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Control (C) vs.&nbsp;Full + Primer (B)</td>
<td style="text-align: left;">0.521</td>
<td style="text-align: left;">negligible</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Short (A) vs.&nbsp;Full + Primer (B)</td>
<td style="text-align: left;">0.530</td>
<td style="text-align: left;">negligible</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-pd-delta-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Public Domain — Delta pairwise VDA effect sizes (Vargha &amp; Delaney 2000).<br>Sig.: *** <em>p</em> &lt; .001, ** <em>p</em> &lt; .01, * <em>p</em> &lt; .05.
</figcaption>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pd-delta" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pd-delta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pd_files/figure-html/fig-pd-delta-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pd-delta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Public Domain — Delta (Q2 - Q3): gap between perceived law and respondent preferences by treatment group.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Within-group Wilcoxon signed-rank tests</strong>: Does each group’s Delta differ significantly from zero?</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Public Domain — Wilcoxon signed-rank tests: Delta vs.&nbsp;0 by group.</caption>
<colgroup>
<col style="width: 19%">
<col style="width: 18%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Group</th>
<th style="text-align: right;">V</th>
<th style="text-align: right;">p</th>
<th style="text-align: right;">CI_lower</th>
<th style="text-align: right;">CI_upper</th>
<th style="text-align: right;">Pseudomedian</th>
<th style="text-align: left;">Conclusion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(pseudo)median…1</td>
<td style="text-align: left;">Short (A)</td>
<td style="text-align: right;">2886</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: left;">Gap exists</td>
</tr>
<tr class="even">
<td style="text-align: left;">(pseudo)median…2</td>
<td style="text-align: left;">Control (C)</td>
<td style="text-align: right;">5677</td>
<td style="text-align: right;">0.0001</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: left;">Gap exists</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(pseudo)median…3</td>
<td style="text-align: left;">Full + Primer (B)</td>
<td style="text-align: right;">480</td>
<td style="text-align: right;">0.1879</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: left;">No significant gap</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>For the Public Domain baseline, Delta should be near zero: if respondents correctly identify the use as non-infringing, their estimate of what the law <em>is</em> (Q2) and what it <em>should be</em> (Q3) should converge. Comparing the delta between respondents’ estimates of the current law (Q2) versus their own preferences (Q3) reveals no meaningful difference between groups. The between-group Kruskal-Wallis test is not significant (see <a href="#fig-pd-delta" class="quarto-xref">Figure&nbsp;<span>4</span></a>), and the pairwise VDA comparisons are all non-significant.</p>
<p>The Control and Treatment A respondents indicated they would prefer consequences be slightly lower on average. By law, there is no penalty to lower. This confirms that the Public Domain scenario functions as the intended baseline: law and preferences align, and the treatment conditions do not create a gap between how respondents perceive the law and what they think the law should be.</p>
</section>
<section id="sec-pd-price" class="level2">
<h2 class="anchored" data-anchor-id="sec-pd-price">7.1.5 Q4: License Price Estimate</h2>
<p><em>What do respondents estimate a non-exclusive license would cost? For a public domain work, the rational price is $0.</em></p>
<div class="cell" data-layout-align="center">
<div id="tbl-pd-price-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-pd-price-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Std. Dev.</th>
<th style="text-align: right;">Median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control (C)</td>
<td style="text-align: right;">8802.56</td>
<td style="text-align: right;">49050.90</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Short (A)</td>
<td style="text-align: right;">2172.88</td>
<td style="text-align: right;">9474.39</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Full + Primer (B)</td>
<td style="text-align: right;">1041.88</td>
<td style="text-align: right;">5260.55</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-pd-price-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: Public Domain — Q4 price descriptive statistics by group (after outlier removal).
</figcaption>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-pd-price-vda" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-pd-price-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: left;">VDA</th>
<th style="text-align: left;">Effect Size</th>
<th style="text-align: left;">Sig.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control (C) vs.&nbsp;Short (A)</td>
<td style="text-align: left;">0.595</td>
<td style="text-align: left;">small</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">Control (C) vs.&nbsp;Full + Primer (B)</td>
<td style="text-align: left;">0.679</td>
<td style="text-align: left;">moderate</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Short (A) vs.&nbsp;Full + Primer (B)</td>
<td style="text-align: left;">0.579</td>
<td style="text-align: left;">small</td>
<td style="text-align: left;">***</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-pd-price-vda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10: Public Domain — Q4 pairwise VDA effect sizes (Vargha &amp; Delaney 2000).<br>Sig.: *** <em>p</em> &lt; .001, ** <em>p</em> &lt; .01, * <em>p</em> &lt; .05.
</figcaption>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pd-price" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pd-price-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pd_files/figure-html/fig-pd-price-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pd-price-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Public Domain — Q4: Non-exclusive license price estimates by treatment group (top 1% trimmed).
</figcaption>
</figure>
</div>
</div>
</div>
<p>For a public domain work, the economically rational license price is $0. There are no copyright restrictions to license around. Any nonzero price estimates reflect residual confusion about the work’s copyright status or a willingness to pay for convenience, attribution, or perceived quality assurance.</p>
<p>The results follow the C &gt; A &gt; B pattern. As shown in <a href="#fig-pd-price" class="quarto-xref">Figure&nbsp;<span>5</span></a> and <a href="#tbl-pd-price-stats" class="quarto-xref">Table&nbsp;<span>9</span></a>, the means differ by roughly $1,000 between groups, with Treatment B producing the lowest estimates and the Control the highest. The plot makes clear that a large concentration of respondents, particularly in Treatment B, correctly priced the license at $0 (visible as the dense cluster at the bottom of the violin). The between-group differences are statistically significant with all pairwise comparisons reaching significance (<em>p</em> &lt; 0.001). Providing explicit information that works in the public domain do not have copyright resulted in the lowest license price estimate at about a third of the Control. Simply listing the work as public domain had about half the effect of the explicit information treatment. VDA pairwise comparisons are reported in <a href="#tbl-pd-price-vda" class="quarto-xref">Table&nbsp;<span>10</span></a>.</p>
</section>
<section id="sec-pd-summary" class="level2">
<h2 class="anchored" data-anchor-id="sec-pd-summary">7.1.6 Summary</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Key Findings — Public Domain
</div>
</div>
<div class="callout-body-container callout-body">
<p>The Public Domain scenario serves as the study’s baseline. Because the Blue Marble photograph is a U.S. government work not subject to copyright (17 U.S.C. § 105), the depicted use is non-infringing across all treatment conditions. The key findings are:</p>
<ol type="1">
<li><p><strong>Baseline partially confirmed.</strong> All group means fall in the low range of the 7-point scale (1.38–2.95 for Q1–Q3), confirming that respondents generally perceive low legal risk for public domain use. However, significant between-group differences exist across all ordinal questions. The Public Domain scenario is not as “flat” as a pure baseline would predict.</p></li>
<li><p><strong>C &gt; A &gt; B pattern confirmed.</strong> The pre-registered ordering holds consistently across Q1, Q2, Q3, and price. Control respondents perceive the highest risk and estimate the highest license prices; Treatment B respondents perceive the lowest risk and estimate the lowest prices.</p></li>
<li><p><strong>Treatment B produces near-consensus.</strong> The explicit statement that the work is “free of known copyright restrictions” drives Treatment B means to approximately 1.40 on the 7-point scale with standard deviations near 1.00. The narrow distributions in the violin plots indicate strong respondent agreement, not just lower means.</p></li>
<li><p><strong>Law–preference gap is zero.</strong> Delta (Q2 - Q3) is near zero across all groups, and the between-group Kruskal-Wallis test is not significant. This confirms that the Public Domain scenario functions as intended: respondents’ perceptions of current law match their normative preferences. There is no systematic tension between “what the law says” and “what it should say.”</p></li>
<li><p><strong>Residual confusion persists.</strong> Despite non-infringing use, Control and Treatment A respondents still report moderate perceived risk (means of 2.50–2.95), well above the scale minimum of 1. This suggests incomplete public understanding of public domain status. Many respondents in these groups do not fully appreciate that U.S. government works carry no copyright restrictions.</p></li>
<li><p><strong>Framing matters even for clear cases.</strong> The central implication is that <em>how</em> copyright information is presented materially affects risk perception, even when the underlying legal question is straightforward. For a non-infringing baseline, moving from “U.S. Government Work” to an explicit statement of copyright-free status reduces perceived risk by approximately 50% and license price estimates by roughly two-thirds.</p></li>
</ol>
</div>
</div>


<!-- -->

</section>

</main> <!-- /main -->
<script>
/*
 * sidebar-toc.js — CC Survey Online Appendix
 *
 * Quarto Book sidebar accordion for within-page sections.
 *
 * Actual Quarto behavior (confirmed from rendered HTML):
 *   - toc-location: left places the TOC as <nav id="TOC"> inside #quarto-sidebar,
 *     AFTER the chapter list. The <ul> has class="collapse" (Bootstrap-hidden).
 *   - There is NO #quarto-sidebar-toc-left element in Quarto 1.8.
 *   - CSS hides the nav#TOC block; this script moves the links to nest under
 *     the active chapter <li>, achieving accordion display.
 *
 * Edge case handled: chapters with a body H1 (e.g. {.unnumbered} intro) produce
 * a TOC where the H1 is the sole top-level link and H2s are nested under it.
 * In that case we skip the H1 (which duplicates the sidebar chapter entry) and
 * promote the nested H2 links instead.
 */
(function () {
  'use strict';

  function injectAuthorLine() {
    // Add author name below the book title/subtitle, above the search bar
    if (document.querySelector('.sidebar-author')) return;

    var sidebar = document.getElementById('quarto-sidebar');
    if (!sidebar) return;

    // Insert after subtitle if present, else after title
    var anchor = sidebar.querySelector('.sidebar-subtitle')
              || sidebar.querySelector('.sidebar-title');
    if (!anchor) return;

    var authorDiv = document.createElement('div');
    authorDiv.className = 'sidebar-author';
    authorDiv.innerHTML = 'Thomas H. Rousse<br>J.D., Ph.D.';

    // Insert between subtitle/title and search bar (equidistant)
    var search = sidebar.querySelector('#quarto-search');
    if (search) {
      search.parentNode.insertBefore(authorDiv, search);
    } else {
      anchor.parentNode.insertBefore(authorDiv, anchor.nextSibling);
    }
  }

  function injectSections() {
    // 1. Find the active chapter <li> in the sidebar
    var activeLink = document.querySelector('#quarto-sidebar .sidebar-link.active');
    if (!activeLink) return;
    var activeItem = activeLink.closest('li.sidebar-item');
    if (!activeItem) return;

    // 2. Find the TOC nav that Quarto placed inside the sidebar
    var tocNav = document.querySelector('#quarto-sidebar nav#TOC');
    if (!tocNav) return;

    // 3. Get all section links (already depth-filtered by Quarto's toc-depth: 2)
    var allLinks = Array.from(tocNav.querySelectorAll('a[data-scroll-target]'));

    // Keep only top-level links (no grandparent <li>)
    var topLevelLinks = allLinks.filter(function (link) {
      var parentLi = link.closest('li');
      if (!parentLi) return false;
      var grandparentLi = parentLi.parentElement && parentLi.parentElement.closest('li');
      return !grandparentLi;
    });

    // Edge case: body-H1 chapters (e.g. {.unnumbered} intro).
    // The sole top-level link IS the chapter title — injecting it would duplicate
    // the sidebar chapter entry. Detect this and promote the nested H2 links instead.
    var chapterText = activeLink.textContent.replace(/^\d+[\.\s]+/, '').trim();
    if (
      topLevelLinks.length === 1 &&
      topLevelLinks[0].textContent.trim() === chapterText
    ) {
      // Promote one level deeper (the H2s nested under the H1)
      topLevelLinks = allLinks.filter(function (link) {
        var parentLi = link.closest('li');
        if (!parentLi) return false;
        var grandparentLi = parentLi.parentElement && parentLi.parentElement.closest('li');
        if (!grandparentLi) return false;
        var greatGrandparentLi = grandparentLi.parentElement && grandparentLi.parentElement.closest('li');
        return !greatGrandparentLi;
      });
    }

    if (topLevelLinks.length === 0) return;

    // 4. Build the nested section list
    var sectionList = document.createElement('ul');
    sectionList.className = 'sidebar-sections list-unstyled';

    topLevelLinks.forEach(function (link) {
      var li = document.createElement('li');
      li.className = 'sidebar-section-item';
      // Replace nav-link class with our sidebar class; keep data-scroll-target
      link.className = 'sidebar-section-link';
      li.appendChild(link); // move (not clone) to preserve Quarto scroll-tracking refs
      sectionList.appendChild(li);
    });

    // 5. Insert immediately after the active chapter <li>
    activeItem.parentNode.insertBefore(sectionList, activeItem.nextSibling);

    // 6. tocNav is already hidden via CSS; no further action needed
  }

  function init() {
    injectAuthorLine();
    injectSections();
  }

  if (document.readyState === 'complete') {
    init();
  } else {
    window.addEventListener('load', init);
  }
}());
</script>
<script>
/*
 * scenario-numbering.js — CC Survey Online Appendix
 *
 * Renumbers tables, figures, and cross-reference links in unnumbered
 * scenario sub-chapters from bare sequential numbers (Table 1, Figure 1)
 * to 3-level format (Table 7.1.1, Figure 7.1.1).
 *
 * Parent chapter: 07-scenarios.qmd = Chapter 7
 * Sub-chapters: pd=1, pu=2, eu=3, ca=4, ls=5, wn=6, fs=7
 *
 * Runs after DOM load. Only modifies scenario pages.
 */
document.addEventListener('DOMContentLoaded', function() {
  var scenarios = {pd:1, pu:2, eu:3, ca:4, ls:5, wn:6, fs:7};
  var path = window.location.pathname;
  var scenarioIdx = null;

  for (var code in scenarios) {
    if (path.match(new RegExp('[/\\\\]' + code + '\\.html$'))) {
      scenarioIdx = scenarios[code];
      break;
    }
  }

  if (!scenarioIdx) return;

  var prefix = '7.' + scenarioIdx + '.';

  // ── Figure captions ──────────────────────────────────────────
  // Quarto renders: Figure&nbsp;N: caption text
  document.querySelectorAll('figcaption').forEach(function(cap) {
    cap.innerHTML = cap.innerHTML.replace(
      /Figure(&nbsp;|\u00A0|\s)(\d+)(?![\d.])/g,
      function(m, sp, n) { return 'Figure' + sp + prefix + n; }
    );
  });

  // ── Cross-reference links ────────────────────────────────────
  // Quarto renders: <a class="quarto-xref">Table&nbsp;<span>N</span></a>
  // or:             <a class="quarto-xref">Figure&nbsp;<span>N</span></a>
  document.querySelectorAll('a.quarto-xref').forEach(function(link) {
    var spans = link.querySelectorAll('span');
    if (spans.length === 0) return;

    // The last span contains the bare number
    var numSpan = spans[spans.length - 1];
    var num = numSpan.textContent.trim();
    if (/^\d+$/.test(num) && !num.includes('.')) {
      // Check the text before the span is "Table" or "Figure"
      var text = link.textContent;
      if (/^(Table|Figure)/.test(text)) {
        numSpan.textContent = prefix + num;
      }
    }
  });
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../07-scenarios.html" class="pagination-link" aria-label="Factorial Vignette Analysis Overview">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Factorial Vignette Analysis Overview</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../_scenarios/pu.html" class="pagination-link" aria-label="7.2 Personal Use">
        <span class="nav-page-text">7.2 Personal Use</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r setup, include=FALSE}</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"_common.R"</span>))</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu"># 7.1 Public Domain {.unnumbered #sec-pd}</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.1.0 Scenario Presentation</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>Respondents saw the following vignette. The text and image were identical across conditions; only the **caption** beneath the image varied.</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>::: {.callout-important appearance="simple" icon=false}</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>An advertising executive at a large company wants to use a picture of Planet Earth for an advertisement. The executive goes to NASA.gov and finds the following image and caption and uses only the image in a full-page print advertisement printed in nationally distributed magazines and newspapers.</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>::: {#pd-instrument}</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>::: {.panel-tabset}</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="fu">### Control (C)</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="al">![](../data/survey-images/Vignette%20Images/The%20Blue%20Marble.jpg)</span>{fig-align="center" width="50%"}</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>U.S. Government Work</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="fu">### Short (A)</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="al">![](../data/survey-images/Vignette%20Images/The%20Blue%20Marble.jpg)</span>{fig-align="center" width="50%"}</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="al">![](../data/survey-images/Vignette%20Images/PD%20Mark.png)</span>{height="20px"} The Blue Marble by NASA</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="fu">### Full + Primer (B)</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>Group B respondents first reviewed a **CC Education** page explaining all six Creative Commons license types and the CC0 Public Domain Dedication before seeing this vignette.</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="al">![](../data/survey-images/Vignette%20Images/The%20Blue%20Marble.jpg)</span>{fig-align="center" width="50%"}</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="al">![](../data/survey-images/Vignette%20Images/PD%20Mark.png)</span>{height="20px"} This work (The Blue Marble, by NASA) is free of known copyright restrictions.</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>::: {.panel-tabset}</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="fu">### Q1: Likelihood</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>*In your opinion, how likely is the executive's company to face legal consequences for this use?*</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span>7-point scale: 1 "Extremely unlikely" to 7 "Extremely likely"</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a><span class="fu">### Q2: Current Law</span></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>*In your opinion, if the executive's company were sued for these actions, what legal consequences do you think it **would** face?*</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span>7-point scale: 1 "No consequences" — 4 "Some negative consequences, such as a court order to stop and/or a moderate fine" — 7 "Very negative consequences, such as incarceration and/or a large fine"</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a><span class="fu">### Q3: Normative</span></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>*In your opinion, what legal consequences **should** the executive's company face for these actions?*</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span>7-point scale: 1 "No consequences" — 4 "Some negative consequences, such as a court order to stop and/or a moderate fine" — 7 "Very negative consequences, such as incarceration and/or a large fine"</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="fu">### Q4: License Price</span></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>*Now imagine that **before** the use described above, the executive's company and the owner of this work agreed on a price for a non-exclusive license. In your opinion, what do you think would be a reasonable price for that license?*</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span>Open response in US dollars</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a><span class="fu">## Scenario Context</span></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>**Legal Context:** Works created by the U.S. federal government are not subject to copyright protection under 17 U.S.C. § 105. The depicted use is **non-infringing across all conditions**. There is no copyright to infringe regardless of whether the caption says "U.S. Government Work," bears a public domain mark, or explains the absence of copyright restrictions. This makes the Public Domain scenario the study's **baseline**. Any between-group differences reflect informational framing effects rather than differences in legal status.</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>**Expected Pattern:** Low scores across all groups, with the pre-registered ordering C &gt; A &gt; B. The explicit statement that the work is "free of known copyright restrictions" (Treatment B) should produce the strongest floor effect, driving responses toward the minimum of the scale.</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>**Design Note:** The vignette deliberately does not include attribution credit for the NASA photograph. Some respondents may perceive the omission of attribution as relevant, even though attribution has no bearing on copyright infringement for a public domain work.</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a><span class="in">```{r pd-analysis}</span></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>pd_results <span class="ot">&lt;-</span> <span class="fu">analyze_full_scenario</span>(</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>  <span class="at">data         =</span> survey_data,</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>  <span class="at">scenario_code =</span> <span class="st">"PD"</span>,</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>  <span class="at">scenario_name =</span> <span class="st">"Public Domain"</span>,</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>  <span class="at">questions    =</span> <span class="fu">c</span>(<span class="st">"q1"</span>, <span class="st">"q2"</span>, <span class="st">"q3"</span>, <span class="st">"delta"</span>, <span class="st">"price"</span>),</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>  <span class="at">export_tiffs =</span> <span class="cn">TRUE</span></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a><span class="in">```{r pd-extract, include=FALSE}</span></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>SC  <span class="ot">&lt;-</span> <span class="st">"PD"</span></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> survey_data</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> pd_results</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>treat_b <span class="ot">&lt;-</span> <span class="st">"B"</span></span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Q1 ──</span></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>pd_q1_c    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q1, <span class="st">"Control (C)"</span>))</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>pd_q1_a    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q1, <span class="st">"Short (A)"</span>))</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>pd_q1_b    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q1, <span class="st">"Full + Primer (B)"</span>))</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>pd_q1_sd_c <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q1, <span class="st">"Control (C)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>pd_q1_sd_a <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q1, <span class="st">"Short (A)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>pd_q1_sd_b <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q1, <span class="st">"Full + Primer (B)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>pd_kw_q1   <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(<span class="fu">as.formula</span>(<span class="fu">paste0</span>(SC, <span class="st">"1 ~ GROUP"</span>)), <span class="at">data =</span> dat)</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Q2 ──</span></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>pd_q2_c    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q2, <span class="st">"Control (C)"</span>))</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>pd_q2_a    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q2, <span class="st">"Short (A)"</span>))</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>pd_q2_b    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q2, <span class="st">"Full + Primer (B)"</span>))</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>pd_q2_sd_c <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q2, <span class="st">"Control (C)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>pd_q2_sd_a <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q2, <span class="st">"Short (A)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>pd_q2_sd_b <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q2, <span class="st">"Full + Primer (B)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>pd_kw_q2   <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(<span class="fu">as.formula</span>(<span class="fu">paste0</span>(SC, <span class="st">"2 ~ GROUP"</span>)), <span class="at">data =</span> dat)</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Q3 ──</span></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>pd_q3_c    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q3, <span class="st">"Control (C)"</span>))</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>pd_q3_a    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q3, <span class="st">"Short (A)"</span>))</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>pd_q3_b    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q3, <span class="st">"Full + Primer (B)"</span>))</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>pd_q3_sd_c <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q3, <span class="st">"Control (C)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>pd_q3_sd_a <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q3, <span class="st">"Short (A)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>pd_q3_sd_b <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>q3, <span class="st">"Full + Primer (B)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>pd_kw_q3   <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(<span class="fu">as.formula</span>(<span class="fu">paste0</span>(SC, <span class="st">"3 ~ GROUP"</span>)), <span class="at">data =</span> dat)</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Delta ──</span></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>pd_delta_c    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>delta, <span class="st">"Control (C)"</span>))</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>pd_delta_a    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>delta, <span class="st">"Short (A)"</span>))</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>pd_delta_b    <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>delta, <span class="st">"Full + Primer (B)"</span>))</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>pd_delta_sd_c <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>delta, <span class="st">"Control (C)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>pd_delta_sd_a <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>delta, <span class="st">"Short (A)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>pd_delta_sd_b <span class="ot">&lt;-</span> <span class="fu">fmt</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>delta, <span class="st">"Full + Primer (B)"</span>, <span class="st">"sd"</span>))</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>pd_kw_delta   <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(<span class="fu">as.formula</span>(<span class="fu">paste0</span>(SC, <span class="st">"25 ~ GROUP"</span>)), <span class="at">data =</span> dat)</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>pd_wilcox_ps      <span class="ot">&lt;-</span> <span class="fu">sapply</span>(res<span class="sc">$</span>tests<span class="sc">$</span>delta, <span class="cf">function</span>(t) t<span class="sc">$</span>p.value)</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>pd_wilcox_all_sig <span class="ot">&lt;-</span> <span class="fu">all</span>(pd_wilcox_ps <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>pd_wilcox_any_sig <span class="ot">&lt;-</span> <span class="fu">any</span>(pd_wilcox_ps <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Q4 (Price) ──</span></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>pd_price_md_c <span class="ot">&lt;-</span> <span class="fu">fmtd</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>price, <span class="st">"Control (C)"</span>, <span class="st">"median"</span>))</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a>pd_price_md_a <span class="ot">&lt;-</span> <span class="fu">fmtd</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>price, <span class="st">"Short (A)"</span>, <span class="st">"median"</span>))</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>pd_price_md_b <span class="ot">&lt;-</span> <span class="fu">fmtd</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>price, <span class="st">"Full + Primer (B)"</span>, <span class="st">"median"</span>))</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>pd_price_m_c  <span class="ot">&lt;-</span> <span class="fu">fmtd</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>price, <span class="st">"Control (C)"</span>))</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>pd_price_m_a  <span class="ot">&lt;-</span> <span class="fu">fmtd</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>price, <span class="st">"Short (A)"</span>))</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>pd_price_m_b  <span class="ot">&lt;-</span> <span class="fu">fmtd</span>(<span class="fu">.g</span>(res<span class="sc">$</span>statistics<span class="sc">$</span>price, <span class="st">"Full + Primer (B)"</span>))</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>pd_kw_price   <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.formula</span>(<span class="fu">paste0</span>(SC, <span class="st">"4 ~ GROUP"</span>)),</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> res<span class="sc">$</span>tests<span class="sc">$</span>price</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a><span class="co"># ── VDA pairwise tables ──</span></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>pd_vda_q1    <span class="ot">&lt;-</span> <span class="fu">format_vda_table</span>(res<span class="sc">$</span>dunn<span class="sc">$</span>q1,    res<span class="sc">$</span>vda<span class="sc">$</span>q1)</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a>pd_vda_q2    <span class="ot">&lt;-</span> <span class="fu">format_vda_table</span>(res<span class="sc">$</span>dunn<span class="sc">$</span>q2,    res<span class="sc">$</span>vda<span class="sc">$</span>q2)</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>pd_vda_q3    <span class="ot">&lt;-</span> <span class="fu">format_vda_table</span>(res<span class="sc">$</span>dunn<span class="sc">$</span>q3,    res<span class="sc">$</span>vda<span class="sc">$</span>q3)</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>pd_vda_delta <span class="ot">&lt;-</span> <span class="fu">format_vda_table</span>(res<span class="sc">$</span>dunn<span class="sc">$</span>delta, res<span class="sc">$</span>vda<span class="sc">$</span>delta)</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>pd_vda_price <span class="ot">&lt;-</span> <span class="fu">format_vda_table</span>(res<span class="sc">$</span>dunn<span class="sc">$</span>price, res<span class="sc">$</span>vda<span class="sc">$</span>price)</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.1.1 Q1: Likelihood of Legal Consequences {#sec-pd-q1}</span></span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a>*Do respondents correctly perceive that public domain use carries no legal risk?*</span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-pd-q1-stats</span></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Public Domain --- Q1 descriptive statistics by group."</span></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a>  pd_results<span class="sc">$</span>statistics<span class="sc">$</span>q1, <span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Group"</span>, <span class="st">"Mean"</span>, <span class="st">"Std. Dev."</span>, <span class="st">"Median"</span>)</span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-pd-q1-vda</span></span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Public Domain --- Q1 pairwise VDA effect sizes (Vargha &amp; Delaney 2000).&lt;br&gt;Sig.: \\*\\*\\* *p* &lt; .001, \\*\\* *p* &lt; .01, \\* *p* &lt; .05."</span></span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(pd_vda_q1)</span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-pd-q1</span></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Public Domain --- Q1: Perceived likelihood of legal consequences by treatment group."</span></span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(pd_results<span class="sc">$</span>plots<span class="sc">$</span>q1)</span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a>Q1 asks respondents how likely the advertising executive's company is to face legal consequences for using the Blue Marble photograph without permission. Because the photograph is a U.S. government work not subject to copyright the correct answer is that legal consequences are very unlikely regardless of the caption.</span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a>The results confirm the pre-registered C &gt; A &gt; B ordering: Control respondents rated the likelihood of legal consequences highest (M = <span class="in">`r pd_q1_c`</span>, SD = <span class="in">`r pd_q1_sd_c`</span>), followed by Treatment A (M = <span class="in">`r pd_q1_a`</span>, SD = <span class="in">`r pd_q1_sd_a`</span>) and Treatment B (M = <span class="in">`r pd_q1_b`</span>, SD = <span class="in">`r pd_q1_sd_b`</span>). Treatment A respondents estimated a likelihood approximately 15% lower than the Control, while Treatment B respondents estimated a likelihood more than 50% lower. As visible in @fig-pd-q1, the Kruskal-Wallis test is highly significant with a large effect size, and all pairwise comparisons are significant (*p* &lt; 0.001). Pairwise VDA effect sizes are reported in @tbl-pd-q1-vda.</span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>These results demonstrate that the American public generally understands that U.S. government work is free from copyright infringement and, as a result, the perceived likelihood of legal consequences is low. Respondents who are told that a work is in the public domain perceive legal consequences as even less likely, and respondents' understanding of the likelihood of legal consequences is lowest when an explicit statement that the work is free from copyright restrictions is included. Despite Public Domain being a baseline scenario, the significant between-group differences indicate that even for non-infringing use, the *framing* of copyright information materially affects risk perception.</span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.1.2 Q2: Perceived Legal Consequences Under Current Law {#sec-pd-q2}</span></span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>*What consequences do respondents believe would follow from using a public domain work?*</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-pd-q2-stats</span></span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Public Domain --- Q2 descriptive statistics by group."</span></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a>  pd_results<span class="sc">$</span>statistics<span class="sc">$</span>q2, <span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Group"</span>, <span class="st">"Mean"</span>, <span class="st">"Std. Dev."</span>, <span class="st">"Median"</span>)</span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-pd-q2-vda</span></span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Public Domain --- Q2 pairwise VDA effect sizes (Vargha &amp; Delaney 2000).&lt;br&gt;Sig.: \\*\\*\\* *p* &lt; .001, \\*\\* *p* &lt; .01, \\* *p* &lt; .05."</span></span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(pd_vda_q2)</span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-pd-q2</span></span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Public Domain --- Q2: Perceived legal consequences under current law by treatment group."</span></span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(pd_results<span class="sc">$</span>plots<span class="sc">$</span>q2)</span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a>Q2 shifts from likelihood to *severity*: if the executive's company were sued, what legal consequences do respondents believe would result under the current law? The response scale runs from 1 ("No consequences") to 7 ("Very negative consequences, such as incarceration and/or a large fine"), with 4 anchored at "Some negative consequences, such as a court order to stop and/or a moderate fine."</span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a>The C &gt; A &gt; B pattern holds with even stronger effect. As reported in @tbl-pd-q2-stats, the Control mean is <span class="in">`r pd_q2_c`</span> (SD = <span class="in">`r pd_q2_sd_c`</span>), Treatment A is <span class="in">`r pd_q2_a`</span> (SD = <span class="in">`r pd_q2_sd_a`</span>), and Treatment B is <span class="in">`r pd_q2_b`</span> (SD = <span class="in">`r pd_q2_sd_b`</span>). The most explicit explanation of the work's copyright status produces the lowest estimate of legal consequences: Treatment B's mean is approximately 50% lower than the Control. The Kruskal-Wallis test returns a large effect size, and all pairwise comparisons are significant (*p* &lt; 0.001). Pairwise VDA effect sizes are reported in @tbl-pd-q2-vda.</span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a>Treatment B's violin plot in @fig-pd-q2 is particularly instructive: the wide base at the bottom of the scale and few selections above it make clear that respondents recognized re-using the public domain work, even for commercial purposes, is not infringement. The explicit statement that a work is "free of known copyright restrictions" collapses uncertainty. Treatment B's standard deviation (<span class="in">`r pd_q2_sd_b`</span>) is roughly 40% smaller than the Control's (<span class="in">`r pd_q2_sd_c`</span>), indicating not just a lower mean but substantially greater consensus among respondents.</span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.1.3 Q3: Normative Preferences {#sec-pd-q3}</span></span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a>*What consequences do respondents believe* should *follow from public domain use? For a true public domain scenario, Q3 should closely track Q2.*</span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-pd-q3-stats</span></span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Public Domain --- Q3 descriptive statistics by group."</span></span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a>  pd_results<span class="sc">$</span>statistics<span class="sc">$</span>q3, <span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Group"</span>, <span class="st">"Mean"</span>, <span class="st">"Std. Dev."</span>, <span class="st">"Median"</span>)</span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-pd-q3-vda</span></span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Public Domain --- Q3 pairwise VDA effect sizes (Vargha &amp; Delaney 2000).&lt;br&gt;Sig.: \\*\\*\\* *p* &lt; .001, \\*\\* *p* &lt; .01, \\* *p* &lt; .05."</span></span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(pd_vda_q3)</span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-pd-q3</span></span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Public Domain --- Q3: Respondent preferences for legal consequences by treatment group."</span></span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(pd_results<span class="sc">$</span>plots<span class="sc">$</span>q3)</span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a>Q3 uses the same severity scale as Q2 but asks what consequences respondents think *should* follow, measuring normative preferences rather than perceptions of current law. For the Public Domain scenario, where the use is non-infringing under all conditions, Q3 responses should closely mirror Q2: respondents who believe there are no legal consequences under current law should also believe there should be none.</span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a>The results confirm this pattern. Treatment B again anchors the bottom of the scale (M = <span class="in">`r pd_q3_b`</span>, SD = <span class="in">`r pd_q3_sd_b`</span>), approximately 47% lower than the Control (M = <span class="in">`r pd_q3_c`</span>, SD = <span class="in">`r pd_q3_sd_c`</span>). Treatment A falls between (M = <span class="in">`r pd_q3_a`</span>, SD = <span class="in">`r pd_q3_sd_a`</span>), approximately 15% lower than the Control. The ordering C &gt; A &gt; B is maintained, and the means track Q2 closely --- explaining that a work is free from copyright restrictions leads respondents to estimate lesser punishment to a moderate degree for Treatment A and to a moderate-to-large degree for Treatment B. The pairwise effect sizes mirror Q2: all comparisons are significant (*p* &lt; 0.001), with VDA values indicating a consistent treatment gradient (see @tbl-pd-q3-vda).</span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a>The close correspondence between Q2 and Q3 is itself a finding: for the Public Domain scenario, respondents' perceptions of current law align with their normative preferences. This is exactly what one would expect for a baseline scenario where the use does not infringe. There is no tension between "what the law says" and "what respondents think the law should say."</span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.1.4 Delta (Q2 - Q3): Law--Preference Gap {#sec-pd-delta}</span></span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a>*Is there a gap between what respondents believe the law says (Q2) and what they believe it should say (Q3)?*</span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a>Delta = Q2 - Q3. Positive values indicate the law is perceived as stricter than preferred; negative values indicate the law is perceived as more lenient than preferred; zero indicates alignment.</span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-pd-delta-stats</span></span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Public Domain --- Delta descriptive statistics by group."</span></span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a>  pd_results<span class="sc">$</span>statistics<span class="sc">$</span>delta, <span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Group"</span>, <span class="st">"Mean"</span>, <span class="st">"Std. Dev."</span>, <span class="st">"Median"</span>)</span>
<span id="cb1-293"><a href="#cb1-293" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-294"><a href="#cb1-294" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-298"><a href="#cb1-298" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-299"><a href="#cb1-299" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-pd-delta-vda</span></span>
<span id="cb1-300"><a href="#cb1-300" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Public Domain --- Delta pairwise VDA effect sizes (Vargha &amp; Delaney 2000).&lt;br&gt;Sig.: \\*\\*\\* *p* &lt; .001, \\*\\* *p* &lt; .01, \\* *p* &lt; .05."</span></span>
<span id="cb1-301"><a href="#cb1-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-302"><a href="#cb1-302" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(pd_vda_delta)</span>
<span id="cb1-303"><a href="#cb1-303" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-304"><a href="#cb1-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-307"><a href="#cb1-307" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-308"><a href="#cb1-308" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-pd-delta</span></span>
<span id="cb1-309"><a href="#cb1-309" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb1-310"><a href="#cb1-310" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Public Domain --- Delta (Q2 - Q3): gap between perceived law and respondent preferences by treatment group."</span></span>
<span id="cb1-311"><a href="#cb1-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-312"><a href="#cb1-312" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(pd_results<span class="sc">$</span>plots<span class="sc">$</span>delta)</span>
<span id="cb1-313"><a href="#cb1-313" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-314"><a href="#cb1-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-315"><a href="#cb1-315" aria-hidden="true" tabindex="-1"></a>**Within-group Wilcoxon signed-rank tests**: Does each group's Delta differ significantly from zero?</span>
<span id="cb1-316"><a href="#cb1-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-317"><a href="#cb1-317" aria-hidden="true" tabindex="-1"></a><span class="in">```{r pd-delta-wilcox}</span></span>
<span id="cb1-318"><a href="#cb1-318" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(pd_results<span class="sc">$</span>tests<span class="sc">$</span>delta)) {</span>
<span id="cb1-319"><a href="#cb1-319" aria-hidden="true" tabindex="-1"></a>  wilcox_rows <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">names</span>(pd_results<span class="sc">$</span>tests<span class="sc">$</span>delta), <span class="cf">function</span>(grp) {</span>
<span id="cb1-320"><a href="#cb1-320" aria-hidden="true" tabindex="-1"></a>    tr <span class="ot">&lt;-</span> pd_results<span class="sc">$</span>tests<span class="sc">$</span>delta[[grp]]</span>
<span id="cb1-321"><a href="#cb1-321" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(</span>
<span id="cb1-322"><a href="#cb1-322" aria-hidden="true" tabindex="-1"></a>      <span class="at">Group     =</span> grp,</span>
<span id="cb1-323"><a href="#cb1-323" aria-hidden="true" tabindex="-1"></a>      <span class="at">V         =</span> <span class="fu">unname</span>(tr<span class="sc">$</span>statistic),</span>
<span id="cb1-324"><a href="#cb1-324" aria-hidden="true" tabindex="-1"></a>      <span class="at">p         =</span> <span class="fu">round</span>(tr<span class="sc">$</span>p.value, <span class="dv">4</span>),</span>
<span id="cb1-325"><a href="#cb1-325" aria-hidden="true" tabindex="-1"></a>      <span class="at">CI_lower  =</span> <span class="fu">round</span>(tr<span class="sc">$</span>conf.int[<span class="dv">1</span>], <span class="dv">3</span>),</span>
<span id="cb1-326"><a href="#cb1-326" aria-hidden="true" tabindex="-1"></a>      <span class="at">CI_upper  =</span> <span class="fu">round</span>(tr<span class="sc">$</span>conf.int[<span class="dv">2</span>], <span class="dv">3</span>),</span>
<span id="cb1-327"><a href="#cb1-327" aria-hidden="true" tabindex="-1"></a>      <span class="at">Pseudomedian =</span> <span class="fu">round</span>(tr<span class="sc">$</span>estimate, <span class="dv">3</span>),</span>
<span id="cb1-328"><a href="#cb1-328" aria-hidden="true" tabindex="-1"></a>      <span class="at">Conclusion =</span> <span class="fu">ifelse</span>(tr<span class="sc">$</span>p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>, <span class="st">"Gap exists"</span>, <span class="st">"No significant gap"</span>),</span>
<span id="cb1-329"><a href="#cb1-329" aria-hidden="true" tabindex="-1"></a>      <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span></span>
<span id="cb1-330"><a href="#cb1-330" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-331"><a href="#cb1-331" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb1-332"><a href="#cb1-332" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb1-333"><a href="#cb1-333" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">bind_rows</span>(wilcox_rows),</span>
<span id="cb1-334"><a href="#cb1-334" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Public Domain --- Wilcoxon signed-rank tests: Delta vs. 0 by group."</span></span>
<span id="cb1-335"><a href="#cb1-335" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-336"><a href="#cb1-336" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-337"><a href="#cb1-337" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-338"><a href="#cb1-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-339"><a href="#cb1-339" aria-hidden="true" tabindex="-1"></a>For the Public Domain baseline, Delta should be near zero: if respondents correctly identify the use as non-infringing, their estimate of what the law *is* (Q2) and what it *should be* (Q3) should converge. Comparing the delta between respondents' estimates of the current law (Q2) versus their own preferences (Q3) reveals no meaningful difference between groups. The between-group Kruskal-Wallis test is not significant (see @fig-pd-delta), and the pairwise VDA comparisons are all non-significant.</span>
<span id="cb1-340"><a href="#cb1-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-341"><a href="#cb1-341" aria-hidden="true" tabindex="-1"></a>The Control and Treatment A respondents indicated they would prefer consequences be slightly lower on average. By law, there is no penalty to lower. This confirms that the Public Domain scenario functions as the intended baseline: law and preferences align, and the treatment conditions do not create a gap between how respondents perceive the law and what they think the law should be.</span>
<span id="cb1-342"><a href="#cb1-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-343"><a href="#cb1-343" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.1.5 Q4: License Price Estimate {#sec-pd-price}</span></span>
<span id="cb1-344"><a href="#cb1-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-345"><a href="#cb1-345" aria-hidden="true" tabindex="-1"></a>*What do respondents estimate a non-exclusive license would cost? For a public domain work, the rational price is \$0.*</span>
<span id="cb1-346"><a href="#cb1-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-349"><a href="#cb1-349" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-350"><a href="#cb1-350" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-pd-price-stats</span></span>
<span id="cb1-351"><a href="#cb1-351" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Public Domain --- Q4 price descriptive statistics by group (after outlier removal)."</span></span>
<span id="cb1-352"><a href="#cb1-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-353"><a href="#cb1-353" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb1-354"><a href="#cb1-354" aria-hidden="true" tabindex="-1"></a>  pd_results<span class="sc">$</span>statistics<span class="sc">$</span>price, <span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb1-355"><a href="#cb1-355" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Group"</span>, <span class="st">"Mean"</span>, <span class="st">"Std. Dev."</span>, <span class="st">"Median"</span>)</span>
<span id="cb1-356"><a href="#cb1-356" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-357"><a href="#cb1-357" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-358"><a href="#cb1-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-361"><a href="#cb1-361" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-362"><a href="#cb1-362" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-pd-price-vda</span></span>
<span id="cb1-363"><a href="#cb1-363" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Public Domain --- Q4 pairwise VDA effect sizes (Vargha &amp; Delaney 2000).&lt;br&gt;Sig.: \\*\\*\\* *p* &lt; .001, \\*\\* *p* &lt; .01, \\* *p* &lt; .05."</span></span>
<span id="cb1-364"><a href="#cb1-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-365"><a href="#cb1-365" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(pd_vda_price)</span>
<span id="cb1-366"><a href="#cb1-366" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-367"><a href="#cb1-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-370"><a href="#cb1-370" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-371"><a href="#cb1-371" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-pd-price</span></span>
<span id="cb1-372"><a href="#cb1-372" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb1-373"><a href="#cb1-373" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Public Domain --- Q4: Non-exclusive license price estimates by treatment group (top 1% trimmed)."</span></span>
<span id="cb1-374"><a href="#cb1-374" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-375"><a href="#cb1-375" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(pd_results<span class="sc">$</span>plots<span class="sc">$</span>price)</span>
<span id="cb1-376"><a href="#cb1-376" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-377"><a href="#cb1-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-378"><a href="#cb1-378" aria-hidden="true" tabindex="-1"></a>For a public domain work, the economically rational license price is $0. There are no copyright restrictions to license around. Any nonzero price estimates reflect residual confusion about the work's copyright status or a willingness to pay for convenience, attribution, or perceived quality assurance.</span>
<span id="cb1-379"><a href="#cb1-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-380"><a href="#cb1-380" aria-hidden="true" tabindex="-1"></a>The results follow the C &gt; A &gt; B pattern. As shown in @fig-pd-price and @tbl-pd-price-stats, the means differ by roughly $1,000 between groups, with Treatment B producing the lowest estimates and the Control the highest. The plot makes clear that a large concentration of respondents, particularly in Treatment B, correctly priced the license at $0 (visible as the dense cluster at the bottom of the violin). The between-group differences are statistically significant with all pairwise comparisons reaching significance (*p* &lt; 0.001). Providing explicit information that works in the public domain do not have copyright resulted in the lowest license price estimate at about a third of the Control. Simply listing the work as public domain had about half the effect of the explicit information treatment. VDA pairwise comparisons are reported in @tbl-pd-price-vda.</span>
<span id="cb1-381"><a href="#cb1-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-382"><a href="#cb1-382" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7.1.6 Summary {#sec-pd-summary}</span></span>
<span id="cb1-383"><a href="#cb1-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-384"><a href="#cb1-384" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip}</span>
<span id="cb1-385"><a href="#cb1-385" aria-hidden="true" tabindex="-1"></a><span class="fu">## Key Findings --- Public Domain</span></span>
<span id="cb1-386"><a href="#cb1-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-387"><a href="#cb1-387" aria-hidden="true" tabindex="-1"></a>The Public Domain scenario serves as the study's baseline. Because the Blue Marble photograph is a U.S. government work not subject to copyright (17 U.S.C. § 105), the depicted use is non-infringing across all treatment conditions. The key findings are:</span>
<span id="cb1-388"><a href="#cb1-388" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-389"><a href="#cb1-389" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Baseline partially confirmed.** All group means fall in the low range of the 7-point scale (<span class="in">`r pd_q3_b`</span>--<span class="in">`r pd_q1_c`</span> for Q1--Q3), confirming that respondents generally perceive low legal risk for public domain use. However, significant between-group differences exist across all ordinal questions. The Public Domain scenario is not as "flat" as a pure baseline would predict.</span>
<span id="cb1-390"><a href="#cb1-390" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-391"><a href="#cb1-391" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**C &gt; A &gt; B pattern confirmed.** The pre-registered ordering holds consistently across Q1, Q2, Q3, and price. Control respondents perceive the highest risk and estimate the highest license prices; Treatment B respondents perceive the lowest risk and estimate the lowest prices.</span>
<span id="cb1-392"><a href="#cb1-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-393"><a href="#cb1-393" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Treatment B produces near-consensus.** The explicit statement that the work is "free of known copyright restrictions" drives Treatment B means to approximately <span class="in">`r pd_q2_b`</span> on the 7-point scale with standard deviations near <span class="in">`r pd_q2_sd_b`</span>. The narrow distributions in the violin plots indicate strong respondent agreement, not just lower means.</span>
<span id="cb1-394"><a href="#cb1-394" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-395"><a href="#cb1-395" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Law--preference gap is zero.** Delta (Q2 - Q3) is near zero across all groups, and the between-group Kruskal-Wallis test is not significant. This confirms that the Public Domain scenario functions as intended: respondents' perceptions of current law match their normative preferences. There is no systematic tension between "what the law says" and "what it should say."</span>
<span id="cb1-396"><a href="#cb1-396" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-397"><a href="#cb1-397" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**Residual confusion persists.** Despite non-infringing use, Control and Treatment A respondents still report moderate perceived risk (means of <span class="in">`r pd_q1_a`</span>--<span class="in">`r pd_q1_c`</span>), well above the scale minimum of 1. This suggests incomplete public understanding of public domain status. Many respondents in these groups do not fully appreciate that U.S. government works carry no copyright restrictions.</span>
<span id="cb1-398"><a href="#cb1-398" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-399"><a href="#cb1-399" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**Framing matters even for clear cases.** The central implication is that *how* copyright information is presented materially affects risk perception, even when the underlying legal question is straightforward. For a non-infringing baseline, moving from "U.S. Government Work" to an explicit statement of copyright-free status reduces perceived risk by approximately 50% and license price estimates by roughly two-thirds.</span>
<span id="cb1-400"><a href="#cb1-400" aria-hidden="true" tabindex="-1"></a>:::</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ludist/cc-survey/edit/main/_scenarios/pd.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/ludist/cc-survey/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>